### ISSUE TITLE
Preview table creation fails for headerless csvs when first row's column value is empty

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#1003]
## Description
The post request to create the preview table fails when using a headerless csv which has empty values for some columns in the first row. While from a table creation standpoint this is expected, we should rather be generating column names ourselves for such cases.

## To Reproduce
* Upload the headerless file from `/mathesar/tests/data/headerless_patents.csv`
   * The first row for this has empty values for some columns
* Create a table using this file from the table POST endpoint: `/api/v0/tables/`
    * This currently fails.

## Expected
Table creation should not fail. The column names should be auto-generated in such scenarios.

**Comment by A1O** [comment]
I'd like to work on this issue.

**Comment by kgodey** [comment]
Go ahead @A1O
