### ISSUE TITLE
Add exceptions to the error handler's exceptions map 

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar#1021]
## Problem
We need a [standardised error format](https://wiki.mathesar.org/en/engineering/standards/api#errors) for the API's but most of the exceptions don't have a standardised format, so we have a wrapper APIException around the known exceptions(IntegrityError, ProgrammingError). Most of the exceptions are handler by Serializer or gets captured by the Views and get converted into APIException. But in some cases the exceptions are not handled, so we have the exception handler convert the exceptions which don't conform to the error API standard. 

We need to list out all the possible uncaught non `APIException` that has to be handled by the exception handler, right now we only have a small list of exceptions added to the exception map.

## Proposed solution

The error handler works by mapping the exceptions to their APIEquivalent. So all the possible list of exceptions and add their APIException equivalent should be added to the mapping list(mathesar/exception_handlers.py:20).

## Related
- #623 is blocking it
-  #1016 is blocking it

**Comment by silentninja** [comment]
Blocked by #1016

**Comment by silentninja** [comment]
Go ahead @ajitg25, thanks for the help!

**Comment by ajitg25** [comment]
I will be adding exceptions other than the APIexceptions but these exception will lead them to which of the functions like u have already added some redirecting them to your set of code, can u plz guide how should i approach

**Comment by silentninja** [comment]
@ajitg25 I added few more information to the problem statement. Let me know if it is not clear.

**Comment by silentninja** [comment]
> can u plz guide how should i approach

Please start by looking into the codebase for exceptions that are missing from the list. If the list gets repetitive, see if the APIException lookup can be automated.

**Comment by kgodey** [comment]
@ajitg25 Are you still working on this?
