### ISSUE TITLE
Split up existing APIs into "DB" and "UI" namespaces

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1029]
## Problem

During [a recent meeting](https://wiki.mathesar.org/en/meeting-notes/2022-01#2022-01-25), we decided to split up the APIs into two namespaces.

## Proposed solution

We should split up our API into two namespaces, e.g. `/db-api/v0/` and `/ui-api/v0/` or something like that.

### UI API
This is for Mathesar UI-specific abstractions and functionality, examples include:
- Mathesar data types
- Filters
- Grouping
- "Link Table" APIs

Goals:
- Limited functionality, strictness, typing
- Make things as easy as possible for the frontend to work with without knowing much
- Define things in terms of other abstractions (e.g. Filters should be related to Mathesar Types, not DB types)
- Dogfood DB APIs

### DB API
This is for direct access to PostgreSQL functionality, examples include:
- Tables
- Schemas
- DB Functions

Goals:
- Broad functionality, doesn't assume any UI
- Allow maximum power, focus on flexibility and lack of assumptions
- Allow DB reflection as much as possible
- (Eventually) allow composition

## Additional context

This will need both backend and frontend work, since the API paths need to be updated in the frontend before merge.

**Comment by kgodey** [comment]
I'm putting this in the "Links between Tables" milestone. Since one of the APIs listed is the linking tables API, it seems like a good target to have the APIs split up by then.

**Comment by seancolsen** [comment]
Will the two namespaces be versioned separately? If so, then `/db-api/v0/` and `/abstractions-api/v0/` make sense. However, if they'll be versioned together, then I think `/api/v0/db/` and `/api/v0/abstractions/` would be more semantic.

**Comment by kgodey** [comment]
> Will the two namespaces be versioned separately? If so, then `/db-api/v0/` and `/abstractions-api/v0/` make sense. However, if they'll be versioned together, then I think `/api/v0/db/` and `/api/v0/abstractions/` would be more semantic.

I think they should be treated as separate APIs and versioned separately. `/api/v0/db/` and `/api/v0/abstractions/` also seem like `db` and `abstractions` are resources offered by the API (like tables, schemas, etc.)

**Comment by dmos62** [comment]
> Will the two namespaces be versioned separately?

I think so. An abstraction endpoint can change without anything in the db API changing and vice-versa.

**Comment by kgodey** [comment]
I updated the issue description to change the names to `db-api` and `ui-api`, I think that's more concise and less ambiguous.
