### ISSUE TITLE
Provide detailed error info for POST to records API when in violation of a not-null constraint

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1051]
## Current behavior

1. Set up a table which contains a `NOT NULL` column.
1. POST an empty request (`{}`) to the `records` API (e.g. by clicking the `+` icon to add a new row to the table).
1. Observe the following response:

    ```json
    [
      {
        "code": 4999,
        "message": "(psycopg2.errors.NotNullViolation) null value in column \"common_name\" of relation \"trees\" violates not-null constraint\nDETAIL:  Failing row contains (11, null, null, null, null, null, null).\n\n[SQL: INSERT INTO public.trees DEFAULT VALUES RETURNING public.trees.id]\n(Background on this error at: http://sqlalche.me/e/14/gkpj)",
        "field": null,
        "detail": null
      }
    ]
    ```

1. Within the response, observe no easy way to identify _which column_ (or columns) was responsible for the error.

## Expected behavior

- For #775, we need enough detail for the front end to be able to display error messages specific to certain cells. For example, if a POST request has two columns with invalid data (perhaps even invalid in _different ways_), we need to be able to match specific error messages to each of those columns.

- @pavish and I are flexible on the exact response schema from the API here, as long as it satisfies the above goal.

- We should also keep #896 in-mind with this change.

## Status

- blocked by #896

**Comment by kgodey** [comment]
@seancolsen Since there's already a draft for #896, I think it's fine to wait until it's complete.

**Comment by seancolsen** [comment]
Cool thanks @kgodey I'm marking this as blocked by #896 then.
