### ISSUE TITLE
Remove url prefixing on frontend

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#1054]
## Description

Currently, the frontend appends a url prefix `/api/v0` in the api util. This was implemented earlier for two reasons:
* Inorder to easily update the api version for future releases, considering the client updates it all with each release.
* Inorder to avoid explicitly adding this to everywhere we need to make a request.

However, with the changes done for https://github.com/centerofci/mathesar/pull/1041, both these reasons are now void:
* We now have two API namespaces, each maintaining their own versions.
* We may have to work with multiple API versions of the same namespace on the client in the future.

We need to remove the common method `appendUrlPrefix` within `/mathesar_ui/src/utils/api.ts` and explicitly mention the prefix in each place where a request is made.

**Comment by sanjeevbhusal** [comment]
Hey, is anyone assigned to it?

**Comment by kgodey** [comment]
@sanjeevbhusal Not yet, do you want to work on it?

**Comment by nimishbongale** [comment]
Hello @kgodey, can I work on this issue?

**Comment by kgodey** [comment]
Sure, go ahead @nimishbongale. I'll defer to @pavish on whether it should be configurable.

**Comment by pavish** [comment]
@nimishbongale 

> do we want this prefix URL to be configurable

No, we do not need it to be configurable at the moment.

**Comment by pavish** [comment]
A bit more information on this issue:

Whenever we make a request from the frontend (In places where we call methods like `postAPI`, `getAPI` etc.,), the `appendUrlPrefix` method checks if the full path is specified, if yes, it does not append any prefix, otherwise it appends the `db` prefix by default.

As mentioned in the issue description above, this is no longer desired since we now deal with multiple namespaces and possibly the need to use multiple versions of the same namespace.

We need to specify the full url everywhere requests are made.
eg., In `stores/schemas.ts`, 
```
const response = await postAPI<SchemaResponse>('/schemas/', {
    name: schemaName,
    database,
})
```
will change to:
```
const response = await postAPI<SchemaResponse>('/api/db/v0/schemas/', {
    name: schemaName,
    database,
})
```

**Comment by nimishbongale** [comment]
> A bit more information on this issue:
> 
> Whenever we make a request from the frontend (In places where we call methods like `postAPI`, `getAPI` etc.,), the `appendUrlPrefix` method checks if the full path is specified, if yes, it does not append any prefix, otherwise it appends the `db` prefix by default.
> 
> As mentioned in the issue description above, this is no longer desired since we now deal with multiple namespaces and possibly the need to use multiple versions of the same namespace.
> 
> We need to specify the full url everywhere requests are made. eg., In `stores/schemas.ts`,
> 
> ```
> const response = await postAPI<SchemaResponse>('/schemas/', {
>     name: schemaName,
>     database,
> })
> ```
> 
> will change to:
> 
> ```
> const response = await postAPI<SchemaResponse>('/api/db/v0/schemas/', {
>     name: schemaName,
>     database,
> })
> ```

I think I have a clearer understanding now, will make the necessary changes! Thanks @pavish!
