### ISSUE TITLE
Ensure that we can set, get, and delete default values for all types

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1064]
## Problem

We need to make sure that we can set, get, and delete default values for all supported DB types.

## Proposed solution

Ensure that tests exists for this functionality for all supported DB types, write new ones if needed.

## Additional context

If support for any DB types are not yet complete by the time this issue is complete, then responsibility for writing tests for those types falls on the person implementing the type.

**Comment by silentninja** [comment]
Blocked by #1156
