### ISSUE TITLE
CSV to table import: Define UI and interactions

### ISSUE THREAD

**Issue by ghislaineguerin** [centerofci/mathesar#107]
### Design Problem
We need to define the interface components and interactions required to implement the **CSV to Table Import Functionality**.

### Context
Importing data from a file is one of the table creation methods listed in [Mathesar's roadmap](https://wiki.mathesar.org/en/roadmap). In the case of CSV to Table, the input source is a CSV file, that once processed by Mathesar, is converted into a table in a new or existing schema.

### Justification
Import from files is a baseline functionality of products in the same category. We want to make Mathesar comparable to other products in the same category.
CSV is one of the most commonly used file formats for tabular data, and it's easily saved from applications like Excel or Google Sheets, making it accessible to users.

### Impact
Users expect the same baseline functionality from products in the same category.

### Scenarios
- The input is a valid CSV file.
- The input is a single CSV file.

**Comment by kgodey** [comment]
@ghislaineguerin per our conversation on Matrix today, this design should provide clear indication when a new schema is created vs. an existing schema being used for a new table.
