### ISSUE TITLE
Improve UX and discoverability for selecting rows on touch devices

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1070]
## Current behavior

- On a mouse device:
    - When I hover on a row, I see a checkbox in the first column, allowing me to select the row.

- On a touch device:
    - Without the ability to hover, new users will will be unlikely to discover the row selection feature.
    - I _can_ click the spot where the checkbox appears, and about 50% of the time, I'm able to move the checkbox from unchecked to checked with just one tap. There must be some subtle timing or positioning which affects the outcome, but I don't understand it. The remaining 50% of the time, the checkbox remains visible after my tap, allowing me to check it with an additional tap. If I want to select multiple rows, it's _possible_, but it's quite annoying. (I'm using Chrome on Android here.)
    - _Un-checking_ the boxes works fine.

## Desired behavior

- The row selection feature is readily apparent to users without hovering.
- Selecting multiple rows is easy and straightforward via touch.

CC @ghislaineguerin because I think we need some UX design work to address this problem.

CC @pavish because you might have thoughts/opinions.

**Comment by kgodey** [comment]
Marking as draft until we figure out the exact behavior.

**Comment by seancolsen** [comment]
Given our new cell-based selection UX this issue is no longer relevant as spec'ed -- so I'm closing it. Our selection UX will likely need more testing and design to accommodate touch devices, but we can take that up in a separate ticket.
