### ISSUE TITLE
Refactor Select and SimpleSelect components, merging them into one

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1099]
## Current

- We have `Select` and `SimpleSelect` components which appear identical to the user but have different props structure.

    Why? Because `Select` came first, and then we decided on a different approach to structuring the props in order to specify the options.

## Desired

- We have only one component named `Select`.

- The props of `Select` behave exactly as the props of `SimpleSelect`.

- All code locations that have been using `Select` have been refactored to use its new props structure.

- `SimpleSelect` is deleted.

- All code locations that have been using `SimpleSelect` have been changed to use `Select` instead (and refactoring should not be necessary here, beyond a simple name change).

- `Select.d.ts` is renamed to `SelectUtils.ts`

- Inside `SelectUtils.ts`, we no longer have `SelectOption` or `SelectOptions` because they're not necessary anymore.

**Comment by pavish** [comment]
I'm picking this up because this refactoring makes things easier for #257
