### ISSUE TITLE
Remove input elements from columns in new record placeholder row

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1115]
## Current behavior

For a boolean checkbox column, the new record placeholder row at the bottom of the table displays an unchecked checkbox. This makes it appear as though there may be another record in the table.

## Desired behavior

The new record placeholder does not show any checkbox at all, no matter if there is a default value for the column or if the column does/doesn't allow NULL.

## Additional context

The current behavior was established in #1080 which contains some discussion about checkboxes

**Comment by seancolsen** [comment]
@ghislaineguerin Can you give an opinion before we proceed?

Personally I'd really like to remove the checkbox from the new record placeholder. I don't see the value that it adds.

**Comment by kgodey** [comment]
@seancolsen How do you see the UX working for adding a new record? As an extreme example, imagine a table with only `id` and one or more `boolean` columns.

**Comment by seancolsen** [comment]
> imagine a table with only id and one or more boolean columns.

Here is the UX I have in mind for adding a new record in a table with a boolean checkbox column:

1. Observe the "new record placeholder row" as an additional row, entirely _blank_.
1. Click anywhere within the new record placeholder row.
1. Observe that above the new record placeholder row, a "record insertion row" appears.
1. Within the "record insertion row", the checkbox displays.
    - If the column has a default value, the the checkbox displays as checked or unchecked depending on that value.
    - If the column has no default value, then the checkbox displays as indeterminate.
    - If the column has no default value and also does not allow NULL, then the checkbox displays as indeterminate and the cell turns red with an error indicator.

Does this answer your question, @kgodey ?

**Comment by ghislaineguerin** [comment]
@seancolsen what you describe makes sense and it would be consistent with the NULL behavior as you've mentioned. It doesn't make sense to show input elements unless the user is ready to interact with them.

**Comment by seancolsen** [comment]
Cool, thanks @ghislaineguerin. Now that we have the go-ahead from you, I've changed the status to "ready".

**Comment by Cronus1007** [comment]
@pavish Shall I work upon this issue?

**Comment by kgodey** [comment]
@Cronus1007 nice to see you here :)

I've assigned the issue to you, please go ahead and work on it.

**Comment by kgodey** [comment]
@Cronus1007 I wanted to follow up on this issue since it's been a few days and I don't see a PR yet. Please let us know if you need any help or if you are no longer working on the issue.

**Comment by Cronus1007** [comment]
@kgodey I am currently working upon this issue. Will raise a draft pr ASAP

**Comment by Cronus1007** [comment]
@pavish While the office hours would be open can we discuss this issue whenever you are free on a meet?

**Comment by pavish** [comment]
@Cronus1007 Sure. The next office hours is [in a few hours today](https://wiki.mathesar.org/en/community/events/2022-03-28-to-2022-03-31), for which I'll be available.

**Comment by Cronus1007** [comment]
>    * If the column has no default value and also does not allow NULL, then the checkbox displays as indeterminate and the cell turns red with an error indicator.

I am unable to detect this in the new record_insertion_row since when i set don't allow null to the boolean columns it returns an error as toast containers. So if you would be able to give me some sort of advice how this has been achieved while implementing for new record_insertion_row

**Comment by Cronus1007** [comment]
@pavish Currently I am unable to get a very clear picture how the UX would really look like. So would want to communicate in order to get a more clear idea about this issue.

**Comment by pavish** [comment]
This issue was discussed in one of our office hours. I am commenting a gist of what was discussed to keep track.
* The place holder row needs to be empty. There should be no input fields shown there.
* Upon clicking a cell in the placeholder row, the existing behavior of adding a new row and selecting the same cell in that new row should be retained.

**Comment by Cronus1007** [comment]
@pavish Can you please specify the files I need to change since I went throught #1080 but unable to resolve this issue.

**Comment by pavish** [comment]
@Cronus1007 Take a look at `/sections/table-view/row/Row.svelte` and `/sections/table-view/row/RowCell.svelte`. 

The property `row.isAddPlaceholder` would be `true` for the placeholder row. Following this property might help you understand the code better.

**Comment by seancolsen** [comment]
@Cronus1007 We're trying to close out this milestone soon, so if we don't have a PR for this issue by 2022-04-19 we'll need to re-assign it to a core team member.

**Comment by Cronus1007** [comment]
@seancolsen Sure. I am currently working upon my GSoC proposal so I was unable to complete it.

**Comment by pavish** [comment]
I'm picking this up as part of my boolean type PR, as it improves some interactions I'm implementing.

The new behavior is as follows:
* Inputs will not be visible on the placeholder cells by default.
* Inputs will become visible when the cell enters active state (when user enters the cell by keyboard interaction), thereby allowing users to enter value on the placeholder row.
