### ISSUE TITLE
NULL values do not display within newly-added column

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1120]
## Reproduce

1. "New Table" > "Import Data" > "Copy and Paste Text"

1. Paste the following data and proceed to create and view the table.

    ```txt
    first_name
    Marge
    Homer
    Lisa
    Bart
    Maggie
    ```

1. Add a new column called `last_name`. 

1. Expect to see `NULL` values for all the cells in the `last_name` column.

1. Observe the cells in the `last_name` column to be blank.

1. Click "Refresh".

1. Observe `NULL` values for all the cells in the `last_name` column.

**Comment by kgodey** [comment]
I moved this to the Initial Data Types milestone since everything else in the `NULL` spec is there.

**Comment by shrey27tri01** [comment]
Hello, I am a new contributor to Mathesar and I would like to work on this issue.

**Comment by kgodey** [comment]
Go ahead @shrey27tri01. Let us know here or in Matrix if you need any help.

**Comment by shrey27tri01** [comment]
I am a bit stuck. The way I understand the flow is as follows: after clicking the "+" button for adding a new column and entering the column name, we use the [Button component](https://github.com/centerofci/mathesar/blob/master/mathesar_ui/src/sections/table-view/header/new-column-cell/NewColumnCell.svelte#L68) inside the `NewColumnCell.svelte` file which has an `on:click` method `addColumn`. This [addColumn function](https://github.com/centerofci/mathesar/blob/master/mathesar_ui/src/sections/table-view/header/new-column-cell/NewColumnCell.svelte#L28) uses an event dispatcher `'addColumn'` which gives a signal to [NewColumnCell](https://github.com/centerofci/mathesar/blob/master/mathesar_ui/src/sections/table-view/header/Header.svelte#L74) in the [Header.svelte](https://github.com/centerofci/mathesar/blob/master/mathesar_ui/src/sections/table-view/header/Header.svelte) file. The attribute `addColumn` inside Header.svelte then calls the following [function](https://github.com/centerofci/mathesar/blob/master/mathesar_ui/src/sections/table-view/header/Header.svelte#L56) inside the same file:
```
function addColumn(e: CustomEvent<Partial<Column>>) {
    void columnsDataStore.add(e.detail);
  }
```

I have understood this much, and am stuck here. I tried logging the output of `e.detail` above on the console, and I get only the schema of the new column:
```
> {name: 'fname', type: 'varchar', nullable: true, primary_key: false}
name: "fname"
nullable: true
primary_key: false
type: "varchar"
> [[Prototype]]: Object
```

Any hints on how to proceed from here would be helpful. I apologize if this may sound like a beginner question!

**Comment by pavish** [comment]
@shrey27tri01 Checkout the stores under `/src/stores/table-data`. These stores constitute the data layer and contain all the data and operations pertaining to the table.

When a column is added using the `add` function in `ColumnsDataStore`, we currently only fetch the columns. We'll need to fetch the rows as well. Also, have a look at the `rename` function for better clarity on this.

**Comment by tsun812** [comment]
Hi, it seems Header.svelte(where column display is) is subscribing to columnsDataStore for update.. Am I missing anything?

**Comment by kgodey** [comment]
@shrey27tri01 I wanted to follow up on this issue since it's been a few days and I don't see a PR yet. Please let us know if you need any help or if you are no longer working on the issue.

**Comment by shrey27tri01** [comment]
@kgodey I was caught up with uni work, hence couldn't work on this. Will surely raise a PR by tomorrow. Really sorry for the delay.

**Comment by shrey27tri01** [comment]
> @shrey27tri01 Checkout the stores under `/src/stores/table-data`. These stores constitute the data layer and contain all the data and operations pertaining to the table.
> 
> When a column is added using the `add` function in `ColumnsDataStore`, we currently only fetch the columns. We'll need to fetch the rows as well. Also, have a look at the `rename` function for better clarity on this.

Okay, I understood a bit about how the `add` function first adds new Column details through the API, then waits for a response from the `fetch()` method, and finally returns the response received. Now to display the NULL values, I need to fetch the row details as well inside the `fetch()` function, similar to what happens on `refresh()` inside the `refresh()` function in `tabularData.ts`. Please let me know if my understanding is correct. If so, should I call the `refresh()` function itself inside the `fetch()` in `columns.ts`?

**Comment by pavish** [comment]
@shrey27tri01 You'll have to dispatch an event from the columns store, to the parent tabular data class (Refer tabularData.ts). You could then fetch the rows in this class.

Refer 'columnRenamed' event in both tabularData.ts and columns.ts which utilizes a similar workflow.
