### ISSUE TITLE
The type inference algorithm should use `TEXT` rather than `VARCHAR`

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1121]
## Reproduce

1. "New Table" > "Import Data" > "Copy and Paste Text"

1. Paste the following data and proceed to create and view the table.

    ```txt
    first_name
    Marge
    Homer
    Lisa
    Bart
    Maggie
    ```

1. From the `columns` API, expect the response for the `first_name` column to have `"type": "TEXT"`

1. Observe instead that the column is `VARCHAR` without a length set.

## Rationale

- I spoke with @kgodey about the Mathesar Text type today and she say that Mathesar should only be configuring either: `TEXT` columns or `VARCHAR` columns with a length specified. She may be able to elaborate on the thinking that went into this decision.

## Additional context

- In #1118, we are doing some work to bring the front end into alignment with the above expectations when the user manually configures the DB settings for the Text type.

**Comment by mathemancer** [comment]
If we _do_ want to always set a length for `VARCHAR` columns (@kgodey is there a place where you've made it clear why you prefer that?), then I strongly suggest using `TEXT` for the default textual database type. Inferring the length based on some subset of the data is going to be quite brittle.

**Comment by kgodey** [comment]
@mathemancer Agreed on using `TEXT` for the default textual database type. 

> @kgodey is there a place where you've made it clear why you prefer that?

I don't have a preference for `VARCHAR` vs. `TEXT` from a backend perspective. During a call with @seancolsen and @pavish last week, it seemed like the logic for the frontend type selection would be simplified if they could use `VARCHAR` for things that had a length and `TEXT` for things that did not have a length. I don't see any harm in us adopting that convention.

**Comment by mathemancer** [comment]
> I don't see any harm in us adopting that convention.

I don't see any harm either.

To the implementer: This change needs to be made in the inference logic. The back end does not currently set default database types for Mathesar types.

**Comment by seancolsen** [comment]
I've updated the ticket description to be more specific about the expected behavior -- specifying `TEXT` instead of "`TEXT` or `VARCHAR` with a length"

**Comment by vrutik2809** [comment]
I would like to work on this issue. Can anyone please elaborate on this issue and how to get started?

**Comment by vrutik2809** [comment]
While adding the column named `test` in my table, I got the following object as `request.data` : 
```python
{
  'name': 'test', 
  'type': 'varchar', 
  'nullable': True, 
  'primary_key': False
}
```
So, I need to change the type from `varchar` to`text` in this.
@mathemancer Please correct me if I'm wrong

**Comment by vrutik2809** [comment]
Sure I will definitely look into that.

Thank you
