### ISSUE TITLE
Add second round of new E2E tests

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1122]
In #640 we added some initial E2E test coverage. This ticket is to track progress towards a second push of E2E tests for existing features.

## Tests to add

- [x] #1123
- [x] #1124
- [x] #1125
- [x] #1126
- [ ] #1127
- [x] #1128
- [x] #1129
- [x] #1130
- [x] #1131

## How to add an E2E test

- See [documentation](https://github.com/centerofci/mathesar/tree/master/mathesar/tests/integration#readme).
- Follow patterns in existing E2E tests.
- Post questions within the specific ticket you're working on, or ask in the "Code - General" channel on [Matrix](https://wiki.mathesar.org/en/community/matrix).

**Comment by kgodey** [comment]
I'm going to close this since we've found E2E tests unreliable and don't want to be writing more.
