### ISSUE TITLE
Add E2E test for deleting a table

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1123]
## Context

See #1122 for more info and instructions on writing E2E tests.

## This test

Write an E2E test which asserts that "deleting a table" works as-expected. Here's a visual demo of what the test should do:

![Peek 2022-03-02 16-41](https://user-images.githubusercontent.com/42411/156454399-fe524794-2fba-46ef-b459-35f0d9c6585a.gif)

## Tips

- Assert that the modal closes, that the tab is no longer visible, and that the entry in the sidebar is no longer visible

**Comment by A1O** [comment]
I’d like to work on this issue.

**Comment by silentninja** [comment]
Thanks, @A1O! I have assigned you the issue. Let us know if you need any help. Feel free to ask questions here or in [Matrix](https://wiki.mathesar.org/en/community#matrix) (our chat system).
