### ISSUE TITLE
Add E2E test for renaming a table

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1124]
## Context

See #1122 for more info and instructions on writing E2E tests.

## This test

Write an E2E test which asserts that "renaming a table" works as-expected. Here's a visual demo of what the test should do:

![Peek 2022-03-02 16-44](https://user-images.githubusercontent.com/42411/156454623-61b79c98-7b74-43e3-875b-7f8f06e96d60.gif)

## Tips

- Assert that the modal closes, that the tab title updates, and that the entry in the sidebar updates

**Comment by A1O** [comment]
I’d like to work on this issue.

**Comment by seancolsen** [comment]
Thanks @A1O! I've assigned it to you. Let us know if you have any questions.
