### ISSUE TITLE
Add E2E test for trying to to rename a table to the name of another table

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1125]
## Context

See #1122 for more info and instructions on writing E2E tests.

## This test

Write an E2E test which asserts that "trying to to rename a table to the name of another table" works as-expected. Here's a visual demo of what the test should do:

![Peek 2022-03-02 16-45](https://user-images.githubusercontent.com/42411/156454830-358873c4-dab6-4500-b4ae-0839bb71642a.gif)

## Tips

- Assert that the error message is shown and that the save button is disabled

**Comment by ManishShah120** [comment]
I would like to take up this issue.

**Comment by seancolsen** [comment]
Thanks @ManishShah120 I've assigned it to you.
