### ISSUE TITLE
Add E2E test for grouping by a column

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1126]
## Context

See #1122 for more info and instructions on writing E2E tests.

## This test

Write an E2E test which asserts that "grouping by a column" works as-expected. Here's a visual demo of what the test should do:

![Peek 2022-03-02 16-54](https://user-images.githubusercontent.com/42411/156455977-833063aa-12d3-4c59-92a5-d2b2c4585d7d.gif)

## Tips

- Assert that the count of the first listed group is correct

**Comment by Forchapeatl** [comment]
Please , May I work on this issue ?

**Comment by kgodey** [comment]
Go ahead @Forchapeatl

**Comment by kgodey** [comment]
@Forchapeatl I wanted to follow up on this issue since it's been a few days and I don't see a PR yet. Please let us know if you need any help or if you are no longer working on the issue.

**Comment by Forchapeatl** [comment]
@kgodey , I am sorry, I forgot. I have been busy with exams. I am sorry. Please assign it to someone else, I am sorry.

**Comment by kgodey** [comment]
@Forchapeatl no problem, I'll unassign you. If you're interested in contributing in the future when you have time, please feel free to comment on an issue.

**Comment by A1O** [comment]
I'd like to work in this issue.

**Comment by silentninja** [comment]
Sure @A1O I have assigned the issue to you.

**Comment by pavish** [comment]
@A1O Grouping is currently broken. There are a number of changes on the backend and it's still being worked upon. The frontend will get updated after all backend work is done. It'll take a while before we get to it.
