### ISSUE TITLE
Add E2E test for converting a text column of numbers to a number column

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1128]
## Context

See #1122 for more info and instructions on writing E2E tests.

## This test

Write an E2E test which asserts that "converting a text column of numbers to a number column" works as-expected. Here's a visual demo of what the test should do:

![Peek 2022-03-02 17-04](https://user-images.githubusercontent.com/42411/156457343-6078bc4c-5213-44e3-9bbe-273463d66204.gif)

## Tips

- Assert that the data type shows as "Number" in the end

**Comment by ManishShah120** [comment]
I would like to take up this issue. :+1:

**Comment by kgodey** [comment]
Thanks @ManishShah120, assigned to you.

**Comment by ManishShah120** [comment]
Hi @seancolsen, I am trying to write the test, but I am getting the error, as `Unable to change column.`

Attached a GIF of it:
![clipped_Giff](https://user-images.githubusercontent.com/45564404/158065479-4f35def8-7307-4612-a0d5-8cff49e00afe.gif)

**Comment by pavish** [comment]
@ManishShah120 Could you please open a separate issue for this?

@silentninja It looks like our integ environment is missing certain db functions, probably because migrations did not run. The error:
```
(psycopg2.errors.InvalidSchemaName) schema "mathesar_types" does not exist
LINE 5:       USING mathesar_types.cast_to_integer(text);
                    ^

[SQL: 
    ALTER TABLE table_tests."All datatypes table"
      ALTER COLUMN text
      TYPE INTEGER
      USING mathesar_types.cast_to_integer(text);
    ]
(Background on this error at: http://sqlalche.me/e/14/f405)
```

Do you have any quick suggestions to resolve this so that @ManishShah120 can continue his work on the test case?

**Comment by ManishShah120** [comment]
> @ManishShah120 Could you please open a separate issue for this?

Sure, On it

**Comment by silentninja** [comment]
I think `mathesar_types` schema is not installed. Are you calling `install.install_mathesar_on_database(engine)`, please refer `patent_schema` (mathesar.tests.conftest.patent_schema) for example

**Comment by pavish** [comment]
@silentninja Ah, makes sense. I believe it does not pertain to this issue but rather an issue with the common `go_to_patents_data_table` fixture.

I'll defer to @silentninja and @seancolsen for information on the changes required. I think it's best to move this discussion to the PR: https://github.com/centerofci/mathesar/pull/1164.
