### ISSUE TITLE
Add E2E test for trying to convert a text column of words to a number column

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1129]
## Context

See #1122 for more info and instructions on writing E2E tests.

## This test

Write an E2E test which asserts that "trying to convert a text column of words to a number column" fails. Here's a visual demo of what the test should do:

![Peek 2022-03-02 17-01](https://user-images.githubusercontent.com/42411/156456897-c3266e94-ceea-4c37-9c5c-64ed4bd78a26.gif)

## Tips

- Assert that the toast message displays. As you can see in the demo, our toast messages are not correctly displaying the full error message (due to #1045), but that's okay. You only need to assert that the first part of the text in the toast message matches.

**Comment by ManishShah120** [comment]
I would like to work on this issue, :+1:

**Comment by kgodey** [comment]
Thanks @ManishShah120, go ahead.
