### ISSUE TITLE
Add E2E test for moving the selected cell with arrow keys

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1130]
## Context

See #1122 for more info and instructions on writing E2E tests.

## This test

Write an E2E test which asserts that "moving the selected cell with arrow keys" works as-expected. Here's a visual demo of what the test should do:

![Peek 2022-03-02 17-07](https://user-images.githubusercontent.com/42411/156457837-213d7e3b-5d35-4ffd-8272-33a46babb694.gif)

**Comment by ManishShah120** [comment]
I would love to take up this issue. :smiley:

**Comment by kgodey** [comment]
@ManishShah120 I assigned you #1128, please work on that first (we have a limited supply of `good first issue` tickets and would like to spread them across different contributors).

**Comment by priyang12** [comment]
hi, can I work on this issue if no one is working on it? @seancolsen @kgodey

**Comment by kgodey** [comment]
Go ahead @priyang12!

**Comment by priyang12** [comment]
hi, I am having an issue Inspecting the page during a test. I followed [readme](https://github.com/centerofci/mathesar/tree/master/mathesar/tests/integration#readme) Page and when i run the 
`docker exec mathesar_service pytest --headed --no-cov -k test_page_shows_welcome_text
 ` Command 
I got this error 
```
startup-window
E       <launched> pid=323
E       [pid=323][err] [323:323:0315/105628.185292:FATAL:ozone_platform_x11.cc(231)] Check failed: x11::Connection::Get()->Ready(). Missing X server or $DISPLAY
```
I am using a mac machine and I installed XQuartz and change the security permission has the error has something to do with that??

**Comment by silentninja** [comment]
Have you tried setting the ip for the `$DISPLAY` environment variable?

> (For Mac OS only): Also change DISPLAY=${DISPLAY} to DISPLAY=${YOUR_IP}:0, e.g. DISPLAY=192.168.29.198:0
> For Mac OS, run xhost +${YOUR_IP} -- e.g. xhost +192.168.29.198

**Comment by pavish** [comment]
@priyang12 

Please make sure all the steps are followed. You might have missed a few:
1. Identify your host's ip address. You can run `ifconfig` to obtain it. Assume your ip is `192.168.29.194`
2. Modify docker-compose.yml.  Change `DISPLAY=${DISPLAY}` to `DISPLAY=${IP}:0` eg., `DISPLAY=192.168.29.194:0`. Notice that you have to add `:0` after your ip.
3. `Run xhost +{your ip}` on your host. Eg., `xhost +192.168.29.194`

After this, try running the tests in headed mode again
