### ISSUE TITLE
Add E2E test for toggling an indeterminate checkbox to true, false, true

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1131]
## Context

See #1122 for more info and instructions on writing E2E tests.

## This test

Write an E2E test which asserts that "toggling an indeterminate checkbox to true, false, true" works as-expected. Here's a visual demo of what the test should do:

![Peek 2022-03-02 17-09](https://user-images.githubusercontent.com/42411/156458049-275c4d7d-30d9-40b8-8d45-09e21ed90887.gif)

**Comment by Cronus1007** [comment]
@seancolsen Shall I work upon this issue?

**Comment by silentninja** [comment]
Thanks! @Cronus1007, I have assigned the issue to you. Let us know if you need any help.

**Comment by Cronus1007** [comment]
@silentninja @kgodey Shall I create a new file under the `tests/integration` folder for this test or is there any such file which is most relevant with this type of test.

**Comment by seancolsen** [comment]
@Cronus1007 

> Shall I create a new file under the tests/integration folder for this test or is there any such file which is most relevant with this type of test.

Good question. There's not really a strict scheme for organizing these E2E tests. 

Here's an idea:

1. Start a new file called `test_cells.py`.
2. Add your new test there.
3. Then also move `test_edit_cell` into that file.
