### ISSUE TITLE
Insert newlines in TextAreaCell only via keyboard shortcut

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1134]
## Current behavior

(When column has Mathesar Type of "Text" and TextAreaCell is displayed)

- If the Text data type is configured without a field size restriction or with a higher limit, a textarea is displayed. Pressing `Enter` in edit mode on the textarea will insert a newline.

## Desired behavior

- Pressing `Enter` with any combination of the following modifier keys inserts a newline at the users cursor position:

    - `Ctrl`
    - `Alt`
    - `Meta` (aka "Cmd" on Mac OS)

- Pressing `Enter` (without any modifiers), or `Shift+Enter`, or `Shift` + any of the above modifiers + `Enter` saves the cell and transitions from edit mode to select mode.

## Additional context

- #1119

**Comment by nk183** [comment]
hi @seancolsen  can I work on this issue

**Comment by kgodey** [comment]
Go ahead @nk183

**Comment by nk183** [comment]
hi @seancolsen @pavish  @kgodey 
I this issue, When text type is selected for a column component : TextArea is called (which is implemented using "textarea"), if we apply char limit  to it, component : TextInput is called (which is implemented using "input").
In case of "input" tag, we can't add new line in it, but we can in "textarea".
But I am not able to understating [code](https://github.com/centerofci/mathesar/blob/de84e7c1418f700ed2758d502b6ea8cfdd4f962a/mathesar_ui/src/components/cell/utils.ts#L23)
the "if"  condition on that. Can you please explain or give me some reference to read.

**Comment by pavish** [comment]
@nk183 That logic is currently being changed to be not based on length, but based on the db type.

There are two types of text input:
1. inputs like uri, email etc., where new lines are not allowed, and
2. text where new lines should be allowed.

For this issue, we need to only consider case 2 and handle the events within the `TextAreaCell`. This issue does not deal with `TextBoxCell`.

There is no much documentation on code architecture, but here are some issues and PRs which might help you understand this better.
* https://github.com/centerofci/mathesar/discussions/1119
* https://github.com/centerofci/mathesar/issues/1118
* https://github.com/centerofci/mathesar/pull/1080

Please let us know if you have further questions, you can also ask them impromptu on our [matrix channels](https://wiki.mathesar.org/en/community/matrix).

**Comment by nk183** [comment]
Hi @pavish ,Thanks for the reply
I am sure that this logic is returning TextBoxCell when theres a limit on text field.

**Comment by pavish** [comment]
@nk183 What I meant is that it behaves that way on the master, but it is being updated on a different branch. I've mentioned the draft PR above: https://github.com/centerofci/mathesar/pull/1144. For Text type, we will never get a TextBoxCell when that PR is merged.

For this particular issue, that logic does not matter. We only need this change to made for TextAreaCell. I can see your confusion arises based on the issue description, I've updated it to make it clearer. Please @ me if you have further questions.

**Comment by aviwad** [comment]
I see @nk183 is already assigned on this. I am interested in this issue too. Should I try to form a PR or is it considered rude if it's already assigned to someone?

**Comment by kgodey** [comment]
@aviwad We generally only assign one person to a task at a time. Please find an unassigned issue ([here's a list](https://github.com/centerofci/mathesar/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3A%22good+first+issue%22)) and comment on it indicating your interest. A maintainer will assign it to you.

Our [contribution guide](https://wiki.mathesar.org/en/community/contributing) might also help.

**Comment by seancolsen** [comment]
At @pavish's suggestion, I have moved this to a later milestone. He is assigned to the PR and will finish out the work that's needed here.
