### ISSUE TITLE
Check whether API accepts strings for boolean columns

### ISSUE THREAD

**Issue by mathemancer** [centerofci/mathesar#1146]
## Description

As in #1145 , we're not doing any validation in the serializer layer to prevent a string being input for the value in a `BOOLEAN` column. Unlike #1145, I can't find any examples where the API is actually accepting a string for a boolean.

## Expected behavior

We should guarantee that we don't accept strings for boolean column values.

## Additional context

This issue is a draft until we know whether it's a real problem, or just something we should validate in the serializer.

**Comment by sahilsaini110** [comment]
@mathemancer I would like to work on this issue, please assign this to me.

**Comment by silentninja** [comment]
@sahilsaini110 This issue is still a draft and not to be worked on until the `status` label is changed to `ready`.

**Comment by sahilsaini110** [comment]
Sure, I am looking forward grt some issues.

**Comment by silentninja** [comment]
@sahilsaini110, the issues listed below would be good candidates to work on. 

- #1145 
- #1107

**Comment by mathemancer** [comment]
After a bit of research, it seems SQLAlchemy _does_ validate that input is a proper boolean.
