### ISSUE TITLE
[docs] Document the steps to set up the project locally

### ISSUE THREAD

**Issue by ManishShah120** [centerofci/mathesar#1158]
## Problem
Presently, we only have the steps in the documentation to get started with development with docker container, which doesn't allow us to install third-party extensions to the project only for development or debugging purpose, and also it's a bit challenging for any beginner to work on the project with the docker instances.

## Proposed solution
It would be nice if we could document the steps to be followed to successfully set up the project in our local environment.

## Additional context
None

**Comment by ManishShah120** [comment]
As discussed on the IRC channel, I am working on it, once I am able to set it up, I'll open a PR for this. 

--Thank You

**Comment by kgodey** [comment]
Thanks for opening this issue @ManishShah120. I've assigned it to you since you're working on it.

**Comment by kgodey** [comment]
@ManishShah120 any update on this?

**Comment by kanishk88** [comment]
hey @kgodey is @ManishShah120 talking about https://docs.mathesar.org/contributing/local-dev/#local-development-setup 
documentation ?

**Comment by kgodey** [comment]
@kanishk88 This issue was to create a version of the local development setup guide that did not use Docker. I'm going to close it because no one else has asked for this.
