### ISSUE TITLE
[UI] Error message gets displayed even when the table name is set to its prior name

### ISSUE THREAD

**Issue by ManishShah120** [centerofci/mathesar#1161]
## Description
When we try to rename a table, but later undo the field with the name of the table as before the error message is still displayed, which should not be expected.

## Expected behavior
The error message should not be displayed as soon as the table name is set to its prior name.

## To Reproduce
```
1. Create an empty table.
2. Try to rename the table name.
3. Then again undo the changes or keep the name of the table as before.
```
## Environment
 - OS: (_eg._ macOS 10.14.6; Fedora 32)
 - Browser: (_eg._ Safari; Firefox; Brave; Chrome)
 - Browser Version: (_eg._ 13; 73)
 - Other info:

## Additional context
Here's a GIF/Video of it

https://user-images.githubusercontent.com/45564404/157963470-f9d2dd53-19ac-4368-a891-0a75b5df5be3.mp4

**Comment by nk183** [comment]
@kgodey @ManishShah120 can I work on this issue?

**Comment by hanuasfaw** [comment]
Hello, there. I am working on a solution to this issue!
