### ISSUE TITLE
Batch updating column using `/tables/` api should reference column using `id` instead of `column_index`

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar#1167]
## Problem
Batch updating Columns using the `columns` field in the `patch` method of the `/tables/{id}/` does not use `id` of the column rather the column to update is identified based on the position of the column objects. This is not ideal due to the following reasons:
- Similar to the `column_index` which is [deprecated in favour](https://github.com/centerofci/mathesar/issues/839) of `id`.
- Column position could have changed resulting in updating a wrong column

## Proposed solution
The following changes have to be made:

-`PATCH` method of the `/tables/{id}` api which has the following structure 

```
{
    "columns": [
        {
            "name": "id",
            "type": "INTEGER"
        },
        {
            "name": "Center",
            "type": "TEXT"
        }
    ]
}
```

should be replaced with 

```
{
    "columns": [
        {
            "id": 1, // Use column id to reference a column, rather than assuming the column based on its index.
            "name": "id",
            "type": "INTEGER"
        },
        {
            "id": 2,
            "name": "Center",
            "type": "TEXT"
        }
    ]
}
```

- The column id's have to be converted into `attnums` which can be fetched from the column object before sending the column data from the service layer to the database layer(before calling any function from the `db` module)

**Comment by ratika-12** [comment]
Can I work on this?

**Comment by silentninja** [comment]
@ratika-12 This issue needs some understanding of the codebase and Django. I confirm in a few minutes, sorry for the wait.

**Comment by silentninja** [comment]
@ratika-12 I have assigned the issue to you, thanks!

**Comment by silentninja** [comment]
@ratika-12 I have updated the proposed solution to make it easier to understand. Let me know if anything is not clear.

**Comment by kgodey** [comment]
@ratika-12 Are you still working on this task? I figured I would follow up since it's been a while and there has not been a PR yet.

**Comment by ratika-12** [comment]
Yes I am working on this task. I will make a pr for this asap.

**Comment by Anish9901** [comment]
@kgodey @silentninja Can I work on this if this is not being worked on currently by @ratika-12?

**Comment by ratika-12** [comment]
Yeah sure !!

**Comment by kgodey** [comment]
Thanks @Anish9901, assigned to you. And thanks for the update @ratika-12.

**Comment by Anish9901** [comment]
>The column id's have to be converted into attnums which can be fetched from the column object before sending the column data from the service layer to the database layer(before calling any function from the db module)

@silentninja Does the attnums have to be passed as a list of attnums to a db layer function or the `id` in validated_data is needed to be replaced with its corresponding attnum.

**Comment by silentninja** [comment]
> `id` in `validated_data` is needed to be replaced with its corresponding attnum?

This should be the preferred option `db` layer should not know about the Django model fields like `id`
