### ISSUE TITLE
Update common-issues wiki to mention common issues with Windows dev environment setup

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#1175]
## Problem
Our windows dev environment setup is rather tricky and developers may run into a range of issues when trying to set it up. While we have documented the steps in our readme, missing any of those steps lead to errors which make it harder for new contributors.

## Proposed solution
We have to update commonly faced problems when such steps are missed, in our [common-issues](https://wiki.mathesar.org/en/engineering/common-issues) wiki page. A PR to update the page should be submitted to our wiki repo: https://github.com/centerofci/mathesar-wiki

## References:
- https://github.com/centerofci/mathesar/issues/1165
- https://github.com/centerofci/mathesar/issues/570
- https://github.com/centerofci/mathesar#developing-in-windows

**Comment by 7saikat7** [comment]
Can I work on it ?? I have faced this issue and solved it now the project is running properly locally on windows 10

**Comment by kgodey** [comment]
Sure, go ahead @7saikat7. You'll need to make the PR to https://github.com/centerofci/mathesar-wiki

**Comment by kgodey** [comment]
Sure, that's fine.

**Comment by kgodey** [comment]
Looks like this is done but wasn't closed by the wiki PR.
