### ISSUE TITLE
Fix undefined displayed during import preview for values in column named with a trailing space

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1177]
## Reproduce

(Use the front end, with Dev Tools open to inspect API requests.)

1. "New Table" > "Import Data" > "Copy and Paste Text"
1. Paste the following text and click "Continue"

    ```csv
    id,a ,b
    1,100,foo
    2,200,bar
    ```

    (Notice that the second column has a trailing space in the column name.)

1. During the data preview, expect to see `100` and `200` in the second column.

1. Instead, observe `undefined`.

    ![image](https://user-images.githubusercontent.com/42411/158440272-e774a4cc-2be1-4b56-9cba-750a96cb19d2.png)

    (Don't click "Finish Import" yet.)

1. Observe an API request made to `/api/db/v0/tables/{table_id}/columns/`. In the response...

    - Expect the name of the second column to be `"a"` (without a trailing space). Why? Because that's what the column name will end up being after the import is finished, which I think makes sense.
    - Observe the name of the column to be `"a "` (with the trailing space).

1. Click "Finish Import".

1. Observe another API request made to that same endpoint which now shows the column name without trailing space. (Good.)

**Comment by seancolsen** [comment]
@silentninja do you think this would make a good first issue?

**Comment by kgodey** [comment]
Quick reminder that we can mark issues as `help wanted` even if they're not good first issues (i.e. if they're suitable for community contributors, but not as an introduction to the codebase).
