### ISSUE TITLE
Columns re-ordered after type change

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1185]
## Reproduce

1. "New Table" > "Import Data" > "Copy and Paste Text"

1. Paste the following data and proceed to create and view the table (by clicking "Continue" and then "Finish Import").

    ```
    id,a,b
    1,100,200
    2,101,201
    ```

1. Click on the column header for column `a` and change the type from "Number" to "Text", clicking "Save".

1. Expect columns to be ordered `id`, `a`, `b`.

1. Once I did this and observed the columns to be ordered `a`, `id`, `b`. Another time. I observed the columns to be ordered `id`, `b`, `a`. I'm not sure what affects the ordering of the columns, but the order seems to remain consistent (even if incorrect) after the type-change operation.

## Implementation
The backend should make sure that the column list in the API should always be ordered by suitable `index`.

## Additional details

- The front end displays the columns in the order it receives them from the columns API. In this case the API is returning the columns out-of-order, which is why I've marked this as a backend bug.
- A while back, we had a [discussion about whether the user should be able to re-order columns](https://github.com/centerofci/mathesar/discussions/803) in which we decided _not_ to support re-ordering columns, at least for now.

**Comment by kgodey** [comment]
> @kgodey for implementation, can we assume that ordering by the column's `id` is a reliable-enough way to obtain the expected column order?

@seancolsen I think it would be ideal for the API to return the column's index as a property and the frontend should order by that. Please make an issue for that; until then, it's fine to order by `id`.

**Comment by seancolsen** [comment]
> Please make an issue for that

I started a [discussion](https://github.com/centerofci/mathesar/discussions/1186) about how to communicate explicit column order, beyond the `id`.

**Comment by vorakunal** [comment]
May I work on this issue?

**Comment by silentninja** [comment]
`column_index` is just incorrectly computed `attnum`. `attnums` is the order by the column are stored on the database, the columns should be ordered by `attnum` and not by `id`

**Comment by silentninja** [comment]
Thanks! @vorakunal I have assigned the issue to you. Let us know if you need any help.

**Comment by mathemancer** [comment]
> `column_index` is just incorrectly computed `attnum`. `attnums` is the order by the column are stored on the database, the columns should be ordered by `attnum` and not by `id`

Sort of, it's an incorrectly computed "dense rank" of the column `attnum`. I agree with @silentninja that we should just use `attnum`, though. For more detail see [my comment](https://github.com/centerofci/mathesar/discussions/1186#discussioncomment-2387738) in the relevant discussion.

**Comment by vorakunal** [comment]
@seancolsen I am not able reproduce the error, I followed the instruction but order is consistent after the type-change operation for both the column.
I'm attaching screenshot of the table after performing operation.

![Screenshot (140)](https://user-images.githubusercontent.com/22933921/160259919-71329a0e-caa6-45bc-b38c-7260c116c808.png)

**Comment by seancolsen** [comment]
@vorakunal Yeah, the fact that you can't reproduce it is not too surprising, given that I was observing some inconsistent behavior. 

@silentninja and @mathemancer  since you have a deeper understanding of the root cause of the problem, would you be able to provide more resilient reproduction steps?

**Comment by silentninja** [comment]
@vorakunal By default, Postgres uses random order, most of the time it is based on the order it is on the disk(creation order) but it cannot be relied upon as per [postgres docs](https://www.postgresql.org/docs/7.4/queries-order.html) It is a random issue and cannot be deterministically reproduced. It is better to have an explicit sorting order than reply on random ordering as some of our use cases depend on the order of the columns

**Comment by silentninja** [comment]
@seancolsen Are there any features on the frontend that rely on the order of the columns, if so can't they be replaced(or reference a column) by column `id`

**Comment by seancolsen** [comment]
@vorakunal just to clarify (from chatting with @silentninja) there is no need to successfully reproduce the bug before applying a fix where you order the columns by the `attnum` property.

**Comment by vorakunal** [comment]
@seancolsen @silentninja Alright, I'll look into it.
Thank you.

**Comment by kgodey** [comment]
Unassigned due to inactivity.

**Comment by Anish9901** [comment]
Can I work on this?

**Comment by kgodey** [comment]
@Anish9901 Sure, go ahead!
