### ISSUE TITLE
Refactor storage of icon definitions

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1187]
## Current code

- In `mathesar_ui/src/sections/table-view/actions-pane/ActionsPane.svelte` we have:

    ```svelte
    <MenuItem on:click={handleDeleteTable} icon={{ data: faTrashAlt }}>
      Delete
    </MenuItem>
    ```

    Here, `{ data: faTrashAlt }` is an object of type `IconProps`. Search the codebase for the literal string `{ data: fa` and you'll see more objects like this.

- And we have some plain `<Icon />` component instances like this code in `mathesar_ui/src/component-library/help/Help.svelte`:

    ```svelte
    <Icon data={faQuestionCircle} />
    ```

    Search the codebase for for the regex `<Icon[^/]*?data` and you'll see more like this.

## Desired code

- I'd like to move all that icon data to a central files.

- We'd have `mathesar_ui/src/component-library/common/icons.ts` for all icons used by the component library (any files within `mathesar_ui/src/component-library`).

- And we have `mathesar_ui/src/icons.ts` for all the icons used by Mathesar (any files within `mathesar_ui/src/` and _not_ in  the component library).

- That `ActionsPane.svelte` example above would become:

    ```svelte
    <MenuItem on:click={handleDeleteTable} icon={iconDelete}>
      Delete
    </MenuItem>
    ```

    and `mathesar_ui/src/icons.ts` would include:

    ```ts
    export const iconDelete = { data: faTrashAlt };
    ```

- That `Help.svelte` example above would become:

    ```svelte
    <Icon {...iconHelp} />
    ```

    and `mathesar_ui/src/component-library/common/icons.ts` would include:

    ```ts
    export const iconHelp = { data: faQuestionCircle };
    ```

- The FontAwesome icons describe the _appearance_ of the icon. In contrast, our `icons.ts` files would describe the _action_ or _concept_ within the context of either the component library or Mathesar. These files would provide a centralized place for us to keep track of the mapping between app concepts and icons.

## Rationale

- It help us keep our icons consistent. (E.g. helping to answer the question "Should I use `faTrash` or `faTrashAlt`"?)

- It makes it easier to pick out icons for concepts we've already defined. (E.g. Helping to speed up the process of figuring out that we use `faThList` for the concept of "grouping".)

- It allows us to add aliases when we'd like to designate the same icon for different actions.

- It helps us move closer supporting custom icons eventually.

@seancolsen said:
> @pavish This is a proposal for a very small refactor that I'd like to run by you. If this sounds good, you can mark the ticket as ready and label it as a good first issue.

Update from @pavish: The proposal sounds good and the issue is ready for implementation.

**Comment by pavish** [comment]
@seancolsen Sounds good to me.

**Comment by rskbansal** [comment]
May I do this one ?

**Comment by pavish** [comment]
Sure @rskbansal, go ahead.

**Comment by kgodey** [comment]
@rskbansal I wanted to follow up on this issue since it's been a few days and I don't see a PR yet. Please let us know if you need any help or if you are no longer working on the issue.

**Comment by manasa-sm** [comment]
Can I work on this?

**Comment by seancolsen** [comment]
Yes, thanks @manasa-sm I've assigned you to it.

**Comment by manasa-sm** [comment]
@seancolsen , I have a small question. Can I name the icons (iconCoffee, iconRocket, etc) similar to that of the fontawesome like this? Or should they be more meaningful
![image](https://user-images.githubusercontent.com/54235627/163677496-5b987a3d-b950-45cc-9b23-8298675c5aa2.png)

**Comment by Cronus1007** [comment]
@kgodey @seancolsen Although this issue has been assigned to @manasa-sm but still can I take up this issue. Since this issue  as well as the PR has not shown any activity in recent times.

**Comment by seancolsen** [comment]
Ok @Cronus1007 that's fine with me. I've closed #1294 and re-assigned this ticket to you.

**Comment by seancolsen** [comment]
@Cronus1007 Are you still working on this?

**Comment by Cronus1007** [comment]
@seancolsen Yes I am working upon this issue.

**Comment by seancolsen** [comment]
I'm putting this in Cycle 3 because it'll help Ghislaine with the styling work and it's a great first issue for devs just starting out with our front end code.

**Comment by rajatvijay** [comment]
Hi @seancolsen 

As you wrote: 
> The FontAwesome icons describe the appearance of the icon. In contrast, our icons.ts files would describe the action or concept within the context of either the component library or Mathesar. These files would provide a centralized place for us to keep track of the mapping between app concepts and icons.


My understanding is that the variable names in the `icons.ts` file should be according to the concept not the appearance. So for example: a trash can icon should  not be `iconTrashCan` rather `iconDelete`. 

If my above understanding is correct here are the problems that I see with this approach

1. Not every icon is used under a fixed concept. For example the icons that we are using in stories randomly  -`faHammer`, what concept do you suggest should be associated here? 
2. Some icons can be used under multiple concepts but same sentiment. For example: `faCheck` can be used for `apply`, `proceed`, `confirmation` but the sentiment is same here: `positive`


Do you think we should rather keep the name of the variable same as of the icon name. So for example: a trash can icon will be `iconTrashCan` instead of `iconDelete`.

**Comment by seancolsen** [comment]
For point 1, this ticket does not apply to stories components. Those components may not even need any changes. 

For point 2, we want to use separate names that correspond to the separate concepts. The line is a little blurry though so some judgement will be required. 

One of the goals of this ticket is to decouple our application code from FontAwesome so that we can begin creating custom icons. 

I can explain more when I'm at my desk, but that might be up to 6hr from now.
