### ISSUE TITLE
A number type column doesn't show '0' value

### ISSUE THREAD

**Issue by A1O** [centerofci/mathesar#1189]
## Description

A number type column shows empty cell if value is equal to 0.

## Expected behavior

A digit '0' should be visible in a cell.

## To Reproduce

1. Create a new column "col1"
2. Change "Data type" to  "Number"
3. Type digit "0" in any cell for the column "col1"

## Environment
 - OS: Docker (docker-compose.yml)
 - Browser: Chromium, Firefox

## Additional context

![Untitled](https://user-images.githubusercontent.com/6394268/158788181-7046fe88-dc1e-48a8-9a3b-000fc3b37931.png)

**Comment by jals413** [comment]
May i work on this issue ?

**Comment by jals413** [comment]
I will need some time , but surely I will try my best to solve this issue <3

**Comment by kgodey** [comment]
@jals413 I wanted to follow up on this issue since it's been a few days and I don't see a PR yet. Please let us know if you need any help or if you are no longer working on the issue.

**Comment by jals413** [comment]
I am currently busy with my personal and college work so don't know when I will be able to work on the issue , So better unassign me for this issue , Once I get free I will try to contribute on some other issue

**Comment by kgodey** [comment]
Thanks for the update @jals413, I've unassigned you.

**Comment by muhsinkamil** [comment]
Hey @kgodey,  I can take a look. Please assign to me

**Comment by seancolsen** [comment]
Thanks @muhsinkamil I've assigned you. Let us know if you need any help.
