### ISSUE TITLE
Add ESLint rule to prohibit explicitly marking class members as public

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1195]
## Problem

- Some of our TypeScript classes have members explicit marked as `public` (e.g. in `mathesar_ui/src/component-library/common/utils/contextValidationUtil.ts`). This keyword is not necessary.

- For consistency's sake, we'd like to standardize on code that does not have `public`, and we'd like to prevent this keyword from inadvertently cropping up in the codebase going forward.

## Solution

1. Modify `.eslintrc.cjs`, using the [`explicit-member-accessibility` rule](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/explicit-member-accessibility.md) to make ESLint show errors for the `public` keywords we already have in `contextValidationUtil.ts`.

1. Remove the `public` keywords necessary to silence the errors from ESLint.

## Rationale

See https://github.com/centerofci/mathesar/pull/1144#discussion_r828241010

**Comment by seancolsen** [comment]
@pavish Does this sound good to you? If so, you can set the status to ready and mark it as a good first issue.

**Comment by priyang12** [comment]
hi, can i work on this issue?

**Comment by seancolsen** [comment]
Thanks @priyang12 I've assigned it to you.
