### ISSUE TITLE
Raise the default Playwright page timeout value

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1197]
## Problem

- Some E2E tests are failing intermittently. For example, [here](https://github.com/centerofci/mathesar/runs/5605572101?check_suite_focus=true) is a CI job that failed but passed when re-ran.
- I'm theorizing that we're hitting Playwright's default 5-second timeout on some operations that take longer.

## Solution

- I think we should raise the timeout value globally.
- Playwright has a [set_default_timeout](https://playwright.dev/python/docs/api/class-page#page-set-default-timeout) method that we can run on the `page` object.
- We need to figure out where in our E2E testing stack is appropriate to call this function so that it applies everywhere.
- I think we should set it to 10 seconds.

## Tips

- If you're working on this, I'd suggest the following. In order to test that your fix works, first set the timeout to something very small, like 50ms, and verify that you see some tests which fail (giving you an indication that your setting has been correctly applied). Then tweak the setting to 10 seconds.

## Additional context

- [Discussion on Matrix](https://matrix.to/#/!UnujZDUxGuMrYdvgTU:matrix.mathesar.org/$xZcuhHRDrvqO7cBYXODdqs1tmRxuWcPlHmxobSR_beo?via=matrix.mathesar.org&via=matrix.org)

**Comment by seancolsen** [comment]
Yes, thanks @Cronus1007 I've assigned it to you

**Comment by Cronus1007** [comment]
@seancolsen @kgodey The solution for this problem might be while we intialize our page object using 
```
def run(playwright):
    webkit = playwright.webkit
    browser = webkit.launch()
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://example.com")
    page.screenshot(path="screenshot.png")
    browser.close()

with sync_playwright() as playwright:
    run(playwright)
```
we can use `page.set_default_navigation_timeout(10000)` in this function to raise the playwright page timeout value. 
What's your opinion about this issue?

**Comment by seancolsen** [comment]
@Cronus1007 I don't quite understand your proposal. Can you describe the changes you have in-mind more specifically? Where would that code go? Alternatively, you could open a draft PR and we can discuss the approach there, even if it's not fully-functional.

Everyone on our team is new to Playwright, so I don't think any of us are going to know exactly the best way to do this off-the-bat. We'll just need to try fiddling with it until we can get it working, I think.

**Comment by aviwad** [comment]
hi. i'd like to take a go at this too! I forked the repo and added the following line of code to the `test_import_from_file` function: 
`page.set_default_timeout(50)`
purely to test if the fix would result in more errors (meaning the setting was applied).

However, I haven't been able to run the integration tests myself. Following the integration steps:
`docker exec mathesar_service pytest --no-cov -k test_import_from_file`
Results in the following error message: 
```
E       ║ Looks like Playwright Test or Playwright was just installed or updated. ║
E       ║ Please run the following command to download new browsers:              ║
E       ║                                                                         ║
E       ║     playwright install                                                  ║
E       ║                                                                         ║
E       ║ <3 Playwright Team                                                      ║
E       ╚═════════════════════════════════════════════════════════════════════════╝

```
running CLI into the mathesar-service docker, and running "playwright install" ends halfway through chromium's installation. digging through the mathesar-service docker logs, the reason is this Python traceback. Now I am lost, as the mathesar-service itself wasn't running, so I can't debug if my integration fix would work.
the traceback:
Traceback (most recent call last):

```
  File "/code/manage.py", line 22, in <module>
    main()
  File "/code/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/code/config/settings.py", line 87, in <module>
    for db_key, url_string in decouple_config('MATHESAR_DATABASES', cast=Csv(pipe_delim))
  File "/usr/local/lib/python3.9/site-packages/decouple.py", line 199, in __call__
    return self.config(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/decouple.py", line 83, in __call__
    return self.get(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/decouple.py", line 68, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: MATHESAR_DATABASES not found. Declare it as envvar or define a default value.
2022/03/22 00:49:51 Command exited with error: exit status 1

```

**Comment by aviwad** [comment]
UPDATE: Turns out I hadn't properly implemented the changes to run integration tests. I wiped my Docker and restarted (This time changing docker-compose.yml)
However, result is still the same:
```
mathesar_service  | decouple.UndefinedValueError: MATHESAR_DATABASES not found. Declare it as envvar or define a default value.
mathesar_service  | 2022/03/22 01:15:29 Command exited with error: exit status 1
mathesar_service exited with code 1

```
mathesar_service doesn't run, and hence not possible to do anything

**Comment by Cronus1007** [comment]
@seancolsen Sure I have submitted a PR linking this issue. We can discuss it there.
