### ISSUE TITLE
Add support for updating display options using tables api column field.

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar#1206]
## Problem

#1207 adds support for suggesting display options for a column when data is imported. Once the suggested changes are finalized by the user, we would save the changes by calling the `PATCH` method of the `/tables/` api . But there is no way to save display options using the `/tables/` api.

## Proposed solution
 In order for the frontend to  save the suggested display options, `/tables/` api should accept `display options` field as part of the `columns` object in the `PATCH` method and update the display options for the column based on that data

```python
# Current API 

request_body = {
"name": "Column 1",
"type": "NUMERIC",

}
response = {
...table data,
{"columns": [
    "name": "Column 1",
    "type": "NUMERIC"
    ]
}}


# Expected API
request_body = {
"name": "Column 1",
"type": "NUMERIC",
"display_options": {"show_as_percentage": true} #  Will raise error if done with current codebase,
}
response = {
...table data,
{"columns": [
    "name": "Column 1",
    "type": "NUMERIC",
    "display_options": {"show_as_percentage": true}
    ]
}}

```

## Additional Context
- Blocked by #1227

**Comment by Cronus1007** [comment]
@silentninja Can you please elaborate the problem statement since I am not unable to clearly get the idea out of it?
Is there a need to set up your work in #1205 in order to get a better idea about this issue?

**Comment by silentninja** [comment]
Please look into #1207 for the reasoning behind this issue. Also, this issue is slightly complicated and not suitable for new contributors. Moreover, we need this issue to be completed for #1205 to be fully complete. If you are comfortable with the codebase, I would love to assign you this as it is really a step forward compared to a good first issue.

**Comment by kgodey** [comment]
@Cronus1007 as @silentninja mentioned, this issue needs more in-depth codebase knowledge and is not a `good first issue`. Please let us know if you're still comfortable with working on it.

**Comment by Cronus1007** [comment]
@kgodey @silentninja Currently I am looking into #1205 and #1207  so I will update whether I would be able to take this by the eod.

**Comment by mathemancer** [comment]
As @pavish pointed out, it's not clear that we still need columns in the tables endpoint.

**Comment by kgodey** [comment]
@mathemancer @pavish The [Import Preview spec](https://wiki.mathesar.org/en/engineering/specs/import-preview-api) says that we save finalized names and types of columns in bulk using the `/tables/` API. Is this no longer true?

**Comment by kgodey** [comment]
> Can we not use the columns endpoint directly

This would not be RESTful, you would be updating multiple resources at once. We generally only use `GET` for list endpoints (and `POST` to create a new resource). We would need to use `PUT` to update all columns at once, which doesn't make sense for a list.

If we want to replace this, I think we should set up a new bulk operations endpoint but it's not worth prioritizing now.

> Either way, I see no point in updating the `tables/` endpoint to support patching column display options.

We're not updating the `tables/` endpoint. This issue is blocked by a redesign of the import preview page. At that point, we'll figure out what APIs are needed and make changes.

**Comment by pavish** [comment]
@kgodey Ah, now I remember why, and see the reasoning behind this issue. Thanks for the clarification.

**Comment by kgodey** [comment]
I don't think we need this, closing.
