### ISSUE TITLE
Design for suggesting display options

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar#1227]
## Problem

When users import data into Mathesar, we are able to infer the imported data and suggest Column types. 

We also have [display options](https://github.com/centerofci/mathesar/issues/392) that can be set for a Column. These display options can also be inferred from the imported data. Moreover, certain Column Types like `Mathesar_Money` need the display options to be inferred during the import process due to various reasons listed in #1207 comments. We need a UX to let the users know of the inferred display options

**Comment by kgodey** [comment]
I'm closing this, we can reopen or re-spec if needed.
