### ISSUE TITLE
Setup bot for auto dependency updates for npm packages

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#123]
**Problem**
npm dependencies need to be regularly monitored and updated to the most recent minor version.

**Proposed solution**
Having a gh bot to do this for us and raise a PR with the changes, would make it a lot more easier for us to maintain this in the long run.

**Comment by pavish** [comment]
I initially thought this was a good idea but now I don't think it is. We already have GH's dependabot which messes up the entire package-lock.json file trying to force update packages, breaking other parent packages.

I have already mentioned reasons behind ignoring Depandabot's PR on several occasions adding a reference to [Dan Abramov's blog post](https://overreacted.io/npm-audit-broken-by-design/). We already have a bot to raise an issue when npm audit fails and it's best we fix failures manually.

@kgodey @seancolsen I think we can close this issue. What do you both think?

**Comment by seancolsen** [comment]
@pavish  Agreed

**Comment by kgodey** [comment]
Sounds good.
