### ISSUE TITLE
Functionality to select all rows at once

### ISSUE THREAD

**Issue by aditmehta9** [centerofci/mathesar#1244]
## Problem
We can select one row at a time right now but if we add checkbox near id column to select all rows at once it would be great if I want to select majority of rows and keep only few

## Proposed solution
Addition of one checkbox to select all rows near ID column

**Comment by kgodey** [comment]
@aditmehta9 We have [a future milestone for performing bulk operations on records](https://github.com/centerofci/mathesar/milestone/9). We need to think through the user experience of working with multiple records. I've marked this issue as a draft until we have a design for it.

**Comment by kgodey** [comment]
We can select multiple rows now, so I'm closing this ticket.
