### ISSUE TITLE
Data type of ID

### ISSUE THREAD

**Issue by aditmehta9** [centerofci/mathesar#1245]
## Problem
Right now we can select only integer for the datatype of ID. But if a user clicks on ID dropdown -> Number-> Number Type. In Number Types, multiple options are shown i.e Float, decimal, integer. But can't select the other 2 number type. Either this option should not be shown or the user should be able to define this data type.

## Proposed solution
Either this option should not be shown or the user should be able to define this data type.

## Additional context
![Screen-Recording-2022-03-27-at-1](https://user-images.githubusercontent.com/35133994/160289509-7c6d922e-4522-4398-afba-975c84f538d7.gif)

**Comment by silentninja** [comment]
We don't support changing the type of columns with dynamic defaults. In this case, `id` column has a `autoincrement` default, so the request gets rejected by the backend. The frontend should not allow such an operation to happen or show an error proper response.

**Comment by kgodey** [comment]
We have [a design issue for handling primary keys](https://github.com/centerofci/mathesar/issues/439). We'll handle the problems listed in this issue there, I've linked to this issue in the issue description for #439. I'm going to close this issue since there's no work to be done here yet.

**Comment by kgodey** [comment]
I wanted to add: Thanks for reporting, @aditmehta9! Some of our features are still unfinished since we're still working towards our first release. Please continue to report any issues you see.
