### ISSUE TITLE
Retain cursor position when changing text within FormattedInput

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1248]
## Current behavior

1. In Storybook, open the NumberInput story.
1. Set the input to contain text `134`.
1. place the cursor between `1` and `3`.
1. Type `2`.
1. Expect the cursor to be between `2` and `3`.
1. Observe the cursor to be after `4`.

    This happens because the value of the input gets reformatted to add the comma.

## Desired behavior

- After modifying the input (via inserting text or deleting text), the cursor position generally meets users' expectations.

- There may be some edge cases where users expectations are not crystal clear. That's okay. We just want to offer some improvement that meets the expectations under most circumstances. For example, let's say we begin with `12,345` and the cursor between `1` and `2`. Then we press forwards-delete. We end up with the text `1,345`. Where should the cursor go? Between `1` and `,` or between `,` and `3`? Either would be fine and would be an improvement over the current behavior (where the cursor ends up at the very end).

## Implementation

1. In `FormattedInput.svelte`, in the function `handleChildValueChange`, you have access to:

    - the value before re-format (as `userInput`)
    - the cursor position before re-format (as the `cursorPosition` property of the return value from `getOutcomeOfBeforeInputEvent`)
    - the value after reformat (as `parseResult.intermediateDisplay`)

1. Write a pure function that takes input of the three values above and returns the resulting cursor position after the text has changed.

1. I suggest using https://www.npmjs.com/package/fast-diff to diff the text values. Then use the old cursor position to figure out where _in the diff_ the cursor should go, and use the diff to figure out where the cursor should go in the resulting text.

**Comment by priyang12** [comment]
hi, I think I have solved this issue should I make a PR, sorry I forget to ask here first and I have used the above package fast-diff but I installed it in dep should I move to devdep

https://user-images.githubusercontent.com/72823974/161074076-4b5629ca-b302-4ff5-9e69-2b0b3cd9dedb.mov

**Comment by seancolsen** [comment]
That's great @priyang12. The behavior in your demo video is exactly what we're looking for. When you open your PR we can sort out any issues with package dependencies there. Thanks!
