### ISSUE TITLE
Setup an Icon library with credits to creators

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#125]
Currently the required icons for Mathesar is taken from the Noun project as per my understanding. @ghislaineguerin let me know if this is right. The licence for each of those icons is unknown. We need to check them and ensure that we can use it in our code, and include appropriate credits if applicable.

We will need to setup a publicly shared icon library in Figma, and have an icon component system in place.

**Comment by kgodey** [comment]
I'm going to close this, we're using different icons now.
