### ISSUE TITLE
Support for Adding Formula Columns in Data Explorer

### ISSUE THREAD

**Issue by ghislaineguerin** [centerofci/mathesar#1252]
As part of the flow for #1065, UI to support various formula settings is required.

## Formula settings
The user should be able to select a formula and define the parameters for that formula. The UI elements for each formula might vary and could include different types of selectors and custom components for actions such as column selection. 

Additionally, these settings will include descriptions to clarify formula concepts if needed.

### Formula selection
1. Browsing the list of available formulas and identifying the formula you need quickly
2. Searching the available formulas
3. Formula placement within the data explorer

### Formula configuration
For every formula listed on [Formulas](https://wiki.mathesar.org/en/product/specs/2022-01-views/04-formulas)
1. User sets a formula's parameters
2. User edits a formula's parameters
3. User changes the formula of an existing formula column

## Additional Context
The [Formulas](https://wiki.mathesar.org/en/product/specs/2022-01-views/04-formulas) page of the Views product spec.

**Comment by kgodey** [comment]
@ghislaineguerin @Dhruvi16 Please close this once https://github.com/centerofci/mathesar-wiki/pull/47 is merged.
