### ISSUE TITLE
Deleting existing rows duplicates newly added rows

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#1287]
## Description
* Open a table with few rows so that there is only one page of rows. Say 10 rows.
* Add a few new rows. Notice the new rows highlighted in green.
* Delete a few existing rows, notice that the rows get refreshed and new rows are loaded in place of deleted rows.
* Notice that the previously added new rows which are duplicates do not get removed.

Resulting in this state:
![Screenshot 2022-04-15 at 12 25 24 AM](https://user-images.githubusercontent.com/11850603/163457868-94698a21-7d1f-4c98-a6cf-ee7dfa74f7f1.png)

## Expected behavior
Duplicates from the newly added rows should get removed.

This was one of the cases previously handled, there might have been a recent regression. Anyone working on this issue must add integration tests for this scenario.

**Comment by kid-116** [comment]
Could I be assigned to this issue?

**Comment by nk183** [comment]
Can I work on this issue?

**Comment by pavish** [comment]
@nk183 Sure, go ahead!

**Comment by nk183** [comment]
hi Pavish is this the expected result

https://user-images.githubusercontent.com/58779460/165279926-ce3c7265-2740-4bc5-b45d-6fcbf07dc6cd.mp4

**Comment by pavish** [comment]
@nk183 The behavior varies based on pagination state.

Scenario 1: When the total number of records are within a single page.
* Upon delete, the deleted rows get removed, rows get fetched from server.
* The fetched rows would contain duplicates of the newly added rows.
* We look through the newly added rows and remove those duplicates from them.
* The status indicators get cleared for the rows that were removed. (The green background)

Scenario 2: When the total number of records exceed the page.
* Assume the page limit is 100, and 110 records are present. We are in page 1, and we add a new record.
* The new record will be shown at the end of the page, with number: 111.
* When we delete an existing row, rows get fetched. The fetched rows are not duplicates of the new row.
* Since there are no duplicates, the new rows are retained.

Scenario 2 is working as expected in master. Scenario 1 has the mentioned bug.

Your video shows the row creation status indicator for the new rows after fetch, which should be removed.
