### ISSUE TITLE
Faulty test `test_import_from_file`

### ISSUE THREAD

**Issue by kid-116** [centerofci/mathesar#1288]
#1270 

## Description
The test `test_import_from_file` in `mathesar/tests/integration/test_imports.py` is failing. It can't be replicated locally and has been troubling in the past as well.

## Expected behavior
The test must give the same result when ran locally and when ran as a part of GitHub workflow checks.

## To Reproduce
Run the test locally and then as a part of GitHub workflows check.

**Comment by kgodey** [comment]
Thanks for opening this, @kid-116.

I think this should be covered by https://github.com/centerofci/mathesar/issues/1285, so I'm going to close this as a duplicate.
