### ISSUE TITLE
Custom `TIMESTAMP`-based type.

### ISSUE THREAD

**Issue by mathemancer** [centerofci/mathesar#129]
**Problem**

We want to store `TIMESTAMP`s in such a way that we can fulfill requirements (1), (2), and (3) from the discussion https://github.com/centerofci/mathesar/discussions/119 .  

**Proposed solution**

When storing a date-time combination (i.e., a timestamp), we should store a timestamp converted to `UTC`, along with the timezone where the date was stored.  This should involve a custom composite type consisting of a naive timestamp along with a TZ in some standardized format (probably UTC offset).

**Comment by pavish** [comment]
@mathemancer Can we close this issue?

We do support both Timestamp with TZ, and without TZ, so I consider all cases to be covered already.

**Comment by mathemancer** [comment]
No.

The PostgreSQL timestamp types can't satisfy the requirements in the linked discussion.  In particular, PostgreSQL doesn't store the timezone given for the `TIMESTAMP WITH TIME ZONE` type, but instead converts the value to the server's timezone and stores it with _that_ timezone. This means we can't satisfy (1) from the linked discussion with the default types. We need a custom type.

I need to write some kind of copypasta for this.

**Comment by kgodey** [comment]
It's still probably worth closing this since we don't plan to work on this anytime soon. We can re-open or open a new fully specced out issue if it becomes a priority.

**Comment by mathemancer** [comment]
@kgodey Fair enough. The implementation of a composite type (this would be the first in our codebase) will likely depend on how the SQLAlchemy removal goes anyway.

**Comment by mathemancer** [comment]
Note to @pavish and @kgodey: Offering users the PostgreSQL `TIMESTAMP WITH TIME ZONE` type is basically offering them a footgun. We may want to consider how that's portrayed. It does not work the way any reasonable person would expect, and for most users it will cause data loss and make Mathesar seem broken.
