### ISSUE TITLE
Number scale not persisting

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1300]
## Reproduce

1. In the front end, edit the DB options for a Number column.
1. Set "Number Type" to "Decimal". Set "Decimal Places" to "3". Click Save.
1. Observe a PATCH request to the columns API which specifies `type_options.scale` to `2`. Good.
1. In the response of this request (and also in the response of the subsequent GET request to the columns endpoint), expect the column to show `type_options` with an object containing a `scale` of `2`.
1. Instead, observe `type_options` to be `null`.

**Comment by silentninja** [comment]
`Numeric` [column type signature](https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-INT) accepts `scale` along with `precision` only. I don't think it is possible to specify `scale` without `precision`.

Also, it is not possible for the backend to set a default value as the backend is not aware of the possible `type_options` for a particular type. So it would end up setting a default value for all the types. We could make it work like `display_options` but that would take a bit of time, so it would be better for the frontend to set a default value for precision.

**Comment by pavish** [comment]
I am going to re-open this issue and mark as draft, because scale is required for money type. However, there is no point in showing precision to the user, and the backend must assume a default value in that case.

It is much better to set a default value on the backend rather than on the frontend.

**Comment by seancolsen** [comment]
@pavish, Mukesh and I have been discussing this privately which has seemed appropriate to me since we're trying to encourage faster work and the responsibility for Numbers rests squarely within our two-person team for this sprint. We're still trying to sort out how we want to handle some of the challenges here, and at this point I'm planning to raise some discussion points with the whole core team during the cool-down period.

**Comment by seancolsen** [comment]
> I might need the scale and precision options for filtering and grouping.

Can you elaborate?

**Comment by pavish** [comment]
I've been building/configuring the input components for all types to display in filters and groups, and they need to make use of the type and display options. I've already configured it for number in the last PR that was raised.

I assume we can leave the configuration of these input components to the owner of the data type, instead of me working on all of them.

**Comment by seancolsen** [comment]
I see. Thanks

**Comment by seancolsen** [comment]
@silentninja and I discussed this on a call today and agreed to move forward with setting the default precision on the back end. As such, I'm marking this ticket as ready.
