### ISSUE TITLE
Unable to load Mathesar when a column contains an unrecognized type

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1316]
## Reproduce

1. Execute this SQL:

    ```sql
    DROP TABLE IF EXISTS "type_test";
    CREATE TABLE "type_test" (
        "id" serial NOT NULL,
        "array_of_ints" integer[]
    );
    INSERT INTO "type_test" ("array_of_ints") VALUES
    ('{ 1, 2, 3 }');
    ```

1. Restart Docker.

1. Try to load the base page.

1. Observe the following error:

    ```
    TypeError at /mathesar_tables/1/
    
    __init__() missing 1 required positional argument: 'item_type'

    ...
    ```

    ![image](https://user-images.githubusercontent.com/42411/165419626-e6679a91-d543-4d03-9ed4-87425161b3ba.png)

## Notes

- I've tried this with a few different types, `integer[]`, `circle`, `jsonb`. I get the same behavior every time.
- After dropping the offending table, I'm able to load Mathesar again.

**Comment by mathemancer** [comment]
Assigning myself because this is a 15 second fix.

**Comment by mathemancer** [comment]
Actually, it's a bit more of a problem the Array problem is different than the non-array column.
