### ISSUE TITLE
Type options dropdown ux is not feasible to use when all options are displayed

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#1325]
## Description
* The type options dropdown (Column header -> Data Type) utilizes vertical space and when the options are all displayed, it exceeds the screen size.
* <img width="1127" alt="Screenshot 2022-04-28 at 11 33 21 PM" src="https://user-images.githubusercontent.com/11850603/165820858-11d882df-f2ea-4bea-9bd5-5bfc9e810b06.png">
* Adding a scrollbar to the options makes is harder to use since there are multiple scrollbars, one for selecting the Mathesar type and one within the database & display options.
* We need to improve the UX for this menu.

## Suggestions
* This is a suggestion, for one of the ways we can improve it by utilizing more horizontal space.
* <img width="1127" alt="Type option suggestion" src="https://user-images.githubusercontent.com/11850603/165822318-8946b411-5b04-45f2-83ee-412ba0a575d6.png">
* Having an additional scrollbar on the right will not seem out of place and we would be able to set a maximum height on this dropdown.

**Comment by seancolsen** [comment]
I just wanted to point out that this is even worse now that I have all the display options in place for the Money type

![image](https://user-images.githubusercontent.com/42411/170782654-ece19c77-6621-468f-aa90-e2b0795ced03.png)

**Comment by kgodey** [comment]
This should be handled by the **Table Inspector** feature.

**Comment by kgodey** [comment]
Closing this since we have the table inspector and the [Data Type Options spec](https://github.com/centerofci/mathesar-wiki/pull/59)
