### ISSUE TITLE
Change column type input to Select

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1328]
## Current behavior

In the screenshot below, the "Set Column Type" field is a scrollable list.

![image](https://user-images.githubusercontent.com/42411/165847702-1d08690a-895e-494a-b3ff-897f1c27d523.png)

As I've been playing with types, I've been frustrated with this interface because the window is so tiny that it's hard to scroll through the options to find the one I want.

## Desired behavior

Use a Select element instead.

**Comment by seancolsen** [comment]
@pavish @ghislaineguerin would this be okay with you?

**Comment by pavish** [comment]
I think we should discuss this later, preferably during the cool down period.

Here's another issue with the type selection dropdown: https://github.com/centerofci/mathesar/issues/1325 that I raised earlier.

I guess the entire dropdown needs to be re-thought once with these problems in mind.

**Comment by seancolsen** [comment]
> I think we should discuss this later, preferably during the cool down period.

Agreed. That's why I've put this in the next "Improvements" milestone, and not in the data types milestone.

**Comment by seancolsen** [comment]
This will be addressed within the Table Inspector re-design.
