### ISSUE TITLE
Allow the user to hide grouping separators for Number and Money

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1329]
## Current behavior

- Look at this table of numbers. The right-most column is storing years as in integer, which I think will be common. But they are displayed with grouping separators. Ugh. That looks terrible!

    ![image](https://user-images.githubusercontent.com/42411/165846061-9648a4bd-2aac-4074-851b-882c77aa8bea.png)

- There is currently no way for the user to disable the display of grouping separators.

## Desired behavior

- The user can use display options to enable/disable grouping separators.

### Schema

- Use the `use_grouping` property as [spec'ed in this comment](https://github.com/centerofci/mathesar/discussions/1243#discussioncomment-2519195).

### UX

- Add a new form field labeled "Use Grouping Separators", with a dropdown input having options "Yes", "No", and "Auto". Display this new field before the already-existing "Format" field.

    For integers, the default is "No".

    For non-integers, and Money, the default is "Yes".

- Modify the "Format" form field to behave as follows:

    - If we have an **integer with grouping separators**, then present the following options:

        | option    | value |
        | --------- | ------- |
        | Use browser locale | `null` |
        | 1,234,567 | `'english'` |
        | 1.234.567 | `'german'`  |
        | 1 234 567 | `'french'`  |
        | 12,34,567 | `'hindi'`   |
        | 1'234'567 | `'swiss'`   |

    - If we have an **integer without grouping separators**, then don't show the "format" option, because it's irrelevant. Keep value as `null`.

    - If we have a **non-integer with grouping separators**, then present the following options:

        | option    | value |
        | --------- | ------- |
        | Use browser locale | `null` |
        | 1,234,567.89 | `'english'` |
        | 1.234.567,89 | `'german'`  |
        | 1 234 567,89 | `'french'`  |
        | 12,34,567.89 | `'hindi'`   |
        | 1'234'567.89 | `'swiss'`   |

    - If we have a **non-integer without grouping separators**, then present the following options:

        | option    | value |
        | --------- | ------- |
        | Use browser locale | `null` |
        | 1234.56 | `'english'` |
        | 1234,56 | `'german'`  |

- When changing the "Use Grouping Separators" field from "No" to "Yes", we set a more specific value for the "Format" field, using the browser locale to resolve ambiguity. For example, if the user has configured `format` to `'german'` (because they just wanted a comma decimal separator), but their locale is `fr-FR`, then we change `'german'` to `'french'`, which also has a comma decimal separator but is more likely to match their desired grouping separator. We can use the browser locale to determine the format option by formatting a number and inspecting it. As a further edge case, if the user has configured `format` to `'german'`, but their locale is `en-US` (which is _not_ a more specific form of `'german'`), then we'd leave the value untouched.

**Comment by kgodey** [comment]
This sounds fine to me, let's do it.
