### ISSUE TITLE
Use a separate Mathesar type for percentage display

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1331]
## Facts

- (A): The display option `show_as_percentage` exists for all Number types, regardless of DB type configuration or other display options.

- (B): We've [decided](https://github.com/centerofci/mathesar/discussions/1269) that the Postgres value `0.5` should be displayed to the user as `50%` when `show_as_percentage` is `True`, and I think we ought to stick to that.

- (C): Because of (B) we need to multiply a number by 100 when formatting the stored value, and divide by 100 when parsing user input.

- (D): To implement (C) easily, we need access to the numerical value of the user input and the numerical value of the stored number.

- (E): To satisfy other constraints, we have [decided](https://wiki.mathesar.org/en/engineering/specs/numbers#api) to assume that dealing with Number values _numerically_ on the front end is not feasible -- so we treat them as strings.

## Problems

- (D) + (E) are in conflict.

    We could relax (D) by moving the decimal place within a string, but that's going to get tricky, and I don't want to spend time handling all the edge cases.

- Also, the UX for configuring the number of decimal places to show is quite tricky to present in a manner that applies well for both percents and non-percents. This is especially problematic if we stick to `scale` as the only mechanism for the user to configure the decimal places (because it will be off by 2).

## Proposal

- Mathesar has a dedicated "Percent" type, distinct from "Number".

- The Percent type maps to only one Postgres type -- `double precision`. This works well because that's how numbers are stored in JavaScript too.

- Grouping separators are off, and there is no way to turn them on. This simplifies the locale formatting options to only two choices.

- Display options (not DB options) exist allowing the user to configure the number of decimal places shown. The format of those display options is TBD. I'm hoping we can agree on all of the above without concerning ourselves with the display options specifically. In #1332, I have a separate proposal for display options that would work well for percentages too.

**Comment by kgodey** [comment]
I'd like @mathemancer to see if there would be any technical issues with implementing this approach in the backend. If not, it sounds fine to me, let's do it.

**Comment by mathemancer** [comment]
If I'm understanding correctly, I think pushing the order of magnitude manipulation to the DB layer. I suggest using `NUMERIC` rather than `DOUBLE PRECISION` for the storage type, since that's our default number type, and also what we're using to back the `MATHESAR_TYPES.MATHESAR_MONEY` type.

To the implementer: just implement it as a `DOMAIN` in the DB. The only caveat is that such a column would look different via other clients (i.e., they'd see `0.5` rather than `50%`), but that's going to be the case with almost any implementation.

**Comment by seancolsen** [comment]
@mathemancer

> pushing the order of magnitude manipulation to the DB layer is fine

Hmmm, sorry if I was not clear. I'm not suggesting the DB layer handles the order of magnitude. Rather, I'm suggesting that a Percent type stores `0.5` and sends this value to the front end as `0.5`. Then the front end formats it as `50%`. Does that make sense?

**Comment by mathemancer** [comment]
I'm definitely confused. How will you avoid treating it as a number in the front end, than? I suppose you'd just use some string-wrangling to 'decode' and 'endode'? Further, why would we need a separate percent DB type? If we're storing and returning 0.5, then percent is precisely a display matter.

**Comment by seancolsen** [comment]
## "Percent" vs "Percentage"

We decided to go with "Percent" instead of "Percentage" based on the following research.

LibreOffice

![image](https://user-images.githubusercontent.com/42411/170307639-80ec967b-c29b-47e1-a6d7-ff980e4ba490.png)

AirTable

![image](https://user-images.githubusercontent.com/42411/170307891-44b5956a-d9b3-4f71-bc7f-2c87ecaab748.png)

Google Sheets

![image](https://user-images.githubusercontent.com/42411/170308234-c2ec43c8-60d3-4e11-9618-e0b73f789514.png)

**Comment by seancolsen** [comment]
@mathemancer and I chatted about this on a call today. We agreed to move forward with my proposal.

I've created the following new tickets:

- #1395 (which has a clearer description of the proposal than above)
- #1396

I also updated the [UI Data Types wiki page](https://wiki.mathesar.org/en/engineering/glossary/ui-types) to document the planned new UI type.

I'm closing this ticket in favor of the two mentioned above, which are more specific.

**Comment by seancolsen** [comment]
Based on this [previous ticket](https://github.com/centerofci/mathesar/issues/434), I noticed that we seem to have been flip-flopping a bit on our design here. So for posterity's sake I'll document some more details about the call that @mathemancer and I had today...

- We considered two options:

    - **"Math in the DB layer"** - The multiplication and division for percentage display and parsing happens in the DB layer. Outside the DB layer, percentage values are handled similar to the way we currently handle values for the "Number" UI type -- we treat them like strings because they might have precision exceeding the capabilities of Python or JavaScript. To represent the value "fifty percent", we store the number `0.5` in Postgres (as any either a `DOUBLE PRECISION`, `REAL`, or `NUMERIC`). Then outside the DB layer, all other parts of our stack see this value as `"50"`.

    - **"Math in the front end"** - The multiplication and division for percentage display and parsing happens in the front end. To represent the value "fifty percent", we store the number `0.5` in Postgres as a `MATHESAR_TYPES.PERCENT`, which is a Domain over `DOUBLE PRECISION`. We use a domain to ensure that the API can represent percentages as a distinct type, separate from `DOUBLE PRECISION`. And we use `DOUBLE PRECISION` to ensure that the front end will always be able to represent the value numerically without loos of precision (thereby retaining capability to multiply and divide it).

- Brent and I were both open to either option. Ultimately we went with "math in the front end" because it seemed a tiny bit easier to implement and seemed likely to offer more flexibility in the long run if we find other use-cases for manipulating percentages numerically on the front end.
