### ISSUE TITLE
Use display options (instead of db options) to format decimal places

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1332]
## Our current design

- When Postgres `scale` is **not** defined, the number is formatted with however many decimal places exist in the stored value.

- When Postgres `scale` **is** defined, the number is formatted to have exactly that number of decimal places, regardless of the stored value.

### (A) Format with fewer decimal places than are stored

Spreadsheets allow this, and in my experience it's quite common to utilize this feature.

![Peek 2022-04-28 21-30](https://user-images.githubusercontent.com/42411/165872370-4e58cdd2-7a92-4e71-943a-22b7dda2009f.gif)

For example, let's say my data is:

| v |
| - |
| 123.4 |
| 9.809215179162 |

To work with this data easily, I'd like to see:

| v |
| -: |
| 123.40 |
| 9.81 |

(Notice that the second value is _rounded_ to `9.81` instead of being truncated to `9.80`)

But I don't want to lose the precision of that second value just to make my life easier looking at the data with all the decimal points lined up. 

I'd like to apply _formatting_ that makes it easy for me to view my data, without changing the actual data.

### (B) Format a floating point number

The Postgres `scale` property does not exist for `real` or `double precision` numbers. Users may want to format values of that type -- especially if we adopt my proposal in #1331.

### (C) Specify minimum digits independently of maximum digits

Let's pretend I'm storing money amounts in USD and I have the following values:

| dollars |
| - |
| 1.4 |
| 2.8191 |

Also, for my task at-hand I'd like to see the full values, with all their stored precision, but I don't happen to know the maximum number of decimal places in my data set (and indeed it could change as I add new data). For this reason I don't want to set a _maximum_ number of decimal places. But I _do_ want to set a _minimum_ number of decimal places to 2 because it's currency. I'd like to see:

| dollars |
| -: |
| $1.40 |
| $2.8191 |

## Proposal

- Add two display options `minimum_fraction_digits` and `maximum_fraction_digits`, which correspond to the the equivalently named options in the browser [Intl API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat)

- Design a UI for the user to configure their decimal settings through these display options (instead of through the `scale` and `precision` options).

- To keep the UI simple, we could begin with one input that sets both `minimum_fraction_digits` and `maximum_fraction_digits` in tandem, thereby satisfying (A) and (B), but not (C). Then later (with more work), we could add a separate checkbox that turns the single input into two separate inputs for more advanced use-cases (without needing to change the display_options schema). (I can clarify this with a mockup if it's confusing.)

- Continue to expose `scale` and `precision`, but hide them behind a checkbox and supply help text to explain their purpose while dissuaded users from setting values there.

**Comment by seancolsen** [comment]
Note that in #1359 it became apparent to me that for the Mathesar Money type, we _need_ `display_options` to control the display of decimal places because we actually can't do it through `type_options`. As such, I see this ticket is being pretty important, because Money values will look pretty bad without it.

**Comment by kgodey** [comment]
The proposal sounds fine to me, let's do it.
