### ISSUE TITLE
Improve client-side validation within "Link Table" dialog

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1343]
## Current behavior

- Within the "Link Table" dialog, there are fields for the user to enter table names and column names. The form does not have any client-side validation on these fields.

- For example, in the many-to-many case, deleting the table name results in this strange UI state:

    ![Screenshot 2022-04-29 at 5 08 41 PM](https://user-images.githubusercontent.com/11850603/165937594-594fcd7c-7ec8-4004-b2eb-bcd901195486.png)

## Desired behavior

- For all text fields in the form, client-side validation shows errors if the field is empty (and prevents form submission).

- In the many-to-many case, the column name fields are hidden if the mapping table name is empty (preventing the awkward form field labels shown in the screenshot above).

- Client-side validation also shows errors for names that collide with existing names. Column names must be unique across all the columns in the relevant table. Table names must be unique across all the table names in the schema.

**Comment by Creative1800** [comment]
Hi @seancolsen, is the issue still available? I would like to work on it.

**Comment by kgodey** [comment]
Sure, go ahead @Creative1800. We will be updating the styling for this modal soon, but we'll still need the validations.
