### ISSUE TITLE
Design better UX in the Link Table dialog for self-referential links

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1345]
## Problem

- In the "Link Table" dialog, when the target table is the same as the base table, the UX gets a bit confusing.

- We have one yes/no question that's borrowed from the non-self-referential situation, and we display diagrams for "Many to Many" and "One to One" -- but I'm not sure this question and choice of diagrams are appropriate.

- A common use-case for self referential links is to model hierarchical structures. However, it's not possible to set up such a link using this dialog. Answering "no" to the yes/no question will create a unique constraint, which we wouldn't want when modeling a hierarchy.

## Solution

- I think it would be good to step back and consider all the use-cases for self-referential links and re-design the form to better cover the use-cases with a more intuitive set of questions and diagrams.

**Comment by ghislaineguerin** [comment]
Will solve this in #1642
