### ISSUE TITLE
Show DEFAULT in new record cells by default

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1362]
## "Limbo"

When adding a new record, there is a to which I'll refer as "limbo". The new record row is in limbo after it's been added to the UI but before it's been saved to the DB. Most times, the new record row only remains in limbo transiently, for a split second, while the request is loading. Any behavior of the row for such a short time is only of negligible concern. However, if there are errors adding a new row, the row may reach stasis in limbo, as described in #775 for example. In this prolonged limbo state, the UX becomes more important and currently has some shortcomings.

## Current behavior in limbo

- When a cell is poised to set the Postgres value to `DEFAULT`, it appears blank.

- After the user edits the cell, the user has no way to revert the cell back to its `DEFAULT` state.

## Desired behavior

- All cells appear as `DEFAULT` by default.

- `DEFAULT` is styled similarly to `NULL`.

- Editing a cell, brings the value out of `DEFAULT`.

- The user can return to `DEFAULT` using the context menu, in a similar fashion to `NULL`.

**Comment by seancolsen** [comment]
@pavish @ghislaineguerin @kgodey Does the above plan sound okay to you?

**Comment by ghislaineguerin** [comment]
I think this makes a lot of sense. How is the default value set?

**Comment by kgodey** [comment]
> * All cells appear as `DEFAULT` by default.

Instead of all cells, can we only show `DEFAULT` for cells that have a default value explicitly set? If so, this sounds fine.

**Comment by pavish** [comment]
It sounds good to me and I think it makes sense.

I'm not sure how well users would be able understand it at first look though.
