### ISSUE TITLE
Partial data loss when attempting to unset scale type_options independently of precision

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1367]
## Reproduce

1. Set up a Number column with "Decimal Places" = `2` and "Max Digits" = `100`.

1. Add row with a value of `1.23`.

1. Now imagine we'd like to also store the value `6.789` without loss of precision. We'll need to modify or remove the "Decimal Places" setting.

1. Edit the DB type options. Remove the `2` in the "Decimal Places" field (leaving the field blank) and save.

1. Observe a PATCH request to the columns API.

1. Expect the response to have `type_options` of `{ precision: 100, scale: null }` or `{ precision: 100 }`.

1. Observe the response to have `type_options` of `{ precision: 100, scale: 0 }`.

1. Expect the cell value within the newly-added row to still be `1.23`.

1. Observe that the value of the cell has changed to `1` because `scale` has been changed to `0`. This is especially bad because it's **data loss**.

## Notes

- The [Postgres docs on numeric types ](https://www.postgresql.org/docs/current/datatype-numeric.html) appear to indicate that Postgres supports NUMERIC with a precision value and without a scale value.

**Comment by mathemancer** [comment]
@seancolsen Setting a column to `NUMERIC(100)` without giving a scale is equivalent to setting `NUMERIC(100, 0)` at the DB layer. There is no way to create a column with a defined precision and an arbitrary scale. I do see how this could be confusing. I suggest we either leave it as-is to replicate the underlying DB behavior, or disallow giving a precision without a scale to avoid confusion.

**Comment by seancolsen** [comment]
> disallow giving a precision without a scale to avoid confusion.

Yes. This is what I'd like to do. Can we do this at the API level with some simple request validation? That will ensure maximal safety against this sort of data loss. Plus it conveniently allows us to side-step the UX design questions related to decimal places and max digits, e.g. in #1420. For the purpose of this ticket, I don't care if there's an unintelligible error message or poor user experience -- I'm just trying to safeguard against data loss from a user doing something like entering `2` into "Max Digits" when they meant to enter `2` into "Decimal Places".

**Comment by mathemancer** [comment]
I can even make it an intelligible error message.
