### ISSUE TITLE
Provide detailed error info when failing to disallow NULL for a column

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1394]
## Reproduce

1. Set up a column which contains a `NULL` value.

1. PATCH to `/api/db/v0/tables/1/columns/<id>/` with:

    ```json5
    {
      "nullable": false
    }
    ```

1. Expect a 4xx HTTP response code.

1. Observe a 5xx HTTP response code.

1. Expect the response body to contain a Mathesar error code specific to this situation.

1. Observe the response body to use the error code `4999` (`UnknownError`).

**Comment by kid-116** [comment]
Could I be assigned to this issue.

**Comment by silentninja** [comment]
Thanks! @kid-116 I have assigned the issue to you.
