### ISSUE TITLE
Support for JSON data type

### ISSUE THREAD

**Issue by Jinxiao0302** [centerofci/mathesar#1407]
## Problem
Adding JSON as a supported data type for Mathesar will allow users to import JSON type data, change a database ﬁeld to a JSON object and enable data validation, modiﬁcation, and browsing. Also, it will allow the grouping, ﬁltering, and sorting operations based on JSON keys.

## Proposed solution
The JSON type of Mathesar will be designed without fixed schema restriction. We would use either default json class of SQLAlchemy or define our own.

## Analysis tasks before coding

- [x] #1409
- [ ] #1410
- [x] #1411
- [ ] #1412

## Tasks to solve when implementing JSON support

- [ ] #1408
- [ ] #1324

**Comment by pavish** [comment]
I'm closing this meta ticket, we'd handle everything using individual tickets since the basic JSON types implementation is currently done.
