### ISSUE TITLE
Unhandled DataError exception when attempting to PATCH a date value with a format that Postgres does not recognize

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1413]
## Reproduce

1. Set up a column with a `DATE` type.

1. PATCH to a record within that table `/api/db/v0/tables/8/records/1/`, setting the value to "99/99/9999".

    ```json
    {"36":"99/99/9999"}
    ```

1. Expect an error response conforming to our [error standards](https://wiki.mathesar.org/en/engineering/standards/api#errors).

1. Observe a response with an HTML body (instead of JSON) and an HTTP status code of 500.

    > DataError at /api/db/v0/tables/8/records/1/
    >
    > (psycopg2.errors.DatetimeFieldOverflow) date/time field value out of range: "99/99/9999"
    > LINE 1: UPDATE public.temporal SET date='99/99/9999' WHERE public.te...

    ![image](https://user-images.githubusercontent.com/42411/171423633-c2a5b28e-deb7-4914-9402-cc0ed272bb55.png)

    ![image](https://user-images.githubusercontent.com/42411/171418729-ed29c324-a6aa-4f04-b57f-c5baf1cff34e.png)

**Comment by Anish9901** [comment]
I'd like to work on this. Assigning myself.
