### ISSUE TITLE
Backend support for importing data into existing tables

### ISSUE THREAD

**Issue by Anish9901** [centerofci/mathesar#1416]
## Problem

Currently, we only support creating a new table when a CSV or TSV file is imported. This limits the user's ability to append/store/view data from multiple files in one place. We would want to add support for importing data into existing tables to allow users to import data into existing tables seamlessly.

## Proposed solution

To implement the above we will use a mix of already implemented APIs with some tweaks and implementation of some additional API endpoints along with some methods to accompany them.

#### Allowing CSV data imports in existing tables through current APIs
- [x] #1419
- [x] #1439
- [x] #1488

#### Overcoming challenges caused by CSV imports and Real-world data
- [x] #1508
- [x] #1574
- [x] #1820

**Comment by sai-sy** [comment]
this is closed, how does a use now import a CSV to an existing table

**Comment by kgodey** [comment]
@sai-sy currently this is only implemented at the backend/API layer at the moment. The UI work is tracked in this issue: https://github.com/mathesar-foundation/mathesar/issues/1964.

We don't have an ETA for implementation yet, but other users have also asked for this feature and we're taking that into account when prioritizing work.
