### ISSUE TITLE
Errors while adding migrations

### ISSUE THREAD

**Issue by Anish9901** [centerofci/mathesar#1469]
## Description

While executing `python manage.py makemigrations` on the master branch you will be prompted with:
```
You are trying to change the nullable field 'base_table' on uiquery to non-nullable without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Ignore for now, and let me handle existing rows with NULL myself (e.g. because you added a RunPython or RunSQL operation to handle NULL values in a previous data migration)
 3) Quit, and let me add a default in models.py
Select an option: 3

root@c90fa9ee5b93:/code# python manage.py makemigrations
You are trying to change the nullable field 'name' on uiquery to non-nullable without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Ignore for now, and let me handle existing rows with NULL myself (e.g. because you added a RunPython or RunSQL operation to handle NULL values in a previous data migration)
 3) Quit, and let me add a default in models.py
Select an option: 3
```
These fields were made mandatory in PR #1464
## Expected behavior

`python manage.py makemigrations` should execute with no errors.

## To Reproduce

Execute `python manage.py makemigrations` on the master branch.

**Comment by silentninja** [comment]
@Anish9901 I think we can ignore the warning as we don't have a database with production data, so Can you choose option 2, it should create the necessary migration files without any default value.

**Comment by mathemancer** [comment]
@kgodey Is there any reason we can't just re-init the migrations (I assume we'll be doing this again later anyway)?

**Comment by kgodey** [comment]
@mathemancer I don't have an objection. Everyone working on the project will need to be notified so that they can reset their DB locally.

**Comment by silentninja** [comment]
@mathemancer re-init for each PR?

**Comment by mathemancer** [comment]
> @mathemancer re-init for each PR?

I was just thinking about doing that to solve the current problem, but I think we could do it for any PR that has some migration issue, until we have users with in-flight webservice DBs.
