### ISSUE TITLE
Newly-created mapping table is not reflected after adding a many-to-many table link

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1477]
## Reproduce

1. Create a many-to-many link by submitting POST request to `/api/db/v0/links/` like so

    ```json
    {
      "referents": [
        { "column_name": "Publications_id", "referent_table": 15 },
        { "column_name": "Genres_id", "referent_table": 17 }
      ],
      "mapping_table_name": "Publications_Genres",
      "link_type": "many-to-many"
    }
    ```

1. Fetch the list of tables with a GET request to `/api/db/v0/tables/?schema=1`

1. Expect the response to contain the newly-created mapping table, "Publications_Genres".

1. Observe the response contains all tables except "Publications_Genres".

1. As a work-around (and for troubleshooting purposes) in `mathesar/reflection.py`, change `DB_REFLECTION_INTERVAL` to `1`. Then re-send the fetch request. Now observe the new table to be reflected.

**Comment by silentninja** [comment]
@seancolsen Is this issue still valid in the current master branch? I tried creating a Many-to-Many link and the table is being reflected correctly

**Comment by seancolsen** [comment]
Yeah, looks like this was fixed :+1:
