### ISSUE TITLE
Need for a breakdown of error messages when a file import goes wrong.

### ISSUE THREAD

**Issue by Dhruvi16** [centerofci/mathesar#1483]
## Description

`InvalidTableAPIException` which returns the error message "Unable to tabulate data" is the only error that is related to file processing and is thrown anywhere a file cannot be correctly processed. This can be confusing for the user to interpret. We need a proper breakdown of errors. More specific messages for the users so it can be debugged easily.

## Expected behavior

A proper concise error message on import failure. 

## To Reproduce

1. Import a corrupted or invalid file.
2. See the error message

## Environment
 - OS: (macOS)
 - Browser: (Chrome)
 - Browser Version: (103.0.5060.134)
 - Other info:

**Comment by kgodey** [comment]
Closing this, we'll open more specific issues for any frontend errors we see.
