### ISSUE TITLE
Remove "_id" suffix from suggested column name within the Link Table dialog

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1542]
## Current behavior

- The "Link Table" dialog suggests new column names according to the pattern `{table_name}_id`

    ![image](https://user-images.githubusercontent.com/42411/185451407-2df6d0b8-18ac-44d6-9a11-8f7ade7005dd.png)

## Desired behavior

- Suggested column names should only include the table name -- not any "id" anywhere.

## Additional context

- [Discussion via email](https://groups.google.com/a/mathesar.org/g/mathesar-developers/c/yu1dOjV7EC8)

**Comment by sristis0202** [comment]
I would like to contribute. Please add

**Comment by seancolsen** [comment]
Thanks @sristis0202 I've assigned you. Ping us on [Matrix](https://wiki.mathesar.org/en/community/matrix) if you need any help.

**Comment by seancolsen** [comment]
@sristis0202 How's it going with this issue? Do you need any help? We'd like to get this completed in the next few weeks, so if we don't see a PR for it by 2022-08-07 we may need to reassign it.

**Comment by kirtanchandak** [comment]
Hey can I work on this issue ?

**Comment by pavish** [comment]
@sristis0202 Since we're not heard back from you, we are going to reassign this issue. Feel free to pick a different issue when you'd like to contribute again.

**Comment by pavish** [comment]
@kirtanchandak Sure, go ahead! I'm assigning this issue to you. Feel free to reach out to us on our [Matrix channels](https://wiki.mathesar.org/en/community/matrix) if you need any help.

**Comment by kgodey** [comment]
@kirtanchandak how are you doing with this?

**Comment by silentninja** [comment]
@kirtanchandak  Since we're not heard back from you, we are going to reassign this issue. Feel free to pick a different issue when you'd like to contribute again.

**Comment by silentninja** [comment]
@kaushikaryan04 I am assigning the issue to you.
