### ISSUE TITLE
Write up using `make initial_setup` for initial local dev setup

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#1556]
## Problem
We have a script that sets up our docker containers, it's called `initial_setup.sh` and it's run via `make initial_setup`. New developers don't know about it though.

## Proposed solution
Make changes to our README to tell people about the script.

## Additional context
Implementing PR: https://github.com/centerofci/mathesar/pull/1486

**Comment by YashRajSingh-4799** [comment]
Hi,
 I am looking for my first open source contribution.
 this issue is quite interesting and beginner friendly 
Can I work on it?

**Comment by kgodey** [comment]
Sure, go ahead @YashRajSingh-4799!

**Comment by dmos62** [comment]
Rudimentary instructions for running `make initial_setup` were added to the readme. Not sure if we want more information. Possibly when we have some use reports of how the script might fail. Closing issue for now.
