### ISSUE TITLE
Improve Record Page

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1580]
- Record
    - [ ] Allow deleting the record
    - [x] ~~Display the record summary in the `<h1>` element and the `<title>` element.~~ (covered in #1600)
- Direct fields
    - [ ] Add a status bar at the top to let users know their data is saved (like we do in the sheet)
    - [ ] Fix updating boolean field
    - [ ] Show loading status when updating an FK field
    - [ ] Focus next input when pressing Enter (unless it's a `textarea`)
    - [ ] Allow user to set values to NULL
    - [ ] Display a tooltip like "Press Tab to Save" or "Press Enter to Save" when focused
- Table widget
    - [ ] Don't show page size input within the pagination widget (so that user can't modify it)
    - [ ] Make it collapsible
    - [ ] Don't show Pagination UI when there is only one page
    - [ ] Allow resizing columns
    - [ ] Header gets cut off while horizontal scrolling within each table widget

**Comment by seancolsen** [comment]
I'm punting this to "Live demo" because I don't think any of these improvements should block the demo video. I might subdivide these tasks into separate milestones later once we get to Cycle 5.

**Comment by kgodey** [comment]
Moved this back to "Demo video" because a lot of these things came up in usability testing. @seancolsen feel free to move things that aren't relevant until the live demo to a separate issue.

**Comment by seancolsen** [comment]
> a lot of these things came up in usability testing

@kgodey Can you be more specific? Which of the tasks listed above are relevant to the demo video?

**Comment by kgodey** [comment]
@seancolsen I saw that you had commented on a bunch of feedback that came up and said it was tracked in this issue. Please see your notes from [the sections under Screens 26 and 27 here](https://www.figma.com/file/F0FmNaNz8hvrgxPax3Bix1/Cycle-3-reference?node-id=856%3A624).

**Comment by seancolsen** [comment]
@kgodey and I chatted about this. I'll be splintering off sub-tasks from this ticket into dedicated tasks for the live demo

**Comment by seancolsen** [comment]
I'm splitting this into smaller tickets to set more granular priorities

- 1843
- 1842
- 1844
- 1845
- 1846
- 1847
