### ISSUE TITLE
Error when selecting a base table for a new exploration makes it impossible for me to create new explorations

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1587]
I got this error from `http://localhost:8000/api/db/v0/queries/` after creating a new exploration and selecting a base table. Most of the time, I don't get this error, but it happened once when I created a new exploration immediately after saving a previous one.

<details>
<summary><h3>Error Response does not conform to the api spec. Please handle the exception properly</h3></summary>

```
Environment:


Request Method: POST
Request URL: http://localhost:8000/api/db/v0/queries/

Django Version: 3.1.14
Python Version: 3.9.8
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'django_filters',
 'django_property_filter',
 'mathesar']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 228, in is_valid
    raise ValidationError(self.errors)

During handling of the above exception ({'name': [ErrorDetail(string='ui query with this name already exists.', code='unique')]}), another exception occurred:
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 466, in handle_exception
    response = exception_handler(exc, context)
  File "/code/mathesar/exception_handlers.py", line 71, in mathesar_exception_handler
    raise Exception("Error Response does not conform to the api spec. Please handle the exception properly")

Exception Type: Exception at /api/db/v0/queries/
Exception Value: Error Response does not conform to the api spec. Please handle the exception properly
```
</details>

Now Mathesar is in a state where any time I try to create a new exploration and set a base table, I get this error. I'm unable to create new explorations. I'll try re-installing Mathesar.

**Comment by mathemancer** [comment]
@seancolsen @pavish The error indicates that the attempted query is being created with the same name (which is disallowed). While we should definitely happen the error more appropriately on the back end, there's not a way to keep getting this error as described unless the front end sends the same name for the query with each request.

**Comment by pavish** [comment]
Ahh. I see the error now, I skimmed at the error message and didn't catch it earlier.

> Most of the time, I don't get this error, but it happened once when I created a new exploration immediately after saving a previous one.

This makes sense, the only chance of this error occurring is when you try to create a new query before the current one is saved & before the query list is re-fetched. We can improve this edge case by maintaining the currently created queries in a cache, and generating the name by taking them into account additionally. I'll assign this issue to me to handle this. We would have to handle this in every place we have dynamically generated names on the frontend.

> Now Mathesar is in a state where any time I try to create a new exploration and set a base table, I get this error. I'm unable to create new explorations. I'll try re-installing Mathesar.

This is the scenario I'm concerned about. Because, this should not happen unless we are unable to fetch the query list(which should throw an error) and the frontend is trying to create a new query with an existing name. I'm not sure what is causing this. @seancolsen could you provide more information on this issue? Unfortunately, I do not know what I'm looking for. @mathemancer Can you weigh in on we might need to debug this?

**Comment by seancolsen** [comment]
I'm digging into this a little bit. Also not entirely sure what I'm looking for in attempting to troubleshoot this problem. But I did uncover a red flag that smells like it's related to this problem. Follow me through a number of observations which don't quite add up...

- I have two schemas -- one with `id = 1` and another with `id = 4`. 

- Let's look at all the queries I have

    ```sql
    select
      q.id as query_id,
      q.name as query_name,
      t.id as base_table__id,
      s.id as base_table__schema_id
    from mathesar_uiquery q
    join mathesar_table t on
      t.id = q.base_table_id
    join mathesar_schema s on
      s.id = t.schema_id
    order by query_id;
    ```

    | query_id | query_name        | base_table__id | base_table__schema_id |
    | -------: | ----------------- | -------------: | --------------------: |
    |        6 | New_Exploration_3 |             36 |                     1 |
    |        8 | New_Exploration_5 |             39 |                     1 |
    |        9 | New_Exploration   |             45 |                     4 |
    |       10 | New_Exploration_1 |             42 |                     4 |
    |       11 | New_Exploration_2 |             45 |                     4 |

    Both schemas have multiple queries saved. Ok.

- Running

    ```
    curl 'http://localhost:8000/api/db/v0/queries/?schema=4' | jq '.results[]|{id,name,schema}'
    ```

    gives

    ```json
    {
      "id": 11,
      "name": "New_Exploration_2",
      "schema": 4
    }
    {
      "id": 10,
      "name": "New_Exploration_1",
      "schema": 4
    }
    {
      "id": 9,
      "name": "New_Exploration",
      "schema": 4
    }
    ```

    Ok that looks good. Fetching the queries for schema 4 does not return any of the queries for schema 1.

- Let's see how the front end renders the Schema Page for schema 4...

    ![image](https://user-images.githubusercontent.com/42411/188156186-edade82d-9f76-461d-9a20-5d4a71ace816.png)

    Uh oh! Schema 4 is displaying the queries for schema 1 as well. 😬

- Let's see what happens when I click on "New_Exploration_3" to load a query from schema 1 within schema 4 🤔 ...

    ![image](https://user-images.githubusercontent.com/42411/188157014-3b22f084-678b-4c59-be9a-dcc3c108c679.png)

    I have columns without having a base table! That's not good. But it kind of makes sense, given the unexpected state at which we've arrived.

- I was eventually able to get past whatever bug was preventing me from creating new queries. I'm not sure how. I was able to create New_Exploration_6 within schema 4. On performing _client-side_ navigation to schema 1, New_Exploration_6 was _not_ visible. Interesting. Loading the page from scratch made it show up. Then I clicked on Data Explorer and the name New_Exploration_7 was generated for me.

- After a bit of unstructured clicking around (apologies that I don't know exactly what I did, it was tricky to reproduce) I was able to reproduce the error 500 response from the server. This was the request:

    ```
    POST http://localhost:8000/api/db/v0/queries/
    ```

    ```json
    {
      "name": "New_Exploration",
      "base_table": 39,
      "initial_columns": [],
      "transformations": []
    }
    ```

    I found it a bit surprising that `name` was `New_Exploration` and not something like `New_Exploration_6`. 

    I'll also say this: my unstructured clicking was _slow and measured_ in an attempt (perhaps in vain) to observe more about the goings on. **No requests were pending** when I clicked "Data Explorer" or when I selected a base table. So I'm not sure a race condition is necessarily at play here.

Because I don't understand much about what's going on under the hood, I'll refrain from speculating about any of the underlying culprits to the unexpected behavior described in this ticked -- but I'm hoping the above info will trigger a light bulb moment for one of you two. If not, I can continue digging deeper.

**Comment by pavish** [comment]
@seancolsen

Thanks, that gives a better idea of where the problem could lie. I'll dig into it.

I do have a question, how were you able to save the query from the frontend without choosing the base_table?

The response you mentioned:
```
{
  "id": 11,
  "name": "New_Exploration_2",
  "schema": 4
}
{
  "id": 10,
  "name": "New_Exploration_1",
  "schema": 4
}
{
  "id": 9,
  "name": "New_Exploration",
  "schema": 4
}
```
does not contain a `base_table` field.

We have a frontend validation which will only save the exploration if the base_table field is present. Provided, this validation is currently not present on the backend and we should implement it.

One assumption is you created these explorations on earlier iterations of data explorer and not the latest one. Quite a bit has changed code-wise in-between PRs. If this is the case, you could experience things breaking here and there and I would suggest creating fresh explorations. If not, we have some other serious bug.

**Comment by seancolsen** [comment]
We had a call about this today and elevated the discussion to a [thread](https://groups.google.com/a/mathesar.org/g/mathesar-developers/c/4svSBM50itg) the mailing list where posed the question: 

> what support (if any) do we envision Mathesar providing for operations between objects in separate schemas?

On the call, I also clarified with Pavish that the JSON response in my comment has fields filtered out via `jq`.

**Comment by pavish** [comment]
@kgodey I'm moving this to Demo video, since it blocked our evaluation

**Comment by pavish** [comment]
I'm assigning this to me, since the changes needed are on the frontend.
