### ISSUE TITLE
Data Explorer frontend - Live demo readiness

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#1597]
The following checklist is for the live demo readiness of Data Explorer
- [x] #1590
- [ ] #1805
- [ ] #1804
- [ ] #1803
- [ ] #1802
- [ ] #1801
- [x] Fix column type calculation bug for summarized columns
- [ ] #1596
- [ ] #1800

**Comment by mathemancer** [comment]
Regarding display options:
- Do we need to have these for non-initial columns, or should they only apply to unaltered initial columns?
- Do we need to persist these separately? I.e., If the user changes the display options for a column on their table, should that also change in the query (this would be my expectation), or should they stay the same in the query?

**Comment by pavish** [comment]
@mathemancer 

> Do we need to have these for non-initial columns, or should they only apply to unaltered initial columns?

It'd be great if we could have it for non-initial columns as well, especially for columns that are aggregated as list. We'd have to copy over display options from the initial column to the newly generated array column. It can be null for aggregations like `count`. We'd have to spec this part out. To start with, we can only have it for the unaltered initial columns.

> Do we need to persist these separately?

No. I wouldn't expect it to persist separately from the table's column.

>  I.e., If the user changes the display options for a column on their table, should that also change in the query (this would be my expectation)

This is my expectation as well. While there are use-cases I can think of, where we might want separately persist display options for queries, I think we can defer it for later.

**Comment by kgodey** [comment]
I've created separate issues for remaining work and prioritized them. I'm closing this one.
