### ISSUE TITLE
Columns not refreshed when undoing a change to base table

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1598]
## Reproduce

1. New Exploration
1. Select base table A
1. Observe columns loaded for base table A
1. Change base table to B
1. Observe columns loaded for table table B
1. Undo
1. Expect to see columns change to display  columns for table A
1. Observe columns for table B

CC @pavish

**Comment by pavish** [comment]
This seems to have been fixed in recent PRs.

Changing base table currently resets everything including undo/redo.
