### ISSUE TITLE
Visually indicate pending request status for update of checkbox cell

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1602]
## Current behavior

- When I edit a text cell, the color turns gray while the cell is saving. That's nice.
- When I edit a checkbox cell by clicking the checkbox, I don't get the save visual indication that the cell value is saving.

## Desired behavior

- Checkbox turns gray when it's saving and becomes disabled.
- When it's done saving, it becomes enabled and turns blue agin.

**Comment by FrantisekHarnicar** [comment]
I would like to work on this issue, can you assign me?

**Comment by kgodey** [comment]
Go ahead and submit a PR @FrantisekHarnicar.
