### ISSUE TITLE
Unable to modify Money cell value

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1603]
## Reproduce

I can edit most cells, but when I try to edit an "Items"."Acquisition Price" cell, no request is made to the server and the display value of the cell immediately reverts to its value before I entered edit mode.

**Comment by pavish** [comment]
I'm assigning this to myself since it's part of Table page and I'm fixing the critical bugs there.

**Comment by kgodey** [comment]
@pavish: @seancolsen said he might have an idea of what's going on with this issue, so you may want to talk to him to speed up work.

**Comment by pavish** [comment]
@kgodey I'm aware of the cause and I've started fixing the issue. I'll check with @seancolsen if I need support.
