### ISSUE TITLE
Set up components library in Figma

### ISSUE THREAD

**Issue by ghislaineguerin** [centerofci/mathesar#161]
### Task Description
We need to build a design system that includes both design and front-end guidelines. Initially, a component library will allow us to create prototypes in Figma. This library will become the foundation for Mathesar's UI, as engineers will reference it to implement product requirements.

### What needs to be done
- Set up a component library in Figma
- Create components based on [current specification documents](https://wiki.mathesar.org/en/design/process/documents)
- Update existing prototypes to use the updated components

### As part of this task
- Identify any conventional components that we might need to incorporate in the future and propose them as a list. 
- Consider how we might keep track of components status within the library (review, ready-to-use, new, deprecated).
- Consider how engineers use the component library to implement design requirements.

**Comment by kgodey** [comment]
Closing this in favor of smaller issues tracking individual components, e.g. https://github.com/centerofci/mathesar/issues/322.
