### ISSUE TITLE
Update Mathesar logo in README

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#1611]
We haven't done this yet because the current Mathesar logo with text currently does not appear good in dark mode, since the text is dark colored. Refer the discussions in [this PR](https://github.com/centerofci/mathesar/pull/1610).

We should dynamically change logos based on [the `prefers-color-scheme` media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), see [this README](https://github.com/supabase/realtime/blob/main/README.md) as an example.

**Comment by kgodey** [comment]
It looks like we can dynamically change this based on [the `prefers-color-scheme` media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), see [this README](https://github.com/supabase/realtime/blob/main/README.md) as an example.
