### ISSUE TITLE
API should respond with HTTP 404 status when attempting to delete a record that does not exist

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1613]
## Reproduce

1. `DELETE` `http://localhost:8000/api/db/v0/tables/1/records/0/`
1. Expect response to have HTTP status code 404 and a body with an error message indicating the record could not be found.
1. Observe response to have HTTP status code 204

**Comment by Anish9901** [comment]
Assigning myself, should be an easy fix.

**Comment by kgodey** [comment]
Thanks @Anish9901
