### ISSUE TITLE
Change behavior of cell selection via row/column headers

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1622]
The cell selection functionality, when performed via the row headers or column headers doesn't match my expected behavior. Our [specs](https://github.com/centerofci/mathesar-wiki/blob/master/design/specs/table-inspector.md) aren't super clear on these details, so I'm using this ticket to get further into the weeds by describing my expected behavior.

I want the cell selection to work the way that LibreOffice works because that seems simple and effective. Some of the UX subtleties are difficult to describe, so if you're confused about what I'm asking for, play with LibreOffice to see how it works. I find it helpful to use LibreOffice as a working prototype.

Below I'll describe the changes I'd like in terms of columns and column headers -- but these changes should apply to rows and row headers too.

## Specific changes

- When all cells in the column are selected, clicking on the column header (or dragging from and to the same column header) resets the selection to zero cells. Instead, this should begin a new selection, selecting all the currently selected cells (effectively retaining the currently selected cells).

- When I drag to select multiple columns, currently no changes are made to the selection. Instead, this should begin a new selection, selecting the cells in all columns between (and including) the starting column and the ending column.

**Comment by seancolsen** [comment]
@rajatvijay would you be willing to take this up when you tackle #1623 and #1534?

**Comment by seancolsen** [comment]
@kgodey and @ghislaineguerin, given that our specs aren't quite clear enough to justify the changes I'm requesting in this ticket, would you like to review my expected behavior to make sure it's also in line with your expectations? Perhaps there was some design rationale behind the currently implemented behavior that I missed.

**Comment by seancolsen** [comment]
Note: @kgodey and I just hopped on a quick call to clarify this ticket a bit. It turns out I wrote the original ticket description based on behavior in a outdated branch (face-palm). I've now updated the ticket description, drastically simplifying it (phew!).

**Comment by kgodey** [comment]
Thanks @seancolsen! I don't think @ghislaineguerin or I need to review this any further.

**Comment by seancolsen** [comment]
@kgodey I see that you marked this as _not_ blocking the demo video. If we don't have this for the demo video, then the only way to select multiple columns to extract them is to select multiple cells within the columns. That still _works_, but it's a bit awkward. For a demo, it would be clearer to show the user selecting multiple columns by clicking on one column header and dragging to the next. So I'd be inclined to try getting this in the demo. Is that okay?

**Comment by kgodey** [comment]
Yes, that's fine @seancolsen.

**Comment by rajatvijay** [comment]
@seancolsen can you explain more or help me reproduce: 

>When I drag to select multiple columns, currently no changes are made to the selection. Instead, this should begin a new selection, selecting the cells in all columns between (and including) the starting column and the ending column.

**Comment by seancolsen** [comment]
@rajatvijay 

> can you explain more or help me reproduce:

1. Navigate to the Patrons table page.
1. Select the "Email" cell in the first row.
1. Press mouse down on the "Last Name" column header cell (but don't lift the mouse button yet).
1. Expect the selection to contain all cells within the "Last Name" column, and only those cells.
1. Instead, observe that the selection to be empty. (This is the bug described in #1768)
1. With the mouse button held down, drag the mouse from the "Last Name" column header cell to the "id" column header cell. Then release the mouse inside the "id" column header cell.
1. Expect the selection to contain all cells within the "id", "First Name", and "Last Name" columns.
1. Instead, observe the selection to be empty. (This is the bug described by _this_ ticket.)
