### ISSUE TITLE
When extracting columns to a new table, the API should allow a name to be specified for the new FK column

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1631]
## Current behavior

- The back end auto-generates the name of the new FK column

## Desired behavior

- The API accepts an additional parameter, allowing consumers to manually specify a name.

## Implementation

- I suggest calling the parameter `new_fk_column_name` or `new_linking_column_name`.

**Comment by kgodey** [comment]
This is a duplicate of https://github.com/centerofci/mathesar/issues/1434

**Comment by seancolsen** [comment]
Thanks @kgodey
