### ISSUE TITLE
Redesign Database Page

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1640]
- [x] Should contain onboarding help content that explains what this page is for.
- [x] There should be special styling for the public schema to indicate its special status
- [x] Explain the purpose of the public schema in context (as part of the schema display)
- [x] "Create schema" should be more prominent
- [x] Show the number of tables and explorations in each schema
- [x] The design needs to cover three states:
    - [x] "Loading" - the list of schemas is loading
    - [x] "Empty" - only public schema is present and it has 0 tables (unused) - we should encourage users to create a new schema
    - [x] One or more schemas are present – we don't need the action item for creating a new schema
- [x] Updated style for the schema creation modal that includes:
    - [x] Schema description
    - [x] A place for copy explaining best practices
- [x] We need a search option for schemas with two states:
    - [x] Search results found
    - [x] No results found
- [x] The page should have centered content and generally be less wide
- [x] More color!

[Design is on Figma](https://www.figma.com/file/xHb5oIqye3fnXtb2heRH34/Styling?node-id=218%3A2)

**Comment by kgodey** [comment]
@rajatvijay @ghislaineguerin I marked this as "in review". please close this when all questions are answered – I see @rajatvijay still has an open question in Figma.

**Comment by rajatvijay** [comment]
@kgodey my comment has been resolved. Its good to close from my end
