### ISSUE TITLE
Redesign Data Import Page

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1643]
We need to go through the current workflow and create a list of requirements for this design.

- [x] Needs styling and layout work
    - [x] Import options 
    - [x] Preview and confirmation
- [x] Needs color 
- [x] Needs help content for new users
- [x] Needs icons for different upload methods

**Comment by ghislaineguerin** [comment]
Link to Design: https://www.figma.com/file/xHb5oIqye3fnXtb2heRH34/Styling?node-id=2295%3A22252
