### ISSUE TITLE
Update Record Selector UX design

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1657]
Issues identified during our usability testing:

- [ ] Foreign Key cells in tables
    - [ ] The record selector is not very discoverable. See "Record selector discoverability" below.
    - [ ] We keep accidentally clicking the Record Page icon when we want to edit the cell. We should move navigating to a linked record somewhere else.
- [ ] Help content 
    - [ ] Dismiss-able help content for anyone opening the record selector the first couple times.
    - [ ] Icon and tooltip explaining what the record selector does
    - [ ] "Locate or create" terminology is confusing.
    - [ ] The next step should always be clearly highlighted in some way.
        - [ ] Before you type anything, the next step should be typing
        - [ ] Once you've typed something, you need to choose between one of the records shown or continue creating a new record. This should be much more apparent.
- [ ] Better loading state that explains what is loading.
- [ ] Nested record selector
    - [ ] Change header to explain that it's nested
    - [ ] KEEP the clear indication of where the record will go, even if style is changed slightly (the blue border and arrow)
    - [ ] Whitespace differences between parent record and nested selector don't look good
- [ ] Adding a new record - rethink flow (see "Add a new record" below)
    - [ ] The "+NEW" location on the side is confusing, what it applies to should be clear
    - [ ]  The +NEW icon shouldn't look like a button
    - [ ] It should be more explicit how to create the new record once you type stuff in. I don't think we should save the record until the user clicks some type of save button.

### Record selector discoverability
To open the record selector, you have to click on the cell and then either: 
(1) click on the small magnifying glass (which is not a common enough icon to understand its meaning), which is a small click target
(2) know to double click on the cell

One potential solution could be to single click on the cell. Since we probably want to move the record page navigation somewhere else, we won't need multiple click targets in the same cell.

@pavish says:

> The ‘open record page’ icon gives an impression as the ‘go to’ action, instead of a double click.
> 
> I’d find it easier if there was an edit icon instead of the link icon, which opens the record selector.

### Record Page icon
One possible solution suggested by @pavish:
>  I’d prefer an hyperlink on the pill with a tool tip mentioning ‘Open record page’ instead of the link icon.

### Add a new record
I think we should make the record selector more context dependent, e.g. the initial action is just selection, then we try to find a match and have a separate “add” action that auto-populates based on what’s been searched for.

We shouldn’t show anything related to adding until we’ve started typing in a search box.

@pavish says:

> The record selector confuses me when trying to add a record, because it’s very different from how we add records normally in a table, or via record page.

> I find using the same UX to do different operations a bit harder to follow. It’ll be nice if searching only did searching, and a button that says ‘New record’ which then opens up the record page in a modal.

**Comment by seancolsen** [comment]
We discussed this on a call today and formed some decisions which are still quite rough but specific enough to allow me to begin implementation without a continued design process. I've rolled the outcome into #1553 and will use that to track implementation.
