### ISSUE TITLE
Update design for Navigation

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1658]
### Design checklist

- [x] Header states for the following
	- [x] Database Page
	- [x] Schema Page
		- [x] It should be clear how to get to other schemas from the Schema Page header
	- [x] Table Page
		- [x] It would be good to have some quick links for common actions in the header (e.g. create new table)
	- [x] Record Page
	- [x] Data Explorer
	- [x] Exploration Page
	- [x] Exploration Editor
	- [x] Data Import Page
- [x] Feedback for all header states
	- [x] Current location should always be in the breadcrumb
	- [x] It should be easy to understand how to get to the Data Explorer from any page
	- [x] The click targets for the dropdowns should be bigger than just the small triangle
	- [x] Database name in header is confusing, we should have some other solution for orienting the user to which Mathesar installation they are in
	- [x] It would be good to have some "quick links" in the header that change depending on what page you're in.

### Raw notes
Explicit navigation[^1] needed for the demo video:
- Schema Page --> Data Import (screen 3)
- Table Page --> Data Import (screen 8)
- Table Page --> related Table Page (screen 14)
- Table Page --> New Table from Scratch (screen 21)
- Schema Page --> Record Page (screen 26)
- Record Page --> related Record Page (screen 29)
- Record Page --> parent Table Page (screen 29)
- Table Page (with groups) --> Data Explorer (screen 31)
- Header --> Data Explorer (screen 34)
- Schema Page --> Exploration Page (screen 37)

Other feedback:
- Add current page to breadcrumb
- On the schema page, it's not clear how to get to other schemas
- Table features are not discoverable
- The schema icon + name should do what the little triangle does right now
- Database name in header is confusing, we should have some other solution for orienting the user to which Mathesar installation they are in
- Would be good to have some kind of action item - quick link to action depending on the page
- Data import page needs to show current location in header
- Getting to the data explorer (from any location in the app) is non-trivial.

[^1]: "Explicit navigation" here means that the user is choosing where they are navigating to. When a user creates a schema and is redirected to the newly created schema, that is _not_ explicit navigation.

**Comment by pavish** [comment]
From https://github.com/centerofci/mathesar/pull/1700#pullrequestreview-1112896884

Concern raised by @pavish:
> When the current item is added to the breadcrumb, there should not be an arrow after it.
> 
> ![Screenshot 2022-09-20 at 2 49 54 AM](https://user-images.githubusercontent.com/11850603/191118786-39258e0e-cb40-4699-85ec-67b4515b5edd.png)
> 
> Notice in the above screenshot, that the arrow with search icon makes it seem like the public schema is within a public schema.
> 
> If breadcrumb search is a concern, we would generally not need it in such scenarios since the pages would contain all links needed. Eg., Schema page will contain all the tables & explorations.


Reply from @seancolsen 

> 
> > When the current item is added to the breadcrumb, there should not be an arrow after it.
> 
> Ok. That's unfortunately not an easy change to make. The breadcrumb system is already hacky, and the design change you're proposing adds even more complexity. I'm okay with going that direction, but before I do I want to make doubly sure that's actually the design we want.
> 
> Consider the Table Page. Its breadcrumb entry has a Record Selector button after it, like so:
> 
> ![image](https://user-images.githubusercontent.com/42411/191126098-f61e3c80-1344-4bf4-b363-31f65a6f3916.png)
> 
> And when the user is on the Record Page, we use that Record Selector button to separate the Table Page link from the Record Page link, like so:
> 
> ![image](https://user-images.githubusercontent.com/42411/191126299-546df40d-5865-4f67-bb8a-ce9b72328874.png)
> 
> Do we want to keep that behavior, or change it somehow?
> 
> 
> Given that this breadcrumb design was a sticking point in the initial design phase and we've already gone back and forth on a bit, I wonder if it would be worth producing another round of mockups like I originally produced [here](https://gist.github.com/seancolsen/d3c42a14ba6c860af6e576205e5092d2#navigation-via-the-site-header) which show the site header and the page title _for every page on the site_. That way all of us can review the entire navigation/breadcrumb design more comprehensively before I go down the road of adding that additional complexity to remove the breadcrumb separator for some specific pages.

**Comment by ghislaineguerin** [comment]
Link to design: https://www.figma.com/file/xHb5oIqye3fnXtb2heRH34/Styling?node-id=2405%3A16114
