### ISSUE TITLE
Optimize MetaData use

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#1671]
### Observation
- Metadata reflection by SqlAlchemy results in 10 query each time a new metadata object is created/reflected,
    - and, most of the methods don't reuse metadata,
    - currently loading the table page requires ~1600 queries to the database;
- `mathesar.reflection.reflect_db_objects`: 
    - reflecting each database object in our model (tables, schemas, databases, columns, constraints) adds 12 query for each object as it uses a new MetaData object instead of reusing the existing MetaData;
- `db.columns.operations.select.get_columns_name_from_attnums`: 
    - fetching column name is needed for accessing the SA column object and each call to fetch the column name results in a metadata reflection call.

### Cause

- `db` module methods not reusing metadata.

### Solution
- Use a single `MetaData` instance;
    - Possibly use a multi-request `MetaData` cache;
        - Possibilities
            - Use session-level cache;
                - Django cache;
            - Use multi-session cache;
                - Maybe file or db to store pickled metadata object;
        - How to keep cache's validity up to date?
            - Maybe invalidate it when doing mutating operations.

**Comment by kgodey** [comment]
Closing this since #1626 is merged. @dmos62 if there are specific issues remaining, please create additional GitHub issues.
