### ISSUE TITLE
Fix regression - Allow setting default value

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#1672]
https://github.com/centerofci/mathesar/pull/1628 removes the Default value option out of the type selector.

We need to add a separate section in the Table Inspector columns tab, to support editing default value as per the [spec](https://github.com/centerofci/mathesar-wiki/blob/master/design/specs/data-type-options.md).

**Comment by rajatvijay** [comment]
![Image](https://user-images.githubusercontent.com/11032856/208387551-7e9fc7aa-1e45-4c7a-adec-edb71618bd2a.png)

Fixed under #1995
