### ISSUE TITLE
Bug with primary keys in Record Selector

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1683]
@pavish reports: 
> Searching for primary key, allows me to try adding a record even when a record with the primary key already exists. This results in an error, but that isn’t visible to the user.

**Comment by seancolsen** [comment]
In #1856 I've implemented logic which throws a toast message showing any errors encountered in the process of creating the record. I think this should suffice enough in the short term that I'm marking that PR to close this ticket. But in the long term, we need more granular error info, so I've opened #1882 to track progress on that.
