### ISSUE TITLE
Creating a one-to-one link via Link Table modal fails

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1685]
@pavish reports:

> Creating a one-to-one record from the UI currently fails with error:
> “This field may not be blank.”
> 
> The new column name input contains a value.

**Comment by kgodey** [comment]
We're not doing this in the demo video, so this is getting pushed to the live demo.

**Comment by mathemancer** [comment]
It seems the request isn't passing along the new column name.

Example request from my installation:
```
{link_type: "one-to-one", reference_table: 10, reference_column_name: "", referent_table: 11}
```
