### ISSUE TITLE
Improve UX after columns are extracted to a new table

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1701]
## Current behavior

- We don't provide a great experience for the user after extracting columns to a new table.
- The new column ends up ordered at the end.
- The new column may be horizontally scrolled out of view (especially given that it's placed at the end of the table).
- The new column is not selected.
- The user doesn't have any indication of success, other than the modal closing.

## Desired behavior

- The new FK column is selected.
- The new FK is horizontally scrolled into view.

## Design questions

- Other than the "desired behavior" above, is there anything _else_ we want to do to communicate success to the user? Do we want to display a toast message?

## Other _eventually_ desired behavior, not covered by this ticket

(Mentioned here for the sake of completeness)

- Our [specs](https://github.com/centerofci/mathesar-wiki/blob/master/design/specs/column-extraction.md) also require the new FK to be positioned in the table where the old columns were. Notwithstanding the ambiguity arising from non-adjacent old columns, merely sorting the new column at all will already require some [formidable work](https://github.com/centerofci/mathesar/issues/1584). I don't want to attempt to address that within this ticket, but I'm highlighting this problem to make it clearer why we have the other problems.

**Comment by seancolsen** [comment]
@kgodey and @ghislaineguerin can you weigh in on the design question above?

@kgodey I wasn't sure which milestone to place this in. This behavior will be visible in the demo video, but in theory we could manually scroll to the column and select it while producing the video.

**Comment by kgodey** [comment]
@seancolsen I think deferring this until the live demo is fine, in the spirit of ruthlessly cutting things.

> Other than the "desired behavior" above, is there anything else we want to do to communicate success to the user? Do we want to display a toast message?

A toast message would be nice.

**Comment by AlekLefebvre** [comment]
@seancolsen like you suggested in #1904, I can help with this issue. I have implemented the FK selection and the toast message. I'm working on scrolling to the new FK and then I'll submit a PR.
