### ISSUE TITLE
Hide grouping separators by default in Number columns

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1709]
## Current behavior

- We default to displaying grouping separators (e.g. `1,234`) in _all_ numbers.
- Users can turn off grouping separators by customizing their display options.
- This "on-by-default" behavior, feels a bit strange for columns like primary keys and years, where users typically don't see grouping separators.
- During import, Mathesar uses the `numeric` type by default -- even if all values within the import data can be cast to integers. @mathemancer explained that we made this decision early on in order to be flexible, and I think it's worth sticking with it. But it means that years don't get imported as integers by default, making it hard to take the approach were heading towards with the discussion in #1527.
- The back end does not set the grouping separator display option during import. It only gets set via the front end if the user manually adjust it.

## Desired behavior

- When the user has not configured any display options:
    - Columns with a UI type of "Number" will be rendered without grouping separators (regardless of their Postgres type). This means that the user will need to manually turn them on sometimes.
    - Columns with a UI type of "Money" will be rendered _with_ grouping separators. The user can turn them off if needed.

**Comment by kgodey** [comment]
I think this makes sense.

We can improve our inference for integers once we have global inference (see https://github.com/centerofci/mathesar/issues/438). It may be worth revisiting this decision afterwards.
