### ISSUE TITLE
Improve readability of column moving logic

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#1715]
## Problem
Our column moving logic is difficult to get into. There's a related bug I've encountered and am of the opinion that a focused effort to improve column moving logic's readability is warranted.

## Proposed solution
@silentninja proposed that we do this together on a call.

## Additional context
@silentninja and @mathemancer seem to have insight into that logic.

Putting this into Live Demo milestone, because I might soon break code affected by this and it will become a prerequisite to fixing it.

**Comment by seancolsen** [comment]
I'm closing this because it's old, has very little discussion, and seems to be low priority. If anyone disagrees with my assessment, we can re-open this.
