### ISSUE TITLE
Exploration name should be unique per schema

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#1720]
## Description
* Previously, we had a nasty bug because the frontend and backend scoped explorations differently with respect to the schema. This was discussed in https://github.com/centerofci/mathesar/issues/1587, and a fix on the frontend was implemented in https://github.com/centerofci/mathesar/pull/1707.
* The problem of scoping explorations within schema still exists.
* A noticeable issue due to that:
   * Create an exploration and save it as 'Exp1' in 'Schema 1'.
   * Create another exploration in 'Schema 2' and save it as 'Exp1'. Notice that an error is throws saying 'An exploration with same name already exists'.
   * The exploration is not visible anywhere within 'Schema 2', so the user would not understand why the error occurred.

## Outcome
We need to figure out the most user friendly way to handle this issue.

cc: @mathemancer, @kgodey, @dmos62

**Comment by mathemancer** [comment]
@pavish This is a non-trivial backend change, since the query doesn't directly have its own schema (the base table does). Why not just put some verbiage like "query names must be globally unique"?

**Comment by pavish** [comment]
@mathemancer That would not be ideal for the user because they create explorations inside a schema, not globally. So, based on our users permission spec, they may not have access to other schemas, so won't know why the error is thrown.

**Comment by kgodey** [comment]
In [this thread](https://groups.google.com/a/mathesar.org/g/mathesar-developers/c/4svSBM50itg/m/tynCvGhiBwAJ), we agreed that we did not want to limit cross-schema operations in the long run, and that backend should provide schema related information to the frontend, but not artificially limit operations. 

As specced, this issue would involve the backend in limiting things by schema, it seems like the wrong direction to go in.

**Comment by pavish** [comment]
@kgodey The cause for concern is because it's an UX issue. I do not know the best way to resolve it, but I do think it's something we should figure out for our initial release, for which I do not think we intend to support multiple databases.

**Comment by dmos62** [comment]
Hm, @mathemancer, do we actually care about a query/exploration's name on the backend? We've given it the unique constraint, but a Query is identified by the Django ID, so do we care what the name actually is?

We may have tech debt relying on the name being unique (that I'm unaware of), but I don't see any reason beyond that to keep the unique constraint.

**Comment by kgodey** [comment]
> do we actually care about a query/exploration's name on the backend?

We do care on the frontend, the name is the primary way a user identifies an exploration.

**Comment by dmos62** [comment]
@kgodey Not sure if you're disagreeing or just adding information. Or, do you mean that a query should have a backend-unique name?

If I was unclear, by saying that we don't care about a query's name on the backend, I meant that we don't use it for identification, so it can be anything the frontend likes, and any constraint we have placed upon it in the backend is superfluous, from backend's perspective.

**Comment by kgodey** [comment]
> Not sure if you're disagreeing or just adding information.

I was adding information, sorry for any confusion.

**Comment by pavish** [comment]
Closed in https://github.com/centerofci/mathesar/pull/2315
