### ISSUE TITLE
Layout components to accommodate new designs

### ISSUE THREAD

**Issue by rajatvijay** [centerofci/mathesar#1740]
## Problem
In order to implement the new designs for the database page and schema page the first thing that we need to do is create components for common layouts. 

## Proposed solution
After looking at the designs here are the common layouts IMHO.

### LayoutWithHeader
This component will have two responsibilities: 
1. Adding a static header on the top.
2. Rendering the children inside the `main` with some `max-width` so that the layout does not spread across the width of the larger screens. This `max-width` behavior can be toggled using a prop since we might not need this restriction for certain pages for example the Table page. 

<img width="1001" alt="Screenshot 2022-09-28 at 2 55 44 PM" src="https://user-images.githubusercontent.com/11032856/192742836-cf4a8329-399f-4318-8f0a-24d67d341376.png">

_NOTE: This will be purely a presentational component._

#### Can we reuse the existing `LayoutWithHeader` component?
We can use this existing component but this might need us to check the layout at other places too where this component is used and make sure no bugs are introduced there which might delay the delivery of the DB and schema page. I suggest we create a new component with the current needs and gradually start using at other places once we do their designs. 

#### Header
The header in itself will be a separate component that gets rendered inside the `LayoutWithHeader` component. I don't see the header requiring any props as of now but if we need this in the future, the `LayoutWithHeader` should support all of the header props too and pass them down to this component. 

### PageTitleAndMeta
<img width="321" alt="Screenshot 2022-09-28 at 3 02 21 PM" src="https://user-images.githubusercontent.com/11032856/192744316-aac327ab-e91f-4abb-b4f9-938e371a2f5a.png">

This component will be responsible for the following things: 
1. Rendering the `type` of the entity. It will be of type `string` but for now `schema` / `database` will be the possible values. 
2. Rendering the `name` of the entity. So if the entity type is a `database` then it will be the name of the DB. 
3. Rendering the `icon` using the `icon` prop of type `IconProps`.
4. Rendering the `description`, if any. 
5. Rendering an action button using the `buttonProps` prop. 

<img width="688" alt="Screenshot 2022-09-28 at 2 57 46 PM" src="https://user-images.githubusercontent.com/11032856/192744204-dd8617b6-99d5-458e-98a0-2abc5ae7443f.png">

_NOTE: This will be purely a presentational component._

**Comment by rajatvijay** [comment]
@seancolsen @pavish can you review this?

**Comment by pavish** [comment]
@rajatvijay 

> We can use this existing component but this might need us to check the layout at other places too where this component is used and make sure no bugs are introduced there which might delay the delivery of the DB and schema page. I suggest we create a new component with the current needs and gradually start using at other places once we do their designs.

This is fine by me.

> PageTitleAndMeta

I'd prefer this component to use slots rather than props that would make it too specific.

**Comment by seancolsen** [comment]
@rajatvijay and I discussed this briefly on a call today and I gave my approval.
