### ISSUE TITLE
Date input should close date picker when losing focus via Tab or Shift+Tab

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1769]
## Steps to reproduce

1. Navigate to the Record Page for one Checkouts record.
1. Click on the "Checkout Time" input field to focus it.
1. Observe the date picker to appear (good).
1. Press Tab to focus on the Due Date input.
1. Expect the Checkout Time date picker to close.
1. Instead, observe the Checkout Time date picker remains open, even when the Due Date date picker has also opened.

https://github.com/centerofci/mathesar/assets/42411/e4d4f9d9-875c-4b0b-9c6c-d627653dcd78

https://github.com/centerofci/mathesar/assets/42411/e1c054a3-dec1-49d9-9362-2dc687949e74

CC @pavish

**Comment by kgodey** [comment]
Moving this to the Backlog – this isn't critical enough to block launch.

**Comment by seancolsen** [comment]
Now that this is in the backlog, I'm opening it up for community contributors. I think it should be a relatively simple fix.

**Comment by varun7singh** [comment]
can i work on this issue rather ? @kgodey

**Comment by seancolsen** [comment]
Thanks @varun7singh. I've assigned you. Be sure to read our [Contributor Guide](https://wiki.mathesar.org/en/community/contributing)

**Comment by varun7singh** [comment]
@seancolsen you can review this #2419

**Comment by rajatvijay** [comment]
@seancolsen I disagree that 

> Expect the Checkout Time date picker to close.

should be the expectation here, rather the date picker popup should be focused, and the `tab` should let the user navigate inside the popup.

**Comment by seancolsen** [comment]
@rajatvijay 

>  the tab should let the user navigate inside the popup

Can you make a case for why we would do this? How would tab-based keyboard navigation behave within the popup? Would every day in the calendar be a focusable button? I'm having trouble imagining any keyboard navigation behavior that would seem useful here. The user can already enter dates via the keyboard by _typing_ the dates. To me that seems way easier than anything we'd be able to come up with using the tab key. Also consider that tabbing through input fields on a form is a very common behavior users expect. If I want to use tab to "skip" a date field, but doing so requires pressing tab like 30 or more times, then we're effectively breaking that common behavior. Maybe I'm misunderstanding your proposal. If you still disagree with my proposal, then it would be nice to see a more detailed explanation of how you envision this working. I'd especially like to see how you would envision a user being able to use the keyboard to move focus past a date input and onto the next focusable element.

**Comment by rajatvijay** [comment]
@seancolsen 

> How would tab-based keyboard navigation behave within the popup? Would every day in the calendar be a focusable button? I'm having trouble imagining any keyboard navigation behavior that would seem useful here

My concern was more from the point of view of making the [date picker component accessible](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/datepicker-dialog/). As a user when I tried performing the steps mentioned in the issue I expected the tab and arrow keys to let me choose the date from the date picker. 

After doing some research I realize that its better to take that as a separate issue. 

> Also consider that tabbing through input fields on a form is a very common behavior users expect. If I want to use tab to "skip" a date field, but doing so requires pressing tab like 30 or more times, then we're effectively breaking that common behavior

I agree this^ is a more common need and easier to implement given we already have: 

> The user can already enter dates via the keyboard by typing the dates


-------

To answer the following question: 

> How would tab-based keyboard navigation behave within the popup? 

See https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/datepicker-dialog/#kbd_label

**Comment by seancolsen** [comment]
@rajatvijay

> ...do you think the expected outcome should rather be:
> 
> _"Expect the Checkout Time date picker to close and move to the next focusable element."_

In the ticket description, I said _"Expect the Checkout Time date picker to close."_

You are proposing that we add _"move to the next focusable element"_ as an additional expectation. What exactly do you mean? Move _what_? The focus? The focus already moves, so I didn't mention that in my expectation or observation because I don't want to modify it.

Can you clarify your opinion? It sounds like maybe I convinced you of my position. If not, what would you like to change?

---

That date-picker in the `w3.org` example works quite differently from ours. It's decoupled from the input. When you focus the input, the date picker doesn't open. When the date picker is open, you can't type a date via the keyboard. I like our design better, especially when considering data entry via cells because with the cells it's would be cumbersome to place that date-picker trigger button somewhere.

**Comment by Pulkit0729** [comment]
Hi @seancolsen , is this still an open issue?

**Comment by seancolsen** [comment]
@Pulkit0729, yes this issue is still open. Feel free to submit a PR for it.

**Comment by Pulkit0729** [comment]
https://github.com/centerofci/mathesar/assets/82268257/a316296f-8b64-49bd-a453-917cb958fb87

Hi @seancolsen , I tried to reproduce the issue, but it seems its working as expected?

**Comment by seancolsen** [comment]
@Pulkit0729 yes this issue is still present. You can't reproduce it within the table cells due some of the special behavior of cells. But I added a couple screencaps reproducing the issue in other areas of the app.

**Comment by Pulkit0729** [comment]
Thanks @seancolsen for the screencaps. It is clear to me now

**Comment by Pulkit0729** [comment]
Hey @seancolsen , Added a PR (https://github.com/centerofci/mathesar/pull/3038) please have a look.
