### ISSUE TITLE
Close context menu on Esc

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1772]
## Current behavior

- We have a custom context menu that opens when right-clicking on a table cell.
- The only way to close it is to click somewhere outside the menu.

## Desired behavior

- Pressing the Esc key closes the context menu

**Comment by surajrane42** [comment]
Hey @seancolsen I would like to work on this

**Comment by kgodey** [comment]
Go ahead @surajrane42, thanks for your interest.

**Comment by Pranav2612000** [comment]
Hey @surajrane42 Were you able to work on this? I'll also like to take a stab at it if you are busy with something else

**Comment by surajrane42** [comment]
Hey @Pranav2612000, I was busy this week & wasn't able to work on it but if you are interested you can take this task.

**Comment by lakshya-dhariwal** [comment]
Hey @kgodey I have created a PR for the issue , if any issues come up in review I'll fix them.
#1829
