### ISSUE TITLE
Changing columns in the "Columns to Move" field should update cell selection in the table

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1790]
Removing or adding columns in the modal field `Columns to Move` should also update the selection in the table. Refer to the image on the right.
<img width="1618" alt="Cycle 3 reference" src="https://user-images.githubusercontent.com/287034/195135297-29b05b07-8379-47e3-af21-f9575ceb54d6.png">

**Comment by AlekLefebvre** [comment]
I'd like to help with this issue. I drafted PR #1904 which fixes the issue and would like some feedback to improve it.
