### ISSUE TITLE
Implement automatic list aggregation when joining on one-to-many link

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1795]
@seancolsen reports:

> The process of joining on a reverse relationship might be confusing. Set base table to Authors. Add id, first name, last name. Observe 14 results. Ok cool. Now add "Publications"."Title" and observe 65 results. What? I understand what happened, but someone who has never used SQL is likely to be confused by this jump in results. 
>
> I have a vague memory of expressing this concern many months ago and hearing from someone that our design was such that one-to-many data like this would be pulled in with an automatic array aggregation.

The [spec](https://wiki.mathesar.org/en/design/specs/visual-query-builder) did specify automatic aggregation, but this wasn't implemented per [this email thread](https://groups.google.com/a/mathesar.org/g/core-team/c/qR-vcl88Uac/m/jsK5QEhFBAAJ) to reduce scope. This is important for good UX and we should implement it for the live demo.

**Comment by kgodey** [comment]
Blocked on design work in #1655

**Comment by dmos62** [comment]
I was initially confused about the difference between this and #1797.

#1797 is a prerequisite for this issue. In #1797, we're talking about backend being able to finish specifying partially-specified group-agg transformations. Here we're talking about addressing the number of rows increasing when you add a "multiple results" initial column to a query, and we're hoping to do that with backend filling in a partial group-agg transformation.

**Comment by dmos62** [comment]
When #1973 is merged, all major building blocks from the backend's side will be implemented, afaik. @pavish can we squeeze this into cycle 6?

If I recall correctly, we decided on finding a design that, when adding a one-to-many initial column, would ask the user if he wants us to add a default summarization.
