### ISSUE TITLE
Summarization should not aggregate fields from the base table

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1797]
@seancolsen reports:

I want to see authors and how many books they've published like this:

```sql
select
  "Authors".id,
  "Authors"."Author First Name",
  "Authors"."Author Last Name",
  count("Publications".id)
from "Authors"
left join "Publications" on
  "Publications"."Author" = "Authors".id
group by "Authors".id
```

I can kind of do this, "Author First Name" and "Author Last Name" are mandatorily aggregated.

---

When we add new columns to a a summarized view and they are from the base table or they are from a column that has a 1:1 relationship with the base table, they should not be aggregated.

**Comment by mathemancer** [comment]
Note that for consistency reasons, all columns in a summarization must either be grouped by, or aggregated.

The UX currently requires the user to choose a _single_ column to group by, and every other column included is aggregated. The resulting request (using the example from @kgodey) is:
```json
{
  "base_table": 5,
  "initial_columns": [
    {
      "alias": "Authors_id",
      "id": 1,
      "display_name": "Authors_id"
    },
    {
      "alias": "Authors_Author First Name",
      "id": 2,
      "display_name": "Authors_Author First Name"
    },
    {
      "alias": "Authors_Author Last Name",
      "id": 3,
      "display_name": "Authors_Author Last Name"
    },
    {
      "alias": "Publications_id",
      "id": 19,
      "jp_path": [
        [
          1,
          22
        ]
      ],
      "display_name": "Publications_id"
    }
  ],
  "transformations": [
    {
      "type": "summarize",
      "spec": {
        "grouping_expressions": [
          {
            "input_alias": "Authors_id",
            "output_alias": "Authors_id"
          }
        ],
        "aggregation_expressions": [
          {
            "input_alias": "Authors_Author First Name",
            "output_alias": "Authors_Author First Name_1",
            "function": "aggregate_to_array"
          },
          {
            "input_alias": "Authors_Author Last Name",
            "output_alias": "Authors_Author Last Name_1",
            "function": "aggregate_to_array"
          },
          {
            "input_alias": "Publications_id",
            "output_alias": "Publications_id_1",
            "function": "count"
          }
        ]
      },
      "display_names": {
        "Authors_Author First Name_1": "Authors_Author First Name_agg",
        "Authors_Author Last Name_1": "Authors_Author Last Name_agg",
        "Publications_id_1": "Publications_id_agg"
      }
    }
  ],
  "parameters": {
    "limit": 100,
    "offset": 0
  }
}
```
Note that the request is to aggregate all columns except `Authors_id`. The proper request to get the effect requested is:
```json
{
  "base_table": 5,
  "initial_columns": [
    {
      "alias": "Authors_id",
      "id": 1,
      "display_name": "Authors_id"
    },
    {
      "alias": "Authors_Author First Name",
      "id": 2,
      "display_name": "Authors_Author First Name"
    },
    {
      "alias": "Authors_Author Last Name",
      "id": 3,
      "display_name": "Authors_Author Last Name"
    },
    {
      "alias": "Publications_id",
      "id": 19,
      "jp_path": [
        [
          1,
          22
        ]
      ],
      "display_name": "Publications_id"
    }
  ],
  "transformations": [
    {
      "type": "summarize",
      "spec": {
        "grouping_expressions": [
          {
            "input_alias": "Authors_id",
            "output_alias": "Authors_id"
          },
          {
            "input_alias": "Authors_Author First Name",
            "output_alias": "Authors_Author First Name"
          },
          {
            "input_alias": "Authors_Author Last Name",
            "output_alias": "Authors_Author Last Name"
          }
        ],
        "aggregation_expressions": [
          {
            "input_alias": "Publications_id",
            "output_alias": "Publications_id_1",
            "function": "count"
          }
        ]
      },
      "display_names": {
        "Publications_id_1": "Publications_id_agg"
      }
    }
  ],
  "parameters": {
    "limit": 100,
    "offset": 0
  }
}
```
Here, the columns of the base table are all included in the `grouping_expressions` block, and the result is as desired.

I recommend against trying to figure out which columns are one-to-one with the chosen grouping key for performance and general complexity reasons. I suggest instead:
- Modify the UI so users can choose more grouping columns (at the moment, it seems only one is possible).
- Default to all base table columns being in the grouping block, and all non-base-table columns being in the aggregation block.

Big picture, I think it's pretty important to let the user choose whether to group by or aggregate each column (but with decent defaults provided) as they choose. For example, our overdue books report requires grouping by a non-base table column, and aggregating a base table column (though you could get around this with the greater depth for joinable tables discussed in other issues, I think the most intuitive flow would still start from checkouts as the base table).

**Comment by dmos62** [comment]
@pavish does Brent's explanation make sense? If so, we should remove the `work: backend` tag.

**Comment by pavish** [comment]
@dmos62 Based on Brent's explanation, this is blocked on design. I'd suggest keeping the tag until the design is finalized.

CC: @kgodey

**Comment by kgodey** [comment]
@mathemancer suggested:

> - Modify the UI so users can choose more grouping columns (at the moment, it seems only one is possible).
> - Default to all base table columns being in the grouping block, and all non-base-table columns being in the aggregation block.

I assume the second point is possible without any design work. I think we should go ahead and implement that.

As long as we have sensible defaults for which columns are in the grouping block, I'm not convinced that we need the UI to switch columns between grouping and aggregation blocks for the live demo. I think we can do that as a future improvement.

**Comment by pavish** [comment]
> I assume the second point is possible without any design work. I think we should go ahead and implement that.

Okay, I'll proceed with this for now.

@kgodey 
However, this takes us back to one of the issues I've been bringing up multiple times now. The UX and the backend are at conflict with eachother and it's left to the frontend to resolve this. Most of the complexity and high work load on the frontend arises due to this, and I would really like to avoid it as much as possible.

Just this simple scenario, where the frontend has to be now aware of the table of the columns present in the `grouping_expressions` and the `aggregation_expressions`, and separate them based on the base table involves a number of isolated components to be aware of these details, and makes the internal model very different from the actual requests being sent to and fro with the server. This is a considerable amount of work which only arises because the UX is not inline with backend expectations.

**Comment by kgodey** [comment]
@pavish I'd actually say that the backend needs to support the UX, not the other way around. But I understand the problem here. 

Would it make more sense for the backend to do this automatically once you add columns to the query? Before you start on this, It might be worth having a call with @dmos62 and @mathemancer to figure out the best architecture so that all the work doesn't fall to the frontend.

**Comment by pavish** [comment]
@kgodey Agreed, I believe a call is warranted. I'll schedule one before I pick this issue.

**Comment by mathemancer** [comment]
While I'm happy to participate in the call, it might be possible there's a middle ground we could reach async.

I didn't intend to demand that the default needed to be _suggested_ by front end logic, just that it should be visible and modifiable from the front end, and the query that's run should be precisely defined by the request. Similar situations (in my mind) would be suggesting types for columns when importing, suggesting display options, etc. The new column mapping suggestions endpoint will work similarly: You ask the back end for some suggestion (say at `/api/ui/v0/queries/suggest_summarization/`, then use that suggested block in your request. Applied to this case, you'd ask the back end for the "default summarization" calculated by the query so far, then use that suggestion (if desired) when requesting query results.

Advantages of this (as opposed to just having `"summarize": "default"` or the like in the request) would be:
- The front end would have enough context to let the user modify the summarization before requesting results.
- You could get a new suggested default _if desired_ when other parts of the query change, but it wouldn't be required. This would help avoid user confusion when they change some other thing about their query and the summarization step changes invisibly.

**Comment by dmos62** [comment]
> Just this simple scenario, where the frontend has to be now aware of the table of the columns present in the grouping_expressions and the aggregation_expressions, and separate them based on the base table involves a number of isolated components to be aware of these details, and makes the internal model very different from the actual requests being sent to and fro with the server. This is a considerable amount of work which only arises because the UX is not inline with backend expectations.

@pavish Data Explorer backend does presume that, as columns "flow" through a query's transformations, the frontend will be able to differentiate which are base table columns. I don't see alternatives or improvements to be made in the API, unfortunately, but if you do, I'd be really interested in hearing about it. We can talk about it on a call, and if you outline some of your ideas async beforehand, I would find that useful as well.

**Comment by dmos62** [comment]
Conversations here grew into us needing a way for the backend to suggest or provide default group-agg transformations. The issue is generalized in https://github.com/centerofci/mathesar/issues/1880.
