### ISSUE TITLE
Fix `array_agg` on money columns

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1798]
`array_agg` on a money column looks pretty weird

![image](https://user-images.githubusercontent.com/42411/193683902-ed885c25-30be-43be-a32b-0e8ccc2a4605.png)

**Comment by dmos62** [comment]
Something similar happens to array aggregation on url columns.

**Comment by pavish** [comment]
@dmos62 @mathemancer I'm re-opening this because I'm noticing this issue currently.

**Comment by pavish** [comment]
I'm removing myself from this issue since no frontend work is needed for this.
