### ISSUE TITLE
Sean's Data Explorer bugs

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1799]
Reported by @seancolsen 

- [ ] Editing the "with display name" field for a column within a summarization will not update the column name anywhere if a filter with an invalid condition is applied after that summarization.
- [x] After I modify the display name for a column, a filter condition operating on that column still displays its old name.
- [x] Checking/unchecking columns within the summarization aggregate settings adds/removes them from the table in the order in which they are checked -- not the order in which they appear in the aggregate list.

**Comment by dmos62** [comment]
These seem like frontend bugs. Can I remove the `work: backend` label?

**Comment by kgodey** [comment]
From the call yesterday, @pavish said he might need backend help with one of these, I don't recall which one.

**Comment by pavish** [comment]
@dmos62 I _might_ need changes regarding placing the `display_name` keys out of the `initial_columns` array. I'll have to start working on the issue to see if that is required.

**Comment by pavish** [comment]
Removing backend tag, since the [mentioned requirement](https://github.com/centerofci/mathesar/issues/1799#issuecomment-1277722230) is already implemented.

**Comment by pavish** [comment]
Moving this to an earlier milestone since this will be fixed along with the remaining Data Explorer work
