### ISSUE TITLE
Deleting a record referenced by an FK should show the correct error message

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1813]
Currently, if you try to delete a record that has a foreign key that links to it, it looks like this. 
<img width="675" alt="Screen Shot 2022-10-12 at 1 09 41 PM" src="https://user-images.githubusercontent.com/287034/195405792-35a2bcf4-d30a-4b1a-ba38-3bb55f5774a9.png">

We should show a human readable error message here. 

Ideally, we should give them an option to delete all records that link to this one, but that's probably out of scope for the demo.

**Comment by pavish** [comment]
@rajatvijay I'm reassinging this to you since it's part of the table page.

**Comment by seancolsen** [comment]
I just tested this and got this error message which looks pretty good:

![image](https://user-images.githubusercontent.com/42411/210825943-09c1ffc3-e6de-4b5c-a9b7-736872887d3e.png)

 @kgodey Can we close this ticket? If not, what should the error message say?

I agree that cascade delete is out of scope for now. I've opened #2202 to track it.

**Comment by kgodey** [comment]
We can close it. Thanks for opening #2202.
