### ISSUE TITLE
Automating the building and pushing of the docker image

### ISSUE THREAD

**Issue by rghdrizzle** [centerofci/mathesar#1825]
## Problem

Before addressing a suggestion , I would like to know if the docker image is pushed to the hub or somewhere else 
and if there is already a pipeline where it automates the building and pushing when the pipeline is triggered  .

## Proposed solution

If there is no such pipeline , then I would suggest to have a pipeline (or a job) to automate the process building  and pushing of the image 

## Additional context

- Blocked by #2032 
- Related to #2034

**Comment by kgodey** [comment]
@rghdrizzle We're still in development mode, so we don't publish our Docker image anywhere yet. We will do this when we do our first release (hopefully in December).

**Comment by rghdrizzle** [comment]
@kgodey Suree!! Hopefully i get to work on it when it goes to production environment

**Comment by kgodey** [comment]
This should be covered by #2040, so closing this.
