### ISSUE TITLE
Design for basic table operations

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#185]
**Problem**

Users may want to:
- create a new empty table
- create a table from copy/pasting data
- create a table by uploading a file from a remote URL
- edit the name of a table
- delete a table
 
We should allow this through the UI

**Proposed solution**

We need a design for how users can accomplish these tasks, including error states if a table is unable to be edited or deleted, or if a user might need to perform additional actions before a table is deleted (such as removing references to it from other places).

**Additional context**

We'll know more about what error states a user might encounter after #184 and #186 are implemented.

**Comment by ghislaineguerin** [comment]
Spec posted here: https://wiki.mathesar.org/design/specs/table-operations
