### ISSUE TITLE
Additional information needed in column_metadata in Query run endpoint

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#1883]
We need the following additional information in the `column_metadata` property in Query run response. This is needed to show the information on the inspector panel based on the [new figma designs](https://www.figma.com/file/xHb5oIqye3fnXtb2heRH34/Styling?node-id=1384%3A6672):
* Table name
* Base column name
* For aggregated columns, it should contain the respective input column alias

Previously, I was able to show the table name and base column name using the information from joinable_tables endpoint, but since we now have the inspector additionally within the Explorations page (where the joinable_tables call is unnecessary), I would like this information to come from the column_metadata.

cc: @dmos62 @mathemancer

**Comment by dmos62** [comment]
What's the base column name for an alias / a column in a query? I've not heard of this term before. Is it the initial column name that can be traced back from a given alias? Does a column generated by aggregation have it?

What's the table name for a column generated by aggregation? Is it not expected to be specified in that case?

**Comment by pavish** [comment]
> What's the base column name for an alias / a column in a query? I've not heard of this term before.

It is the name of the underlying column in the table.

> Does a column generated by aggregation have it?

No. It does not.

> I wouldn't expect a column name to be an identifier for an initial column. I'd expect an alias if the goal is to identify the initial column associated with another alias.

The goal is to show information of the underlying table and column to the user. We do not do any operation based on the column name.

> What's the table name for a column generated by aggregation? Is it not expected to be specified in that case?

For columns generated by aggregation, we do not need the column name or the table name. We however, need the alias of the initial_column which was used to generate this column.

--

For initial_columns: We need underlying table_name and column_name in the table.
For generated columns: We need alias of the associated initial_column.

It would be helpful to have an additional flag specifying if the column is 'initial' or 'generated'.
