### ISSUE TITLE
When column is selected, change active cell to the first cell in column

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1884]
## Steps to reproduce

1. Open an exploration with multiple columns.
1. Click on a cell to select it.
1. Click on the column header for a different column.
1. Expect the active cell to move to the first cell within the selected column.
1. Instead, observe the active cell to remain at the cell initially selected. This is a problem because the active cell does not lie within the set of selected cells.

~~I'm only able to reproduce this within the Data Explorer (the Table Page does not have this bug).~~ (See [below comment](https://github.com/centerofci/mathesar/issues/1884#issuecomment-1303052829))

CC @pavish

**Comment by pavish** [comment]
When a column is selected, I think the best UX would be to set the activeCell to the cell in the first row associated with the selected column.

**Comment by rajatvijay** [comment]
Closing this since this cannot be reproduced anymore.
