### ISSUE TITLE
Allow dragging to select cells from active cell

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1885]
## Steps to reproduce

1. Open an exploration or table page.
1. Click a cell to select it.
1. Initiate a drag from that same cell, dragging to an adjacent cell.
1. Expect the two adjacent cells to become selected.
1. Instead, observe that only the initial cell is selected.

CC @pavish because this is a regression introduced in #1875

**Comment by pavish** [comment]
Good catch. I noticed that the active cell was being reselected each time the user clicks on the same cell and selection related stores were updated twice for each selection operation, and removed the additional call. Turns out, this logic depends upon that call which is not the best way to do this. We need to handle this bug without re-activating the same cell.

**Comment by seancolsen** [comment]
Interestingly, I just noticed that dragging from the active cell _does_ work if the active cell is an FK cell. But it doesn't work if the active cell is another type of cell, like a number cell. Weird. Just wanted to mention this for consideration during implementation.

**Comment by kgodey** [comment]
Moving to backlog; doesn't block launch.

**Comment by seancolsen** [comment]
@pavish I am taking this up now and I'd like some more info from you so that I don't undo your work.

In `SteppedInputCell.svelte` if I change...

```ts
function handleMouseDown() {
  if (!isActive) {
    dispatch('activate');
  }
}
```

...to

```ts
function handleMouseDown() {
  dispatch('activate');
}
```

...then what exactly is the problem? 

You said:

> I noticed that the active cell was being reselected each time the user clicks on the same cell and selection related stores were updated twice for each selection operation, and removed the additional call. Turns out, this logic depends upon that call, which is not the best way to do this. 

I'm not following you. Can you provide step-by-step instructions to reproduce the unwanted behavior that you previously fixed? I'd like to try to figure out how to fix the bug which this ticket describes without introducing a regression, but I don't understand the original problem that you were fixing when you introduced this bug.

**Comment by rajatvijay** [comment]
@seancolsen I already had this in progress.

**Comment by seancolsen** [comment]
@rajatvijay and I just chatted about this. He's already done some work on this. He'll open a PR soon and I will review it.

**Comment by pavish** [comment]
@seancolsen 

> I'm not following you. Can you provide step-by-step instructions to reproduce the unwanted behavior that you previously fixed? I'd like to try to figure out how to fix the bug which this ticket describes without introducing a regression, but I don't understand the original problem that you were fixing when you introduced this bug.

This was a performance improvement. A number of actions were triggered when a cell became active and I wanted to remove the unnecessary actions due to the same cell being activated again.
