### ISSUE TITLE
Re-focus table cell after opening record selector on that cell

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1892]
## Steps to reproduce

1. Go to the Table Page for a table that has a foreign key column.
1. Open the Record Selector from an FK cell.
1. Close the Record Selector, either via Esc, the close button, or by submitting a value.
1. Expect the cell within the table to remain selected and active.
1. Instead observe that after closing the Record Selector, the cell is no longer active.

## Related

- #1917

**Comment by seancolsen** [comment]
Related:

- #1873
- #1771

**Comment by ana42742** [comment]
Hey, I would like to work on this. Could you please assign it to me?

**Comment by seancolsen** [comment]
Sure, go ahead @ana42742
