### ISSUE TITLE
No row should be selected when a cell within the placeholder row is selected

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1912]
## Steps to reproduce

1. Go to a table page.
1. Select a cell within the last row of the table.
1. Observe that, in addition to the cell being highlighted, the row header is also highlighted, indicating that a cell within the row is selected. Good.
1. Press the `DownArrow` keyboard key.
1. Observe the cell selection to move into the "placeholder" row (that you can use to create new records). Good.
1. Expect that _no row headers should be highlighted_ (not even the placeholder row header).
1. Instead, observe that the same row header as before is highlighted, putting the cell selection out of sync with the row selection.
1. A further symptom of this problem is that within the table inspector, the "Record" tab shows an action to delete a record. But no record should be selected at this point.

**Comment by lakshya-dhariwal** [comment]
Hey @seancolsen I would like to take a stab at this.
Can I be assigned?

**Comment by kgodey** [comment]
Go ahead and submit a PR, @lakshya-dhariwal!

**Comment by shrey27tri01** [comment]
If no one is currently working on this issue, I would like to take this issue up :)

**Comment by kgodey** [comment]
Sure, go ahead @shrey27tri01

**Comment by Hatilar420** [comment]
Hey,
Can I work on this issue, If no one is currently working on it?

**Comment by seancolsen** [comment]
@shrey27tri01 are you still working on this? 

@Hatilar420 I would say that if we don't hear anything from @shrey27tri01 in 1 day from now, then you can start working on this.

**Comment by shrey27tri01** [comment]
Apologies for the silence. I wouldn't be able to work on this issue for now. @Hatilar420 you can take this up :)

**Comment by Hatilar420** [comment]
Thanks @shrey27tri01 :)
@seancolsen working on this issue .

**Comment by Hatilar420** [comment]
Hi @seancolsen @kgodey,
I've opened a PR for this issue. Can you please take a look and review it? Thanks! :)
