### ISSUE TITLE
Cell selection is stuck in drag mode after closing the record selector

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1917]
## Steps to reproduce

1. Navigate to the table page for a table with an FK column.
1. Double on a cell that opens record selector.
1. Choose an entry within the record selector using the mouse or keyboard.
1. Observe that the record selector closes and the cell value is modified. (Good.)
1. Move the mouse around without clicking.
1. Expect no changes to the cell selection.
1. Instead, observe that the selected cells are modified while moving the mouse as if you are dragging to select cells.

    https://user-images.githubusercontent.com/11850603/201178024-e4aecf05-5acf-4b19-a79a-0adced15f43a.mov

Originally [reported](https://github.com/centerofci/mathesar/pull/1856#pullrequestreview-1176277377) by @pavish

## Related

- #1892

**Comment by kgodey** [comment]
Moving this to the Backlog – this isn't critical enough to block launch.
