### ISSUE TITLE
Dropdown arrow for boolean cell is improperly positioned

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1919]
## Steps to reproduce

1. Navigate to the table for for a table containing a boolean column.
1. Configure the data type to display the value as a dropdown.
1. Select a boolean cell.
1. Observe a downwards facing chevron dropdown arrow.
1. Expect the dropdown arrow to be positioned at the right of the cell.
1. Observe the dropdown arrow is underneath the value.

![image](https://user-images.githubusercontent.com/42411/201194241-304b4bc7-051c-49cd-81e0-082cd561d2ee.png)

**Comment by steve-lgtm** [comment]
is this issue available?

**Comment by seancolsen** [comment]
Yes it is, @steve-lgtm. Feel free to submit a PR. Note that this ticket is somewhat high priority at the moment, so if we don't see a PR from you within the next week, then we may need to re-assign it. Thanks for your help!

**Comment by steve-lgtm** [comment]
@seancolsen I create pull request
