### ISSUE TITLE
Design for editing a record

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#192]
**Problem**

The user should be able to edit existing records in a table.

**Proposed solution**

We need a design to allow users to edit records.
- Edits will be instantaneous (there does not need to be a "save" button).
- The user should not be allowed to enter invalid data.
- There should be an indicator somewhere that shows the user that data has not been saved yet while the data is being synced with the backend.

**Comment by ghislaineguerin** [comment]
Specs posted at https://wiki.mathesar.org/design/process/documents/add-update-delete-records-specs
