### ISSUE TITLE
Show banner throughout application when "live demo mode" is turned on.

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1923]
We should show a banner at the top of the screen on all pages that explains that Mathesar is in live demo mode and that each session has its own copy of demo data and that data will be deleted regularly.

Assigning this to @mathemancer to make sure it gets implemented at some point, @ghislaineguerin for the design, and @pavish for the frontend.

**Comment by ghislaineguerin** [comment]
Link to design in figma: https://www.figma.com/file/xHb5oIqye3fnXtb2heRH34/Styling?node-id=3066%3A21916
