### ISSUE TITLE
API for nested record selector is returning an error

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1924]
## Steps to reproduce
1. Go to https://staging.mathesar.org/mathesar_dviiwc8o/692/tables/4845/
2. Click on the record selector dropdown for record ID 1
3. Click on the record selector dropdown for the author in the search row
4. Type "an"
5. Select author "Hannah Jensen"
6. Observe the record selector stuck on loading.

## Context
The app makes a `GET` request to `https://staging.mathesar.org/api/db/v0/tables/4843/records/?limit=10&offset=0&search_fuzzy=%5B%7B%22field%22%3A24624%2C%22literal%22%3A4%7D%5D`

The response is a `500` error with body:
```
[
  {
    "code": 4101,
    "message": "(psycopg2.errors.UndefinedColumn) column Publications.Publishers does not exist\nLINE 2: ...ations\".\"Publication Year\" AS \"Publication Year\", \"Library M...\n                                                             ^\nHINT:  Perhaps you meant to reference the column \"Publications.Publisher\".\n\n[SQL: WITH anon_4 AS \n(SELECT \"Library Management\".\"Publications\".id AS id, \"Library Management\".\"Publications\".\"Publisher\" AS \"Publisher\", \"Library Management\".\"Publications\".\"Author\" AS \"Author\", \"Library Management\".\"Publications\".\"Title\" AS \"Title\", \"Library Management\".\"Publications\".\"ISBN\" AS \"ISBN\", \"Library Management\".\"Publications\".\"Publication Year\" AS \"Publication Year\", \"Library Management\".\"Publications\".\"Publishers\" AS \"Publishers\", %(param_1)s + CASE WHEN (\"Library Management\".\"Publications\".\"Author\" = %(Author_1)s) THEN %(param_2)s ELSE %(param_3)s END AS __mathesar_relevance_score \nFROM \"Library Management\".\"Publications\"), \nanon_3 AS \n(SELECT anon_4.id AS id, anon_4.\"Publisher\" AS \"Publisher\", anon_4.\"Author\" AS \"Author\", anon_4.\"Title\" AS \"Title\", anon_4.\"ISBN\" AS \"ISBN\", anon_4.\"Publication Year\" AS \"Publication Year\", anon_4.\"Publishers\" AS \"Publishers\", anon_4.__mathesar_relevance_score AS __mathesar_relevance_score \nFROM anon_4 \nWHERE anon_4.__mathesar_relevance_score > %(mathesar_relevance_score_1)s ORDER BY anon_4.__mathesar_relevance_score DESC), \nanon_2 AS \n(SELECT anon_3.id AS id, anon_3.\"Publisher\" AS \"Publisher\", anon_3.\"Author\" AS \"Author\", anon_3.\"Title\" AS \"Title\", anon_3.\"ISBN\" AS \"ISBN\", anon_3.\"Publication Year\" AS \"Publication Year\", anon_3.\"Publishers\" AS \"Publishers\" \nFROM anon_3), \nanon_1 AS \n(SELECT count(%(count_1)s) AS _count \nFROM anon_2)\n SELECT anon_1._count \nFROM anon_1]\n[parameters: {'count_1': 1, 'param_1': 0, 'Author_1': 4, 'param_2': 4, 'param_3': 0, 'mathesar_relevance_score_1': 0}]\n(Background on this error at: http://sqlalche.me/e/14/f405)",
    "field": null,
    "detail": null
  }
]
```

**Comment by seancolsen** [comment]
Note: I was able to reproduce this on staging and I was _not_ able to reproduce this locally within the master branch.

**Comment by mathemancer** [comment]
@seancolsen @kgodey Were you able to reproduce this without going to that specific key? I had to filter available objects in APIs based on your session ID. In particular, @seancolsen I would _expect_ that you can't succeed at that URL, since you'd have a different session ID cookie.

**Comment by mathemancer** [comment]
Update: I've managed to reproduce on staging with my own sessionid cookie, and trying to access an appropriate table. I'll investigate from there.

**Comment by mathemancer** [comment]
After tinkering with this for a while on our new demo server, I think this is solved there. I'm assuming this was caused by some cruft left around in staging, so this issue can be closed.

Please reopen and ping me if this is happening at some point on the demo server.

**Comment by seancolsen** [comment]
@mathemancer 

> I would expect that you can't succeed at that URL, since you'd have a different session ID cookie.

Then, it it a problem that I can view the whole page at that URL? 

![image](https://user-images.githubusercontent.com/42411/201935991-30fda9ae-ec71-402c-81f6-4cd7b6bd6e74.png)

**Comment by mathemancer** [comment]
@seancolsen It's not a problem. The partitioning is specifically _not_ intended to be for security. The reason I'd expect there to be problems in some API calls to an inappropriate DB for your `sessionid` key is that I had to inject a `database` parameter and filter on it for a number of request types. However, for speed and efficiency, I didn't bother to enforce that filtering when getting a specific table, or specific database object in general. The only filtering is on listing calls.
