### ISSUE TITLE
Design for adding a new record to a table

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#193]
**Problem**

Users should be able to add a single new record to a table.

**Proposed solution**

We need a design for adding a new record to a table.
- Users should be able to enter new data in an empty row in the table interface (we won't be using a form interface yet).
- There does not need to be a "save" button, but the data cannot be saved until all required fields have valid data in them. There should be some indication showing the user that data has not been saved yet and what actions they need to take in order to save data. (e.g. "You need to fill out X and Y fields before the data can be saved.")
- Once data can be saved, there should be an indication to the user that data is being synced to the backend, which will go away when the sync is complete.
- Once a new record is added, the user should have the option to add another new record.

**Comment by ghislaineguerin** [comment]
Specs posted at https://wiki.mathesar.org/design/process/documents/add-update-delete-records-specs
