### ISSUE TITLE
Design for deleting a record

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#194]
**Problem**

The user should be able to delete a record from a table.

**Proposed solution**

We need a design for the user to delete a record from a table.
- There should be an indicator that lets the user know that the deletion is in process. It should go away once the backend has confirmed the record has been deleted.
- We should think about a confirmation step before deleting a record (at least, until we have undo functionality implemented).

**Comment by ghislaineguerin** [comment]
Specs posted at https://wiki.mathesar.org/design/process/documents/add-update-delete-records-specs
