### ISSUE TITLE
Don't allow public schema to be edited

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1954]
We currently allow editing the public schema's name and description from the schema page. We should disable this.

<img width="968" alt="Screen Shot 2022-11-18 at 12 03 58 PM" src="https://user-images.githubusercontent.com/287034/202761131-265da99a-6f76-4f02-b680-7a98851427b3.png">

**Comment by kgodey** [comment]
Marking this as both backend and frontend so we can make sure to disable this at an API level as well.

**Comment by ayao451** [comment]
@kgodey Can I tackle this issue!

**Comment by kgodey** [comment]
Sure, go ahead @ayao451!

**Comment by harikishantk** [comment]
I'm interested to work upon. May I?

**Comment by kgodey** [comment]
Sure, go ahead @harikishantk

**Comment by rajatvijay** [comment]
Hi @harikishantk. Since there has been no response here for the last 2 weeks. I am gonna take this up.

**Comment by dmos62** [comment]
Reopened to track backend progress.
