### ISSUE TITLE
Pick better columns to show within the list of table links

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#1960]
## Reproduce

1. Use the Library Management schema.

1. Open the Publication table page and look at the Links section within the table inspector.

    ![image](https://user-images.githubusercontent.com/42411/202919488-903b16d5-d91e-46ba-8f20-f5a04b6d298b.png)

1. Expect the column shown under "Authors" to be "Author", but observe it to be "id"
1. Expect the column shown under "Publishers" to be "Publisher", but observe it to be "id"

CC @rajatvijay

**Comment by pavish** [comment]
This is mentioned as a review comment on the PR: https://github.com/centerofci/mathesar/pull/1876#discussion_r1027396659, where incorrect logic is used to identify the linked columns.
