### ISSUE TITLE
On schema page, entire table card should be clickable

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1978]
Currently, only the "Go to Table" area takes you to the table. But the entire card should be clickable and take you to the table (except for the "..." button and the "Find Record" button.

**Comment by LFLATH** [comment]
@kgodey Hello! I was thinking of taking on this issue. I messed around with it a little bit and have the current behavior. The whole card is clickable and takes the user to the table and the other sections are still working as before. I was wondering if you wanted the card to also have an altered style on hover. Currently, when hovering over it you wouldn't know the card is clickable unless you clicked on it. Would it be good to transform the cursor or change the background of the whole card?

I have included an image of the current state of the code. My only addition is the <a> tag that calls the same function that the Go to Table area uses.
<img width="438" alt="Screenshot 2022-11-29 at 8 22 08 PM" src="https://user-images.githubusercontent.com/63031670/204684394-ca17b79d-671b-404f-ba7e-c906bd672ef5.png">
 Thanks for any advice.

**Comment by kgodey** [comment]
@LFLATH I do think it makes sense to transform the cursor and have a different background color. @ghislaineguerin, what should the background color for the main card body be?

**Comment by LFLATH** [comment]
I messed around a little bit in the styles and currently have it looking like this. There is that awkward white bar at the bottom which I don't think looks great.

<img width="520" alt="Screenshot 2022-11-30 at 1 51 57 PM" src="https://user-images.githubusercontent.com/63031670/204883691-ad00b815-56b9-4ed5-8bb7-ce254aeb4762.png">

When I applied the styles to the whole container it looks like this.
<img width="520" alt="Screenshot 2022-11-30 at 1 57 43 PM" src="https://user-images.githubusercontent.com/63031670/204884817-90278008-079b-4929-bc1f-a7990a57bc50.png">

But this runs into this problem where when hovering over Go to Table the whole card has a background change.
<img width="520" alt="Screenshot 2022-11-30 at 1 58 30 PM" src="https://user-images.githubusercontent.com/63031670/204884966-8efe3e1d-98d1-43b7-ac2e-cdeb9259bfc4.png">

**Comment by kgodey** [comment]
I'm pretty terrible at frontend stuff but @seancolsen or @rajatvijay should be able to help with applying the hover. I agree that we only want it to apply to the card area and not the buttons, and we don't want the white bar.

**Comment by LFLATH** [comment]
I have messed around with the styles a little bit and have reached the current look.
<img width="1116" alt="Screenshot 2022-11-30 at 3 31 51 PM" src="https://user-images.githubusercontent.com/63031670/204901948-2f0f77a5-c44f-451c-8045-fa3a8ca3ddaa.png">
I think this is similar to what is desired, but I am not sure. There is probably a way better way to do this though!

**Comment by seancolsen** [comment]
@LFLATH without seeing your CSS it's hard to offer much critique. Feel free to open a PR with your changes and we can continue the conversation there.

That said, here are a few thoughts about the approach we ought to take...

- The card needs to have a hyperlink covering its entire area.

- _Within_ the card, we need to have a couple buttons.

- That combination of requirements is tricky because placing a button inside a hyperlink is invalid HTML and can lead to UX and a11y problems.

- I'd suggest the following approach

    - The hyperlink should be absolutely positioned so that it covers the whole card. It should be empty, but have an aria-label set to the table name.

    - Hovering the hyperlink should set a javascript variable within the card like `linkIsHovered`. Then the card should set a CSS class like `link-is-hovered` at its root level in order to make styling choices such as the background color.

    - The buttons should be relatively positioned and have a z-index higher than that of the hyperlink so that the user can click them. Make sure to follow our [code standards](https://github.com/centerofci/mathesar-wiki/blob/master/engineering/standards/frontend.md#component-spacing-and-layout) for z-index.

    - Note that with this approach, the "Go to Table" part is just plain text. Design-wise, I'm not sure we need it anymore, but we can remove it later if our design team chooses.

**Comment by LFLATH** [comment]
@seancolsen  I am super sorry for not considering that! I am still getting used to working with other people. I made a PR for my current approach, but when I get a second I will implement what you have mentioned. Sorry about this again!

**Comment by kgodey** [comment]
@seancolsen I assigned you this issue since you're reviewing the associated PR.
