### ISSUE TITLE
Creating a Table with round brackets results in API error

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar#1979]
## Description
Creating a Table whose name contains round brackets, for example, a Table with the name "Cycle 6 (Release)" and then creating a foreign key referencing the Table causes most of the APIs to return an error. This happens due to a bug SQLAlchemy foreign key parsing regex.  

## Expected behavior
Since the bug is due to SQLAlchemy, it is not feasible to fix it. So we should prevent creating a Table whose name contains round brackets by validating the Table name on the backend.

## To Reproduce
1. Create a Table whose name contains round brackets, for example, a Table with the name "Cycle 6 (Release)"
2. Create a foreign key in a different that references any column of the Table created in Step (1).
3. Try refreshing the Tables page or send a request to `/tables/` API, the backend with throw an error

**Comment by kgodey** [comment]
I moved this to the first release milestone because this is a pretty severe bug, it ends up making the entire schema unusable.

It might also be worth creating an upstream issue for SQLAlchemy.

**Comment by Anish9901** [comment]
I'd like to take this one. I have already figured out how to implement the solution proposed by @silentninja.
