### ISSUE TITLE
Users & Permissions design

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#1985]
# New pages

## New Admin section
We need a new section of Mathesar that's only accessible to administrators. For the purposes of this issue, we'll only be designing the "Users" sub-section but we'll be adding other sections as part of our installation and deployment work.

- [x] Main admin panel page
- [x] Users sub section
    - [x] See list of users
    - [x] See list of permissions for each user
    - [x] Add new user
      - [x] Handle errors when user cannot be created
    - [x] Delete user
      - [x] Handle errors when user cannot be deleted 
    - [x] Edit user details
      - [x] Handle errors when editing fails 
    - [x] Display permissions for a given user
    - [x] Reset user's password
      - [x] Handle errors when operation fails

## New User Settings page
We'll need a user settings page for the user to edit their own settings. Right now, that will only include a "Account" sub-section but we'll include more sections in the future for the user to configure their personal settings.

- [x] Main user settings page
- [x] Account sub-section
    - [x] See their details
    - [x] Edit their own details
      - [x] Handle errors when editing fails 
    - [x] Change their password
      - [x] Handle errors when operation fails
    - [x] Delete their account
      - [x] Handle errors when operation fails

## Styling for log in page
- [x] Show log in form
- [x] Styling for errors

## Change password page
This page will show up when an admin has reset the user's password and the user is logging in using the new password. The user will need to change their password before being allowed into the application.
- [x] Explain the page
- [x] Show form for changing the password
- [x] Styling for errors
- [x] Handle the case where someone opens the URL directly – should show an error message that tells the user how to change their password the normal way.

## Post log out page
Once users log out successfully, they should be directed to a page with a message that says "You've successfully logged out" or something like that.

- [x] Design the page 

# Changes to existing designs

## Navigation changes
The navigation should be updated to include the following
- [x] Link to the admin section (only visible to admins)
- [x] User settings page (visible to all users)
- [x] Log out action

## Database page changes
We need to have different actions / options available depending on the user's permissions:

- [x] Users with Manager permissions
  - [x] Show the list of people with access to the database
  - [x] Allow adding users to the DB
    - [x] Handle errors
  - [x] Allow removing users who have access to the DB
    - [x] Handle errors
- [x] Users with Editor & Viewer permissions
  - [x] Disable creating / deleting / editing schemas

## Schema page changes
We need to have different actions / options available depending on the user's permissions:

- [x] Users with Manager permissions
  - [x] Show the list of people with access to the database
  - [x] Allow adding users to the schema
    - [x] Handle errors
  - [x] Allow removing users who have access to the schema
    - [x] Handle errors
- [x] Users with Editor & Viewer permissions
  - [x] Disable creating / deleting / editing the schema
  - [x] Disable creating / deleting / editing any tables
- [x] Users with Viewer permisions
  - [x] Disable creating / deleting / editing explorations

## Table page changes
We need to have different actions / options available depending on the user's permissions:

- [x] Users with Editor or Viewer permissions
  - [x] Disable editing table name and description
  - [x] Disable adding / deleting constraints 
    - [x] Constraints modal
    - [x] Table Inspector (checkboxes)
  - [x] Disable creating new columns
  - [x] Disable editing column name
  - [x] Disable changing data type
  - [x] Disable setting default value
  - [x] Disable creating table links
  - [x] Disable moving & extracting columns
- [x] Users with Viewer permissions
  - [x] Disable editing records
  - [x] Disable adding records
  - [x] Disable deleting records
  - [x] Disable editing record summary
  - [x] Disable editing column display options

## Record page changes
- [x] Users with Viewer permissions
  - [x] Disable editing records
  - [x] Disable adding records
  - [x] Disable deleting records

## Data Explorer changes
- [x] Users with Viewer permissions
  - [x] Disable saving explorations

## Exploration Editor changes
- [x] Users with Viewer permissions
  - [x] Disable saving changes to explorations

## Exploration Page changes
- [x] Users with Viewer permissions
  - [x] Disable editing name / description of explorations

# Additional context
[Users & Permissions](https://wiki.mathesar.org/en/product/specs/users-permissions) product spec.

**Comment by silentninja** [comment]
@kgodey I have a few questions

- What does `For everyone` mean? For example in the case of database permission, can some user not having any role related to the database see the list of people with access to the database?

- > - Users with Viewer permission - Disable creating / deleting / editing explorations
    
    The [Permissions Spec](https://wiki.mathesar.org/en/product/specs/users-permissions#schema-permissions) shows only the Schema Manager can create/delete an exploration which seems to be conflicting with the rule here, so which one is correct?

**Comment by kgodey** [comment]
Also thanks for catching these, @silentninja.
