### ISSUE TITLE
Table creation from data file should infer data types automatically

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#200]
**Problem**

Currently, we create an all-string table when we create a table from a data file. In order to support our [design for file import](https://wiki.mathesar.org/design/process/documents/table-import-specs), we'll need to show the user the types we recommend for each column.

**Proposed solution**

We should have an API that provides inferred data types for each column in a table. We don't actually want to change the table yet, just infer data types for each column.

**Additional context**

See #92 for DB functions to be used for this.

Related to #199, although I don't think it's actually blocked by it.

**Comment by mathemancer** [comment]
@kgodey Recall that the implementation for type inference of a column changes the type of the column to the inferred type.  If we want to change that, we'll need to ticket and implement that change.

**Comment by kgodey** [comment]
@mathemancer I misremembered, I thought that we had separate functions to determine the type of a column and actually alter the type. 

I think it would make the most sense to not alter the data immediately since that might change how the data is rendered and confuse the user. I'm also concerned about situations where the user cycles through a few different types and each new type casting alters the data based on the previous altered state of the data rather than on their original file.

**Comment by mathemancer** [comment]
I see your point, and I think it makes some sense.  I'm not at all opposed to changing that behavior.  The cost will be slower type inference, but the benefit will be more safety.  Basically, we'll be losing any parallelization and short-circuiting we're getting for "free" from the query planner with the current method.  We might also come back to this after we have "undo" functionality (or at least until we've thought about and specced it for DDL operations).  The reason for that is that if we have robust enough undo, "check if this works without altering" and "alter, then alter back if we don't like the results" should be indistinguishable in outcome (and could also be made indistinguishable for users).  This would alleviate the safety concerns with "testing via altering"

**Comment by kgodey** [comment]
@mathemancer I agree on revisiting once we have undo specced out.

Re: ticketing, I think it's fine to work on changing that behavior as part of this ticket.

**Comment by eito-fis** [comment]
Did we have a set endpoint in mind for this? I was imagining returning type data alongside the response for table POST requests, but would guess there are a couple ways of doing this.

**Comment by kgodey** [comment]
We should have a separate endpoint for this, along the lines of `v0/tables/<id>/type_suggestions/`. The user might not be ready to review imported data right away after the table is created, and the UI should have a way of getting type suggestions for a table on demand.
