### ISSUE TITLE
Make list of things that aren't reflectable and we want to backup

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#2001]
We don't have a simple way to know which parts of Mathesar service state are not reflectable from a user database (e.g. queries or column display options). We want to have a comprehensive list, because those are the things we'll be backing up.

Related feature/issue: #1815

**Comment by dmos62** [comment]
@silentninja do we need to backup anything that can't be reflected in relation to users and permissions?

**Comment by kgodey** [comment]
Quick note that @mathemancer might have done some work related to this while making Explorations and display options part of the dataset for the live demo.

**Comment by silentninja** [comment]
> do we need to backup anything that can't be reflected in relation to users and permissions?

All the Models in the [users module](https://github.com/centerofci/mathesar/blob/23595de7864098468ebe2d1501f89182aa45adc9/mathesar/models/users.py) can't be reflected

**Comment by mathemancer** [comment]
To me, the easiest way to know that is to access the Django tables directly. Things that are stored there can't be reflected from the user DB. That said, everything is indexed by OIDs, which will change on the user DB in a backup/restore cycle.

**Comment by dmos62** [comment]
I initially approached the metadata backup/restore problem as a question of backing up a small number of models and restoring them later. I now think that to backup all interesting metadata, we'd need a more general mechanism, and for that we don't really need a "metadata backup whitelist", which was the goal of this issue.

The amount of metadata we have and its complexity is quickly growing (`users` module is an example). So we probably don't want backup/routine routines tailored to specific pieces of metadata.
