### ISSUE TITLE
Investigate putting JSON inside an SQL dump

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#2002]
Related issue: #1815

When making backups, we need to store an SQL dump (probably from `pg_dump`) and some JSON describing non-reflectable Mathesar state, like queries and display options. It would not be ideal to keep these two pieces of data in two separate files. Another non-ideal solution is to archive the two files.

This issue is about investigating putting that JSON inside the SQL dump, in a way that does not affect the behaviour of the SQL dump when restoring it, but so that we can recover our JSON from it. That would give us portability and possibly simplicity and performance advantages over `tar`/`zip` archiving.

**Comment by dmos62** [comment]
Seems trivial, but only when using the default, but less popular, plain text `pg_dump` format (not the popular binary file format you'd get by doing `pg_dump -Fc`).

We'd prepend a block of JSON to the SQL dump, and the JSON block would be in a multi-line SQL comment; note the strings marking start and end of our JSON:

```
/* START OF MATHESAR METADATA JSON
[...]
*/ END OF MATHESAR METADATA JSON
```

During user database restoration we would pipe the plain text sql dump into `psql` and the JSON would not have an effect. When preparing to restore Mathesar metadata, we'd find our JSON block by looking for lines delimited by `/* START OF MATHESAR METADATA JSON` and `*/ END OF MATHESAR METADATA JSON`, and parse that into Mathesar state.

**Comment by mathemancer** [comment]
A quick experiment shows that you can append lines to the custom format dump file without creating a problem. I wasn't able to figure out how postgres knows the file is over, though. A look in hexl didn't show any particular character (or bytes) ending the dump section, so I'm not sure how robust that would be.

My instinct, given our needs, would be to dump to SQL, and use the comment idea you suggested. We could also consider figuring out how to 
- create a "django backup" schema in the user DB,
- dump that along with their data

**Comment by dmos62** [comment]
Thanks for input @mathemancer! I considered inserting into the binary custom dump format, but I also concluded that that's not robust enough. A "django backup" schema might be interesting to explore if the SQL dump format proves insufficient.
