### ISSUE TITLE
Record summaries of `NULL` values should not show "null" text.

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2004]
## Reproducing
1. See Author in https://staging.mathesar.org/mathesar_tables/318/tables/19749/17. The record summary is configured to be `{first name} {last name}` and this author (who has no first name) is showing up as `null Abu'l-Fazl`
1. Also see Language in https://staging.mathesar.org/mathesar_tables/318/tables/19749/1, which is showing up as "null"

## What I'd expect
1. The record summary should be ` Abu'l-Fazl`
2. The record summary should be an actual `NULL` value

**Comment by kgodey** [comment]
Not sure if this is a backend or frontend issue so assigning both to @silentninja and @seancolsen.

**Comment by kgodey** [comment]
Also this is the data set we're going to be using for the demo video, so this is high priority.

**Comment by seancolsen** [comment]
This issue is limited to the front end. Unfortunately, meeting your expected behavior would require some significant re-architecting, as we have been operating under the assumption that record summaries are always strings. I don't think we should pursue this until after the release, and we should adjust our demo data as needed to avoid hitting this.

**Comment by kgodey** [comment]
Okay, I didn't realize it would be a lot of work. We can adjust our demo data to unblock the video.

People will still hit this in the live demo, having `NULL` records is pretty common, in fact it's the default for all new fields. We should fix this before publicizing the demo widely.

I've created a new [public launch milestone](https://github.com/centerofci/mathesar/milestone/61) for these kinds of issues.

**Comment by seancolsen** [comment]
@kgodey I spent some time pondering this while laying in bed sick yesterday, and I came up with a shorter (albeit somewhat hacky) path towards implementing the behavior that I _think_ you're after. Please take a look at #2017 to see if it's what you have in-mind.
