### ISSUE TITLE
Delete icon for new records

### ISSUE THREAD

**Issue by rajatvijay** [centerofci/mathesar#2012]
Figma: 
<img width="301" alt="Screenshot 2023-01-20 at 6 56 36 PM" src="https://user-images.githubusercontent.com/11032856/213705651-2399951c-5175-4d19-ac4f-8b5db5e4e223.png">

**Comment by rajatvijay** [comment]
@kgodey I was working on this and had this concern:

Since the records are being saved in real-time and once the record is saved there is already a context menu with the delete record option. Even these new records before being re-positioned can be selected and deleted from the table inspector. 

Do we really need a delete icon here? 

cc: @seancolsen @ghislaineguerin

**Comment by seancolsen** [comment]
I would prefer that we _not_ add this delete icon, keeping the row header as-is.

**Comment by kgodey** [comment]
This was a solution to a problem that came up during usability testing – it's extremely easy to add new rows / records accidentally, and it breaks the flow of data entry to have to go delete them in the table inspector. No one has provided any reasoning for why we _shouldn't_ do this.

That being said, this is not a launch blocker, so if there are higher priority issues available, we can move this to a later milestone or pause it until we do further usability testing.

**Comment by seancolsen** [comment]
> it's extremely easy to add new rows / records accidentally

This seems like the more fundamental design problem to tackle. I agree we need more design work here.

**Comment by pavish** [comment]
>  it's extremely easy to add new rows / records accidentally, and it breaks the flow of data entry to have to go delete them in the table inspector. 

We also have the right-click context menu to delete rows.

> No one has provided any reasoning for why we shouldn't do this.

I personally think the UX needs to be consistent for all rows. What if the user wants to select a row that they newly created? A delete icon in the row header prevents them from being able to click/select there.

**Comment by ghislaineguerin** [comment]
I agree with consistency being more important and I'm ok with removing the delete button since we now can select and remove via inspector or contextual menu.

**Comment by kgodey** [comment]
I forgot about the context menu. I'll close this.
