### ISSUE TITLE
Reset migrations

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#202]
A reminder for us to reset migrations before the first release.

- [x] Reset migrations in the repo
- [x] Send email to developer mailing list with local instructions
- [x] Reset migrations on all servers tracked in Ansible
  - [x] `staging.mathesar.org` probably needs a reboot 
  - [x] `library.mathesar.org` can be removed entirely, since we're not using it

**Comment by mathemancer** [comment]
@kgodey I've removed `library.mathesar.org` from the ansible playbooks in [this PR](https://github.com/centerofci/mathesar-ansible/pull/35) , but I figure I'll use it for testing the hosted prod setup since it already has a domain, etc. set up.
