### ISSUE TITLE
Improve responsiveness of long table names within the Table Page actions pane

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2020]
## Current behavior

Long table names are truncated even when there is enough space to display the name -- and the truncate is done with with no ellipsis

![image](https://user-images.githubusercontent.com/42411/205687233-4d636676-0d63-489a-904b-8a566338848a.png)

## Desired behavior

- The table name is only truncated when there is not enough space in the actions pane to display the whole name
- An ellipsis is used to indicate that the name has been truncated.

**Comment by SumeetHaryani** [comment]
Hey @seancolsen, I would like to work on this issue

**Comment by kgodey** [comment]
Go ahead @SumeetHaryani

**Comment by seancolsen** [comment]
@SumeetHaryani this issue is actually already fixed.

![image](https://user-images.githubusercontent.com/42411/213921028-c5de49dc-e2bb-4ebb-974d-5e5ff099d2bd.png)

Sorry I failed to close it earlier.

**Comment by SumeetHaryani** [comment]
Alright, @seancolsen 
Any other frontend-related issues you would like to suggest? where I might be able to help :)
