### ISSUE TITLE
Use ModificationStatus component within the Table Page.

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2021]
Use the ModificationStatus component to render the status UI within the actions pane on the Table Page.

**Comment by pavish** [comment]
@kgodey I think this might be required for the demo video.

This component shows the styled statuses  i.e 'Unsaved changes', 'All changes saved' etc., The record page and the exploration editor both use this component, however the table page displays text which is improperly aligned.

In table page:
![Screenshot 2022-12-20 at 1 12 35 AM](https://user-images.githubusercontent.com/11850603/208507114-71a7909c-095c-4b34-a08d-704e50f422e0.png)

In record page & exploration editor:
![Screenshot 2022-12-20 at 1 13 21 AM](https://user-images.githubusercontent.com/11850603/208507143-05257c8f-03ff-49bc-a551-fd20b67117ea.png)
![Screenshot 2022-12-20 at 1 12 20 AM](https://user-images.githubusercontent.com/11850603/208507164-3bee2f31-fcf7-4b0f-8e70-405f0ce91b2e.png)

I assume this will be visible during the demo, and we should add this to https://github.com/centerofci/mathesar/issues/2079. What do you think?

**Comment by kgodey** [comment]
@pavish agreed, added

**Comment by pavish** [comment]
I'm going to pick this up, as I recently modified this component.
