### ISSUE TITLE
Add background colors to table icons

### ISSUE THREAD

**Issue by rajatvijay** [centerofci/mathesar#2025]
![Screen Shot 2022-12-05 at 1 50 42 AM](https://user-images.githubusercontent.com/287034/205568385-181f6c38-4983-4717-8489-54bba846b741.png)
<img width="399" alt="Screenshot 2022-12-06 at 7 53 52 PM" src="https://user-images.githubusercontent.com/11032856/205937510-d7298211-ccf0-4219-8268-38710274d09b.png">

**Comment by kgodey** [comment]
@rajatvijay Please update the one for the table page header now, we already have a colored header for the Exploration Page ([see here](https://staging.mathesar.org/mathesar_tables/3/explorations/9/)). Different colors for different tables is a more complicated issue and we can handle that later.

**Comment by kgodey** [comment]
I'm going to close this. The table page header icon now has a color, and per-table colors are tracked in https://github.com/centerofci/mathesar/issues/1668
