### ISSUE TITLE
We need an "is not empty" filter

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2026]
## Problem

We have an "is empty" filter for all data types, but there's no way to filter on "is not empty".

## Proposed solution

We should have a new "is not empty" filter.

**Comment by seancolsen** [comment]
Should we instead have a "not" modifier that can be applied to all filters?

**Comment by kgodey** [comment]
I do think that's a better solution in the long run. 

It wouldn't currently work for the Data Explorer because we don't have modifiers for filters (and that's what I need it for). I think implementing modifiers for queries would take a lot longer than just adding an "is not empty" filter, but @pavish and @dmos62 would know better.

**Comment by dmos62** [comment]
@seancolsen filtering API is a subset of the function API; while filtering doesn't support modifiers (like Kriti pointed out), the functions API does. So far we've been solving these kinds of problems by creating a filter for each variation a user might want. If or when we decide that we need a more powerful filtering/transformation UI, backend is already in an ok position to support that.

**Comment by pavish** [comment]
> Should we instead have a "not" modifier that can be applied to all filters?

It is not a technical issue, rather a design problem which needs to be solved. Our design does not take modifiers or multiple and/or nesting into account.

At the moment, for this issue, I'd like to only add the 'is not empty' filter to existing filters list.
