### ISSUE TITLE
Show edit exploration breadcrumb as a child of saved exploration item instead of the direct child of the schema

### ISSUE THREAD

**Issue by rajatvijay** [centerofci/mathesar#2029]
## Current

**Saved Exploration**
<img width="890" alt="Screenshot 2022-12-07 at 3 41 55 AM" src="https://user-images.githubusercontent.com/11032856/206034579-1f96f693-b717-4fb6-9085-13c0f4c40102.png">

**Editing Saved Exploration**
<img width="690" alt="Screenshot 2022-12-07 at 3 42 00 AM" src="https://user-images.githubusercontent.com/11032856/206034589-2571339f-740b-42ad-b7b7-92d6d3ad7e77.png">

## Expected

**Saved Exploration**
<img width="696" alt="Screenshot 2022-12-07 at 3 44 10 AM" src="https://user-images.githubusercontent.com/11032856/206034934-38e711e2-637a-4eba-902f-0a26c1d9cefe.png">

**Editing Saved Exploration**
<img width="869" alt="Screenshot 2022-12-07 at 3 44 03 AM" src="https://user-images.githubusercontent.com/11032856/206034974-2490feb4-5869-4051-aa32-e6ca36c0ecca.png">

Blocked on: https://github.com/centerofci/mathesar/issues/2030

**Comment by kgodey** [comment]
Moving to backlog; doesn't block launch.

**Comment by pavish** [comment]
This seems to be fixed already.
