### ISSUE TITLE
API to upload file from URL

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#203]
**Problem**

We should allow users to upload data files by specifying a URL where they are hosted.

**Proposed solution**

This API should download the data file from the remote URL and save it as a data file. It can then be processed as any other data file.

**Additional context**

See [Add table from file import spec](https://wiki.mathesar.org/design/process/documents/table-import-specs).

**Comment by eito-fis** [comment]
Before I start on this, is anyone familiar with possible security risks posed by this kind of operation? Downloading random files off the web does make me a little nervous. Although, I guess it isn't too different from just uploading a file manually and given the self-hosted context, maybe we don't have to worry much?

**Comment by kgodey** [comment]
I can't think of any security risks inherent to downloading the file from a URL, it's just a convenience so that the user doesn't have to download the file onto their computer and upload it manually.

We should treat all incoming files with the same suspicion, whether from a URL or uploaded manually. I'll create an issue to do an evaluation of security issues with uploaded files in the future.
