### ISSUE TITLE
Table not found error

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2038]
## Steps to reproduce

1. Navigate to http://localhost:8000/mathesar_tables/
1. Click on "Library Management" to open schema with id `217` (or similar)
1. On the "Authors" table card, hover the "Go to Table" hyperlink. Observe that it uses schema `217` (or equivalent) in the URL. Good.
1. In the navigation header, open the "Choose a Schema" dropdown, and click on "public", navigating to http://localhost:8000/mathesar_tables/1/
1. Observe that table cards now use schema id `1` in their URLs. Good.
1. Use the same schema switcher to navigate back to "Library Management".
1. Hover the "Go to Table" hyperlinks for various tables.
1. Expect these URLs to use schema `217` (or equivalent).
1. Instead observe the table URLs to use schema `1`. Bad.
1. Clicking on one of these URLs rightly displays an error message like:

    > Table with id 1267 not found.

**Comment by rajatvijay** [comment]
@seancolsen this issue is not reproducible anymore. Here is the loom for this: https://www.loom.com/share/9349e37089aa4d649b7ebb7532beafd8

Closing this, for now, will re-open if reported again.

**Comment by seancolsen** [comment]
Looks good. I am also no longer able to reproduce.
