### ISSUE TITLE
Document Mathesar configuration variables

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar#2039]
## Problem
We need to have a hassle-free process to help the user set up the credentials and other configuration data necessary to run Mathesar. The credentials we need to run Mathesar are
- SECRET_KEY
- Database credentials to store Mathesar related Metadata like display_options
- STATIC_ROOT
- MEDIA_ROOT
- Database credentials to connect to the User Database

## Proposed solution
We already have `.env` file to store the config data. We would need a wiki document or a README instruction explaining the config fields and the values that should go into it.

**Comment by kgodey** [comment]
> We would need a wiki document or a README instruction explaining the config fields and the values that should go into it.

@mathemancer and I discussed documentation – we'll be setting up a separate documentation site using something like MkDocs at `docs.mathesar.org`
