### ISSUE TITLE
API to fetch the latest version from the GitHub Releases API and return it to the frontend

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar#2045]
We need a Mathesar version API 
- To fetch the latest version using the Github release API and return it to the frontend
- To return the current version of Mathesar

**Comment by dmos62** [comment]
The [design spec](https://groups.google.com/a/mathesar.org/g/core-team/c/-vRhHAgaTeU/m/gv75Wg8KAgAJ) ended up needing following information:

- for both the installed release and the latest release:
  - tag name,
  - link to release notes,
  - release date.
