### ISSUE TITLE
Automatic import of tables when new database is connected.

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#205]
**Problem**

When a user sets up an existing database in Mathesar, they'll expect to see their tables. We don't currently do anything to sync existing databases with Mathesar.

**Proposed solution**

We should create instances of the appropriate Django models for tables in existing databases.

**Additional context**

Blocked by #61

**Comment by kgodey** [comment]
This might already be handled by #61, if it is, we need to verify that it works.

**Comment by mathemancer** [comment]
Currently, if an existing DB is added to the `DATABASES` constant in the settings, the schemata and tables from the DB should be returned in the API once the cache expires.  The tricky parts I can think of will be:
- the custom functions and types associated with Mathesar won't be installed on the DB without the user running the `install.py` script.
- I think the way we're configuring the `mathesar_tables` database with an environment variable means the user will have to add a new environment variable and read it in to have more than one DB for their tables at a time.

**Comment by eito-fis** [comment]
Just to clarify, is it correct to say that the goal here is to test automatic import from multiple databases? It seems like the db reflection PR already handles and tests most of the automatic import capability, and its more tests with multiple databases that we're missing.

**Comment by kgodey** [comment]
Yes, I think additional tests would be great. This issue was written before the DB syncing was completed and I hadn't realized it would be handled already.
