### ISSUE TITLE
Show field-specific errors when a CHECK constraint fails on POST/PATCH records

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2053]
## Steps to reproduce

1. Set up a table with an email column that has a unique constraint and contains a couple records with values for the column.

1. PATCH one of the records (e.g. at `/api/db/v0/tables/1270/records/5/`), attempting to set its email value to be a duplicate. You can do this via the front end on the record page.

1. Observe a response like the following

    ```json5
    [
      {
        "code": 4208,
        "message": "The requested update violates a uniqueness constraint",
        "field": null,
        "detail": {
          "constraint": 2316,
          "constraint_columns": [5264],
          "original_details": "Key (\"Email\")=(foo@bar.org) already exists."
        },
        "stacktrace": [
          // omitted for brevity
        ]
      }
    ]
    ```

    This is **good** because the front end is able to display an error message _on the specific field causing the problem_.

1. PATCH the same record, this time attempting to se the email value to a value like "nope" that is not a valid email address.

1. Expect to see an error response structured like the one above, with a `detail` property that the front end can _somehow_ use to determine the relevant field causing the error.

1. Instead, observe an error response like the following

    ```json5
    [
      {
        "code": 4999,
        "message": "(psycopg2.errors.CheckViolation) value for domain mathesar_types.email violates check constraint \"email_check\"\n\n[SQL: UPDATE \"Library Management\".\"Patrons\" SET id=%(id)s, \"First Name\"=%(First Name)s, \"Last Name\"=%(Last Name)s, \"Email\"=%(Email)s WHERE \"Library Management\".\"Patrons\".id = %(id_1)s]\n[parameters: {'id': 5, 'First Name': 'Laura', 'Last Name': 'Sotos', 'Email': 'this is not an email address', 'id_1': '5'}]\n(Background on this error at: http://sqlalche.me/e/14/gkpj)",
        "field": null,
        "detail": null,
        "stacktrace": [
          // omitted for brevity
        ]
      }
    ]
    ```

    This leads to poor UX on the record page as show in this unwieldy error message:

    ![image](https://user-images.githubusercontent.com/42411/206338913-37052639-9980-434c-8026-be97c270f2c3.png)

**Comment by ayao451** [comment]
May I work on this issue? @bonnieguo7 @csavoy2 @elainewangg

**Comment by kgodey** [comment]
Sure, go ahead

**Comment by ayao451** [comment]
@kgodey Hi Kriti! I was doing some snooping for the past day, but I was unsure where the actual error message is generated! I tracked the failed requests to this path:

sendXHRRequest | @ | requestUtils.ts:103
-- | -- | --
  | patchAPI | @ | requestUtils.ts:153
  | patch | @ | RecordStore.ts:78
  | func | @ | RecordPageContent.svelte? [sm]:70
  | proceed | @ | FormSubmitWithCatch.svelte? [sm]:26
  | proceed | @ | SpinnerButton.svelte? [sm]:26
  | (anonymous) | @ | index.mjs:1004
  | bubble | @ | index.mjs:1004
  | click_handler | @ | Button.svelte? [sm]:27


But every error I sent went to that path, so I was wondering where the actual error is generated. I tried running grep on the specific error, but it seems like the error message just outputs its payload, though I am unsure where.

Thank you so much!!!

**Comment by Aditramesh** [comment]
@kgodey can i work on this?

**Comment by kgodey** [comment]
I think this was fixed by #2098. @Anish9901 can you confirm?

**Comment by Anish9901** [comment]
Yes this issue is fixed, but we haven't yet figured out a way to determine which columns are actually causing the error.

**Comment by kgodey** [comment]
That's fine, we can close this for now and open a new issue if that comes up in the future.
