### ISSUE TITLE
Add onboarding message to record page

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2054]
[Figma](https://www.figma.com/file/xHb5oIqye3fnXtb2heRH34/Styling?node-id=1714%3A12860&t=gZs7XiS5EijsS0Pg-0)

![image](https://user-images.githubusercontent.com/42411/210445124-1d9ec564-c85d-4edd-8f48-042f98c22596.png)

**Comment by seancolsen** [comment]
@kgodey @ghislaineguerin  can we close this without implementing? Personally I feel that this message is so trivial that it adds no value to the page and only takes up space.

**Comment by kgodey** [comment]
@seancolsen okay, that's fine. My reasoning for this message was to be a tutorial for people encountering this page for the first time. But we can see if people get confused during usability testing and figure out how to mitigate it if that happens.
