### ISSUE TITLE
Fix dark text on dark background for NULL value in record summary within navigation header

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2055]
## Steps to reproduce

1. Configure a record to produce a record summary which contains a `NULL` value.
1. Navigate to the Record Page for that record.
1. In the site header, observe dark text on dark background that is difficult to read

    ![image](https://user-images.githubusercontent.com/42411/206465773-290df103-54cc-4df0-bc58-60f6234d6ad7.png)

## Considerations

Fixing this cleanly may require some careful thought about how we're setting text colors. Ideally we'd apply a fix at a high level which preserves our ability to easily compose components without needing to think about text color everywhere. I'd like to have a way of saying "within the entire site header, invert all the colors". We'll need to do something like this for dark mode eventually, so I think it's worth considering what strategy we'll employ for that. We'll probably want to make use of CSS variables somehow, but I haven't thought through it all yet.

**Comment by kgodey** [comment]
Moving this to the Backlog – this isn't critical enough to block launch.

**Comment by seancolsen** [comment]
This was actually fixed in #2257
