### ISSUE TITLE
Duplicate schema creation

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#206]
**Describe the bug**
We are currently able to create a new schema with an existing schema name, creating duplicates on our mathesar_schema table.

**Expected behavior**
* Schema name should be unique per db in mathesar_schema table.
* If a new schema creation is attempted with the same name as an existing schema, a 400 should be thrown with proper error message.

**Comment by kgodey** [comment]
This can be implemented by making the schema name unique in the Django DB model.
