### ISSUE TITLE
Add support for self-referential links within Link Table modal

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2084]
Description and discussion pending

**Comment by seancolsen** [comment]
@kgodey can we bump this to "2023 or Later"? I think users are very unlikely to need this, so it seems low-priority to me compared to other features.

**Comment by kgodey** [comment]
@seancolsen I disagree about users being unlikely to need this, I've built more than one DB schema in the past that used self-referential links and it would be a red flag for me if a product I was evaluating didn't support them. We should have this for the release.
