### ISSUE TITLE
Change modal background to gray

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2085]

**Comment by pavish** [comment]
@seancolsen 
I assume this change is required across all modals in the product (based on the figma designs). This ticket is not limited to the link table modal. Is that correct?

**Comment by seancolsen** [comment]
@pavish you're correct. @kgodey [stated](https://github.com/centerofci/mathesar/pull/2080#issuecomment-1350319323) that she and @ghislaineguerin would like _all_ modals changed to use the gray background to match Figma. We'll need to do a bit of testing to make sure that all our modals work well with the gray background.
