### ISSUE TITLE
NULL-valued array cell should not display NULL inside a pill

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2094]
Here I'm showing Items records along with their checkout times.

![image](https://user-images.githubusercontent.com/42411/207722597-c4f84930-cb8c-4578-827c-7d07d76f6aef.png)

Because Items record `2` has no Checkouts records, I would expect to see `NULL` in the selected cell _without_ the `NULL` text inside a pill. Putting the `NULL` text inside a pill makes it appear as though Items record `2` has one related Checkouts record which has a `NULL`-valued checkout time.

**Comment by pavish** [comment]
@dmos62 This change is required from the backend. So, I'm assigning this issue to you.

**Comment by dmos62** [comment]
I'm not sure what alternative can we offer. We could remove `NULL`s from the results of `array_agg`, but then what if the user cares about `NULL`s? Maybe I'm missing some obvious solution (input @mathemancer?).

I hope this doesn't turn into a too-sophisticated-too-early feature.

**Comment by seancolsen** [comment]
@dmos62 

> we can't differentiate between a NULL that means that there are no checkouts for this item and a NULL that means that there is a checkout, but its date is NULL.

Ahh, ok this is interesting. Since my experience with Postgres is somewhat limited, I'm still learning about he array type. I just played around with the SQL a bit.

- I have data that looks like this

    ```sql
    select 
      i.id as "Item id",
      c.id as "Checkout id",
      c."Checkout Time"
    from "Items" i
    left join "Checkouts" c on c."Item" = i.id
    where i.id <= 4
    order by i.id;
    ```

    |  Item id | Checkout id |       Checkout Time         |
    | -------- | ----------- | --------------------------- |
    |        1 |          37 | 2022-05-30 11:55:28.596846  |
    |        1 |         172 | 2022-09-26 13:06:16.249656  |
    |        2 |      `NULL` | `NULL`                      |
    |        3 |          35 | `NULL`                      |
    |        4 |          64 | 2022-06-23 10:16:01.683293  |
    |        4 |         122 | `NULL`                      |

- My naive approach to aggregating that data went like this... 

    ```sql
    select 
      i.id as "Item id",
      array_agg(c."Checkout Time") as "Checkouts"
    from "Items" i
    left join "Checkouts" c on c."Item" = i.id
    where i.id <= 4
    group by i.id
    order by i.id;
    ```

    |  Item id |                          Checkouts                           |
    | -------- | ------------------------------------------------------------ |
    |        1 | {"2022-05-30 11:55:28.596846","2022-09-26 13:06:16.249656"}  |
    |        2 | {`NULL`}                                                       |
    |        3 | {`NULL`}                                                       |
    |        4 | {"2022-06-23 10:16:01.683293",`NULL`}                          |

    Sure enough, items 2 and 3 both show an array with one `NULL` value. That's not what I originally expected, but it makes sense now that I think about it.


- So I guess what I was expecting was this:

    ```sql
    select 
      i.id as "Item id",
      case when max(c.id) is null
        then null
        else array_agg(c."Checkout Time")
      end as "Checkouts"
    from "Items" i
    left join "Checkouts" c on c."Item" = i.id
    where i.id <= 4
    group by i.id
    order by i.id;
    ```


    |  Item id |                          Checkouts                           |
    | -------- | ------------------------------------------------------------ |
    |        1 | {"2022-05-30 11:55:28.596846","2022-09-26 13:06:16.249656"}  |
    |        2 | `NULL`                                                         |
    |        3 | {`NULL`}                                                       |
    |        4 | {"2022-06-23 10:16:01.683293",`NULL`}                          |

    But I can see how that might just not be worth bothering with.

Based on the above experiments, I'm closing this ticket because I can see that our current implementation behaves consistently with Postgres.

When we add support for formulas in the future, I imagine I could use a formula akin to the `case` statement above to achieve my desired behavior.

**Comment by dmos62** [comment]
Yeah, your second example is how I interpreted your suggestion. We'll be able to address this by making expressions more powerful or providing specialized aggregation functions, but the current behaviour is likely to stay the default.
