### ISSUE TITLE
Eliminate nested buttons in Constraints modal

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2101]
## Problem

- In the Constraints modal (accessible via the "Advanced" section of the table inspector), we have two nested buttons

    ![image](https://user-images.githubusercontent.com/42411/207884961-e97683bf-da64-44f0-a317-90311cc43a91.png)

- Nested buttons are bad for a11y and also mean that when you click on the trash icon, the constraint expands.

## Solution

- We should remove the nesting.

- We should make changes to the `Collapsible` component to support an additional slot (named "trigger-aside") that gets placed alongside the trigger button.

- `ConstraintTypeSection` and `ConstraintCollapseHeader` should get refactored to move the trash button into the "trigger-aside" slot.

- The resulting buttons should be alongside each other, no longer be nested, like this:

    ![image](https://user-images.githubusercontent.com/42411/207912832-dec56ce2-d8d9-476d-9d75-d4f8210f72c2.png)

**Comment by seancolsen** [comment]
Also see a related issue #2102 which might be worth fixing at the same time.

**Comment by SumeetHaryani** [comment]
Hi @seancolsen, I would like to work on this issue, could you please assign me?

**Comment by seancolsen** [comment]
@SumeetHaryani Thanks, sure go ahead. Our workflow is such that we only assign tickets to core team members, but you're welcome to submit a PR for this.

**Comment by seancolsen** [comment]
@SumeetHaryani I've assigned this ticket to you since you've submitted a PR for it
