### ISSUE TITLE
Improve handling of overflow in constraints modal

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2102]
In the Constraints modal, overflow of long constraint headers obscures information and causes the delete button to disappear.

![image](https://user-images.githubusercontent.com/42411/207916205-7f378d03-ef33-4773-9f8f-043ecdd6b91d.png)

We should fix this by adding wrapping and/or truncation.

Notes

- The HTML is slated to be slightly rearranged in #2101 which should hopefully fix the button problem. But we'll still need to ensure we can see all the columns somehow.

- We have a `Truncate` component which is already in-use here. To fix this issue via truncation, we'll need to set `overflow: hidden` on some parent elements appropriately.

**Comment by SumeetHaryani** [comment]
Hi @seancolsen, I would like to work on this issue, could you please assign me?

**Comment by seancolsen** [comment]
@SumeetHaryani Thanks, sure go ahead. Our workflow is such that we only assign tickets to core team members, but you're welcome to submit a PR for this.

**Comment by seancolsen** [comment]
@SumeetHaryani I've assigned this ticket to you since you've submitted a PR for it
