### ISSUE TITLE
Pre-release visual consistency updates

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2105]
We have noticed some inconsistencies between the Figma design guidelines and the implementation in our project. In particular, we need to fix the following issues:

- [x] Buttons
  - [x] Ensure use of primary, secondary and tertiary buttons is consistent
  - [x] Ensuring that all buttons have styles for all states
  - [x] Ensure consistent styling of button text (font size, font weight, text color)
- [x] Forms
  - [x] Form field labels are consistently styled
  - [ ] All form fields have consistent styles (includes styles for the default state, hover state, focus state, and error state)
- [x] Navigation
  - [ ] Consistently styling active and hover states for navigation menu items 
- [x] Headers
  - [x] Ensure consistent styling of all headers (font size, font weight, text color, background color)
  - [x] Apply consistent padding and margin to headers
- [x] Modals
  - [x] Verify that the background color for the modal is applied consistently throughout the application
  - [x] Confirm that the size of the modal is appropriate for the content it contains
  - [x] Check that all actions within the modal (such as buttons or links) are styled correctly and consistently
- [x] Alerts
  - [x] Ensure warnings, tips and system suggestions are used consistently
- [x] Tabs
  - [x] Ensure consistent styling of all tabs
  - [x] Ensure styles exist for all tab states (default, active, disabled, hover)
- [x] Toast Messages
  - [x] Colors match the design guidelines for each state (info, warning, error)
  - [x] Typography size and spacing is consistent
- [x] Typography
  - [x] Set variables for all font sizes
  - [x] Ensure that font sizes are consistently applied and that different font sizes are used appropriately
- [x] Layout
  - [x] Verify that the padding and widths of elements within the layout are consistent with the design
  - [x] Confirm that the layout looks good and functions correctly on different screen sizes and devices
- [x] Clean Up
  - [x] CSS variables - as per [Sean's suggestion](https://github.com/centerofci/mathesar/issues/2105#issuecomment-1358244320)
- [x] Data Import Preview
  - [x] Ensure that styles are applied consistently
  - [x] Ensure that layout is optimal for interacting with the table and form elements

**Comment by seancolsen** [comment]
This list looks good to me.

One more idea:

- Look for CSS colors which are defined outside of CSS variables, and move them into CSS variables where possible.

    Here's a quick stab at a regex that finds offending CSS

    ```
    ^\s*((?!--)\S).+?(#[0-9a-fA-f]{3}\b|#[0-9a-fA-f]{6}\b|#[0-9a-fA-f]{6}\b|rgba?\(|hsla?\()
    ```

    It gets about 200 hits. Ideally all our colors would be defined in CSS variables and that regex would not have any matches in our codebase.

If I think of more clean-up tasks like this, I'll post them here.

**Comment by kgodey** [comment]
Looks good to me. The only thing I'd add is re-styling the data import preview confirmation page – Pavish ended up doing some improvisation with the understanding that you'd look at it again in this issue.

**Comment by pavish** [comment]
Looks good to me as well. I agree with Kriti that we need to take a look at the Import preview page once again.

**Comment by seancolsen** [comment]
Another thought for @ghislaineguerin:

It would probably be helpful (and more efficient in some cases) to look through Storybook instead of looking through the app. For example, with the toast system, you can open the story to see all the ways we display toast messages, and it's easy to re-open them as you work on modifying the styles.

**Comment by kgodey** [comment]
Another issue I noticed – there's no hover color for explorations in the Schema Page.
