### ISSUE TITLE
Prevent navigating to the Table Page for an unconfirmed import

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2110]
## Steps to reproduce

1. Begin creating a new table by importing data.
1. When you get to the seconds step ("Finish setting up your table"), navigate back to the schema page.
1. Navigate to the table page for another table in the schema.
1. From that other table page, open the table selector in the navigation header.
1. Expect either:
    - that the list of tables does not contain the partially-imported table.

        _or_

    - that the list of tables _does_ contain the partially imported table, but that the table displays an asterisk (to indicate that its import process is incomplete) and that clicking on the entry for the table navigates to the import confirmation page.

1. Instead, observe that the partially-imported table displays in the list without an asterisk, and that clicking on the table navigates to the table page.

## Implementation ideas

- I think it might be best to fix this by redirecting the table page to the import confirmation page if the table is partially imported.

CC @pavish for thoughts on implementation

CC @ghislaineguerin and @kgodey for opinions on which of the two expectation scenarios described above might make more sense for users.

**Comment by pavish** [comment]
> that the list of tables does contain the partially imported table, but that the table displays an asterisk (to indicate that its import process is incomplete) and that clicking on the entry for the table navigates to the import confirmation page

I think this should be the behaviour. This is currently how it is presented on the Schema page, it should be presented the same way on the navigation pane.

**Comment by kgodey** [comment]
Yes, @pavish is correct.

**Comment by ghislaineguerin** [comment]
What @pavish described is the ideal behavior.

**Comment by kgodey** [comment]
Moving to backlog; doesn't block launch.
