### ISSUE TITLE
Unexpected constraint error when inserting

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#2116]
Kriti reports:

> there's some sort of constraint error that happens when I try to create this record from https://staging.mathesar.org/mathesar_tables/4/tables/27774/

Note, I think the correct link to the intended table is https://staging.mathesar.org/mathesar_tables/4/tables/28333/.

Kriti provides a screenshot:

<img width="1034" alt="Screen Shot 2022-12-16 at 6 36 06 PM" src="https://user-images.githubusercontent.com/2715476/208418820-fadce0c8-41b9-4df3-990e-ae8c3eda700a.png">

I was able to reproduce.

Request:

```
POST | https://staging.mathesar.org/api/db/v0/tables/28333/records/

{
"131354":"The Olympian Affair",
"131359":"2023",
"131360":"0-3929-5604-7",
"133278":175,
"133941":203
}
```

Response:

```
[
  {
    "code": 4208,
    "message": "The requested insert violates a uniqueness constraint",
    "field": null,
    "detail": {
      "constraint": 52141,
      "constraint_columns": [
        134623
      ],
      "original_details": "Key (id)=(6) already exists."
    }
  }
]
```

Not sure what `Key (id)=(6)` refers to.

Unsure if this is unintended behaviour, but the record search starts listing records that seemingly don't match the search once you select a foreign record in the "Authors_id" or "Publishers_id" columns.

**Comment by mathemancer** [comment]
This is a data problem. One of the id-generating sequences isn't getting properly set. I'll look into it.

**Comment by kgodey** [comment]
@mathemancer, @seancolsen, and I looked at this on a call, it's related to an old version of the data. It works fine with newer data, so this is no longer blocking the demo video.

There is still a bug - probably both a frontend and backend bug, since the frontend isn't sending the `POST` request to create a new record. So I'm moving to the next milestone to investigate it before release.

**Comment by seancolsen** [comment]
> probably both a frontend and backend bug

I created #2124 for a front end issue that is sort of related here

**Comment by dmos62** [comment]
> There is still a bug - probably both a frontend and backend bug, since the frontend isn't sending the POST request to create a new record.

@kgodey I'm not sure what you mean; when I reproduced this bug, a POST was being sent to the `records` endpoint. If this is something else, someone care to create appropriate issues?

**Comment by kgodey** [comment]
@dmos62 - they may be different bugs – Sean, Brent, and I were on a call together and found an issue where a `POST`request wasn't being sent.

**Comment by seancolsen** [comment]
@kgodey can we close this ticket now that we're tracking some front end work in #1356? Or is there other back-end work still needed here?

**Comment by kgodey** [comment]
Backend work is being tracked in #2144. This can be closed.
