### ISSUE TITLE
Set up documentation

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#2117]
In the `[Mathesar Core] New documentation` email thread, we discussed a setup for hosting documentation.

This task is about implementing a documentation setup based on that. IIRC, we've not speced it out fully, so the email thread, as it is now, is a starting point for the spec.

**Comment by dmos62** [comment]
Brent's commentary (from our sync): starting out with `mkdocs` will give us more flexibility than starting with `Read the Docs`, because Read the Docs would require us to host with them (to support versioning).

Also, versioning working is not that important right now. Knowing that we can make it work *is* important.

**Comment by kgodey** [comment]
@dmos62 Please ensure this issue is tracked in https://github.com/centerofci/mathesar/issues/2034
