### ISSUE TITLE
Frontend unit test cases: Readonly table view

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#213]
Currently, unit tests are not written on the frontend.

We need to start writing tests for the readonly table view.

**Comment by pavish** [comment]
@kgodey This issue was created earlier when we hadn't decided on the testing structure.

As discussed, we will use integ tests for testing user actions. This issue is entirely based on user actions and will be covered by https://github.com/centerofci/mathesar/issues/640

Can we close this issue?

**Comment by kgodey** [comment]
@pavish Sure, go ahead.
