### ISSUE TITLE
Modify form system to disable all inputs while the form is processing

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2132]
- (A) When adding a new column, we have a small form in a dropdown (`NewColumnCell.svelte`). This form disables its inputs while loading. This pattern is nice and we should employ it at a lower level so it is used throughout the app.

- (B) On the Record Page, we use the form system to save field values for the record. This form does _not_ disable its inputs while the form is loading. It should.

- We should make changes within `src/components/form` so that (B) has the same user experience as (A) (disabled inputs while loading). Then we should remove the code from (A) which manually sets the inputs to disabled -- thereby giving (A) the same developer experience as (B) (no need to think about disabling inputs while the form is loading).

- Notice that on the Record Page the `id` field is disabled even when the form is _not_ loading. We should ensure that this behavior remains.

**Comment by DanyaalMahmood** [comment]
Hi @seancolsen I'd like to work on this. Could you please assign me this issue.

**Comment by seancolsen** [comment]
Sure @DanyaalMahmood, go ahead

**Comment by DanyaalMahmood** [comment]
Hey @seancolsen I have linked a PR, could you please review it? Thanks.
