### ISSUE TITLE
Money type is not being inferred correctly.

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2143]
## Expected behavior

On importing [library_books.tsv.zip](https://github.com/centerofci/mathesar/files/10273334/library_books.tsv.zip), the "Acquisition Price" should show up as Money. 

If you attempt to cast it to Money during the import preview step, it should work.

## Actual behavior
"Acquisition Price" is showing up as a Number. Casting it to Money is throwing this error, which I can't copy/paste easily)
<img width="1915" alt="Screen Shot 2022-12-20 at 6 36 56 PM" src="https://user-images.githubusercontent.com/287034/208786612-2a95d936-81ac-44a2-ac5d-d84e7e28be37.png">

**Comment by kgodey** [comment]
Casting it to Money works fine once the table has been imported and confirmed.

**Comment by mathemancer** [comment]
This is a data problem (my fault).  `'14.25'` (the string) is not valid money, and can't be inferred to be. `'$14.25'` is, and can be.

The reason it works when it's past the confirmation step is that we _do_ allow casting any numeric to money. For text, we require a currency symbol. We can't change that without breaking type inference (right now).

**Comment by mathemancer** [comment]
If there's a bug here, it's that the change of type at the confirmation step starts over at text every time. If it was actually trying to change a _numeric_ column to money at that stage, it would work.

**Comment by mathemancer** [comment]
Okay, I've fixed the data issue, pushed the change to the relevant branch [here](https://github.com/centerofci/mathesar-data-playground/blob/a9da905d6c21b172d496a24db2d737ad746fa0c7/realistic_library_simulation_video/raw_tsvs/library_books.tsv) . 

I've also DMed you a copy for convenience, @kgodey .

**Comment by kgodey** [comment]
Thanks @mathemancer, I'll close this.
