### ISSUE TITLE
Breadcrumb out of sync after browser "back" button

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2149]
## Steps to reproduce

1. Use our Library Management schema.
1. Navigate to the Publications table page.
1. Group by Publisher.
1. Click on "Summarize Table", navigating to the Data Explorer
1. Observe the site navigation breadcrumb to be "Library Management / Data Explorer". Good.
1. Press the "Back" button on your browser.
1. Expect the navigation breadcrumb to contain "Library Management / Publications".
1. Instead, observe it to be "Library Management / Data Explorer" as before.

**Comment by kgodey** [comment]
I ran into a stale breadcrumb issue on a call today, but I don't have reproduction steps handy. I know there was an Exploration Page breadcrumb in the nav even though I wasn't on an Exploration Page.

**Comment by seancolsen** [comment]
Duplicate of #2030
