### ISSUE TITLE
Improve pluralization within schema constituent counts

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2156]
![image](https://user-images.githubusercontent.com/42411/209041996-13363137-d557-40a2-a891-59de51fd587e.png)

**Comment by seancolsen** [comment]
> There's also the "1 explorations" above it that's wrong.

Roger that. I'll clean this all up.

**Comment by kgodey** [comment]
Here's another place where "Table" should be pluralized. The explorations tab seems fine. 

<img width="916" alt="Screen Shot 2022-12-22 at 12 06 15 PM" src="https://user-images.githubusercontent.com/287034/209188732-d16561a9-6459-4c08-b063-2fd8c1e2d460.png">

**Comment by seancolsen** [comment]
@kgodey 

> "Table" should be pluralized (the search box)

Thanks for pointing that out. I just noticed this comment from you, and pushed 3cb5bd9969d372ceae1a83cef375304e292da1c6 to my PR to address this.
