### ISSUE TITLE
Summarization suggestion aggregates columns instead of grouping, when the base column is a unique key column

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2157]
## Description
* Select a table with a unique key column as the base table in Data Explorer Eg., Patrons
* Add the unique key column, along with a few other columns. Eg., Email, first name, last name
* Summarize by the unique key column. Expect the other columns to be grouped, instead notice that they are aggregated as a list.

Related comment/issue: https://github.com/centerofci/mathesar/issues/2145#issuecomment-1362358413

>  _Summarize based on patron email (there should be LESS than 180 rows at this point, and only "Book Title" should show up as a List)_
> For this point, we'd expect patron first name and last name to be part of the grouped columns, instead they are getting aggregated as list. Summarization suggestion aggregates them instead of grouping.
> Currently, the list has a single value but it's still an array column so it appears inside a pill, which looks like this:
![Screenshot 2022-12-22 at 8 47 29 AM](https://user-images.githubusercontent.com/11850603/209048160-425bcbd6-38d1-41ed-af12-ec98e35f5816.png)
> What we'd expect is this:
![Screenshot 2022-12-22 at 8 47 45 AM](https://user-images.githubusercontent.com/11850603/209048184-d86308c9-1775-4edd-8928-57c697053f87.png)

**Comment by kgodey** [comment]
@dmos62 please prioritize this, it's a nice to have for the demo video.
