### ISSUE TITLE
Incorrect icon color for public schema in breadcrumb

### ISSUE THREAD

**Issue by ghislaineguerin** [centerofci/mathesar#2159]
### Problem
Icon colors in breadcrumb are being overwritten by a specific rule, causing incorrect colors to be displayed. The overwrite is being applied to locked schemas (e.g. public).

### Expected behavior
Icon colors in breadcrumb should display correctly and should not be affected by any overwriting rules.

### Screenshot
<img width="573" alt="image" src="https://user-images.githubusercontent.com/845767/209155505-6748a408-f835-47bd-9801-3beb5fce1733.png">

**Comment by seancolsen** [comment]
Duplicate of #2109
