### ISSUE TITLE
Breadcrumb link text is not visible when summary is NULL

### ISSUE THREAD

**Issue by ghislaineguerin** [centerofci/mathesar#2160]
### Problem
Navigate to the record page, where the record has a NULL summary.
Observe the text color of the breadcrumb link.

### Screenshot
<img width="517" alt="image" src="https://user-images.githubusercontent.com/845767/209157078-f2bc6f0d-f8c9-44bb-abb0-ed8841921679.png">

**Comment by ghislaineguerin** [comment]
@seancolsen here's the ticket for NULL record summaries

**Comment by seancolsen** [comment]
Duplicate of #2055
