### ISSUE TITLE
Double check the joining logic

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2161]
## Description
* We need to come with a set of scenarios and the result we expect to achieve and double check our joining logic to ensure that the result matches our expectations.
* Some critical scenarios:
  - Joining multiple times to the same table using different paths
  - Joining multiple times to the same table with the same path
  - Both the above cases for links to & from base table
  - Joining self referential tables with themselves by both forward & reverse links
  - Joining tables that link to base_table and contain circular references with multiple tables involved

The list is to be updated.

Edit1:

- More scenarios:
  - Join from same table multiple times via reverse, one-to-many link (supposedly fixed in the [PR that started this discussion](https://github.com/centerofci/mathesar/pull/2148))

**Comment by dmos62** [comment]
This [PR](https://github.com/centerofci/mathesar/pull/2148), the bug fixed by it, and the changes in it started the discussion about needing more tests.

**Comment by dmos62** [comment]
@pavish do you think this issue is something to keep open?

**Comment by pavish** [comment]
@dmos62 I agree, I think we can close it.
