### ISSUE TITLE
KeyError after extracting tables

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2163]
### To reproduce
1. Import [library_books.tsv.zip](https://github.com/centerofci/mathesar/files/10288575/library_books.tsv.zip)
2. Sort table by Author Last Name
3. Extract Author First Name and Author Last Name to new "Authors" table
4. Observe table get filled with `DEFAULT` values - reload the page and observe table fail to load
5. Notice the request to the `/records/` API  still using the extracted column(Author Last Name) to sort the records `[{"field":<Author Last Name column id>,"direction":"asc"}]` which doesn't exist within the Table Library anymore

### API Error
Request made to: https://library.mathesar.org/api/db/v0/tables/231/records/?limit=500&offset=0&order_by=%5B%7B%22field%22%3A1076%2C%22direction%22%3A%22asc%22%7D%5D

Response traceback:

```
Environment:


Request Method: GET
Request URL: https://library.mathesar.org/api/db/v0/tables/231/records/?limit=500&offset=0&order_by=%5B%7B%22field%22%3A1076%2C%22direction%22%3A%22asc%22%7D%5D

Django Version: 3.1.14
Python Version: 3.9.2
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'django_filters',
 'django_property_filter',
 'mathesar']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'mathesar.middleware.CursorClosedHandlerMiddleware',
 'mathesar.middleware.PasswordChangeNeededMiddleware',
 'django_userforeignkey.middleware.UserForeignKeyMiddleware',
 'django_request_cache.middleware.RequestCacheMiddleware']



Traceback (most recent call last):
  File "/opt/virtualenvs/library-mathesar/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/virtualenvs/library-mathesar/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/virtualenvs/library-mathesar/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/virtualenvs/library-mathesar/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/virtualenvs/library-mathesar/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/virtualenvs/library-mathesar/lib/python3.9/site-packages/rest_framework/views.py", line 466, in handle_exception
    response = exception_handler(exc, context)
  File "/var/www/library.mathesar.org/mathesar/mathesar/exception_handlers.py", line 59, in mathesar_exception_handler
    raise exc
  File "/opt/virtualenvs/library-mathesar/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/library.mathesar.org/mathesar/mathesar/api/db/viewsets/records.py", line 67, in list
    name_converted_order_by = [{**column, 'field': column_ids_to_names[column['field']]} for column in order_by]
  File "/var/www/library.mathesar.org/mathesar/mathesar/api/db/viewsets/records.py", line 67, in <listcomp>
    name_converted_order_by = [{**column, 'field': column_ids_to_names[column['field']]} for column in order_by]
  File "/opt/virtualenvs/library-mathesar/lib/python3.9/site-packages/bidict/_base.py", line 387, in __getitem__
    return self._fwdm[key]

Exception Type: KeyError at /api/db/v0/tables/231/records/
Exception Value: 1076
``

**Comment by kgodey** [comment]
Navigating to the `Authors` table and going back to `Items` fixed the error.

**Comment by silentninja** [comment]
It's the same error tracked by #2138. @kgodey can you verify by checking the records response when doing the step **4. Observe table get filled with DEFAULT values - reload the page and observe table fail to load**

**Comment by kgodey** [comment]
It seems like it's happening intermittently. I tried reproducing and it didn't happen again.

**Comment by silentninja** [comment]
Ignore my previous comments. Another error popped up when I was trying out this error and I made wrong assumption. 

The reason for the current error tracked by this issue has to do with the frontend. The frontend is still using the extracted column for sorting and that leads to the backend throwing an error. While it should be validated on the backend too instead of throwing a 500 error, it's majorly a frontend issue.

**Comment by kgodey** [comment]
I think we should separate this into two issues: the frontend issue with sorting continuing to be applied and a backend issue for handling the error more gracefully. The backend issue can go in post-release improvements. @silentninja or @pavish could you split the issues?

**Comment by pavish** [comment]
> could you split the issues?

I just noticed this. I've already have a PR ready for the frontend issue, so I think we can skip the issue creation.

**Comment by kgodey** [comment]
Okay, we can use this issue for the backend, but the reproduction steps in the main body won't work. Instead, this is just about handling the error correctly.

**Comment by kgodey** [comment]
Actually, I'll just close this, we can handle the backend issue if it comes up again.
