### ISSUE TITLE
When user directly accesses '/auth/login' when already logged in, it should redirect the user to the home page

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2192]
If a user session is active, the url `/auth/login/` should redirect to the home page i.e. database page. Currently, it displays the login page.

**Comment by IyadElwy** [comment]
Hey! I submitted a PR for this issue.

**Comment by kgodey** [comment]
Thanks @IyadElwy!

**Comment by kgodey** [comment]
@silentninja Assigning this to you since you're the reviewer.
