### ISSUE TITLE
Return 401 for unauthenticated requests to /api/ and redirect to login page for other urls

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2193]
## Description
When user is not authenticated:
- Endpoints within /api/ should return a 401.
   - Currently some of them within /api/ return a 403, and some perform redirection to login page. They should all return a 401.
- All other endpoints which have associated views such as /, /<db_name>/, /<db_name>/<schema_id>/ etc., should redirect to login page.

## Frontend work
* Within api/requestUtils
  * Check if the response status is 401.
    * If yes, reload page.

**Comment by kgodey** [comment]
I don't have time for this. :(

@silentninja or @dmos62: can you take this?

**Comment by pavish** [comment]
Un-assigning myself since I'm not actively working on this right now.

**Comment by dmos62** [comment]
@pavish what you're asking in this PR seems simple to implement, so I'll just do that.

However, this doesn't seem like a long-term solution. The problem seems to be that the frontend can't differentiate between a user not having access because we can't identify him (he's not logged in) and not having access because his account doesn't have access.

**Comment by silentninja** [comment]
@pavish @dmos62 It makes more sense to use `401 Unauthorized` in case of login failure instead of `403 Access Forbidden`. 
DRF does this correctly, but the view that renders the initial HTML page seems to be using the Django `login_required` decorator which is using `403`. So we should be overriding the `login_required` decorator.

**Comment by dmos62** [comment]
@silentninja thanks for the insight. `login_required` decorators seems to return a `302` in case a login is required. I'll keep digging.

**Comment by silentninja** [comment]
> @silentninja thanks for the insight. `login_required` decorators seems to return a `302` in case a login is required. I'll keep digging.

Hmm that's correct, then I don't think any API should return 403 for an unauthenticated user. @pavish Can you point to the URLs that return `403` in case of invalid login credentials?

**Comment by dmos62** [comment]
@silentninja @pavish what's the process for setting up users and permissions to test this?

**Comment by pavish** [comment]
@dmos62 

> what's the process for setting up users and permissions to test this?

Please refer the [backend meta ticket](https://github.com/centerofci/mathesar/issues/1673).

**Comment by dmos62** [comment]
@pavish I'm not sure I understand the difficulty you're facing. Can't you check the url to tell if it's the login page? The 302 response should redirect you to something like `/auth/login?next=/path/you/tried/to/access`.

**Comment by pavish** [comment]
@dmos62 There are multiple issues here:
1. I get 403s when a user session is invalid. I either need it to provide me a 401, or redirect to the login page with a 200.
   - Some APIs I noticed with 403s.
      -  GET /api/db/v0/tables/?schema=1&limit=500
      -  GET /api/db/v0/queries/?schema=1&limit=500
      - I haven't checked all the APIs. I believe it should be checked while making the changes.
  - Some respond with a 302, and redirect to login page, which I'd like to be consistent.
2. When I get a login page in response with a redirection, the browser handles everything, so the end response we get is a 200. I noticed that there is a responseURL with the final path, which I can make use of. So, we can avoid the requirement of a header with 'is-login-page': true.

**Comment by dmos62** [comment]
@pavish ok, as I understand it, the only problem right now is that some API endpoints return the same status code when their session is invalid as when they have a valid session, but insufficient permissions.

I'd expect API endpoints to not return redirects (3xx) for authentication or permission reasons. 4xx seems to make more sense. @silentninja sanity check me on this.

I'll see about getting better status codes.

**Comment by pavish** [comment]
@dmos62 When user is not authenticated:
* Endpoints within `/api` should return a 401.
* All other endpoints such as `/`, `/<db_name>/`, `/<db_name>/<schema_id>/` etc., should redirect to login page.

**Comment by Anish9901** [comment]
@pavish is it ok if all the `api/` endpoints redirect to the login page instead of 401s if the user isn't logged in?

**Comment by pavish** [comment]
@Anish9901 

> Is it ok if all the /api/ endpoints redirect to the login page instead of 401s if the user isn't logged in?

The requests for these /api/ endpoints are made by us directly as ajax requests. So checking on the response status is the easiest/cleanest way for the frontend to identify that the user is unauthenticated. Redirecting to the login page for these would not be a great idea. I would prefer a 401 for these.

The other endpoints such as `/`, `/<db_name>` etc., are requested directly by the browser, since these are typed in at the url bar. So they need to redirect to the login page.

**Comment by Anish9901** [comment]
@pavish I have a couple of more questions. 
1. How do I invalidate a session?
2. Is this what is needed when there is a redirect to the login page?
![Screenshot from 2023-02-10 02-42-47](https://user-images.githubusercontent.com/52523023/217950768-1ae52693-366d-46be-ac66-d56f3d494177.png)

**Comment by pavish** [comment]
@Anish9901 

> 1. How do I invalidate a session?

Logging out invalidates the session. There's a log out option on the top pane right most dropdown.

> 2. Is this what is needed when there is a redirect to the login page?

No. It was the initial requirement, we had a bunch of discussions on the comments and came up with a final set of requirements. I've updated them in the issue description.
