### ISSUE TITLE
Implementing consistent padding for fixed width page header and content

### ISSUE THREAD

**Issue by ghislaineguerin** [centerofci/mathesar#2200]
### Problem
Fixed width pages, such as database and schema pages, have an inconsistency in padding between the header section and the content, resulting in misalignment of elements within those sections. 

### Proposed Solution
We need to implement a consistent padding that ensures proper alignment at the edge of the page. 

See example:
> <img width="460" alt="image" src="https://user-images.githubusercontent.com/845767/210335585-a87fb997-1c49-42f6-a64c-84b1cdc43033.png">

_Originally posted by @ghislaineguerin in https://github.com/centerofci/mathesar/issues/2146#issuecomment-1369580831_

**Comment by kgodey** [comment]
Moving to backlog; doesn't block launch.

**Comment by reachaadrika** [comment]
Can I work on this issue ? @kgodey  , If @ghislaineguerin  is fine with me taking this up ?

**Comment by MANISH-LAB** [comment]
can i work on this issue? @kgodey  @ghislaineguerin

**Comment by Anish9901** [comment]
@reachaadrika @MANISH-LAB this issue is still in draft stage and not ready to be worked on yet.

**Comment by reachaadrika** [comment]
Hey @ghislaineguerin @Anish9901 , so now this issue is ready to be worked upon , can I be assigned this one ? 
Also a quick question before I work on this , the page contents are needed to be moved towards left right in alignment with the icon ?

**Comment by kgodey** [comment]
sure @reachaadrika, assigned.

**Comment by ghislaineguerin** [comment]
@reachaadrika The gap in the content was added so that there's extra padding around when the viewport is narrow. Given that I think we might need to replicate the same in the header section. So I'd say icon needs to be moved.

**Comment by reachaadrika** [comment]
@ghislaineguerin Sure thing , I got it , I will align the icon with the content without moving around the content and only playing with the icon position , right ?

**Comment by reachaadrika** [comment]
Have a look at this ?
![image](https://user-images.githubusercontent.com/64789514/224109100-3fe70498-4a46-478a-9098-530ffe6595da.png)

**Comment by reachaadrika** [comment]
@ghislaineguerin have a look at mini version .
![image](https://user-images.githubusercontent.com/64789514/224111223-45f4b3d8-5506-4fe5-a93c-6b6b7a289c56.png)

**Comment by ghislaineguerin** [comment]
> @ghislaineguerin Sure thing , I got it , I will align the icon with the content without moving around the content and only playing with the icon position , right ?

Not necessarily. It's more of a padding issue I'd say. The buttons on the right side should also line up as well. I can't see the full container in your screenshots. Can you add one that shows the entire width?

**Comment by reachaadrika** [comment]
Yes  , have a look @ghislaineguerin 
![image](https://user-images.githubusercontent.com/64789514/224116113-3fa4afb4-884e-47ab-8c5b-cdedbf6b5b58.png)
![image](https://user-images.githubusercontent.com/64789514/224116670-d8559f37-24e5-4369-9681-83a7d0a060d9.png)

**Comment by ghislaineguerin** [comment]
Looks good. Can you please open a draft PR so that I review the code?

**Comment by reachaadrika** [comment]
Yes sure , also before making a PR , I found one more inconsistency , is that in your browser too , And I even tried to solve it but the changes are not reflected , I will share it here once @ghislaineguerin

**Comment by reachaadrika** [comment]
There is an inconsistency here in the description , span that has been added , I tried to fix it by twerking the margins, padding and adding some if blocks , but no changese are reflected here , this span is part of the container classs , can you have a look once here too and then I wil open a PR , also is a "draft PR" something different , or just like  " normal PR "
![Uploading image.png…]()

**Comment by ghislaineguerin** [comment]
It's a draft PR please.

**Comment by reachaadrika** [comment]
Got it !

**Comment by reachaadrika** [comment]
Done @ghislaineguerin !

**Comment by pavish** [comment]
This is fixed as part of https://github.com/centerofci/mathesar/pull/2847
