### ISSUE TITLE
Add "UI for data entered outside Mathesar” data set

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#2203]
Goal is to demo Mathesar's explorations being used as custom UI for data pulled (and constantly updated) from a third party API.

## This involves two routines:

1. a hook in `demo/install.py` that will:
    - setup the schema,
    - log the database;
2. a cron job (defined in our [ansible repo](https://github.com/centerofci/mathesar-ansible/)) that will:
    - download metadata about N most recent articles from arxiv,
    - normalize it,
    - for each logged database (by script 1.),
        - insert the normalized metadata into the database.

## Data set (source API):

Normalized by downloading script.

https://arxiv.org/
https://pypi.org/project/arxiv/

## Tasks

- [x] centerofci/mathesar#2212
- [x] centerofci/mathesar-ansible#29

**Comment by dmos62** [comment]
@mathemancer should we try to mitigate a user changing or removing the schema or parts of it?

**Comment by kgodey** [comment]
> should we try to mitigate a user changing or removing the schema or parts of it? 

If the cron job fails for a given database, we could just delete that database / session entirely. Not sure if it's worth the trouble, though.

**Comment by dmos62** [comment]
@kgodey according to the plan we drafted with @mathemancer, the user, upon logging in for the first time, will see the schema, but all its tables will be empty, and the cron job will periodically (every 15 seconds to 30 minutes) push data into it from arxiv. I think the safest way to handle this will be the cron job silently failing; if we delete the database on cron job's failure, then a user making a breaking change to the schema would cause his database to be deleted.

**Comment by kgodey** [comment]
Okay, sounds good.

**Comment by dmos62** [comment]
Both subtasks are complete. Marking as done.
