### ISSUE TITLE
Live demo server often shows "502 bad gateway" error

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2223]
Refreshing sometimes fixes it, but not always.

**Comment by silentninja** [comment]
This can happen when a deployment is in progress. Are you trying to access when a deployment is in progress or when a deployment has taken place recently?

**Comment by silentninja** [comment]
Lack of memory in the server can also be the reason. I will look into it when I have time.

**Comment by kgodey** [comment]
> This can happen when a deployment is in progress. Are you trying to access when a deployment is in progress or when a deployment has taken place recently?

No, this is happening all the time.

> I will look into it when I have time.

@silentninja This is blocking the live demo / product from being usability tested (our top goal), so please make this your highest priority over later goals.

**Comment by silentninja** [comment]
Update on the issue:
The error is happening due to server timeout. It takes more than 30 seconds for the `login` request to complete, so the gunicorn closes the connection as the timeout is 30 seconds. I suspect that loading the dataset synchronously is the problem.

**Comment by silentninja** [comment]
#2230 should fix this error.

**Comment by kgodey** [comment]
@mathemancer said on Matrix that he found a reflection-related bug that was causing this.
