### ISSUE TITLE
Allow users to add/remove filter conditions via the column header menu

### ISSUE THREAD

**Issue by ghislaineguerin** [centerofci/mathesar#2232]
## Problem
Currently, users can only apply filters to specific columns from the filter options in the table toolbar. It would be convenient to have filter options available at the column header level. 

## Proposed Solution
We propose adding a filter option to the column header menu to make it easier for users to filter specific columns. The option would open the current filter popup and have the selected column pre-selected. 

[Figma design](https://www.figma.com/file/xHb5oIqye3fnXtb2heRH34/Styling?node-id=1304%3A7357&t=WotuvB0jSNIg0eab-0)

![image](https://user-images.githubusercontent.com/42411/211939479-6ad69117-7d0f-4faa-a4f4-e2f2c1452edb.png)

## Additional Questions
From [Matrix Discussion](https://matrix.to/#/!xInuTkBwjXZXYatIlm:matrix.mathesar.org/$X5V9YArIFwaVVB7q341a_u1fTx_IhlNNWrfejm2g2Zg?via=matrix.mathesar.org&via=matrix.org)
- When a filter condition is already applied, would it be worth keeping the "Filter Column" option in the context menu, allowing the user to add another filter condition too?
- And if more the one filter condition is applied, we'll need to consider what behavior the "Remove Filter" action should take.

**Comment by seancolsen** [comment]
Can we move this from Icebox so Backlog? This is quite high on my priority list.

**Comment by kgodey** [comment]
@seancolsen @ghislaineguerin No decision is needed here, right? This is just an issue to look at later?

**Comment by seancolsen** [comment]
@kgodey I see two small design questions here:

1. If multiple filter conditions are added for the same column, how does the "Remove Filter" menu entry behave?

    My preference would be for the menu entry to text to be dynamic depending on the number of filter entries applied for the column. E.g.

    - "Remove Filter"
    - "Remove 2 Filters"
    - _etc_

    This should be pretty easy, especially with the improvements to the `labeledCount` function that I made in #2243.

    Then, (as would be apparent from the label) clicking on that menu entry would remove _all_ filter conditions for that column

1. If a filter condition is already applied, can I use the context menu to add another one?

    My preference would be "yes". We'd keep the "Filter Column" option in the menu even when a filter is already applied. Clicking it always adds a new filter condition for the column.

**Comment by kgodey** [comment]
@seancolsen Your preferences sound fine to me, let's do that.

**Comment by reachaadrika** [comment]
@kgodey & @seancolsen  , Can I work on this issue ?

**Comment by MANISH-LAB** [comment]
i can do it,assign to me please

**Comment by MANISH-LAB** [comment]
hey i have a query.
i just went through demo version mathesar from  the link provided in read me.
there i can see the functionality of user being able to add/remove filter conditions in the column header menu so that means its already implemented. then what am i supposed to do or you can tell me if i am missing out something as i am new to open source.

**Comment by kgodey** [comment]
@MANISH-LAB I also just looked at it and it's not implemented. Grouping and sorting is implemented, but not filtering. 

Can you send a screenshot of what you're seeing?

**Comment by MANISH-LAB** [comment]
sure here, as you can see the filtering can be done on any column name and filtering options column wise are also there 
![exmpl](https://user-images.githubusercontent.com/60395916/223244328-81d51f72-ab26-46bd-9b22-9898df19eb59.jpg)

**Comment by kgodey** [comment]
@MANISH-LAB sorry for the confusion. that's not what we mean by the "column header". Try right clicking on a column header (e.g. where it says "# id"). That's where we want the filtering options implemented. Please see the issue description for the design and more details.

**Comment by MANISH-LAB** [comment]
okay so the figma design is how your proposed solution should be
and when i click on respective column header filter, a pop up with filtering options should come up right.
ps: i guess the title of issue should be changed to " Allow users to add/remove filter conditions via column headers" because column header menu is where all the column names are listed

**Comment by kgodey** [comment]
@MANISH-LAB yes, correct.
