### ISSUE TITLE
Show confirmation when deleting records via table inspector

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2236]
## Steps to reproduce

1. Use the row header context menu to delete a record.

1. Observe a confirmation dialog before deleting a record. Good

    ![image](https://user-images.githubusercontent.com/42411/211886133-5036bf42-0c7e-499d-837c-10a34ff16950.png)

1. Use the Table Inspector to delete a record.

    ![image](https://user-images.githubusercontent.com/42411/211885994-f43cee7c-5d30-435e-a500-0df3453c9529.png)

1. Expect a similar confirmation dialog.

1. Instead, observe that the record is deleted without confirmation.

**Comment by Hatilar420** [comment]
Hi, 
Can i work on this issue , if no one is working on it ?

**Comment by rajatvijay** [comment]
@Hatilar420 sure, feel free to start work on this. 😄

**Comment by Hatilar420** [comment]
Hey @seancolsen,
I've opened a PR for this issue. Can you please review it? Thanks!
