### ISSUE TITLE
Set up staging environment for Mathesar

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#225]
**Problem**

@ghislaineguerin needs access to a deployed version of Mathesar to check design implementation.

**Proposed solution**

We should set up a staging environment for Mathesar. It needs to have some sort of auth to access it, since we don't have auth implemented for Mathesar itself.

**Checklist**
This is primarily to track progress for the author's benefit.
- [x] Parameterize settings file in `mathesar` repo.
- [x] Create repository for Ansible playbooks: https://github.com/centerofci/mathesar-ansible (private to maintainers)
- [x] Set up base Ansible tasks (install basic systems packages)
- [x] Set up database setup Ansible tasks
- [x] Set up HTTPS Ansible tasks [UNTESTED!]
- [x] Set up repo setup Ansible tasks (types schema installation, migration, etc.)
- [x] Set up frontend build tasks
- [x] Set up webserver deployment tasks
- [x] Set up basic auth tasks
- [x] Update README of Ansible repo to be comprehensive.
- [x] Set up other maintainers with deploy access to staging.

I'll create a separate task to set up auto-deploy on merge to `master`: #359.

**Comment by kgodey** [comment]
My plan is to set up an Ansible playbook to provision a Mathesar instance and use that to set up the staging server. I'm not going to be using Docker in the playbook/staging server.

**Comment by kgodey** [comment]
I moved this to milestone #2 since that's when we're planning to get this done.

**Comment by kgodey** [comment]
@andyharley-cci Assigning this to you. Please note that I have HTTPS setup marked as done, but I haven't tested it. The tasks prior to the HTTPS commit have actually been run on the staging server.

**Comment by andyharley-cci** [comment]
@kgodey I think I've progressed this issue along well, with only the frontend remaining (which is now in a new issue).

Some notes:
- using virtualenv everywhere
- nginx with letsencrypt and some basic auth on it (password is in 1password)
- gunicorn used for serving wsgi
- updated readme with instructions on how to get access to staging. the playbooks create a 'deployer' user for people to add their SSH keys to

The server looks like it's running - though I'm not sure how to directly interact with the API just yet. I can hit various endpoints but I end up with a permissions error. Should there be some django user setup automation done as well? Or is this handled by the UI usually? e.g. https://staging.mathesar.org/api/v0/schemas/

**Comment by kgodey** [comment]
@andyharley-cci Nice work, thanks!

We don't have any functionality related to users or permissions implemented yet (hence the need for basic auth), so I'm not sure why it's giving you a permissions error. Looks like it might be trying to process the basic auth header, see: https://stackoverflow.com/questions/40094823/django-rest-framework-invalid-username-password. I think it would make sense to update `REST_FRAMEWORK` settings in the Mathesar settings file as described.

**Comment by andyharley-cci** [comment]
Great, thanks for that. #435 looks to resolve that when I tested it. 

Some endpoints fail (presumably due to no data), but others are now succeding

```
$ curl -u staging:${AUTH_PASS} https://staging.mathesar.org/api/v0/database_keys/
["mathesar_tables"]
```

**Comment by kgodey** [comment]
@andyharley-cci None of the endpoints should be failing with no data unless there are bugs, could you file bugs with tracebacks for any that are?

**Comment by kgodey** [comment]
I made an issue for the one bug I saw: https://github.com/centerofci/mathesar/issues/437

**Comment by kgodey** [comment]
The staging server now works!
