### ISSUE TITLE
Importing a CSV with a large number of columns times out at confirming data step

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2250]
A user tried importing a CSV with 62 columns on a production setup with nginx. The preview endpoint timed out after a minute.

We should either (ideally, both):
- Improve performance of the endpoint with multiple columns.
- Provide an option to skip inference if the process takes too long.

**Comment by mathemancer** [comment]
@kgodey Can you provide the CSV so we can verify that this was inference timing out?

If not, can you describe the data a bit? (I.e., was it lots of columns of JSON, or lots of columns of booleans?)

Was the timeout at 30 seconds? If so, we'll need to consider how to deal with larger and larger data sets. While I think we can solve this specific problem through parallelization of the inference algorithm over the columns (assuming a reasonably limited number of rows in the CSV), we need a way to deal with data sets that take more than 30 seconds to process for various operations.

**Comment by kgodey** [comment]
@mathemancer 
- I cannot provide the CSV, it's confidential information. It's mostly text columns, with two email columns, one or two date columns, one or two number columns. 
- The timeout was at 60 seconds.

Please note that it timed out on production, but not when I tested it locally.

**Comment by dmos62** [comment]
I fabricated a big csv that took 6 minutes to infer column types, but no timeout (locally). I'll try on staging.

@kgodey you say that it was reproduced in production, but I'm not sure what that means, given that our prod and demo environments seem to be rapidly changing. More insight into how to reproduce might be useful.

**Comment by kgodey** [comment]
@dmos62 for "production", I meant any server deployed with our Ansible setup.

> I fabricated a big csv that took 6 minutes to infer column types

This _is_ the problem. Most production webservers have timeouts configured, so anything that takes longer than 30sec or 60sec will time out. The action item here is to improve performance.

**Comment by dmos62** [comment]
> The action item here is to improve performance.

The 6 minute inference was on a 100 mb csv file with multi-digit number of columns. I wasn't expecting more speediness, to be honest.

@kgodey I think the problems are the following:

- column type inference is possibly inefficient;
- we're not handling timeouts;
- we're trying to fit column type inference into a HTTP transaction; that's not smart, because the duration of this task depends on input outside our control;
- infering column types is an uninterruptable, monolithic operation for which you don't see incremental progress; there's no reason why we couldn't do it per-column;
- column type inference is obligatory.

I don't have insight into how much we can improve the efficiency of column type inference, but I do think it's not enough on its own. We definitely can't make it so fast that all of these other problems never come up.

I think it would make sense to fix this in this order:

- handle the timeouts and size-limit panics,
- make column type inference optional,
- make it per-column,
- decouple inference from an HTTP transaction,
- make column type inference more efficient.

**Comment by kgodey** [comment]
Thanks for the summary @dmos62.

> - handle the timeouts and size-limit panics,

I don't think we can handle timeouts in our product – they are configured by the external web server during deployment. Users may choose to deploy with any type of web server and configuration.

> - make column type inference optional,
> - make it per-column,
> - decouple inference from an HTTP transaction,

We will need new UX for these. We should decide on the UX before doing any work here. We're not going to be adding new features to our pre-release workload, so this needs to wait until after release.

> - make column type inference more efficient.

Please explore options for this, since this is the only work we can do purely on the backend.

**Comment by kgodey** [comment]
Moved to backlog since this doesn't actually block launch.

**Comment by dmos62** [comment]
Opened another issue to track the subtasks: https://github.com/centerofci/mathesar/issues/2346

**Comment by kgodey** [comment]
@dmos62 Can you also make a product / design issue in the backlog for these items?

> make column type inference optional,
> make it per-column,
> decouple inference from an HTTP transaction

**Comment by dmos62** [comment]
> Can you also make a product / design issue in the backlog for these items?

Yes.

> I see you made https://github.com/centerofci/mathesar/issues/2346, but it doesn't make sense to clump all of these into one issue – they require a bunch of different types of work and can be done independently of each other as separate improvements.

My intent was to declump them into a meta issue (#2346), where they're in a checkbox list and can be lazily converted into discrete issues, like I did for #2347 when I started working on it. I'll convert the rest of them to issues and label the #2346 as a meta ticket.

**Comment by kgodey** [comment]
@dmos62 In this case, I'm not sure that a meta issue makes sense. Meta-issues are for a single feature that's being broken up into smaller (related) parts for implementation. In this case, each part can be implemented separately; there's no "larger feature" that's being completed based on smaller parts.

**Comment by dmos62** [comment]
@kgodey in my mind, the larger task being completed is making csv importing reliable and performant. All of these subtasks have this same end goal.

**Comment by kgodey** [comment]
@dmos62 That makes sense. The issue description in #2346 does not explain that it's meant to make CSV importing more reliable or the motivation for it, please make sure it does.

**Comment by kgodey** [comment]
Also please make sure the meta-issue includes the newly opened issues that you and Brent discussed.
