### ISSUE TITLE
Ordering by a non-orderable column (implicitly or explicitly) causes a backend crash

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#2305]
## Bug

Brent [writes](https://github.com/centerofci/mathesar/pull/2253#pullrequestreview-1251718380):

> At one point, you note in a comment that there's a bug whenever we have internal columns of JSON type, and no primary key in a table. This bug is still present for _any_ non-orderable column type if there is no primary key in the table (e.g., if the user attaches to a preexisting DB). It's easy to figure out whether or not a type is orderable in PostgreSQL. See the [docs page for ORDER BY](https://www.postgresql.org/docs/current/queries-order.html#id-1.5.6.9.5.10) and the [docs page for Operator Classes](https://www.postgresql.org/docs/9.5/indexes-opclass.html).

Brent is referring to [this comment](https://github.com/centerofci/mathesar/blob/8c215b2efdd740da0d530b624763cf260e12ca90/db/records/operations/sort.py#L47).

The error message received upon such a crash is: `could not identify an ordering operator for type json` (`json` is the type of the unorderable column in this case.

## Solution

The solution is, as explained by Brent, to make sure that every column we order by (implicitly or explicitly) is orderable.

## Severity

Because of this, a JSON column (it's non-orderable), can make a query/table view unrenderable, but only when the table/query does not have a primary key, which cannot happen in a Mathesar-created table. It can only happen when Mathesar is used to access a pre-existing database.

**Comment by Hatilar420** [comment]
Hi 
Can i work on this issue ?

**Comment by dmos62** [comment]
@Hatilar420 sure, I'll assign you!

**Comment by dmos62** [comment]
Assigned myself by mistake. Meant to assign @Hatilar420.

**Comment by Hatilar420** [comment]
sure np @dmos62

**Comment by Hatilar420** [comment]
Hi @dmos62, Can you help me in reproducing this bug ? are there any pre-existing tables or any query that i can use to reproduce this bug ?

**Comment by dmos62** [comment]
@Hatilar420 I don't have a dataset, but to manufacture one yourself you can create a Postgres table via `psql` that 1) doesn't have a primary key (PK) and 2) has a non-orderable (e.g. JSON) column. You can't use Mathesar to create the table, because it can't create a table without a PK.

This should break our backend, because it strives to provide total ordering by ordering by all columns, ignoring the fact that some columns cannot be ordered by (e.g. JSON columns).

**Comment by Hatilar420** [comment]
sure, working on it

**Comment by Hatilar420** [comment]
Hi @dmos62 while solving this issue, I came across this method. Can you give me an example or tell me how we are using this method since I see no declarations of it? and what is the parameter `relation` we passing to it? 

![image](https://user-images.githubusercontent.com/29446639/218450296-d746adc5-28d5-4336-ac3a-5971fde9ee9e.png)

**Comment by dmos62** [comment]
@Hatilar420 to answer these questions you can check out the superclass `Transform` and how it's used in the codebase.

**Comment by Hatilar420** [comment]
Hi, @dmos62  is this the desired response? I am getting a `200` response from it. After I implemented the solution. Since Mathesar doesn't support JSON yet. It is displaying the data like that.
If it is not desired, then what should be the desired response? 
![image](https://user-images.githubusercontent.com/29446639/218479771-30426f82-dc84-4a6d-b89e-322add38b90c.png)

**Comment by dmos62** [comment]
@Hatilar420 yes, the expected result is that backend doesn't attempt to order by a non-orderable column and thus doesn't crash. Submit a PR and I'll be able to give further feedback.

**Comment by Hatilar420** [comment]
Hi @dmos62, I have opened a PR please check it out. Thanks
