### ISSUE TITLE
First time password reset should redirect to login page instead of confirmation page

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2312]
## Description
* After the user resets their password at the page: `/auth/password_reset_confirm`, they are redirected to `/auth/reset/done/`.
* They should be redirected to `/auth/login` instead.

**Comment by pavish** [comment]
We are currently working on updating the UX, which might render this issue void. However, this will remain open until the UX is finalized.

**Comment by pranayrishith16** [comment]
I think this can be solved by having a custom view with `/auth/reset/done/ ` as its urls and that view containing a redirect to **login**. If no one is working on this, @pavish could you assign me this, I'll try.

**Comment by pavish** [comment]
I'll leave it to @silentninja to confirm the approach required here.

@pranayrishith16 I'm assigning this issue to you, please make sure you get the approval of the approach from @silentninja here, before submitting a PR.

**Comment by pranayrishith16** [comment]
@pavish I have been trying but I am having a lot of docker issues, could you assign this to some other person.

**Comment by pavish** [comment]
@pranayrishith16 Sure, I've unassigned you from the issue. Please feel free to ask questions on getting your Mathesar development setup ready in the [matrix channels](https://wiki.mathesar.org/en/community/matrix).

**Comment by Subhojit-Dey1234** [comment]
@pranayrishith16  can you assign me? I want to work on this issue.

**Comment by silentninja** [comment]
Sure @Subhojit-Dey1234 I have assigned you the issue

**Comment by Subhojit-Dey1234** [comment]
@silentninja Thanks
