### ISSUE TITLE
Fix API error response when filtering on an invalid date

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2326]
## Steps to reproduce

1. Send a request like

    ```http
    GET http://localhost:8000/api/db/v0/tables/1/records/?limit=500&offset=0&filter={"equal":[{"column_id":[6]},{"literal":["2"]}]}
    ```

    Here, column with id `6` is a date column, and the value `"2"` is a partially-entered date that should be considered invalid.

1. Expect an error response conforming to our [error standards](https://wiki.mathesar.org/en/engineering/standards/api#errors)

1. Instead, observe an HTTP 500 Django error.

**Comment by aagman945** [comment]
I would like to work on this issue

**Comment by seancolsen** [comment]
Thanks @aagman945. Please open a PR with your changes when you're ready.
