### ISSUE TITLE
Should we allow users to specify PK values while adding records? If so, how?

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2336]
## Purpose of this ticket

In #1356, @pavish said:

> Users should be able to edit a PK column cell in an un-saved row

In working to implement that functionality, I've uncovered a number of questions.

**This ticket exists to discuss and agree upon a standard approach to allowing (or disallowing) editing of PK values.**

## Current behavior (_and possible changes noted via_ 🛠)

- For existing records:

    - I can't edit PK values for existing records anywhere. I think we all would agree this behavior is good.

- When creating a new record:

    - On the Table Page

        - If all non-PK columns are nullable, I cannot supply a PK value for my new record because the the front end never prompts me for any input before submitting a request to create an empty record.
        
            > 🛠 We could potentially change this behavior, but it would require some UX design work. We'd need some sort of "Submit" button somewhere.

        - If columns has a NOT NULL constraint without having a default value, then I _can_ supply values for _non-PK_ cells before creating the record, but I _can't_ supply values for _PK_ cells because the PK cell is disabled.
        
            > 🛠 We could potentially allow editing within that cell, but doing so cleanly appears to require a moderate amount of front end refactoring. Further, due the the importance of UX consistency, we may not want to attempt this sort of change until we've done the design work necessary to allow PK values to be entered everywhere. After all, If Mathesar allows me to enter PK values, then I should be able to do so regardless of whether the table contains any NOT NULL columns without default values.

    - Using the Record Selector, I can enter a PK value before creating a record.

        - If I enter a PK value that already exists, the record is not saved, but error behavior needs some improvement to let me know how to fix the problem.
        
            > 🛠 We have #1882 for improvements to the error behavior.

        - If I enter a PK value that does not already exist, **I _can_ save a record with a PK value!**

            > 🛠 If we want to disallow entering PK values via the Record Selector, then we'll need to change some behavior within the Record Selector. The UX here may need some thought. Do we silently disregard the PK value the user entered? Or do we alert the user somehow? If so, how?

            **HOWEVER!** I'm not sure we _want_ users to enter PK values. I played around a bit and was surprised to learn that [Postgres does not increment its SERIAL sequence when I insert records with PK values](https://stackoverflow.com/questions/9108833/postgres-autoincrement-not-updated-on-explicit-id-inserts). This means that if I supply a custom PK value during record creation, the sequence will increment to that value, at which point Mathesar won't be able to insert any more records without custom PK values. That's very bad! It looks like we could solve this with a trigger, but that feels a little messy.

## Sean's proposal

- Users cannot specify custom PK values

- We modify the Record Selector so that it silently discards user-entered search values into PK fields before creating new records. (This will be very easy.)

## Questions

- Does my proposal sound okay? If not, how would you like this to work?

@pavish @kgodey @mathemancer

**Comment by kgodey** [comment]
Your proposal sounds fine, @seancolsen. I don't see much value in allowing users to enter custom PK values.

**Comment by seancolsen** [comment]
Thanks @kgodey. I'll track implementation in #2337
