### ISSUE TITLE
Design for text data type

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#234]
## Problem

Users will want to store data in a column with the text data type. We should allow them to do so and provide an intuitive user experience for them.

## Proposed solution

We need a design for the following functionality:
- Displaying text columns in tables (I assume we don't need to change existing behavior for this, but I'm putting the requirement in here for the sake of completeness)
- Creating a new column with the text data type (which should also be the default for new columns)
- Changing an existing column to the text data type (including error states)
- Showing non-technical users a friendly name for the text data type. (The underlying Postgres data type could be `VARCHAR`, `TEXT`, or `CHAR`)

### Options

Text columns will have the following options:

#### Specific to Text
- Maximum length (this will be validated at the DB level)

#### Common to all Columns
- Default value (this will be the default value of the column if the user doesn't enter anything)
- Allow empty values (whether the column is nullable)
- Unique (whether the values in the column have to be unique, validated at the DB level)

### Grouping
Text columns will be able to grouped by:
- First letter of value
- First word of value

### Filtering
Text columns will support the following filters:
- contains
- is
- is not
- starts with
- ends with
- does not contain
- does not start with
- does not end with
- is empty
- is not empty

**Comment by ghislaineguerin** [comment]
Specs posted at https://wiki.mathesar.org/e/en/design/specs/data-types-text
