### ISSUE TITLE
Show cell content in table inspector Cell tab

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2342]
## Current behavior

- The Table Page has a table inspector with tabs for "Table", "Column", and "Record".

    ![image](https://user-images.githubusercontent.com/42411/214344467-a4ee7386-d0cb-437a-a52a-6c07adaedbd7.png)

- The inspector on the Exploration Page also has a tab for "Cell" which shows the cell content.

    ![image](https://user-images.githubusercontent.com/42411/214347520-392319c8-30ac-4ee4-854e-e8058a8e491a.png)

    This is nice for cells that have longer content

## Desired behavior

- The inspector on the Table Page has a "Cell" tab which behaves similarly to the "Cell" tab on the Exploration Page.

**Comment by SumeetHaryani** [comment]
Hi @seancolsen, I would like to work on this issue

**Comment by seancolsen** [comment]
Sounds good @SumeetHaryani. Go ahead.

**Comment by seancolsen** [comment]
@SumeetHaryani We made some changes yesterday to our [Contributor Guide](https://wiki.mathesar.org/en/community/contributing) and now we are assigning tickets to community contributors, so I'm assigning this ticket to you. If we don't see any progress in 1 week (from today), I'll unassign it. If you need more time you can comment here to give us an update and let us know you're still working on it. Thanks for your help!

**Comment by seancolsen** [comment]
@gulianow this issues already has an open PR so I would suggest working on others instead.
