### ISSUE TITLE
Use Truncate component in Record Selector table cells

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2345]
## Current behavior

- We have a `Truncate` component that we use in some places when we might not have enough space to show some text. It shows the full text on hover. For example, here it is in action in the column header cell

    ![image](https://user-images.githubusercontent.com/42411/211377873-28f95aab-6b32-42b1-b386-64bee68d473d.png)

- On the Table Page, when the value in a data cell is too long, we truncate it, but we don't use the `Truncate` component. That means that users don't get the popover behavior which shows the full value.

    ![image](https://user-images.githubusercontent.com/42411/214341948-89e5b32b-9e6f-43ca-a128-7dd65bfc2af2.png)

    Whether or not users _should_ see the popover on table cells is debatable. We have #2342 to show the entire cell content within the table inspector, so I don't think we need a popover here.

- _However_ in the Record Selector we're also rendering table cells, but our needs are a bit different. Here we don't have a table inspector. Also, we don't let the user resize columns. So we do have a compelling need to show some sort of popover for truncated text, otherwise the user may have no other means of distinguishing records that appear to be duplicates from the first portion of their cell content.

    Currently, we have a rather crude mechanism for displaying popover text -- we put it into the `title` attribute.

    ![image](https://user-images.githubusercontent.com/42411/214348846-0730fce7-4b17-4f1b-8026-e5c079eaafd7.png)

    We have some [logic](https://github.com/centerofci/mathesar/blob/25b1f8496488ab30c4d0e0da747193ae99a3a3ca/mathesar_ui/src/systems/record-selector/RecordSelectorDataCell.svelte#L14L38) which shows the title tooltip only when the text is sufficiently long.

- Further, the table widget in the Record Page also renders table cells and doesn't have a table inspector. Here, I think it would be nice to at least experiment with showing the popover.

## Desired behavior

- We should use the `Truncate` component for table cells.

- On the Table Page, we should pass a prop down to all the `Truncate` components, setting `passthrough={true}`

- Within the Record Selector, and on the Record Page, we should keep `passthrough={false}` (as it is by default), producing table cells which show popover content when the values are truncated.

**Comment by seancolsen** [comment]
Sounds good, @SumeetHaryani. Go ahead.

**Comment by seancolsen** [comment]
@SumeetHaryani We made some changes yesterday to our [Contributor Guide](https://wiki.mathesar.org/en/community/contributing) and now we are assigning tickets to community contributors, so I'm assigning this ticket to you. If we don't see any progress in 1 week (from today), I'll unassign it. If you need more time you can comment here to give us an update and let us know you're still working on it. Thanks for your help!

**Comment by SumeetHaryani** [comment]
@seancolsen  on the Record Page, do you mean we should keep passthrough={false} (as it is by default)

**Comment by seancolsen** [comment]
@SumeetHaryani yes. Thanks. Good catch. I've updated the ticket description.

**Comment by Anish9901** [comment]
Unassigning due to inactivity.

**Comment by Harish-b-03** [comment]
Heyyy @seancolsen :wave: , can I work on this issue?. 

Thank you :grin:

**Comment by kgodey** [comment]
Assigned to you @Harish-b-03

**Comment by Anish9901** [comment]
Unassigned due to inactivity.

**Comment by Ary0405** [comment]
Hey I would like to work on this issue. Please assign it to me.

**Comment by seancolsen** [comment]
Sure @Ary0405, go ahead.

**Comment by Ary0405** [comment]
I looked through the code. Can you help me with what to change in the code ?

**Comment by pavish** [comment]
> Can you help me with what to change in the code ?

@Ary0405 The issue description provides detailed information on what is required. Could you please ask specific questions, so that we'll be able to assist you better?

**Comment by Ary0405** [comment]
<img width="1440" alt="Screenshot 2023-03-15 at 11 42 52 PM" src="https://user-images.githubusercontent.com/76778991/225404276-75a57e73-507f-4db2-b78e-bb60c3ad5781.png">
Is this the desired output you want?

**Comment by seancolsen** [comment]
@Ary0405 Yes, that's the desired behavior.

**Comment by rajatvijay** [comment]
@Pulkit0729 sure, assigned this to you.

**Comment by Pulkit0729** [comment]
Hi, I had doubts with the desired behaviour, you are asking
On the Table Page, we should pass a prop down to all the Truncate components, setting passthrough={true}
With that truncate wont happen on table page. But we want to add truncate on table page.
Also I wanted to know that if we can edit the Truncate.svelte for adding cell wrapper related functionalties as mentioned in https://github.com/centerofci/mathesar/pull/2687#discussion_r1149864314

**Comment by seancolsen** [comment]
@Pulkit0729 

> With that truncate wont happen on table page. But we want to add truncate on table page.

The goal here is to truncate table cells in certain contexts and not in other contexts. In the Record Selector, we _do_ want the "truncate" behavior. In the Table Page, we _don't_ want the truncate behavior. Both of those UIs use the same components, so we want to insert the Truncate component into that tree so that it can be enabled in certain contexts. On the Table page we don't want the truncate _behavior_, but we do want the Truncate _component_ (because the table page shares the cell component structure with the Record Selector).

> if we can edit the Truncate.svelte for adding cell wrapper related functionalties

I'm not sure what sort of functionalities you're referring to here, but I wouldn't imagine this PR would warrant any edits to `Truncate.svelte`. If you feel the need to edit that file, we can discuss your changes in the PR or you can describe the changes in more detail before making them so that I can give an opinion about it.

**Comment by Pulkit0729** [comment]
Alright, i think i got it, so the behaviour in the https://github.com/centerofci/mathesar/issues/2345#issuecomment-1470527401 isn't the final output desired.

**Comment by seancolsen** [comment]
> so the behaviour in the https://github.com/centerofci/mathesar/issues/2345#issuecomment-1470527401 isn't the final output desired.

I see. That screenshot demonstrates that the Truncate component has been successfully applied, which is why I said _"that's the desired behavior"_. It's not exactly the end result because we actually want to disable truncation in that particular context, but the screenshot represents the bulk of the work that I expect this issue to involve.

**Comment by Pulkit0729** [comment]
Okay got it, 
Regarding the changes in Truncate.svelte, as mentioned in https://github.com/centerofci/mathesar/pull/2687#discussion_r1149864314, some columns in table have right side horizontal alignment like money or time, so for that we have to pass a prop to Truncate for controlling this alignment , so that no existing functionality breaks

**Comment by seancolsen** [comment]
@Pulkit0729 Ok hmmm. I'm not sure if that case will warrant changes to Truncate.svelte or not. Use your best judgement and make sure to test number cells. Try to avoid changes to low-level components if you can.

**Comment by Pulkit0729** [comment]
Hi @seancolsen , I have added a PR. I have also done some changes to truncate component. Please suggest a way around if the componet is not to be changed.

**Comment by seancolsen** [comment]
Fixed via #3077
