### ISSUE TITLE
Scroll sheet all the way down and select first non-pk cell when clicking the New Record button

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2348]
## Steps to reproduce

1. Identify a table with lots of records, and load its Table Page from scratch.

1. Press "New Record" button.

1. Expect to see the empty record row

1. Instead, observe that the sheet has been scrolled down, but not all the way.

    ![image](https://user-images.githubusercontent.com/42411/214366757-87f2dd28-d70d-400c-9079-b94f70152ce0.png)

    This is likely to confuse new users

1. Expect the active cell (and cell selection) to move to the cell within the new record and within the first column which is not a primary key. This way, I can start entering new data quickly.

1. Instead, observe that the active cell is still the first cell in the table.

    It's possible that fixing the cell selection problem may also fix the scrolling problem, which is why I've lumped these problems into the same ticket. But I'm not sure, so feel free to split this ticket into two during implementation if needed.

**Comment by SumeetHaryani** [comment]
Hey @seancolse,
With reference to added screenshot. Is this the ideal behavior we are expecting here?
![image](https://user-images.githubusercontent.com/38041443/214372878-28371f97-81ba-418e-8fe7-0a3b623e9089.png)

**Comment by seancolsen** [comment]
@SumeetHaryani Yep -- that's the ideal behavior!

**Comment by seancolsen** [comment]
@SumeetHaryani Please work on a maximum of two issues at a time, leaving other tickets unclaimed for newcomers. Thanks.

**Comment by SumeetHaryani** [comment]
Got it, noted...

**Comment by Sukshan** [comment]
hey sean, would like to work on this issue! would you assign it to me.

**Comment by seancolsen** [comment]
Sure, @Sukshan go ahead.

**Comment by Sukshan** [comment]
@seancolsen

**Comment by ShravaniRoy** [comment]
hello @seancolsen , I am interested in solving this issue. If it remains inactive, please assign it to me.

**Comment by faraz16iqbal** [comment]
Hi @seancolsen! This issue has been inactive for a while. Can I pick this up?

**Comment by faraz16iqbal** [comment]
@seancolsen alright that sounds good. Thank you so much!

**Comment by seancolsen** [comment]
#2515 is merged which handles half of the problem. I've split the other half of the problem into a new ticket #2704
