### ISSUE TITLE
Design for email data type

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#235]
## Problem

Users will want to store emails. We should allow them to do so and provide an intuitive user experience for them.

## Proposed solution

We need a design for the following functionality:
- Displaying email columns in tables (should they be clickable?)
- Creating a new column with the email data type
- Changing an existing column to the email data type (including error states)
- Showing non-technical users a friendly name for the email data type. (The underlying Postgres data type will be a custom `EMAIL` type)

### Options

Columns of this type will have the following options:

#### Common to all Columns
- Default value (this will be the default value of the column if the user doesn't enter anything)
- Allow empty values (whether the column is nullable)
- Unique (whether the values in the column have to be unique, validated at the DB level)

### Grouping
Columns of this type will be able to grouped by:
- First letter of value
- Email domain name

### Filtering
Columns of this type will support the following filters:
- contains
- does not contain
- is
- is not
- is empty
- is not empty
- domain contains
- domain does not contain
- domain is
- domain is not

**Question:** should we support all the additional filters that the text data type supports or is that too many?

## Additional Context
- The email data type may not be available to all users, since it's a custom type. We should not allow users to change data to the email type if it is not available.

**Comment by ghislaineguerin** [comment]
Specs for this issue can be found here: https://wiki.mathesar.org/en/design/specs/email-data-type
