### ISSUE TITLE
When loading the Schema Page, show the correct number of loading skeletons

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2351]
## Current behavior

- On the Schema Page we show nine loading skeletons [relevant code](https://github.com/centerofci/mathesar/blob/25b1f8496488ab30c4d0e0da747193ae99a3a3ca/mathesar_ui/src/pages/schema/TableSkeleton.svelte#L4)

## Desired behavior

- The Schema Page loads a number of skeletons equal to the number of tables in the schema.

## Implementation notes

- We actually already have the number of tables in the schema in the [num_tables](https://github.com/centerofci/mathesar/blob/25b1f8496488ab30c4d0e0da747193ae99a3a3ca/mathesar_ui/src/AppTypes.ts#L18) property of `SchemaEntry`, so it should just be a matter of connecting some dots.
- When I played around with this briefly, I was able to get it working when loading the Database Page (i.e. http://localhost:8000/mathesar_tables/ ) then navigating to the Schema Page. But the skeleton count was incorrect when navigating from a Schema Page to a different Schema Page (via the ) switcher dropdown in the navigation header. Make sure to get that working too.

**Comment by Hatilar420** [comment]
Hi @seancolsen, w
working on this issue.

**Comment by Hatilar420** [comment]
Hi @seancolsen, Can you please attach a screenshot of the loading skeletons? I am unable to reproduce this bug. Thanks

**Comment by IamEzio** [comment]
Hi @Hatilar420! I started working on this issue yesterday and since a week had been passed since your last comment, I took the liberty to open a PR myself. Sorry if it caused any inconvenience.

@seancolsen Please take a look at PR #2420. Thanks!

**Comment by faraz16iqbal** [comment]
@kgodey this issue has been inactive for a while. Can I pick this up?

**Comment by seancolsen** [comment]
@faraz16iqbal no, this issue is active in the linked PR, #2420
