### ISSUE TITLE
Show focus indicator for boolean input in record selector

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2352]
## Steps to reproduce

1. Set up a table with a boolean column.

1. Open the record selector for that table (e.g. "Find a Record" from the Schema Page)

1. Observe that other columns in the table have inputs below the column header which show a thick blue border when focused.

    ![image](https://user-images.githubusercontent.com/42411/214419476-f259fa11-c5d6-4b1d-826b-169488fa585f.png)

1. Expect the boolean input to display a similar focus indicator, but observe that when it's focused it hardly changes appearance at all.

## Related tickets

- We have #1918 for improvements to keyboard behavior _after_ the input is focused.

**Comment by Sauvic016** [comment]
Hi  I would like to work on this issue ,can you please assign it to me.

**Comment by seancolsen** [comment]
Sure @Sauvic016 please go ahead and begin work. We're not currently assigning tickets to community contributors but you're welcome to submit a PR.

**Comment by azr-arch** [comment]
i am trying to run frontend locally, vite server runs but doesnt working on local host

**Comment by seancolsen** [comment]
@azr-arch you can ask for help on [Matrix](https://wiki.mathesar.org/en/community/matrix)

**Comment by seancolsen** [comment]
@Sauvic016 We made some changes yesterday to our [Contributor Guide](https://wiki.mathesar.org/en/community/contributing) and now we are assigning tickets to community contributors, so I'm assigning this ticket to you. If we don't see any progress in 1 week (from today), I'll unassign it. If you need more time you can comment here to give us an update and let us know you're still working on it. Thanks for your help!

**Comment by Sauvic016** [comment]
Thanks for assigning , but I'm sorry I wont be able to work on this . Please assign it other contributors.

**Comment by SaraSaadoun** [comment]
Hello, after working on this issue for hours, here is what I have reached in case it may help others to solve this.

I think this is because the field type for "Boolean" field is button, so focus will not work in this case.

**Comment by Sukshan** [comment]
@Anish9901 please assign this issue to me if no one is working on it

**Comment by Anish9901** [comment]
Assigned to you @Sukshan. Thanks!

**Comment by Hatilar420** [comment]
Hi @Anish9901 , can i work on this if no one is working on it ?

**Comment by Anish9901** [comment]
Assigned to you @Hatilar420. Thanks!

**Comment by yash7raut** [comment]
@Anish9901, Can I work on this issue?

**Comment by Anish9901** [comment]
@yash7raut This issue is already assigned to @Hatilar420. Please look through other issues to work on.

**Comment by yash7raut** [comment]
Ok @Anish9901
