### ISSUE TITLE
Remove passing --input-element-text-align as style variable and pass it as a prop

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2353]
## Description
* We currently pass `--input-element-text-align='right'` in three components.
 - FormattedInputCell.svelte
 - MoneyCellInput.svelte
 - NumberCellInput.svelte
* Since passing down a css variable creates a div element that covers the component, this leads to global styles not working as expected.
* Notice:
  * Filters:
![Screenshot 2023-01-25 at 3 08 16 AM](https://user-images.githubusercontent.com/11850603/214426880-bb65f788-3c07-4a63-861c-ca1681a5a5dd.png)
  * The input has a distinct border. Notice that this does not happen to text inputs.
  * Data Explorer transformations:
![Screenshot 2023-01-25 at 3 08 58 AM](https://user-images.githubusercontent.com/11850603/214426962-c25d7d5c-d2f2-49d6-9636-46796dfaa911.png)
  * Notice that there is no gap for the input. Text inputs work as expected with the gap.

I'd like to remove passing down css props directly, for this issue we'll have to remove: --input-element-text-align='right'.

Instead,
1. we can have a different prop for horizontal text alignment,
2. or have a prop called `cssVariables` that can get css variables and place it on the elements. This way we'll have more control instead of a div being placed automatically. Refer LayoutWithHeader component, where we use such a method.

I'd prefer option 2.

**Comment by pavish** [comment]
@kgodey I'm placing this in Usability testing blockers because this is quite noticable.

**Comment by pavish** [comment]
@rajatvijay I'm assigning this to you since you needed issues and this one blocks/will-come-up in usability testing.

**Comment by kgodey** [comment]
Moving this to launch blockers, this isn't a large enough issue to block usability testing, even if it is noticeable.

**Comment by seancolsen** [comment]
@rajatvijay Yes, your understanding of pattern (C) is correct. I'm fine with using (B) as long as we extract that logic into a utils function.
