### ISSUE TITLE
Make column type inference optional

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#2358]
Root issue: #2346

Currently, the frontend makes it obligatory to perform type inference during import. This can be a blocking bug if 

1. the type inference takes too long to perform (to be addressed by https://github.com/centerofci/mathesar/issues/2359 and https://github.com/centerofci/mathesar/issues/2347),
2. and type inference is a synchronious operation tied to a HTTP transaction that is subject to timeouts (it currently is) (tracked by https://github.com/centerofci/mathesar/issues/2360).

We can improve Mathesar's inference speed, but we can't ever make 1 impossible, because a user can always just give you a workload that's too big. Fixing 2 would get rid of timeouts and would be a significant improvement, but the user could still present such a big workload that he might be stuck waiting for it to finish for a very long time. Therefore, making type inference during importing optional is essential to a robust import process.

## Similar to

- #3051

**Comment by dmos62** [comment]
@seancolsen would you care to pick this issue up?

This issue seems to be the most direct and easy way to make the import process robust. It also seems to be largely frontend work, and it would be a workaround for the [import timeout problem](https://github.com/centerofci/mathesar/issues/2995).

In https://github.com/centerofci/mathesar/issues/2346 I track additional ways to improve imports. Making type inference a per-column operation (one HTTP transaction, one column type inferred) is the next thing I'd do, but that involves significantly more work and coordination.

**Comment by seancolsen** [comment]
I'm working on this now.

(@dmos62 my approach has shifted a tiny bit since our call earlier today.)

I'm planning to open a draft PR soon which will have screenshots of the app withe UI that I'm proposing. We can continue the discussion about how best to solve the larger problems at that point because we'll have a concrete example of some UX to reference.
