### ISSUE TITLE
Make all sidebar panes resizable

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2362]
## Current behavior

- We have sidebar pane in the following locations

    - The table inspector

        ![image](https://user-images.githubusercontent.com/42411/214592856-0e3a618c-769a-421a-8da4-b9c3ed59f484.png)

    - The exploration inspector

        ![image](https://user-images.githubusercontent.com/42411/214593044-52a9a337-5013-4c31-97bf-b6e73cb6ad6a.png)

    - The left pane in the exploration editor

        ![image](https://user-images.githubusercontent.com/42411/214593271-2080398e-c3da-4956-880a-5cfc8bd27d20.png)

- The width of these sidebars is currently hard-coded and cannot be adjusted by the user.

## Desired behavior

- All sidebars can be re-sized.

- The re-sizing UX is similar to that when resizing columns. The styling of the resizing grip should match that of the column resizing and should extend the full height of the side panel.

- After being resized, the new width is not persisted anywhere. We have #2387 for that.

@kgodey @ghislaineguerin @pavish @rajatvijay how does my proposed UX sound?

**Comment by kgodey** [comment]
@seancolsen Your UX sounds fine. I assume we'll want to have some sort of minimum width, though.

**Comment by seancolsen** [comment]
@kgodey Good point about the mid-width. The column resizing is implemented to have a min-width. Anyone implementing this ticket can look at how that's done and follow the pattern there.

**Comment by raunak-dev-edu** [comment]
Hello @seancolsen ,
I would like to work on this issue. Could you please assign it to me?

**Comment by rajatvijay** [comment]
@seancolsen looks good to me. I would also preserve a max-width, letting a user pull it completely to the other end and make it full width won't make much sense.

**Comment by pavish** [comment]
@seancolsen The proposal sounds good to me.

> After being resized, the new width is persisted in local storage, per sidebar type (i.e. three separate settings, per our three separate sidebar types). 

We would have to make this a separate issue, I don't think it should be coupled with this issue. We'll need a common architecture to store such information.

**Comment by seancolsen** [comment]
@pavish Sounds good. I've split this ticket into two. Here we'll only cover resizing. Then in #2387 we'll cover persistence (and I've marked that ticket as restricted to maintainers so that we may decide on the architecture).

**Comment by seancolsen** [comment]
Thanks @raunak-dev-edu. I've assigned this ticket to you. I see you have [one other ticket](https://github.com/centerofci/mathesar/issues/2378) assigned to yourself as well. Per our [Contributor Guide](https://wiki.mathesar.org/en/community/contributing), you'll have one week to make progress on these tickets before we may unassign them so that others may take them up.

**Comment by raunak-dev-edu** [comment]
Hello @Anish9901, I have been trying to fix this issue since last week but cannot do it within the time limit. I understand following the Contributor Guidelines, you have unassigned this to me. But I want to fix this issue as soon as I can. For now, you can leave it to unassign. Once I figure out the solution. I will first tell you to assign and then apply a new PR for this.
Thanks

**Comment by Anish9901** [comment]
Hey @raunak-dev-edu, feel free to open a PR for this issue. I'll reassign it to you if we don't get a fix/PR from other contributor(s) sooner.

**Comment by raunak-dev-edu** [comment]
Thank you @Anish9901

**Comment by RyanWalker277** [comment]
Hey @Anish9901! I saw that @raunak-dev-edu was assigned an issue but had to drop it due to being busy with a tech competition. I'm interested in fixing the issue and was wondering if you could assign it to me instead. I will try to prepare a patch asap. Let me know if that's possible!

**Comment by Anish9901** [comment]
Assigned to you @RyanWalker277. Thanks!

**Comment by Anish9901** [comment]
Unassigned due to inactivity by @RyanWalker277.

**Comment by kgodey** [comment]
@Anish9901 there is a PR for this, https://github.com/centerofci/mathesar/pull/2607

**Comment by Anish9901** [comment]
@kgodey sorry didn't notice that it didn't show up in project view. Reassigning @RyanWalker277

**Comment by charvimehradu** [comment]
Alright thankyou

**Comment by pavish** [comment]
@RyanWalker277 Thanks for reaching back, I'll unassign you from the ticket.

> I would request to keep the PR open inside anyone else wants to work on this and needs some reference

Closing the PR does not delete it from the repository. Everyone would still be able to see the PR, so they can still use it for reference.

**Comment by charvimehradu** [comment]
yes

**Comment by charvimehradu** [comment]
Greetings everyone,
I wanted to bring up that I've been trying to solve this issue, but I haven't been able to figure it out on my own. I'm wondering if any of you might be able to offer some guidance or assistance.
I've been proceeding with the issue as best as I can, but I've hit a roadblock and could really use a little help. I'm considering making a pull request and addressing it there for further discussion. If that's not the best approach, I'd appreciate any suggestions on how to proceed.
Thank you for your time and help with this. I look forward to hearing your thoughts.

**Comment by rajatvijay** [comment]
@charvimehradu thanks for reaching out. 

>I'm considering making a pull request and addressing it there for further discussion.

This sounds good.
