### ISSUE TITLE
Dropdown overflow makes column selection impossible on short viewports

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2364]
## Steps to reproduce

The following UI locations have dropdowns which don't scroll as the list of columns gets too long to fit within the viewport

- The grouping column select

    ![image](https://user-images.githubusercontent.com/42411/214597965-9e1f0ebd-b16d-4e49-9e84-6e776f35457f.png)

- The record summary template column select

    ![image](https://user-images.githubusercontent.com/42411/214598572-086873d6-fcfb-411e-82d4-4d2b2d449fc2.png)

- The constraint columns multi-select

    ![image](https://user-images.githubusercontent.com/42411/214599272-a2f1a683-d46f-4799-88b6-fd18ac79e4d9.png)

You can split this into multiple issues if you like, submitting a PR to fix just one of the above problems

**Comment by Mayuresh0072** [comment]
@seancolsen @Hello, I want to work on this issue. Please assign me this issue. Thanks.

**Comment by seancolsen** [comment]
Sure, go ahead, @Mayuresh0072

**Comment by seancolsen** [comment]
@Mayuresh0072 We made some changes yesterday to our [Contributor Guide](https://wiki.mathesar.org/en/community/contributing) and now we are assigning tickets to community contributors, so I'm assigning this ticket to you. If we don't see any progress in 1 week (from today), I'll unassign it. If you need more time you can comment here to give us an update and let us know you're still working on it. Thanks for your help!

**Comment by Mayuresh0072** [comment]
Thanks for assigning issue , I have started working on the issue. I will update about the progress as soon as I complete it.

**Comment by AshishPandagre** [comment]
Hey @seancolsen
I would like to work on this. Please assign it to me.

**Comment by AshishPandagre** [comment]
Hi, so I was working on this, and there are essentially 2 ways to fix this-

-> simply, add `max-height: 400px` and `scroll-y: auto` on the DropdownMenu.
Obviously, with this method, the dropdown will always have a height of 400px.

-> If we want the dropdown menu to stretch to the end of viewport (instead of 400px height always), we'd have to do it in a javascript manner, by setting dropdownMenu's height to be `clientHeight - offsetTop_of_dropdown`.

@seancolsen, let me know, which one should we go ahead with.

**Comment by seancolsen** [comment]
@AshishPandagre it's hard to tell without looking at a PR and testing out the functionality to see if various edge cases are handled appropriately. Please use your best judgement, taking into account the overall goal of delivering a high-quality product with a clean UX. Then we can sort out any issues with your implementation during PR review.

**Comment by Harshkumar77** [comment]
Hey, you can assign me the issue if its open.

**Comment by Anish9901** [comment]
Assigned to you @Harshkumar77. Thanks!

**Comment by manik-dhanjal** [comment]
Hey @Anish9901,
can you please assign this issue to me it is simple CSS change will not take much time.

**Comment by kgodey** [comment]
@manik-dhanjal This is assigned to @Harshkumar77. If we don't see activity in the next few days, we'll make this available for assignment again.

**Comment by manik-dhanjal** [comment]
Thanks for assigning

**Comment by Hatilar420** [comment]
Hi @kgodey, can I take this issue?

**Comment by kgodey** [comment]
Assigning this to @manik-dhanjal due to inactivity by @Harshkumar77.

**Comment by manik-dhanjal** [comment]
Thank you @kgodey
