### ISSUE TITLE
Add more space at the bottom of the Schema Page

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2367]
On the Schema Page, when the viewport is short enough to require vertical scrolling, we should have some more space between the bottom of the tables list at the bottom of the viewport.

![image](https://user-images.githubusercontent.com/42411/214620528-d1e7233e-45f3-4b6e-8558-9f710d4b17fc.png)

**Comment by Mayuresh0072** [comment]
@seancolsen  Hi, I want to work on this issue and contribute. Please assign me this issue. Thanks.

**Comment by PraddyumnYadav** [comment]
I Am Trying to work on this issue Currently but i am unable to understand the CodeBase here Can You Please Give Me some Tips related to this.

**Comment by seancolsen** [comment]
@Mayuresh0072 go ahead. I see that you've also [commented on another ticket](https://github.com/centerofci/mathesar/issues/2364#issuecomment-1403977543) too. Please work on a maximum of two tickets at a time. Thanks. We are currently not using GitHub's "assign" feature with community contributors, but you're welcome to submit a PR for this ticket when you have completed the work.

**Comment by seancolsen** [comment]
@PraddyumnYadav let's give @Mayuresh0072 a chance to work on this one first. You're welcome to look for another ticket to work on. If you need help get started you can ask in Matrix. Generally speaking, the core team has very little capacity to provide assistance, so I suggest formulating clear and specific questions which other people can answer asynchronously.

**Comment by PraddyumnYadav** [comment]
> @PraddyumnYadav let's give @Mayuresh0072 a chance to work on this one first. You're welcome to look for another ticket to work on. If you need help get started you can ask in Matrix. Generally speaking, the core team has very little capacity to provide assistance, so I suggest formulating clear and specific questions which other people can answer asynchronously.

Can You Please Tell me What is Matrix.

**Comment by seancolsen** [comment]
@Mayuresh0072 We made some changes yesterday to our [Contributor Guide](https://wiki.mathesar.org/en/community/contributing) and now we are assigning tickets to community contributors, so I'm assigning this ticket to you. If we don't see any progress in 1 week (from today), I'll unassign it. If you need more time you can comment here to give us an update and let us know you're still working on it. Thanks for your help!

**Comment by Mayuresh0072** [comment]
Ok , sure.

**Comment by IamEzio** [comment]
@seancolsen I'd like to work on this. Thanks!

**Comment by manik-dhanjal** [comment]
Hi @seancolsen, I would like to work on it can you please assign it to me?

**Comment by kgodey** [comment]
There's already a PR for this @manik-dhanjal
