### ISSUE TITLE
Design for boolean data type

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#237]
## Problem

Users will want to store booleans. We should allow them to do so and provide an intuitive user experience for them.

## Proposed solution

We need a design for the following functionality for the boolean data type:
- Displaying columns of this type in tables (do we want to provide different options, such as checkboxes / or custom text for "yes" or "no"?)
- Creating a new column with this data type
- Changing an existing column to this data type (including error states)
- Showing non-technical users a friendly name for this data type. (The underlying Postgres data type will be `BOOLEAN`)

### Options

Columns of this type will have the following options:

#### Common to all Columns
- Default value (this will be the default value of the column if the user doesn't enter anything)
- Allow empty values (whether the column is nullable)

**Note**: Unique doesn't make sense here as an option since booleans only have two values

### Grouping
There's no custom grouping for booleans, just the regular value based grouping should be fine since there's only two possible values plus null.

### Filtering
Columns of this type will support the following filters:
- is
- is not
- is empty
- is not empty

**Comment by ghislaineguerin** [comment]
Specs posted on https://wiki.mathesar.org/en/design/specs/boolean-data-type
