### ISSUE TITLE
Navigate to linked record via grouping header row

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2375]
## Current behavior

- For foreign key columns, we have an entry in the cell context menu allowing users to navigate to the table page for the linked record.

    ![image](https://user-images.githubusercontent.com/42411/214890211-a3758351-4f61-489e-81a2-5fe6e644eb48.png)

- When the table page is grouped by a foreign key column, we display the record summary in the group header row

    ![image](https://user-images.githubusercontent.com/42411/214625501-00be3d88-fcda-4dc8-be84-265eddbb0b54.png)

## Desired behavior

- Those record summaries in the group header row should hyperlink to the record page using the same URL found within that context menu link.

- The hyperlinks should display with text underlined to cue the user that they are clickable.

**Comment by rohitguptaa22** [comment]
Hi, I am professionally a frontend developer at junior level. I have never contributed towards open source and it was always tempting. I may be able to understand this issue and think this will be a good start
Please assign this task to me

**Comment by anzal1** [comment]
can i work on this issue @seancolsen ?

**Comment by silentninja** [comment]
Thanks @anzal1 I have assigned the issue to you

**Comment by Aadijindal07** [comment]
is it open if yes i would love to contribute kindly assign

**Comment by Anish9901** [comment]
Unassigning due to inactivity. @Aadijindal07 If you are still up for this issue I can assign it to you.

**Comment by Hatilar420** [comment]
Hey @Anish9901, Can i work on this ?

**Comment by Anish9901** [comment]
Go ahead @Hatilar420 I've assigned you.

**Comment by ShravaniRoy** [comment]
Hi @Anish9901 , I am a first-time contributor. If the issue remains inactive, kindly assign it to me.
