### ISSUE TITLE
Clarify that the record selector only displays the first 10 records

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2378]
## Current behavior

- The Record Selector shows the first 10 records in a table

    ![image](https://user-images.githubusercontent.com/42411/214914657-828c91b9-9021-483f-b53b-6b06eb21eba8.png)

- Users may be confused when first encountering this because there is no way to scroll or paginate to see more records. Some users might think that the table only contains 10 records

## Desired behavior

- When fewer than 10 records are shown, then the behavior is the same as current.

- When 10 records are shown:

    - If no filters are applied, the following text displays at the bottom right of the window

        > The first 10 records are shown. Filter to see more.

        It should use `color: var(--color-text-muted);` and `font-size: var(--text-size-small);`

    - If at least one filter is applied, then the following text displays

        > The 10 best matches are shown. Continue filtering to see more.

        ![image](https://user-images.githubusercontent.com/42411/214915790-c81839ba-99ba-4441-aa73-d05cb2ff4f99.png)

        It should display at the bottom right of the window, right-aligned and vertically centered with respect to the "Create Record" button.

@kgodey Does this sound okay to you? If so, we can un-draft this and label it as "good first issue" and "help wanted".

**Comment by kgodey** [comment]
Sounds good @seancolsen

**Comment by Hatilar420** [comment]
Hi @seancolsen @kgodey ,
Can i work on this ?

**Comment by raunak-dev-edu** [comment]
Hello @seancolsen @kgodey 
I would like to work on this issue. Could you please assign it to me?

**Comment by seancolsen** [comment]
Thanks @raunak-dev-edu

**Comment by maskros-m** [comment]
Hi @seancolsen @kgodey @raunak-dev-edu 
Would there be a possibility for me to work on this with raunak-dev-edu if they are not against it? This is for a school assignment and I'm training in front-end development too, so I'd really love some first experience. If not, it's completely fine too.
Thank you for reading!

**Comment by seancolsen** [comment]
@maskros-m That sounds unconventional but acceptable if you two are able to work out an agreement to collaborate. Just please coordinate within a channel limited to the two of you so that you minimize notifications to core team members. You can also search for other tickets to work on by following the steps in our [Contributor Guide](https://wiki.mathesar.org/en/community/contributing). The core team has very limited capacity to provide assistance to community contributors.

**Comment by raunak-dev-edu** [comment]
Hello @seancolsen . This issue was assigned to me and I had also made PR before @SEGRR. But still, Instead of merging my PR #2405, you have merged his PR. May, I know why?

**Comment by seancolsen** [comment]
Apologies, @raunak-dev-edu. I did see both these PRs before merging the other one.

Ideally we'd like to avoid having two PRs for the same ticket, which is why our contribution guidelines instruct community contributors to avoid working on tickets that are currently assigned or that have open PRs. So ideally @SEGRR would have chosen a different issue to work on. We have a lot of prospective GSoC contributors right now and it leads to more chaos than we're able to gracefully accommodate. 

Your PR and the other one both needed some follow-up work before being merge-ready. The other PR just needed _less_ work so I chose to merge it for the sake of my time. If we had more time, I would have worked with you to get yours merged since you opened it first. However, the core team unfortunately has very little bandwidth right now to manage community PRs. If you plan to apply for GSoC, you can still count this PR as a contribution.

**Comment by raunak-dev-edu** [comment]
Thanks a lot @seancolsen
Its ok, I understand your problem. I am willing to apply gsoc23 in mathesar only as I am working on other issue too. This was my first PR so I get hurt but no way I understood your condition now and I am amazed with mathesar community for such a kind nature. Now, Its motivating me to contribute more in mathesar only. 
Thanks again for taking my this contribution as valid for applying in Gsoc'23.

**Comment by SEGRR** [comment]
I admit it was my mistake. Before starting work on this issue I didn't see it was assigned to @raunak-dev-edu . After I completed work I saw it was assigned. Still I created a PR.
I see my mistake and hope not to repeat again 😃
