### ISSUE TITLE
Design for Number data types

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#238]
## Problem

Users will want to store numbers. We should allow them to do so and provide an intuitive user experience for them.

## Proposed solution

We need a design for the following functionality for the number data type:
- Displaying columns of this type in tables
- Creating a new column with this data type
- Changing an existing column to this data type (including error states)
- Showing non-technical users a friendly name for this data type. (The underlying Postgres data type could be any one of these: https://www.postgresql.org/docs/current/datatype-numeric.html, it will be `NUMERIC` by default). 

### Options

Columns of this type will have the following options:

#### Specific to this Type
- Number type. Options are: integer, decimal, float, percentage, unknown/mixed (By default, "unknown/mixed" should be selected so that the user doesn't need to make a choice)
- If decimal is selected:
  - number of decimal points
  - number of digits before the decimal point
- if integer:
  - big int
  - small int
  - regular int   
- if float:
  - 6 decimal digits precision
  - 15 decimal digits precision
- if percentage:
  - number of decimal points 

We should make sure to present these options in a way that's helpful to people who know what they're doing and that non-technical people can ignore.

#### Common to all Types
- Default value (this will be the default value of the column if the user doesn't enter anything)
- Allow empty values (whether the column is nullable)
- Unique (whether the values in the column have to be unique, validated at the DB level)

### Grouping
Columns of this type will be able to grouped by:
- Range

We need to figure out how to show the appropriate ranges based on the data. e.g. if the data is numbers between 1 and 100, the ranges might be 1-10, 10-20, or even 0-1, 1-2, etc. but a range of 0-100, 100-200 wouldn't make sense. We should make some educated guesses but allow the user to choose different granularities of ranges.

### Filtering
Columns of this type will support the following filters:
- between
- equals
- does not equal
- greater than
- lesser than
- greater than or equal to
- less than or equal to
- is empty
- is not empty

## Additional Context
- We should support different number formats. Should we automatically figure this out by locale or have display options?
- Percentages should be displayed with a `%`

**Comment by mathemancer** [comment]
We'll want to think about how to handle calculated columns (which is in the roadmap) when the number types of the columns used in the calculation are different.

**Comment by ghislaineguerin** [comment]
Specs posted at: https://wiki.mathesar.org/e/en/design/specs/number-data-type

**Comment by ghislaineguerin** [comment]
Reopening issue to merge number and percentage types into a single type
