### ISSUE TITLE
Design for money data type

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#239]
## Problem

Users will want to store data that represents money. We should allow them to do so and provide an intuitive user experience for them.

## Proposed solution

We need a design for the following functionality for the money data type:
- Displaying columns of this type in tables
- Creating a new column with this data type
- Changing an existing column to this data type (including error states)
- Showing non-technical users a friendly name for this data type. (The underlying Postgres data type will be a custom type).

Columns of this type can be either our custom `MATHESAR_MONEY` type (which has more functionality) or the default `MONEY` type in the database. Most of the functionality will remain the same, but we cannot change the currency or decimal precision for the default `MONEY` type.

### Options

Columns of this type will have the following options:

#### Specific to this Type
- Currency
- Decimal precision

(Both of these should have pre-filled options)

#### Common to all Types
- Default value (this will be the default value of the column if the user doesn't enter anything)
- Allow empty values (whether the column is nullable)
- Unique (whether the values in the column have to be unique, validated at the DB level)

### Grouping
Columns of this type will be able to grouped by:
- Range

Please see #238 for notes about ranges.

### Filtering
Columns of this type will support the following filters:
- between
- equals
- does not equal
- greater than
- lesser than
- greater than or equal to
- less than or equal to
- is empty
- is not empty

## Additional Context
- Marking this as blocked by #238 since this is a numeric type and a lot of design decisions made there will impact this.
- #269

**Comment by ghislaineguerin** [comment]
Specs posted on: https://wiki.mathesar.org/en/design/specs/money-data-type
