### ISSUE TITLE
We should be able to create new admin users, upgrade existing users to admin

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2392]
## Description
* `is_superuser` is currently a readonly property in Users APIs.
* We should be able to set them while an admin is editing a user.
* Users (including super-users) should not be able to modify it's value for themselves.

**Comment by pavish** [comment]
@kgodey This needs to be on 'Launch blockers' since this is required by the UX for Users & Permissions.

**Comment by aagman945** [comment]
I would like to work on this

**Comment by kgodey** [comment]
Moved to launch blockers, @pavish. @aagman945 feel free to submit a PR, but since this is needed soon, we may reassign to a member of the core team if we don't see a PR for this in the next couple of days.
