### ISSUE TITLE
Use Watchtower for upgrades

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#2395]
We're switching from using our own [Update Companion container](https://github.com/centerofci/mathesar/issues/2072) to using [Watchtower](https://containrrr.dev/watchtower/), because our Update Companion lacks the ability to handle docker networking and we don't want to implement it ourselves.

```[tasklist]
## Setup Watchtower
- [ ] https://github.com/centerofci/mathesar/issues/2397
- [ ] https://github.com/centerofci/mathesar/issues/2399
- [ ] https://github.com/centerofci/mathesar/issues/2398
```

**Comment by kgodey** [comment]
@dmos62 Should we delete the update companion repo?

**Comment by dmos62** [comment]
@kgodey basically yes, but I'd prefer to keep it around a while longer in case I need some tid bit of information from it. Maybe let's wait until next week before we delete it.

**Comment by kgodey** [comment]
Okay, please let me know (by making an issue) when we should delete it. I'll need to remove it from our workflows in the main repo.

**Comment by dmos62** [comment]
Implemented.
