### ISSUE TITLE
UX and frontend implementation for upgrades

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#2396]
### Notes
- [Current Figma design](https://www.figma.com/file/xHb5oIqye3fnXtb2heRH34/Styling?node-id=3804%3A28864&t=HyNupYmgZ9PqjEGr-0)
- [Issue with user flow](https://github.com/centerofci/mathesar/issues/227)

### Tasks
- Finalize the user flow
- Request Figma UX changes if needed
- Implement the frontend (create additional GitHub issues if needed)

### Feasibility 
Watchtower, our docker image upgrade backend, doesn't report progress. The only progress reporting available to the frontend will be periodically calling some HTTP endpoint on the service container to check whether it is online or not.

The final UX should take this into account.

**Comment by Aadijindal07** [comment]
i would like to contribute so kindly assign

**Comment by kgodey** [comment]
This is not open for contribution, @Aadijindal07.

**Comment by kgodey** [comment]
Since we don't have any other issues for UX or frontend right now, I've repurposed this issue to cover all UX and frontend work for upgrade. @seancolsen Please update the issue after we have a finalized user flow.
