### ISSUE TITLE
Modify page routing to allow for any database name

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2402]
## Current behavior

- Many of our pages have URLs that begin with the database name.
- We also have routes that begin with things like `administration` and `auth`.
- Those routing rules produce an ambiguous routing grammar making it impossible to use Mathesar with a database named "administration" (for example).

## Desired behavior

We should change `/<db_name>/` to `/db/<db_name>`

**Comment by Aadijindal07** [comment]
To make the routing rules unambiguous, one possible solution would be to add a prefix, such as "/db/", before the database name in the URL. This way, even if the database name is "administration" or "auth", the URLs would still be clear and distinguishable. However, other options could also be considered, like using a different prefix, like "/data/", or using a different structure for the URLs altogether. It ultimately depends on the requirements and goals of the system.

I would like to get assign and help

**Comment by kgodey** [comment]
@Aadijindal07 this is restricted to maintainers. Please find an issue without a `restricted` label.

**Comment by pavish** [comment]
@kgodey This has been on my mind as well and I'd like to move this to launch blockers. We are sure to run into some issue from our users because of such restricted routes, and I think the fix should be small enough once we decide on the approach.

**Comment by kgodey** [comment]
@pavish I made the priority high, but I don't think this blocks launch. If we have time before launch, we can do it.

**Comment by silentninja** [comment]
@silentninja +1 from me. I have expressed my concerns about having a wildcard URL route capture in a few other discussions as well. In addition to the concerns expressed by @seancolsen, 

1. Having a wildcard URL leads to debugging nightmares, for example, if I mistyped a URL or if a particular route is configured incorrectly, we would end up getting a "Database not found" error instead of an incorrect URL error
2. This also leads to us having to be mindful of the order in which the URLs are placed on the backend.

**Comment by pavish** [comment]
> One possibility would be changing /<db_name>/ to /db/<db_name>, but we may want to consider other options as well

I think this sounds like a good solution. We should handle this issue sooner than later since the url change will affect users who bookmark links.

@seancolsen @silentninja What are your thoughts on this? Can we finalize this behaviour and mark the issue as ready?

**Comment by seancolsen** [comment]
Good call, @pavish. I un-drafted it.

**Comment by pavish** [comment]
I'm adding this as a nice-to-have for `0.1.2` since this seems to be an issue that we can fix quick and has high impact.

**Comment by silentninja** [comment]
> Can we finalize this behaviour and mark the issue as ready?

Yes
