### ISSUE TITLE
Remove "Short Name" field on user form

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2404]
I'd like to remove the "Short Name" field on the user form. In a [Matrix discussion](https://matrix.to/#/!xInuTkBwjXZXYatIlm:matrix.mathesar.org/$2e6ULgkergV1BZwlHxpNBNUKcG4W-bnetG9bApfg23M?via=matrix.mathesar.org&via=matrix.org) @kgodey said this was fine. It's an optional field so we can keep it in the API but just remove the form UI until we have a use-case for short names.

**Comment by pavish** [comment]
I'm assigning this to me because I made the changes needed for this in https://github.com/centerofci/mathesar/pull/2390. I did not notice that the issue was assigned to @seancolsen before making the changes.
