### ISSUE TITLE
Add version info to `common-data`

### ISSUE THREAD

**Issue by mathemancer** [centerofci/mathesar#2408]
## Problem

We need to give the front end info about what version of Mathesar is running, and what version is available.

## Proposed solution

We should add info about updates to the `common-data` blob. After discussing with @seancolsen , the info should be:

```json
{
  "current_release": "vX.x.x",
  "current_release_timestamp": "YYYYMMDDhhmmss",
  "newest_release": "vZ.z.z",
  "newest_release_timestamp": "YYYYMMDDhhmmss",
  "update_available": true,
}
```

## Additional context

This is going to likely replace having the front end call an API to figure out if there's an update available or not.

**Comment by dmos62** [comment]
If I understand correctly, this is about embedding current and newest release information in every view's render, and getting rid of the version/release-info endpoints.

There's a few problems here:

- one of the ways that frontend will be able to gauge upgrade progress is by querying for the backend's version; this makes that complicated (you'd prefer to check by querying an endpoint and not an html renderer);
- to get information about the newest release (which includes checking whether an update is available), which will be necessary to render an html view, you'll have to query github releases api; you could cache the result, but that's awkward.

I don't think that this is a good idea, unless I'm misunderstanding something. Also, why include version information with the `common-data` blob? Is it commonly needed information?

**Comment by mathemancer** [comment]
This might become more clear once the front end issue is written, but the goal is to:
- show the current version in the corner somewhere almost always, and
- Have a notification when the version is out of date.

Regarding the caching, I think the version checking for the back end should be completely detached from the requests from the front end. It should be either a django background process or (my preference) a cron job.



> * one of the ways that frontend will be able to gauge upgrade progress is by querying for the backend's version; this makes that complicated (you'd prefer to check by querying an endpoint and not an html renderer);

Maybe I'm missing the point here. The `common-data` is included in pretty much every page load. As far as checking on progress, the current concept is to keep the request open until it succeeds or fails. On the next page load, you'd immediately notice if the version was still out of date.

**Comment by kgodey** [comment]
I put my concerns about this plan in the related email thread.

**Comment by dmos62** [comment]
@seancolsen `Release.timestamp` should probably be `string | null`, since we don't hardcode that: it's fetched from a third-party API and might not be available.

**Comment by dmos62** [comment]
@mathemancer I think we need a way to trigger an immediate newest release check, so that we can have a check for updates button. A cron-job and having it in common-data is supplementary, in my eyes.

**Comment by mathemancer** [comment]
> @mathemancer I think we need a way to trigger an immediate newest release check, so that we can have a check for updates button. A cron-job and having it in common-data is supplementary, in my eyes.

What if they never click the button? Remember that the main reason for all this trouble is to strongly encourage updating frequently while we iterate quickly in the alpha stage.

**Comment by dmos62** [comment]
@mathemancer I think we're in agreement. The reason why the button is important for me is that it makes update checking feel more reliable, since it let's you be proactive about updates, which means you can feel in control when you want to feel in control. The notifications or badge is great in their own right, but if you don't have a way to be proactive about updates, the _power_-user might feel deprived.
