### ISSUE TITLE
Design for duration data type

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#241]
## Problem

Users will want to store durations. We should allow them to do so and provide an intuitive user experience for them.

## Proposed solution

We need a design for the following functionality for the duration data type:
- Displaying columns of this type in tables
- Creating a new column with this data type
- Changing an existing column to this data type (including error states)
- Showing non-technical users a friendly name for this data type. (The underlying Postgres data type will be `INTERVAL`). 

### Options

Columns of this type will have the following options:

#### Specific to this type
- Display options (whether to show days, seconds, etc.)

#### Common to all Types
- Default value (this will be the default value of the column if the user doesn't enter anything)
- Allow empty values (whether the column is nullable)
- Unique (whether the values in the column have to be unique, validated at the DB level)

### Grouping
Columns of this type will be able to grouped by:
- Range

Please see #238 for notes about ranges.

### Filtering
Columns of this type will support the following filters (same as Number):
- between
- equals
- does not equal
- greater than
- lesser than
- greater than or equal to
- less than or equal to
- is empty
- is not empty

The filter value should support different date formats as well as natural language like "an hour" or "2 days".

## Additional Context
- Marked as blocked until ranges are figured out in #238.

**Comment by ghislaineguerin** [comment]
Specs posted on https://wiki.mathesar.org/en/design/specs/data-type-duration
