### ISSUE TITLE
Warn live demo users that Mathesar does not work on mobile devices

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2413]
## Problem

1. When I log in to the demo site on my phone, I initially get the impression that Mathesar is designed with mobile devices in-mind because the login page works great on a small screen.

    <img src="https://user-images.githubusercontent.com/42411/216607439-6d864b00-f125-4402-87ee-c71552277b4b.jpg" alt=screenshot width=300 />

1. Then when I navigate to a table page, Mathesar is basically unusable.

    <img src="https://user-images.githubusercontent.com/42411/216606655-220f70d1-8f10-401a-875b-c074f7d3ea25.jpg" alt=screenshot width=300 />

    ![Screenshot_2023-02-03-08-28-33-05_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/42411/216615249-d92b2094-eb06-46d0-a369-57e89968d3ec.jpg)

1. A new user viewing the table page on a mobile device may conclude that their experience of the table page is our _intended_ experience of the table page, leaving them with a poor opinion of Mathesar

## Ideas

- This is a tricky problem to solve though. There are a number of separate issues with mobile devices:

    - (A) in portrait mode, the screen is too narrow
    - (B) in landscape mode, the screen is too short
    - (C) without a mouse, the user has no way to scroll the sheet (#2363)

- For (A) and (B), I think we need to catch users with small screens on the login page and somehow convince them to move to a device with a larger screen before logging in. I imagine we'd still let them log in on a small screen, but we'd first display some sort of warning to make it very clear that their device is unsupported.

    I would see us doing this by inserting a warning box above the "Live Demo Mode" box. We'd use CSS to show the box only when the viewport is short or when the viewport is narrow. I'm not sure of the exact breakpoints, but we could tweak them as-needed. The copy might be something like:

    > ⚠️ **Unsupported Device** ⚠️
    >
    > Mathesar is a spreadsheet-like application with a rich UI that does not yet function well on screens this small. Improved support for mobile devices is on our [roadmap](https://mathesar.org/roadmap.html). In the mean time, we encourage you to try Mathesar on a device with a larger screen.

- Some users (e.g. my mom) use a laptop with a touch screen and do all their scrolling via touch. For them, there's basically nothing we can do for (C) short of fixing #2363. Users on tablets will have the same problem, but there might be more we can do at the login screen by [detecting the absence of a mouse](https://stackoverflow.com/questions/7838680/detecting-that-the-browser-has-no-mouse-and-is-touch-only) and displaying a warning.

@kgodey I think this belongs in the "Release blockers" milestone, but I know you are guarding that milestone tightly, so I've not assigned a milestone. I'll leave the decision to you, but my recommendation is that we treat this issue as a must-have before we attempt any sort of publicity. Personally, I only ever read Hacker News on my phone.

**Comment by kgodey** [comment]
I agree this makes sense in launch blockers; it's a small fix with a big impact. Please thank Libby for being an (inadvertent) usability tester!

**Comment by AshishPandagre** [comment]
https://user-images.githubusercontent.com/53047854/216982634-6f7c12ab-fb0d-4637-9f85-8675cb00e941.mp4

Has this issue been fixed ??

**Comment by kgodey** [comment]
@AshishPandagre Mathesar needs a lot of work before it's usable on mobile devices, we don't plan to fix it before the first release.

**Comment by IamEzio** [comment]
@seancolsen I'd like to work on this issue. Please assign this to me. Thanks!

**Comment by seancolsen** [comment]
@IamEzio please see our [Contributor Guide](https://wiki.mathesar.org/en/community/contributing). Issues marked as "restricted" are not suitable for community contributors.
