### ISSUE TITLE
Unable to create a schema in the browser while running in the development environment 

### ISSUE THREAD

**Issue by Aditramesh** [centerofci/mathesar#2415]
## Description
When local environment is set up and run using `docker compose  up` ,i am unable to create a schema via the browser.I am getting an internal server error with the following description ,"When making an XHR request, the server responded with an error, but the response body was not valid JSON."

## Expected behavior
User should be able to create schema

## To Reproduce
1.Clone repository at `master` at  https://github.com/centerofci/mathesar/commit/8f47f3412467eee4a2e899845392194484e33232
2.Follow the steps to set the local environment 
3.go to the web page 127.0.0.1:8000
4.click on the new schema icon
5.once submit button is clicked the following error shows up,"When making an XHR request, the server responded with an error, but the response body was not valid JSON."

## Environment
 - OS:macos
 - Browser: chrome

**Comment by kgodey** [comment]
@Aditramesh Could you please add the details of the backend / API error and the steps you ran while setting up the project locally?

**Comment by Aditramesh** [comment]
@kgodey i was getting a 500 internal server error,with the following message "When making an XHR request, the server responded with an error, but the response body was not valid JSON."

steps followed were exactly the ones given in docs
1.installed docker
2.copied the .env file using the command given in docs
3.ran the command docker compose up
 i could fix the issue by changing 
MATHESAR_DATABASES=(mathesar_tables|postgresql://mathesar:mathesar@mathesar_db:5432/mathesar) in .env file to 
MATHESAR_DATABASES=(mathesar_tables|postgresql://mathesar:mathesar@mathesar_db:5432/mathesar_**django**),once i did this it works fine and a new schema can be added

**Comment by varun7singh** [comment]
![image](https://user-images.githubusercontent.com/73738410/217060908-31e98d51-b9ea-489d-b4ff-99a4e5699ff3.png)
this is the response sent

**Comment by Anish9901** [comment]
@Aditramesh @varun7singh Actually the mathesar_django database is intended to be used for migrations created by Django.
To fix the above problem please follow these steps:
1. Execute `docker-compose up`
2. Execute `docker exec -it mathesar_db psql -U mathesar -d mathesar_django` in another terminal instance.
3. Execute `CREATE DATABASE mathesar;` in the psql shell you just created.
4. Revert the .env file to the original. 
5. Restart the docker container and visit http://localhost:8000

You should see a public schema already present.

**Comment by varun7singh** [comment]
@Anish9901 yeah works
