### ISSUE TITLE
Make header css common

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2416]
## Description
* We have a fair share of typography related css which are placed in components, which leads to inconsistencies across the app.
* We'll need a set of global typography related css classes which we can use.
* For eg.,
  *  Refer [this comment](https://github.com/centerofci/mathesar/pull/2390#discussion_r1092323637) for inconsistencies in headers across pages due to per-component css.
  * We also have headers in table page and exploration pages.
  * We'll need a set of global css classes for headers, which we can then use within the components.
* ~~Whoever takes this up **should also go through the product for other places with the same issue as the headers**, mention them in the comments, get approval from maintainers, and fix them in their PR.~~ This part can be taken up individually as issues are raised. 

Update:
* This issue is limited to headers, and typography related changes can be taken up incrementally as we make our design system more concrete.

**Comment by Aadijindal07** [comment]
@pavish i will like to contribute can you provide some more information

**Comment by yuviS003** [comment]
@pavish I would like to contribute so kindly assign me

**Comment by pavish** [comment]
@Aadijindal07 Go ahead, I've assigned this issue to you.

> if possible please provide some more information it would be very helpful.

Please ask more specific questions so that I can help you out better. I'd suggest you to take a look at the codebase and play around with it to understand the issue.

Note that if we don't receive a PR on this in a week's time, we may have to un-assign you from the issue.

@yuviS003 I'm assigning this issue to @Aadijindal07 since they commented first. Please feel free to look for another open issue.

**Comment by Anish9901** [comment]
Unassigned due to inactivity.@yuviS003 I can assign this issue to you if you are still up for it.

**Comment by Hatilar420** [comment]
Hey @Anish9901 , can i take this up if no one is working on it ?

**Comment by Anish9901** [comment]
Assigned to you @Hatilar420. Thanks!

**Comment by Hatilar420** [comment]
Hey @pavish, I see many declarations for `font-size` and `font-weight` which have various different values and some have similar values. Are there any standard values for different typographies in Mathesar?

**Comment by Hatilar420** [comment]
Hey @pavish, I've opened a PR for this issue, which only adds common typographies for the header element. Please review the PR and let me know if the folder structure and overall changes are okay. So I can proceed with fixing the rest of the inconsistencies in the codebase.
Thank you.

**Comment by faraz16iqbal** [comment]
Hey @pavish, I see that this issue has been stagnant for the past 2 weeks. If this has not been resolved yet, can I work on it?

**Comment by Hatilar420** [comment]
Hi @faraz16iqbal, i am still working on this issue. Just needed to approve some changes before continuing further. 
Thanks

**Comment by faraz16iqbal** [comment]
@Hatilar420 alright, thanks for informing!

**Comment by varshadr** [comment]
Hi @pavish ! Can I work on this issue?

**Comment by rajatvijay** [comment]
@varshadr Sorry but no since @Hatilar420 already has an open ongoing PR for this https://github.com/centerofci/mathesar/pull/2516
