### ISSUE TITLE
Design for usage of Foreign Key constraints

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#243]
## Problem

Relational databases involve relationships between tables. We should provide an intuitive user experience for users seeking to create relationships between data in two different tables.

## Use Case
Imagine a scenario where the user is creating a database of movies. For the purposes of this issue, unless specified otherwise, let's assume that all movies have a single director. The user has two tables in the database. 

#### Movies
| ID | Title | Release Year | 
|-|-|-|
| 1 | Taxi Driver | 1976 |
| 2 | Sense and Sensibility | 1995 |
| 3 | Silence | 2016 |
| 4 | Gemini Man | 2019 | 

#### Directors
| ID | Name | Date of Birth | 
|-|-|-|
| 1 | Martin Scorsese | 1942-11-17 |
| 2 | Ang Lee | 1954-10-23 |

They now want to link each movie to its director.

### Creating New Links

- The user is browsing the **Movies** table and wants to add a "director" column to the movie table that pulls in directors from the **Directors** table.
  - They should be able to add a new column and create a foreign key constraint to the **Directors** table.
- The user is browsing the **Directors** table and wants to be able to link each director to the movies they've made.
  - We should guide them towards going to the **Movies** table instead and setting up the link there. 
- The user realizes that sometimes movies have multiple directors and they want to support mapping movies to multiple directors (from either the **Movies** or **Directors** tables)
  - We should guide them towards setting up a mapping table between movies and directors.

### Adding a FK to an Existing Column
- Users can add a foreign key to an existing column that has data in it as long as the data matches the data in the corresponding column of a related table. If the data does not match, the operation will fail and we should show the user an error message.

### Viewing Existing Links
The user imports an existing database that has foreign keys set up already and wants to see it reflected correctly within Mathesar.

#### Scenario 1: Single column FK linked to primary key of related table

Imagine an altered **Movies** table with the following structure. The "Director ID" column has a FK constraint that is linked to the "ID" column of the **Directors** table.

| ID | Title | Release Year | Director ID |
|-|-|-|-|
| 1 | Taxi Driver | 1976 | 1 | 
| 2 | Sense and Sensibility | 1995 | 2 |
| 3 | Silence | 2016 | 1 | 
| 4 | Gemini Man | 2019 | 2 | 

#### Scenario 2: Single column FK linked to non-primary key column of related table

Imagine an altered **Movies** table with the following structure. The "Director Name" column has a FK constraint that is linked to the "Name" column of the **Directors** table.

| ID | Title | Release Year | Director Name |
|-|-|-|-|
| 1 | Taxi Driver | 1976 | Martin Scorsese | 
| 2 | Sense and Sensibility | 1995 | Ang Lee |
| 3 | Silence | 2016 | Martin Scorsese | 
| 4 | Gemini Man | 2019 | Ang Lee | 

#### Scenario 3: Multi-column FK linked to multiple columns of related table

Imagine an altered **Movies** table with the following structure. There is a multi-column foreign key set up for the "Director ID" and "Director Name" columns, they are linked to the "ID" and "Name" columns of the **Directors** table.

| ID | Title | Release Year | Director ID | Director Name |
|-|-|-|-|-|
| 1 | Taxi Driver | 1976 | 1 | Martin Scorsese | 
| 2 | Sense and Sensibility | 1995 | 2 | Ang Lee |
| 3 | Silence | 2016 | 1 | Martin Scorsese | 
| 4 | Gemini Man | 2019 | 2 | Ang Lee |

### Editing data in columns with FKs
- It seems like a good idea to allow users to see a preview of the data in the related table so that they can identify data.
  - e.g. users may want to see the director's name instead of director ID in the Movie table, even though they should use the director ID to set up the foreign key.
- When adding new data to a column with a foreign key, it seems like there should be some sort of autocomplete to allow them to find data easily. There may be millions of rows in the related table.
- We may want users to be able to add data in the related table while editing a foreign key? For example, imagine adding a new record to the **Movies** table:

| ID | Title | Release Year | Director ID |
|-|-|-|-|
| 5 | Anatomy of a Murder | 1959 | - | 

Now you want to add the director for this movie, but "Otto Preminger" is not in the **Directors** table. It would be inconvenient for you to have to navigate to the **Directors** table and add the director, it would be nice to be able to add a new one directly from the **Movies** table. However, keep in mind that **Directors** may have many required fields that are not visible on **Movies**, so we need a way to edit the whole related record.

## Technical Design Notes
- The user should be able to select which column from the other table should be used as the foreign key. By default, we should guide them towards using the primary key of the other table since that's a good practice.
  - This means they should be able to set up Scenario 1 and 2 under "Viewing Existing Links" 
- We should not allow users to change the type of a column with a foreign key. We need a design for appropriate errors.
- We should not allow users to delete a table if a column from that table is used in a foreign key in another table. We need a design for appropriate errors.
- If there is a foreign key in a table, it should show up in the table constraints view and the user should be able to remove it.

**Comment by mathemancer** [comment]
I think framing this as a "type" like integer is a "type" is going to be confusing.I also suggest giving the user their choice of what column(s) from the other table to show in the table with the foreign key (i.e., if they have a Teachers table, they may want to show a teacher name rather than teacher ID in their classes table)

**Comment by kgodey** [comment]
@mathemancer I'm not sure about this. On the one hand, we want to reflect tables accurately and encourage people to use views when they want to see joined data. On the other hand, we want to be user friendly and show people what their relationships represent.

At this point in the product, we don't have views yet, so I'm treating this as an intermediate step. When we have views, the user experience here should change.

**Comment by kgodey** [comment]
Marking this as ready. This issue should be treated as an intermediate step, we will make relationships nicer by automatically creating views in the next milestone.

**Comment by kgodey** [comment]
Actually, I'll just move this to the next milestone to avoid the need for an intermediate step.

**Comment by seancolsen** [comment]
@kgodey @ghislaineguerin can we close this ticket now that the [Foreign Key Spec](https://wiki.mathesar.org/en/design/specs/foreign-key-constraints) is finalized? Or is there still more design work to do here?

**Comment by ghislaineguerin** [comment]
@seancolsen I think we can close it.

**Comment by kgodey** [comment]
@seancolsen I left it open as a reminder that we needed to make tickets to cover implementation (that's why the `work` label is set to `product`), but since you're working on those actively, I don't think there's any need to reopen it.
