### ISSUE TITLE
Create and publish first release

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2434]
- [x] Decide on versioning strategy
- [x] Clear old releases from GitHub
- [x] Clear old releases from DockerHub
- [x] Update README to say "public alpha"
- [x] Follow release process https://wiki.mathesar.org/en/product/release-process
- [x] Deploy release to demo server

**Comment by kgodey** [comment]
Blocked on upgrade frontend work.

**Comment by kgodey** [comment]
@mathemancer I started the release branch, here's the PR: https://github.com/centerofci/mathesar/pull/2620. Release notes below.

## Release notes
Mathesar's first alpha release! Features
- **Built on Postgres**: Connect to an existing Postgres database or set one up from scratch.
- **Set up your data models**: Easily create and update Postgres schemas and tables.
- **Data entry**: Use our spreadsheet-like interface to view, create, update, and delete table records.
- **Filter, sort, and group**: Quickly slice your data in different ways.
- **Query builder**: Use our Data Explorer to build queries without knowing anything about SQL or joins.
- **Schema migrations**: Transfer columns between tables in two clicks.
- **Uses Postgres features**: Mathesar uses and manipulates Postgres schemas, primary keys, foreign keys, constraints and data types. e.g. "Links" in the UI are foreign keys in the database.
- **Custom data types**: Custom data types for emails and URLs (more coming soon), validated at the database level.
- **Basic access control**: Users can have Viewer (read-only), Editor (can only edit data, but not data structure), or Manager (can edit both data and its structure) roles.
- **Basic documentation**: Users can install Mathesar using Docker Compose, and tricky product features are documented.

**Comment by mathemancer** [comment]
Okay, it's done! :rocket:
