### ISSUE TITLE
Promotional images for launch

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2437]
- [x] Website
  - [x] Open graph images, if not already fixed in https://github.com/centerofci/mathesar-website/issues/57 (1200 x 630 px)
- [x] Twitter account header (1500 x 500 px)
- [x] Twitter profile picture (400 x 400 px)
- [x] Open Collective header (2736 x 650 px)
- [x] Launch announcement
  - [x] Blog post header
  - [x] Social media image to share for launch
    - [x] Instagram/Facebook: (1080 x 1080 px)
    - [x] Twitter: (1024 x 512 px)
    - [x] LinkedIn: (1200 x 627 px)

@ghislaineguerin - please talk to me if you need to know dimensions for any of these.

**Comment by kgodey** [comment]
Assigned to myself to get it out of draft state.

**Comment by ghislaineguerin** [comment]
Images uploaded to https://drive.google.com/drive/u/1/folders/1OAI9EbZD3VXsJ_xA66vaJ4YIZI1dyRCc
