### ISSUE TITLE
Implementation for text data type

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#244]
## Problem

Users will want to store text data in columns. We should allow them to do so and implement this type appropriately in the backend.

## Proposed solution

We should support Text types in Mathesar and allow users to use them.

Tasks that need to completed:
- [x] #234 
- [x] #404
- [x] #405
- [x] #407
- [x] #406
- [x] #408
- [x] #254 

## Additional context
Related issues and PRs:
- #269
- #127 
- #135

**Comment by mathemancer** [comment]
Unless we have a specific reason to use `TEXT`, we should probably use `VARCHAR` for the column type even when unlimited.  This will make it easier to work with.  (There shouldn't really be any difference in the DB between `TEXT` and unlimited-length `VARCHAR` w.r.t. performance and whatnot.)

**Comment by kgodey** [comment]
@mathemancer Updated the ticket. I also added a section about reflecting existing `TEXT` fields correctly.

**Comment by rootxnet** [comment]
Working on it.

**Comment by kgodey** [comment]
Closing this since all subtasks are done.
