### ISSUE TITLE
Sync & improve styles in explorations listing and users listing

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2440]
## Description
* The `schema/explorations` listing section and `administration/users` listing have similar UX.
* The styling however differs in both pages. Some of them:
  * Position of the 'Clear' button after searching.
  * Empty states.
  * Loading state.
  * Error state.
* Both pages do not contain hover/focus indications for the rows.

## Requirement
* Identify styles and markup that need to be common between both pages, create a common component for that.
* Add proper empty, loading, and error states.
* Add focus and hover indications for the rows.

## Related
* https://github.com/centerofci/mathesar/pull/2423#pullrequestreview-1292041282

**Comment by Hatilar420** [comment]
Hi @pavish, can i work on this issue ?

**Comment by Anish9901** [comment]
@Hatilar420 I see, you already have 4 issues assigned to you of which 2 don't have a PR yet, please open PRs for those before getting assigned any new issues.

**Comment by Hatilar420** [comment]
Hi @Anish9901 , I have already started working on this issue and I am going to open a PR for the same soon in a couple of hours. Can you please assign me this issue this time as an exception ?

**Comment by Anish9901** [comment]
Assigned to you @Hatilar420. Thanks!
