### ISSUE TITLE
Show appropriate breadcrumbs for /administration/users/* pages

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2441]
## Description
* Moving to /administration/ adds a breadcrumb `Administration` on the top nav. This is good.
* Selecting General or Users tab, does not add a breadcrumb.
* Moving to users add/edit pages do not add appropriate breadcrumbs.

## Requirement
* The general and users tabs should add appropriate breadcrumbs.
   * General: `Administration > General`
   * Users: `Administration > Users` 
* User add page should display a breadcrumb: `Administration > Users > New user`.
* User edit page should display a breadcrumb: `Administration > Users / ${username}`

## Related
* [Figma designs](https://www.figma.com/file/xHb5oIqye3fnXtb2heRH34/Styling?node-id=3666%3A25085&t=cQ0Nar63adTFGwkU-0)

**Comment by IamEzio** [comment]
@pavish I'd like to work on this issue. It would be great if you could assign this to me. Thanks!

**Comment by Anish9901** [comment]
Thanks @IamEzio, assigned to you.

**Comment by Harshkumar77** [comment]
Hey, you can assign me the issue if its open.

**Comment by Anish9901** [comment]
@Harshkumar77 , @IamEzio already has a PR open for this issue please look through other issues to work on.

**Comment by manik-dhanjal** [comment]
Hi @Anish9901, If this issue is still open then I would love to contribute to it. Can you please assign it to me.

**Comment by Anish9901** [comment]
@manik-dhanjal The issue is still open but there is a PR already open for it. Please look through other issues to work on.

**Comment by manik-dhanjal** [comment]
No problem @Anish9901, Thanks for letting me know.
