### ISSUE TITLE
Handle 404 pages throughout the app

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2442]
## Description
* Client side routing: A non existent url results in a blank screen, or has obscure errors.
* Server side routing: A non existent url entered on the browser results in a 404, which returns a django 404 page.

## Expected behavior
* 404s should be clearly presented to the user in all valid cases.
* The 404 page should be consistent in appearance in both server side & client side routing.

**Comment by NOOBBITS** [comment]
I would like to work on this issue.
Kindly assign the same to me, if feasible

**Comment by Anish9901** [comment]
@NOOBBITS As you can see in the labels of this issue, it is marked to be taken up by maintainers and require an in-depth knowledge of the codebase. Please look through other issues to work on.
