### ISSUE TITLE
QA for users & permissions

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2454]
We need to make sure that users & permissions features function correctly. We should test all actions for all roles.

This issue is for coming up and executing a comprehensive plan for manual testing.

- [x] Document what needs to be tested - @Anish9901 
- [x] Use documentation to populate [testing spreadsheet](https://docs.google.com/spreadsheets/d/18I5SP22_R_ZqPXUPrWalvPeP-bh4bgdpl-g6ccAhU8Y/edit#gid=0) with everything that needs to be tested - @Anish9901 
- [x] Test everything in the spreadsheet on `staging.mathesar.org` and make GitHub issues for any bugs - @Anish9901 @rajatvijay  

### Notes
- We can't start QA until #2205 is done.

**Comment by Anish9901** [comment]
### Users and Roles
- Superuser(admin)
- Schema or DB specific user roles
  - Manager
  - Editor
  - Viewer

### Admin should be able to perform the following:
- Add a user (with and without display name and email).
- Edit other user's and own details (like display name and email).
- Delete users.
- Edit any user's credentials.
- Edit their own credentials.
- Add, remove, and view permissions of all users.
- Able to login and out.

### Users other than Admin should be able to perform the following:
- Able to login and out.
- Edit their own credentials.
- View their roles.

### Roles hierarchy
Superuser > Manager > Editor > Viewer
- A Superuser has access to everything.
- Managers have access to everything Editors and Viewers have access to, along with the things specified below. 
- Editors have access to everything Viewers have access to, along with the things specified below.
- Viewers have the least amount of access that is specified below.

### Managers should be able to perform the following:
- Create, Delete, and Update tables.
- Create, Delete, and Update columns.
- Create, Delete, and Update constraints.
- Create, Delete, and Update schemas.
- Create table settings.
- Split tables.
- Move columns to another table.

### Editors(& Managers) should be able to perform the following:
- Create, Delete, and Update records.
- Delete and Update table settings.

### Viewers(& Editors & Managers) should be able to perform the following:
- View tables(along with columns and records and constraints).
- Create, Delete, Update, and View explorations.
- View databases(along with properties like types and functions).
- View schemas.

**Comment by kgodey** [comment]
Thanks @Anish9901! This looks great and it'll be really helpful for testing.

I've assigned back to myself to coordinate next steps.

**Comment by pavish** [comment]
@Anish9901 

Here is an update related to Explorations which is incorrect in the above comment:

Viewers should not be able create, delete, and update Explorations. They can view explorations and run a query. They cannot save the query.

**Editors(& Managers) should be able to perform the following:**
* Should be able to create, delete, and update Explorations

**Viewers(& Editors & Managers) should be able to perform the following:**
* Run a query

cc @kgodey Please verify this.

**Comment by kgodey** [comment]
Yes, that's correct @pavish

**Comment by Anish9901** [comment]
Updated as per https://github.com/centerofci/mathesar/issues/2454#issuecomment-1435378490 .Thanks @pavish.

**Comment by kgodey** [comment]
@Anish9901 @rajatvijay I've created [a spreadsheet](https://docs.google.com/spreadsheets/d/18I5SP22_R_ZqPXUPrWalvPeP-bh4bgdpl-g6ccAhU8Y/edit#gid=0) to track everything that needs to be tested. Please fill out the spreadsheet with the remaining items and coordinate between yourselves to complete the testing.

I've updated the main issue description with a checklist.

Please use `staging.mathesar.org` and create users as needed.

**Comment by kgodey** [comment]
I assigned filling out the spreadsheet to @Anish9901 since @rajatvijay also has #2455 to work on.

**Comment by kgodey** [comment]
Testing complete, no issues found.
