### ISSUE TITLE
Documentation for users & permissions

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2455]
We need to document usage of users & permissions on `docs.mathesar.org` 
Documentation should cover:
- [x] How to add new users
- [x] How to add users to DBs or schemas
- [x] What each user permission can and can't do
- [x] Order of precedence of permissions (what happens if users have multiple permissions that apply to the same object) - currently the frontend implements this differently from the backend, but we should document the backend behavior.

### Notes
- WIP PR: https://github.com/centerofci/mathesar/pull/2535
- Related issues for reference:
  - #2454 
  - #1673 
  - #1985 
  - #2205 
- [Original product spec](https://wiki.mathesar.org/en/product/specs/users-permissions) 

#### References
- [Google Drive roles docs](https://support.google.com/a/users/answer/9310249?hl=en#shared_drive_change_access)
- [Unofficial Google Drive roles explanation](https://blog.suitebriar.com/google-shared-drive-permissions-explained-in-plain-english)

**Comment by anasos20** [comment]
Where are the details ??

**Comment by kgodey** [comment]
@anasos20 This issue is marked as a draft, so there are no details yet. :)

**Comment by kgodey** [comment]
@rajatvijay I've fleshed out the issue, added some references, and assigned to you. I also started a skeleton PR with a blank "Users" page - #2535. Please push updates in that PR.

**Comment by pavish** [comment]
@kgodey 

> currently the frontend implements this differently from the backend, but we should document the backend behavior.

Atleast until we change the UX and the frontend, shouldn't we be documenting the frontend behaviour? Our users are only going to be using the frontend, and if we have different behaviour mentioned in the docs compared to the actual implementation, it's going to be confusing for them.

We can update the docs after we update the frontend code.

**Comment by kgodey** [comment]
> Our users are only going to be using the frontend.

In my mind, if the permissions are not enforced at the API level, then they're not valid. Our initial target users are software engineers, I can guarantee you some of them will mess around with the API. We will lose trust if we document permissions that are not enforced by the backend.

I do think we should add a note in the documentation saying we currently have a bug with our implementation and our frontend restricts permissions in the UI if you add a more restrictive lower-level permission. We can advise users to avoid doing that (which is fine, because once the frontend is in sync with the backend, the lower-level permissions will be redundant anyway).

**Comment by kgodey** [comment]
I've documented this in the PR. I'll add you as a reviewer, @pavish
