### ISSUE TITLE
Demo server 500 right after login: "mathesar_demo_template" is being accessed by other users

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#2466]
## Description

Response was `500 https://demo.mathesar.org/` with following body:

![2023-02-13_18-14](https://user-images.githubusercontent.com/2715476/218511825-d0aa4e0e-1f0d-4a78-aafa-3080d33258a0.png)

Reloaded after ~5mn (waited a long time because was submitting this bug report): view rendered fine, but I had no schemas (while I expected to see all the demo schemas). Another logout and login fixes it.

## To Reproduce

Logged out of the demo server and logged back in.

**Comment by dmos62** [comment]
Happens quite often.

**Comment by mathemancer** [comment]
The problem is that you can't _use_ the template DB while it's being accessed in a read/write capacity. I think this is (almost certainly) happening because we're leaving a connection open to the template DB somewhere.

**Comment by dmos62** [comment]
So I should be able to reproduce by starting two demo database creations simultaniously, right?

**Comment by dmos62** [comment]
Current plan is to find each engine and connection being instantiated in the related code and make sure it's `dispose`d of. There are places where they're instantiated inside a `try` statement, but the disposal isn't happening in the `finally` (meaning that it might not happen at all). Also, use something like `SELECT COUNT(*) from pg_stat_activity;` with load testing to count number of connections.

Not to forget that `demo/management/commands/clean_stale_db.py` also instantiates engines and thus might leak connections.

**Comment by dmos62** [comment]
After talking to @mathemancer, the problem seems to be the initialization of the template database running too often, due to how it is defined (as a Django initialization hook). Will redefine it so that it only runs once, when the demo server is starting.

**Comment by dmos62** [comment]
I'm on leave for next two days. Current status of this is this:

This 500 seems to be caused by a maintenance-related connection being opened to the demo Postgres template database. It's different from #2487, because these connections are short-lived, while in #2487 they are long-lived.

Currently, the hypothesis is (and this is supported by the interrupting connections being short-lived) that this is maintenance or redundant initialization being performed on the template database (by the service layer) and it's interrupting "cloning" of the template database when a new demo user is logging in.

To hopefully fix this, two PRs are submitted:
- https://github.com/centerofci/mathesar/pull/2491
- https://github.com/centerofci/mathesar-ansible/pull/34

One depends on the other. Their goal is to assure that the demo template database is only provisioned when the demo server is being provisioned.

**Comment by dmos62** [comment]
Fixed by https://github.com/centerofci/mathesar/pull/2491 as far as I can tell.
