### ISSUE TITLE
`clean_stale_db --force` kills demo databases newer than 3 days

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#2467]
## Description
`clean_stale_db --force` is meant to only kill demo databases older than 3 days (by default), but that doesn't seem to be the case.

## Additional context

https://github.com/centerofci/mathesar/blob/master/demo/management/commands/clean_stale_db.py

**Comment by kgodey** [comment]
@dmos62 What is it doing instead of 3 days? Depending on the answer, this may be a launch blocker.

**Comment by dmos62** [comment]
@kgodey I've not tested this extensively, but it's killed my demo database that was minutes old.

**Comment by kgodey** [comment]
@DankMemes4President Yes, please do, thanks!

**Comment by kgodey** [comment]
@dmos62 I moved this to launch blockers, we can't have people's databases getting deleted while they're checking out the live demo.
