### ISSUE TITLE
Implementation for money data type

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#249]
## Problem

Users will want to store monetary data in columns. We should allow them to do so and implement this type appropriately in the backend.

## Proposed solution

Postgres has a built-in `MONEY` type, but the currency used for it is locked to the `lc_monetary` setting of the Postgres installation ([see docs](https://www.postgresql.org/docs/current/datatype-money.html)). We need to support storing money in different currencies in different columns, so we will create a custom `MATHESAR_MONEY` type.

Tasks that need to completed
- [x] #239 
- [x] #655 
- [x] #417
- [x] #420
- [x] #1105
- [x] #418
- [ ] #419
- [x] #259
- [x] #1063
- [x] #1094

Moved to a later milestone:
- #656 
- #657 

## Additional context
- #118 architectural discussion
- #269

**Comment by pavish** [comment]
I'm going to close this meta issue since the one pending item: https://github.com/centerofci/mathesar/issues/419 is tracked separately.
