### ISSUE TITLE
Allow users to sign up for Mathesar mailing list from live demo

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2494]
Users may be interested in signing up for the mailing list once they've looked at our live demo for a while. We should allow them to do so. Many users won’t return to the website after playing with the demo, so they miss out on signing-up.

One idea:
- Consider setting up an opt-in pop up that emerges after 10-15 minutes of continuous use. Copy can be the same as mailing list sign-up on our website.

We can also consider other UI ideas.

**Comment by IamEzio** [comment]
Hi @kgodey! This looks interesting and I'd very much like to work on this issue. Thanks!

**Comment by kgodey** [comment]
@IamEzio Sorry, I should have marked this as a draft. We need to spec this out more since it's unclear how to implement this.

**Comment by IamEzio** [comment]
Ah ok. No problem

**Comment by AbhinavOhri** [comment]
Hi @kgodey , I have some ideas:
1.) A "join our mailing list" highlighted text on the "demo mode" alert, or
2.) A "join our mailing list" button on navbar, or
3.) An exit intent pop-up which appears when the user is closing the tab.

**Comment by kgodey** [comment]
Thanks @AbhinavOhri! Those are good ideas. I'll defer to @seancolsen on determining final implementation details.
