### ISSUE TITLE
Issues with installation

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2503]
I tried following [the docs](http://docs.mathesar.org/installation/docker-compose/) on my Mac. I wiped out all Docker images and containers before I started.

My Docker version: 20.10.8, build 3967b7d
My docker-compose version 1.29.2, build 5becea4c

### Issue 1: It failed.
`sudo docker compose --profile prod up -d --wait` failed and the script exited with ``unknown flag: --wait`

I had no idea what to do next or how to troubleshoot. Therefore I couldn't finish the install and can't provide feedback for the remaining steps.

**Edited to add**: I later found the Troubleshooting section that explains what Docker versions to use. This should be in requirements, and we should have minimum requirements clearly stated. #2504 addresses this somewhat. We may also want to check Docker versions ourselves and refuse to install if we don't have the right versions, because it's disconcerting for the script to exit without any indication about what's wrong.

I'll test with updated Docker versions tomorrow.

### Issue 2: Admin user is not validated
I accidentally hit Enter without entering a username when it asked me for an admin user. It then asked me for a password.

The script should make sure that the username actually exists and prompt the user for a username if it doesn't.

### Issue 3: Secret generation

```
Generating secret key...
tr: Illegal byte sequence
Secret key generated successfully.
```

I'm not sure what `tr: Illegal byte sequence` is but it made me worry.

### Issue 4: Config file location should be configurable.

This is the following step:

```
We begin by creating a directory on your system where we can put some files for
Mathesar to use.
```

It's fine to have a default, but the user should be able to change it.

### Issue 6: Usernames should have default values
This applies to both system database username and admin username. The user should be able to change them.

I'm also wondering if we should offer to auto-generate passwords (again, the user should be able to override).

### Issue 7: Install script docs are too verbose.
When I run the install script, the documentation is extremely verbose. Especially when I first run the script, it prints 2 terminal screens worth of stuff and it's overwhelming. I don't know what's important and what's just explanatory. 

For example, the secret key steps says:

```
********************************************************************************
In order to keep Mathesar's web server secure, we'll randomly generate a secret
key. It's not necessary for you to know this secret, since it's just for
internal Mathesar use.

Generating secret key...
tr: Illegal byte sequence
Secret key generated successfully.
********************************************************************************
```

This is a lot to take in, especially for people unfamiliar with Mathesar. I do like the docs, but not the location. I would move the explanations of what's happening to the docs site, and make the output just:

```
Generating secret key...
Secret key generated successfully.
```

The docs site can have a "explanation of what the install script does" section and move the longer stuff like this there: 

```
In order to keep Mathesar's web server secure, we'll randomly generate a secret
key. It's not necessary for you to know this secret, since it's just for
internal Mathesar use.
```

This applies to other steps too.

**Edited to add**: Here's [a screenshot](https://user-images.githubusercontent.com/35857179/161526235-5ee0d592-0105-4a57-aa53-b1048dca6aad.png) of NocoDB's installation process (from [this page](https://docs.nocodb.com/getting-started/installation)). Much less overwhelming!

### Issue 8: Postgres port

One of the steps says:

```
If you have a PostgreSQL database already running on this machine you may need
to choose a custom port for Mathesar's database to avoid conflict. If you're not
sure, just press ENTER to use the default port of 5432.
```

Isn't the DB going to be running in a container? Why would there be a second DB in the container with the same port?

### Issue 9: Final message
I didn't get this far, but the script says:

```
If running locally, you can access Mathesar by navigating to http://localhost
in your web browser.
```

This is weird because we ask for a domain earlier in the process. We should adapt this message to whether they set up a domain.

**Comment by mathemancer** [comment]
> ### Issue 4: Config file location should be configurable.
> This is the following step:
> 
> ```
> We begin by creating a directory on your system where we can put some files for
> Mathesar to use.
> ```
> 
> It's fine to have a default, but the user should be able to change it.

This will break a bunch of things. We need at least some location on the user's drive where we know that `docker-compose.yml` and `.env` live, or we can't really hope to help them much with upgrading, stopping/starting containers, etc.
