### ISSUE TITLE
Unable to update database_roles and schema_roles

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2505]
## Description
* Both PUT and PATCH requests are not allowed in
  - `/api/ui/v0/database_roles/<id>/`
  - `/api/ui/v0/schema_roles/<id>/`
* These endpoints should allow a PUT or a PATCH request, inorder to enable the user to update permissions from the UI.

cc: @kgodey @silentninja

**Comment by silentninja** [comment]
> inorder to enable the user to update permissions from the UI.
@pavish Is this a product requirement? On the backend, the update methods are not implemented intentionally. Refer to the description of the PR https://github.com/centerofci/mathesar/pull/1774

**Comment by pavish** [comment]
> Is this a product requirement?

Yes, this is part of the UX. Refer [figma design](https://www.figma.com/file/xHb5oIqye3fnXtb2heRH34/Styling?node-id=4609%3A35101&t=wTXGRUr23u5MgjGK-1).

> the update methods are not implemented intentionally

@kgodey Could you confirm what's the next steps needed here? The UX requires updating permissions, but the backend APIs don't support it.

**Comment by kgodey** [comment]
@pavish I think we should go with your compromise. I didn't implement editing permissions because by default, you could change the user as easily as you could change the role. It seems like a potential security issue. Thinking through it and implementing the correct validations will take longer and seems unnecessary right now.

**Comment by pavish** [comment]
@kgodey Okay, thanks. I'll improvise the UX for now.

I'm keeping this issue open and moving it to backlog, since this is needed for the long run.

**Comment by kgodey** [comment]
I marked this issue as a draft since we need to work through security implications before implementing.

**Comment by pavish** [comment]
I'm closing this issue since, we proceeded with a different UX.
