### ISSUE TITLE
Implementation for duration data type

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#251]
## Problem

Users will want to store duration data in columns. We should allow them to do so and implement this type appropriately in the backend.

## Proposed solution

We should support a duration type in Mathesar and allow users to use it. Postgres has a built in type for this – `INTERVAL`, so we'll use that.

Tasks that need to completed:
- [x] #241
- [x] #430
- [x] #431
- [ ] #432
- [x] #433
- [x] #261

## Additional context
Related issues and PRs:
- #269
- #127 
- #135

Also see [Postgres "Date/Time Types" docs](https://www.postgresql.org/docs/current/datatype-datetime.html).

**Comment by pavish** [comment]
I'm closing this issue since the one pending item https://github.com/centerofci/mathesar/issues/432 is tracked separately.
