### ISSUE TITLE
Deploy Mathesar to GCP using Deployment Type 1

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2510]
- [x] use `install.sh` on a fresh server
- [x] Set up some domain (e.g., `testing.mathesar.org`)
- [x] see what happens

**Comment by mathemancer** [comment]
Used `library.mathesar.org` to go through this, found a couple problems:
- SSL wasn't quite wired up properly.
- The prod docker image was not loading static files.

**Comment by silentninja** [comment]
> SSL wasn't quite wired up properly.

- #2530 should fix it.

> The prod docker image was not loading static files.

#2531 should fix it 

Adding these PR's for reference
