### ISSUE TITLE
Test demo analytics and make sure they work well

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2512]
- Blocked on #202

**Comment by pavish** [comment]
@kgodey I don't see our demo site added to the simpleanalytics account present on 1password. 

@silentninja Do we use a different account for it?

**Comment by pavish** [comment]
This is blocked because I'm unable to test it without the account details.

**Comment by pavish** [comment]
Update: I added `demo.mathesar.org` to our simpleanalytics dashboard, and it seems to work.

**Comment by pavish** [comment]
I've tested this and analytics seems to work as expected. Events and page views seem to get updated live.

**Comment by pavish** [comment]
@kgodey Can we close this issue, or is there anything additional we need to test here?

**Comment by kgodey** [comment]
Nothing else, @pavish. Thanks!
