### ISSUE TITLE
Backend/API implementation for Choice data type

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#252]
## Problem

Users will want to store columns with data restricted to a certain set of values. We should allow them to do so and create related tables appropriately in the backend.

## Proposed solution

This involves multiple parts, we might want to split each part into sub-issues.

### Implementation
This is not really a type. Choices will be stored in a separate table and there will be a foreign key field linking it to the current table. Users should be able to add/edit/update choices.

### Inference
We should detect choices when data is imported and suggest it to users automatically. We should suggest this if there's a limited (<10, number should be configurable and perhaps scale according to the number of rows imported) set of values.

### Creating/updating the appropriate column.
Users should be able to specify options for the columns and edit the options for existing columns:
- Default value
- Allow empty values (should create not-null constraint if false)
- Unique (should create unique constraint if true)

In addition, users should be able to add/edit/update choices.

### Filtering
We should ensure that we support all filtering options in #242 for this field in our API.

### Altering Columns
We should ensure that we support altering columns to this type (as appropriate).

### Display options
We need to be able to store colors associated with each value.

## Additional context

Please see #242 for related design issue, the context might be helpful.

Marking this as blocked by https://github.com/centerofci/mathesar/issues/253 since this is an extension of relationships.

**Comment by mathemancer** [comment]
What's the advantage of this over a column with a foreign key restriction?  The underlying implementation is the same.  (i.e., PG will actually just create a table for the ENUM, and set up a foreign key restriction).  If we want to help users make great DB schema designs, shouldn't we just help them create that table via the splitting operation we already have rather than making a type?  We'd also avoid needing another editing flow (i.e., to edit the options in the ENUM), since they'd just edit the attached table instead.

**Comment by kgodey** [comment]
@mathemancer I think you're right, I'll edit the tickets to instead create a separate table rather than an `ENUM`. We will need to do this one eventually to reflect `ENUM` columns in existing databases, but we probably don't need that for the MVP.

**Comment by kgodey** [comment]
Choices are actually just going to be relationship fields. I'm going to move this to the Views milestone because displaying non-ID fields from related tables (which is what choices will be) will mean creative a view.

**Comment by kgodey** [comment]
This issue doesn't make sense any more since relationships aren't "types" and choices are just subsets of relationship. I'm creating new issues to spec out how relationships will work. I'll close this and we can create new issues related to choices in the future if needed.
