### ISSUE TITLE
Installation usability test - high priority issues

### ISSUE THREAD

**Issue by mathemancer** [centerofci/mathesar#2523]
## Problem

We did a round of usability testing on the `install.sh`; issues were found. This issue collects the feedback together. 

### Code
- [x] ~User should press ENTER at the `DOCKER SETUP` step so they have time to read.~ Not sure what this means.
- [x] Multiple people have reported not being able to log in or not being able to create a schema once logged in. Please verify this works. (Note from @kgodey: we have root SSH access + admin user access to this instance, if it will help debug).
- [x] Determine how `admin` user is being created in prod installation setup. This is causing a bug if the user also tries to create a superuser named `admin`.
- [x] Use proper user for `pg_isready` to avoid `FATAL:  role "root" does not exist` spam in logs.
- [x] Figure out warning when starting containers:
  `RequestsDependencyWarning: urllib3 (1.26.14) or chardet (5.1.0)/charset_normalizer (2.0.7) doesn't match a supported version!`

### Copy
- [x] ~Make some troubleshooting items into prerequisites (e.g., docker versions)~ Already fixed
- [x] Change "terminal window" -> "terminal" in docs - Fixed in #2549 
- [x] ~Format important words in documentation specially~ - Unclear what "important" means
- [x] ~Make separate section with description of files output by `install.sh` (environment file)~ - Already fixed
- [x] ~Add separate "Maintenance" section in docs for upgrades and so on.~ - New "Administration" section under "Installation" should fix this.

### Notes
- #2550 was pulled out from here.
- Styling related issues are tracked in #2457 
- Some issues pulled into #2570

**Comment by kgodey** [comment]
Marking as draft until the remaining testers send their feedback and I do some prioritization.

**Comment by kgodey** [comment]
@mathemancer I triaged this. Unchecked items should be prioritized. Feel free to split up into smaller issues if things can be parallelized.

**Comment by kgodey** [comment]
@mathemancer Here is an additional testing report that I have not triaged: https://docs.google.com/document/d/1brAzWeIr-PYH6NJFdxTM21suk0cUmhiR/. Please use your best judgement about which issues should be fixed.

**Comment by mathemancer** [comment]
> @mathemancer Here is an additional testing report that I have not triaged: https://docs.google.com/document/d/1brAzWeIr-PYH6NJFdxTM21suk0cUmhiR/. Please use your best judgement about which issues should be fixed.

I saw one thing that is a launch blocker there, the health check is failing. That should be fixed by https://github.com/centerofci/mathesar/pull/2562 .

**Comment by mathemancer** [comment]
It should be noted that the `admin` user problem disappeared on it's own

**Comment by mathemancer** [comment]
After trying `install.sh` in a few contexts, using `admin` for the admin user, I can no longer recreate the issue we were having. I'm checking that box, and closing this unless it reappears.
