### ISSUE TITLE
Have consistent behaviour for access level precedence in frontend and backend

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2537]
## Description
> - On the backend, if the user has 2 permission access levels, one on the database and one on the schema, the highest permission level will take precedence.
>   - If user is `viewer` on db, and `manager` on schema, the user will have `manager` access on the schema.
>   - If user is `manager` on db, and `editor` on schema, the user will have `manager` access on the schema.
> - The frontend behaviour is currently: access level on schema takes precedence over access level on the database. By this definition,
>   - If user is `viewer` on db, and `manager` on schema, the user will have `manager` access on the schema.
>   - If user is `manager` on db, and `editor` on schema, the user will have `editor` access on the schema.
> - This is because:
>     - This is the simplest to implement and easier to convey to the user UX wise.
>     - I didn't think this was a priority for the launch.
>     - We can update this behaviour to be the same as that on the backend, once we come up with a better UX to convey 

We need both frontend and backend to be consistent.

We require a better UX to let the user understand the precedence of the roles when user has roles at both the database and schema level.

Related:
* https://github.com/centerofci/mathesar/pull/2524#issuecomment-1437431896

**Comment by pavish** [comment]
@kgodey I've moved this to 'Launch Nice-to-Haves' milestone with a later iteration (2023-03-10), since this is high priority.

**Comment by Ciggzy1312** [comment]
Hey @pavish is it up for grabs, then I would like to give this a try
Seems to be a good starting point for me to get involved in this project as I want to participate in GSOC under Mathesar

**Comment by Ciggzy1312** [comment]
Sorry, my bad
Didn't notice
