### ISSUE TITLE
Optimize reflection in the Mathesar codebase

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2544]
- [x] Find a reflection hotpath and setup profiling
  - With the goal to find out which parts or instances of reflection are slowing things down
- [x] Figure out what changes could be beneficial
  - `mathesar/state/django.py::reflect_columns_from_tables` (1.46s, ~23%)
    - ~25% of time spent in `models._set_default_preview_template`; candidate for optimization
- [x] Make following changes
  - `mathesar/state/django.py::sync_databases_status` (3.4s, ~50%)
    - [x] Instead of saving every database, save only when a change was performed (should shave ~1-20%)
  - `mathesar/state/django.py::reflect_db_objects` (6.34s, 100%)
    - [x] Make sure we don't check the status of all databases when parametrizing reflection with a single database (should shave ~50% in those cases)
    - [x] Make sure is always parametrized by `db_name`, so that reflection is limited to a single db (in cases where `db_name` is not specified, but could be, should shave >75%)
  

Note, above speed-up percentage estimates based on [profile below](https://github.com/centerofci/mathesar/issues/2544#issuecomment-1441848721).

Edit: more tasks in the comments.

**Comment by dmos62** [comment]
Attaching profile of a database being created and reflection triggered during demo login: [mathesar_demo_login_1677159168.prof.zip](https://github.com/centerofci/mathesar/files/10814194/mathesar_demo_login_1677159168.prof.zip).

**Comment by dmos62** [comment]
Above PR should shave ~50% (~3s) off the scenario in the profile.

**Comment by dmos62** [comment]
Above PR should shave ~20% off the scenario in the profile.

**Comment by dmos62** [comment]
Attaching profile of a database being created and reflection triggered during demo login: 
[demo_login_db_creation_1677682059.prof.zip](https://github.com/centerofci/mathesar/files/10862276/demo_login_db_creation_1677682059.prof.zip)


![2023-03-01_16-49](https://user-images.githubusercontent.com/2715476/222175460-dd651a40-1c65-4d9f-8a93-5c4fcb68d240.png)

Commentary:

- `sync_databases_status` is not a concern anymore;
- interestingly, `reflect_constraints_from_database` has balooned from taking 1.19s (in the [previous profile](https://github.com/centerofci/mathesar/issues/2544#issuecomment-1441848721)) to taking 6.47s;
    - could there be something inside it that makes its performance dependent on total number of demo databases?

**Comment by dmos62** [comment]
Profile after applying above PR (profile of a database being created and reflection triggered during demo login): [demo_login_db_creation_1677687813.prof.zip](https://github.com/centerofci/mathesar/files/10863354/demo_login_db_creation_1677687813.prof.zip)

![2023-03-01_18-30](https://user-images.githubusercontent.com/2715476/222202477-8e219334-91b6-4da1-840f-458897500beb.png)

Commentary:

- same conditions as [previous profile](https://github.com/centerofci/mathesar/issues/2544#issuecomment-1450291112);
- this PR cuts reflection time by ~50% (by making changes to `reflect_constraints_from_database`).

**Comment by dmos62** [comment]
```[tasklist]
```
