### ISSUE TITLE
Optimize connection management in the Mathesar codebase

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2545]
Please figure out what needs to be done here and fill this issue out.

**Comment by dmos62** [comment]
[PgBouncer](https://github.com/centerofci/mathesar/issues/2546#issuecomment-1440453250) might be a way to solve this problem without changing Mathesar's code.

**Comment by kgodey** [comment]
This issue should be dedicated to changes we can make in the codebase.

**Comment by dmos62** [comment]
If it's true that some of our woes come from sqlalchemy not releasing connections when we do `engine.dispose()` and instead releasing them to its pool, we can try doing `create_engine(..., poolclass=NullPool)`:

https://docs.sqlalchemy.org/en/20/core/engines.html#sqlalchemy.create_engine.params.poolclass
https://docs.sqlalchemy.org/en/20/core/pooling.html#sqlalchemy.pool.NullPool

Might not be appropriate in all scenarios, but could be helpful where we're creating very short-lived engines with clear usage (e.g. demo's `load_arxiv_data`).

**Comment by dmos62** [comment]
Might run into some aspects of this in https://github.com/centerofci/mathesar/issues/2596

Asked @silentninja if I can take this over in the interest of not having similar tasks split across multiple people. He agreed.
