### ISSUE TITLE
Optimize Postgres settings - session timeout, connection limit, etc.

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2546]
We need to update Postgres settings for the demo server – session timeout, connection limit, etc. 

This can be tested live, but should be updated in Ansible so that we can deploy the same configuration to other servers easily.

### Notes
- Connections may be memory intensive, pay attention to that.
- Postgres connections according to docs, 128 MB

**Comment by dmos62** [comment]
It's worth considering setting up [PgBouncer](https://www.pgbouncer.org) to pool connections in one of the more aggressive modes.

**Comment by dmos62** [comment]
The Postgres configuration option for controling when to timeout idle connections is not available in our version of Postgres (13). It's first introduced in Postgres 14, afaict.

The config option I'm referring to (and I assume @silentninja was referring to the same one when he suggested it) is `idle_session_timeout`. Below are the links to the 14th and 13th versions of the relevant documentation document (you'll notice that `idle_session_timeout` is not the second one):

https://www.postgresql.org/docs/14/runtime-config-client.html#GUC-IDLE-SESSION-TIMEOUT
https://www.postgresql.org/docs/13/runtime-config-client.html#GUC-IDLE-SESSION-TIMEOUT

There's a similar setting that is present in the 13th version: `idle_in_transaction_session_timeout`; but, it's for closing idle connections that have transactions option, which, I suspect, is usually not the case in our demo server. @mathemancer could you sanity check me here?

**Comment by dmos62** [comment]
Unless my above comment is wrong, I'll consider that this task is only about increasing max connection count.
