### ISSUE TITLE
Load test live demo and find any additional problems

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2547]

**Comment by dmos62** [comment]
Load tested (without load balancing):

![2023-02-28_19-13](https://user-images.githubusercontent.com/2715476/221927736-f38884d2-3e63-4317-9243-301acbd46a5d.png)

![2023-02-28_19-19](https://user-images.githubusercontent.com/2715476/221928689-61d9478a-9580-4595-a625-4ae1824a744a.png)

I'll provide commentary more tomorrow, but the short of it is that concurrent users are still a big problem (especially concurrent logins). Increasing number of databases seems to play a lesser role now, but Postgres connections still linger (there are 145 at the end of above load test runs). Failures experienced were almost uniquely timeouts.

In the charts you see 4 load-test runs:

1. 0.5 user per second ramp up to 20 concurrent users;
2. 0.5 user per second ramp up to 50 concurrent users;
3. 0.5 user per second ramp up to 50 concurrent users;
4. 0.5 user per second ramp up to 50 concurrent users.

The table is showing stats for the last (4th run).

**Comment by dmos62** [comment]
Commentary of above screenshots/load-tests:

- "Number of Users" chart is the most telling: what you see happening in the last three runs is that we try to ramp to 50 users, but, then most of their login attempts timeout, and we're left with 5-25 users that did succeed in logging in and are executing requests;
  - in other words, concurrent logins are still a big problem;
  - notice that run `#2` is not actually labeled in the chart and run `#3` is labeled as `#2` (locust frontend is somewhat buggy);
- aggregated median response time is 39 seconds; and it's 85 seconds for logging in;
- static asset responses are ~1.1 second (this is true even when unloaded).

**Comment by dmos62** [comment]
Not seen in above runs, but after running load tests for a while, the server seems to not a ble to serve requests anymore (for one concurrent user). Might be that reflection slowness is still proportional to number of databases.

**Comment by seancolsen** [comment]
I'm closing since it seems like there is most likely no further action required here.
