### ISSUE TITLE
Frontend implementation for Email Mathesar type

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#255]
## Requirements

Users should be able to:
- view data in columns that have the Mathesar email custom type
- see validation errors if the data they enter is not a valid email
- change data type to and from the email DB type
- view, set, and change data type options related to email data type
- ~~group data by email-specific grouping options~~
- ~~filter data by email-specific filtering options~~

Update:
- Grouping will be handled in #1073 
- Filtering will be handled in #1072 

## DB Type Mapping
All columns of this type map to `MATHESAR_TYPES.EMAIL`. Please note that we should make sure it's available before showing it as an available type.

### Design
- The [Global Data Types](https://wiki.mathesar.org/design/specs/global-data-type-components) spec has the latest version of the UX.
- The [Email Data Types](https://wiki.mathesar.org/design/specs/email-data-type) spec has an older version of the UX but more information on user scenarios.

### Backend
- `/api/v0/tables/` lists the name and DB type of each columns 
- `/api/v0/tables/<id/columns/` lists column information in more detail
- `/api/v0/databases/<id>/types/` maps Mathesar types to DB types and provides a list of filtering and grouping options per-type.
  - These should be used to populate the filter and grouping options dynamically. 
  - This should also be used to determine the availability of the email type on a given database. It is a custom type so it's not available on all databases.
- Updates to column types and type options should happen via `PATCH` requests to `/api/v0/tables/<id>/columns/<id>/`. These updates include
  - Changes to the data type (`type`)

## Additional Context
- #235 (design)
- #269 (concept of Mathesar types)
- #498 (conversation about data types)
- Blocked by backend work:
  - #409

**Comment by kgodey** [comment]
Marking this as ready since filtering and grouping have been moved to other issues and remaining backend work is done.

**Comment by seancolsen** [comment]
Most of the work here appears to be done, so I'm closing this ticket in favor of a few remaining tickets that are more specific.

To address this ticket's requirements:

- **_view data in columns that have the Mathesar email custom type_**

    - This appears to work

- **_see validation errors if the data they enter is not a valid email_**

    - This mostly works. Here's what the error looks like.

        ![image](https://user-images.githubusercontent.com/42411/165423345-e7ccfd08-8764-4f79-acc9-82f2ffb0f1f2.png)

        The error message could be a little more specific. But think it's a small enough issue that I'm not sure it's worth opening a ticket.

- **_change data type to and from the email DB type_**

    - Tracked in:

        #1317

        #1318

- **_view, set, and change data type options related to email data type_**

    - I've gone digging through the specs and not found any type options or display options specified for the Email type.

- **_group data by email-specific grouping options_**

    - Tracked in #1073

- **_filter data by email-specific filtering options_**

    - Tracked in #1072
