### ISSUE TITLE
Setup PgBouncer on the demo server to timeout and pool connections

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#2553]
There are two related issues that aim to:
- time out Postgres connections
  - https://github.com/centerofci/mathesar/issues/2546
- and reduce the number of connections we spawn
  - https://github.com/centerofci/mathesar/issues/2545

I suggest that it's worth trying to do that with [PgBouncer](https://www.pgbouncer.org/) (a Postgres connection pooler) instead, for the following reasons:

- We can't seem to configure connection timeouts in our Postgres version (see [this comment](https://github.com/centerofci/mathesar/issues/2546#issuecomment-1441471183)), which is what [#2546](#2546) was trying to do;
- Diving around Mathesar codebase looking for ways to optimize connections is laboursome, which is what [#2545](#2545) is about.

The way I see PgBouncer working is that we configure it to:
- Use `pool_mode` set to `transaction` to release Postgres-PgBouncer (in contrast to PgBouncer-Mathesar connections) connections back to pool after each transaction;
- Restrict the number of Postgres-PgBouncer connections per database to 1; I hope that this together with above `pool_mode` setting with result in Mathesar using at most a single Postgres-PgBouncer connection per database (without crashing);
- Aggressively timeout Postgres-PgBouncer connections.

Above should work if Mathesar does not try to query the same database asynchroniously (via multiple PgBouncer-Mathesar connections) and/or if PgBouncer can transparently block PgBouncer-Mathesar connections until a Postgres-PgBouncer connection is released.

**Comment by dmos62** [comment]
@mathemancer @silentninja @kgodey review this proposal please.

**Comment by kgodey** [comment]
@dmos62 I assume you mean we should set up PgBouncer for the demo server. I think that's fine – I don't have any objections to it.

I don't think it's a substitute for #2545 since #2545 will also help us in non-demo mode, and help other Mathesar users who don't deploy using PgBouncer.

**Comment by dmos62** [comment]
@kgodey yes, this is a suggestion to try out PgBouncer for demo mode. However, it could be used outside it as well.

The thing with #2545 is that it's a potentially high-effort, but short-lived improvement. Short-lived, because when we eventually phase out sqlalchemy, these optimizations (and problems) will go away with it.

**Comment by kgodey** [comment]
Makes sense @dmos62
