### ISSUE TITLE
Demo user should not have the `admin` role, they should have `db manager` access.

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2554]
## Description
* Our live demo has a `demo` user with `admin` role.
* This allows the demo user to be able to create new users, and perform upgrades etc.,
* We should convert demo user to the standard role, and provide them with a database manager access.

**Comment by pavish** [comment]
@kgodey I think this should be part of `Launch Blockers`.

**Comment by pavish** [comment]
This seems to be a nice-to-have for `0.1.2` since we've been facing a number of issues with people messing with our demo. I'm going to place it in that milestone. We can remove it if needed based on the time constraints.

**Comment by kgodey** [comment]
This isn't going to solve any issues we've faced with our demo. Mukesh fixed those in #2676.

I think we should close this. Having the demo user be an admin allows them to get a demo of the admin section too, which seems like a good thing to me.

**Comment by pavish** [comment]
@kgodey Okay, sounds good to me. Closing this issue.

**Comment by pavish** [comment]
The admin user has access to upgrade Mathesar, which we should not allow the demo user to do, but considering that we will always run the upgraded version in our demo, I suppose we should be good.

**Comment by kgodey** [comment]
The demo isn't deployed using our Docker setup, so users can't upgrade it in any case.
