### ISSUE TITLE
Add client side validations for email, username, password length

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2555]
From https://github.com/centerofci/mathesar/issues/2432

> Part of fixing this issue is finding the default settings & criteria Django uses, and identifying those that can be validated on the frontend. Once you have that figured out, please add a comment to the ticket, get an approval from one of us on the core team, and implement it.

**Comment by pavish** [comment]
Conversation from #2432

> @IamEzio: I am working on the first task, i.e, Add client side validations for email, username, password length.
> could you please provide me all the parameters against which I should validate username and password? It would be great if there is a doc with all such rules. Thanks!

Response is in ticket description.

**Comment by yuvraj-wale** [comment]
hey I would like to work on this issue please assign it to me, thanks.

**Comment by pavish** [comment]
@yuvraj-wale We already have @IamEzio working on this from the original meta ticket.

We'll wait for a day for @IamEzio to respond on the status. If there's no response or if they're not planning to continue on this, we'll assign this issue to you.

**Comment by IamEzio** [comment]
Hi @pavish, I'll be happy to continue working on this. Thanks!

**Comment by IamEzio** [comment]
@pavish @kgodey I went through the [documentation](https://docs.djangoproject.com/en/4.1/ref/contrib/auth/) on how Django validates the `username` and `password` field. 

 - Username should be `150 characters or fewer. Usernames may contain alphanumeric, _, @, +, . and - characters.`

 - Passwords can  `be arbitrarily long and can contain any character.` Additionally, we can validate if the inputs for `New Password` and `Confirm Password` fields are same wherever applicable.
 
 - Email inputs should pass the regex ``/^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/``
  which is done by default if we specify **_type_** as **_email_** in ``<input>`` tags. Currently, we input email as simple text (using `TextInput` from `@mathesar-component-library`).

If these validations sound good to you guys, I can start working on implementing them. Thanks!

**Comment by kgodey** [comment]
I'll defer to @pavish here.

**Comment by pavish** [comment]
@IamEzio Looks good to me! You could start working on them.

**Comment by lord2anil** [comment]
i want to work on this issue

**Comment by kgodey** [comment]
@lord2anil - @IamEzio is assigned to this. If we don't see activity for a week, it will be open again.
