### ISSUE TITLE
Change the name of `User` role

### ISSUE THREAD

**Issue by rajatvijay** [centerofci/mathesar#2557]
## Problem

The naming of the User role is a bit confusing. We are adding a new user and the name of the role is also User. We should come up with a different terminology for the non-admin user role.
![image](https://user-images.githubusercontent.com/11032856/220952071-1f5a8dbd-e7fe-43e6-be89-474aea568b49.png)

## Solution
We should change the "Role" label to "User Type" and the "User" value should be changed to "Standard".

**Comment by rajatvijay** [comment]
@kgodey assigned to you since you will be coming up with the correct name. 

For the milestone: I am confused between blocker and nice to haves. Please update this too.

**Comment by Ciggzy1312** [comment]
@rajatvijay @kgodey can I give this one a try as I think it will be a good starting point for me to get involved in the project
Also considering I am aiming to take part in GSOC under mathesar

**Comment by kgodey** [comment]
@Ciggzy1312 This issue is restricted to maintainers, sorry.
