### ISSUE TITLE
Wait until server is ready after upgrade to reload page

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2566]
Reported by @dmos62:

The service layer container takes time to restart after upgrade. The frontend reloads page as soon as upgrade request completes, this causes the page to display a 502.

We need to wait until the service is ready before reloading the page.

**Comment by pavish** [comment]
@kgodey I'm prioritising fixing this, since after upgrade the page displays a 502 until the server restarts. The user would have no idea what's happening.

While we need a better solution on the backend in the long run, for the time being, I'm planning to make continuous requests to a single endpoint (with a delay) until we're met with a 200, before reloading the page after a successful upgrade.

**Comment by kgodey** [comment]
Sounds good @pavish.
