### ISSUE TITLE
Installation usability test - issues with install script

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2570]
- [x] Issues from [WB testing report](https://docs.google.com/document/d/1brAzWeIr-PYH6NJFdxTM21suk0cUmhiR/edit)
  - [x] DOCKER VERSION CHECK - too many spaces
  - [x] DATABASE CREDENTIALS - There should be an explanation that the credentials are valid for BOTH databases.
  - [x] CONFIGURATION DIRECTORY
    - [x] Change text to “The environment file will be installed at /etc/mathesar/.env” 
    - [x] Set directory permissions to `0640`
  - [x] DOCKER SETUP
    - [x] Add confirmation prompt  
  - [x] Remove example.com from superuser setup
- [x] Screenshot 1 - We need some space after "Enter the password" – configuring the local DB should be a different step or at least separated better.
- [x] Screenshot 2 - DISPLAY variable warning
- [x] ~Screenshot 3 - `43/20` is disconcerting~ wontfix

### Moved to other issues
- #2614
- #2615
- #2617

### Screenshot 1
<img width="697" alt="Screen Shot 2023-02-24 at 2 20 51 PM" src="https://user-images.githubusercontent.com/287034/221297049-5683259c-52bb-4950-ac47-4c8e24c3e938.png">

### Screenshot 2
<img width="1005" alt="Screen Shot 2023-02-24 at 2 30 17 PM" src="https://user-images.githubusercontent.com/287034/221297231-0a00111f-ebed-48f1-92fa-c57c58d30c30.png">

### Screenshot 3
<img width="1005" alt="Screen Shot 2023-02-24 at 2 30 56 PM" src="https://user-images.githubusercontent.com/287034/221297509-b5cd8eb5-e58b-4291-ba38-60658ef3df9d.png">

### Screenshot 4
<img width="1096" alt="Screen Shot 2023-02-24 at 2 44 40 PM" src="https://user-images.githubusercontent.com/287034/221297602-4a49a65d-6904-401d-a49e-d14471596321.png">

**Comment by silentninja** [comment]
> Remove example.com from superuser setup

@kgodey `email` is mandatory when creating a superuser, so we use a dummy email address. I don't think it would affect the user in any reasonable manner. So I am not sure if we need to find a workaround for this

**Comment by kgodey** [comment]
@silentninja If we add email notifications in the future (which is quite likely), then the emails set up here will all be wrong. I think it's better to prompt the user to enter their email.

**Comment by kgodey** [comment]
@silentninja It's fine to use a default and explain that we're not using email for anything yet, but we will probably support email notifications in the future.

**Comment by silentninja** [comment]
> Django reports makemigrations is needed

There is a problem with Django migration changes detector when running `migrate` after setting up Django using `django,setup()`. For some reason, it is considering `mathesar.models.query.UIQuery` model as missing. 

We can suppress the warnings but I don't want to remove other valid logs. I am thinking of adding a note before the `migrate` call to ignore the specific warning, will that be okay @kgodey ?

**Comment by kgodey** [comment]
Just ignore that issue for now @silentninja. Make a separate issue for it and we can deal with it after launch.
