### ISSUE TITLE
Installation issues on a Debian 11 server

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2572]
I tried following the installation steps in a Debian 11 server on GCP. I connected an existing database (I set one up on GCP too). It took forever, and it ended up saying `Container mathesar_service Unhealthy`.

This seems like the same issue reported by one of our usability testers. Anyone should be able to reproduce it by spinning up a Debian 11 server in GCP and trying to install Mathesar on it.

I tried stopping and re-starting Mathesar using the commands in the docs, and I got a bunch of logs, but no indication of whether the site was up. I tried going to the server's IP in my browser, but there was no response. Finally, after a few minutes, I saw the login screen. I tried logging in, but it kept telling me my username and password were wrong.

List of issues, including some additional ones I ran into:
- [ ] Installation didn't work. Installation script ended up saying `Container mathesar_service Unhealthy`
- [ ] I couldn't log in after the site was up.
- [ ] The install script stopped midway because of `wget` being missing. We should add `wget` to our dependencies and check if it's installed when we check for Docker. See "wget failure" image.
- [ ] My DB password had an `)` in it, which broke the `.env` file and the script. This password was auto-generated by GCP, so it seems like a pretty common issue.
- [ ] It took a long time to pull all the images (2-3 min), and I was worried there was something wrong. We should warn users it could take a while (or fix the issue).
- [ ] Once I stopped and started Docker, I did not know how to exit. `Ctrl+C` quit all the Docker containers and took down Mathesar. We should update the start command in the docs to be a command that runs in the background.
- [ ] The user needs to have some feedback on whether starting the containers worked successfully.
- [ ] Handle DB connectivity failing

### wget failure
<img width="587" alt="Screen Shot 2023-02-24 at 2 19 39 PM" src="https://user-images.githubusercontent.com/287034/221282401-eb48dcea-6add-4c5f-8b1c-4b10179348b1.png">

### Password failure
<img width="618" alt="Screen Shot 2023-02-24 at 2 23 33 PM" src="https://user-images.githubusercontent.com/287034/221280197-b6d3b6e0-d3fb-43d4-9a7e-91c6f5da5485.png">

**Comment by mathemancer** [comment]
> This seems like the same issue reported by one of our usability testers. Anyone should be able to reproduce it by spinning up a Debian 11 server in GCP and trying to install Mathesar on it.

I've tested the current docker image and `install.sh` on Debian 11 in GCP. In fact, _every_ docker image (that I publish) and `install.sh` are tested on Debian 11 in GCP.

**Comment by kgodey** [comment]
Weird! I figured it should be reproducible. I'll try again on Monday.

**Comment by pavish** [comment]
It is reproducible on my mac M1 atleast. `wget` does not come pre-installed and I installed it a short while back. Should I open a separate issue for it?

**Comment by mathemancer** [comment]
@kgodey @pavish Should have been more clear:
- The `wget` problem is real, but noted elsewhere.

The other issues are more debatable.
