### ISSUE TITLE
Demo Mode documentation

### ISSUE THREAD

**Issue by mathemancer** [centerofci/mathesar#2581]
## Problem

Demo mode is super useful for developers, and might even be useful for 'prod' users trying out Mathesar for the first time, since it would give them some data toy to play with initially. But, we don't have documentation for it.

## Proposed solution

We ought to document Demo mode somewhere.  For devs, the `README.md` would suffice, but I think it might be more appropriate in the main docs, since (as mentioned above) a process for 'real' users to have toy data would be pretty nice. As a supporting example, Scikit-learn (the popular python ML package) comes with a number of well-known demo / test data sets to work with.

## Additional context

The lack of this documentation, and my own faulty memory, have already generated some [issues](https://github.com/centerofci/mathesar/issues/2559) that we could have stopped before they got started.

**Comment by dmos62** [comment]
To get the ball rolling, some of the things we might want to document:

- how to setup a demo server;
- load-balancing information (if we're using it);
- demo datasets:
  - how they are defined,
  - what's special about the special datasets (e.g. arxiv);
    - and what additional logic they require;
- how each user gets a session and each session gets a database;
- how databases are provisioned (the template database).

**Comment by kgodey** [comment]
@dmos62 Should I assign this to you? I think we should add this to https://docs.mathesar.org/ under "Contributing"

**Comment by dmos62** [comment]
@kgodey sure, though I feel like I have more urgent things to work on. Could you set the priority for this task just so we're clear on how I should prioritize things?

**Comment by kgodey** [comment]
@dmos62 prioritized. I assume now that you have some fixes for the demo mode, you'll deploy and do another round of load testing. I would prioritize further tasks based on how the load testing turns out.
