### ISSUE TITLE
Issues with installation process that connects an existing DB

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2599]
- [x] Tester Marius reports (server credentials in Upwork)
  - [ ] It seems that even if you select existing database, it still tries to start a docker container for the database, creating a conflict?
- [x] Tester Mohammad reports an error as well ([details here](https://docs.google.com/document/d/15m9eZFocAsU1V9inLKxC6i_KQxMdu28snRrBPOrf5Hk/edit))

**Comment by mathemancer** [comment]
Current thinking is:
- Marius's issue stems from trying to wire up to a DB on localhost.
- Muhammad's stems from a disallowed character in the DB name.

I'll modify the script to complain about those things.
