### ISSUE TITLE
Django erroneously reports makemigrations is needed

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2615]
There is a problem with Django migration changes detector when running `migrate` command after setting up Django using `django,setup()`. For some reason, it is considering `mathesar.models.query.UIQuery` model to be missing.

**Comment by Sukriti-m** [comment]
Hi @kgodey 
I want to work on this issue.
I'd be grateful if you could assign this issue to me.

**Comment by kgodey** [comment]
Go ahead @Sukriti-m, thanks!

**Comment by aagman945** [comment]
@kgodey @Sukriti-m  `management.call_command('migrate')` are lazy it creates migration only for those models which are registered on `admin.site`, registering `UIQuery` on `admin.py` should resolve this issue

**Comment by Anish9901** [comment]
Unassigned due to inactivity.

**Comment by Sukshan** [comment]
Can I work on this issue @Anish9901

**Comment by Anish9901** [comment]
Go ahead @Sukshan.
