### ISSUE TITLE
Make Docker Setup changes from WB testing report

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2617]
Please see the "Docker Setup" section on page 10 of [this report](https://docs.google.com/document/d/1brAzWeIr-PYH6NJFdxTM21suk0cUmhiR/edit). The tester has suggested new language and provided a diff of the install script changes required. We should consider implementing these.

**Comment by SainiAditya1** [comment]
Hey @kgodey I want to work on this can u please describe in brief what exactely have to do with this issue...

**Comment by SainiAditya1** [comment]
And the above mention report is not  accessable .

**Comment by kgodey** [comment]
Out of date.
