### ISSUE TITLE
1.0 is not a boolean

### ISSUE THREAD

**Issue by frafra** [centerofci/mathesar#2656]
## Description
The software detects `1.0` as a boolean instead of a numeric, which makes the system fail.

UI: `When making an XHR request, the server responded with an error, but the response body was not valid JSON.`
Database: `ERROR:  1.0 is not a boolean`

## Expected behavior

The software should cast `1.0` to numeric.
If the auto-casting mechanism fails, an informative error should be shown.

## To Reproduce

Create a test CSV file and import it.
```column
1.0
```

**Comment by frafra** [comment]
Be aware that it is not possible to change to numeric if you have more than one column affected by this issue, as the software would state `Data Type Change Failed: When making an XHR request, the server responded with an error, but the response body was not valid JSON.`, thus making it impossible to import the data.

**Comment by kgodey** [comment]
Thank you for reporting this, @frafra. We will fix in our next release (next week).
