### ISSUE TITLE
Speed up column reflection

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#2663]
Refer to this comment for profile at the time of writing: https://github.com/centerofci/mathesar/issues/2544#issuecomment-1450451207

Currently, `mathesar/state/django.py::reflect_columns_from_tables` (or more specifically `mathesar.models.base._set_default_preview_template` call inside) is taking 1.37/4.40s. See if that can be improved.

**Comment by thesujai** [comment]
@dmos62 Thanks for assigning me this issue.
Here is a change i want to make which I think will optimize the function:

the `mathesar.models.base._set_default_preview_template` we can find `preview_settings` before if condition and simply do a if check  by `preview_settings.customized`. Also inside the if condition instead of of creating a new variable for template i.e 'preview_template' we can directly store template by `preview_settings.template=compute_default_preview_settings(table)`
and later save the settings
Like this:
    preview_settings = table.settings.preview_settings
    if not preview_settings.customized:
        preview_settings.template = compute_default_preview_template(table)
        preview_settings.save() 

This is better because we were using tables.settings twice now we are doing only once
 Let me know your views on this

**Comment by dmos62** [comment]
@thesujai please continue working on the issue, but I'll unassign you so that other contributors can work on this in parallel. That's important since we have only so many issues available for GSoC candidates to contribute to on the backend.

**Comment by Aritra8438** [comment]
Hi, @dmos62, while working on this issue, I have noticed that, ```compute_default_preview_template``` is taking **much longer** when it comes to **column reflection**.

Currently, ```compute_default_preview_template```  filters all the columns and checks which among them might be a preview column. **So, **if we have n tables with n columns**, it will take almost **O(n<sup>2</sup>)** time to filter out all the columns of a specific table and assign one as the preview column.** Moreover, this operation will be performed each time a **user creates a new table or creates a new column or deletes one.** 

One specific optimization we can do is to store the already calculated preview templates for each table and return them directly upon function call. We need to check if preview column still exists for a table as it might be deleted by the user. If it exists, we return it, else we calculate again to assign a new preview template. **This can be done using dictionary data-structure available in python and the time complexity will reduce to **O(log(n))**.**

Upon implementing this logic, there was a noticable change in **time-consumption of adding a column** (My local database contains around 18 tables with around 50 columns):

**Before implementation:**

<img width="651" alt="before_new_column_addition" src="https://user-images.githubusercontent.com/64671908/228644902-4796734e-2ca1-4b4f-95d1-5c9daef0cca6.png">

**After implementation:**

<img width="655" alt="after_new_column addition" src="https://user-images.githubusercontent.com/64671908/228645072-3a8c5a59-2923-4ac5-9a9d-3c37967b0c88.png">

**Not surprisingly,  ```compute_default_preview_template``` is now taking less.**

However, the performance didn't change considerably for **empty table creation (from scratch)** as for a table-column pair to be added to the dictionary, we need to calculate for initial assignment of preview column to the table.

**Before implementation:**

<img width="649" alt="befor_new_table_creation" src="https://user-images.githubusercontent.com/64671908/228647410-48679d19-f60f-45ee-a876-69a1c7f64f04.png">

**After implementation:**

<img width="655" alt="after_new_table_creation" src="https://user-images.githubusercontent.com/64671908/228647444-36a8403a-5557-442f-b179-5ee75d7820a9.png">

**Comment by dmos62** [comment]
Not relevant at the moment. Remove SQLAlchemy projects are currently ongoing. If optimizations in reflection are still needed, we'll likely revisit them after that. Link to first of Remove SQLAlchemy projects: https://github.com/centerofci/mathesar/issues/2737
