### ISSUE TITLE
Set up GitHub Action to automatically make a PR to develop when something is merged to master

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2664]
One idea is https://github.com/marketplace/actions/action-automerge, but it might not work because of our branch protections. We need an action that makes a PR instead of attempting to merge.

**Comment by kgodey** [comment]
Go ahead @Vikrant-Khedkar. You won't be able to test this on this repo (because of permissions), so I recommend creating a test repo and testing the action there first.

**Comment by Vikrant-Khedkar** [comment]
can you explain to me a little more like should I fork it and then do it there.

**Comment by kgodey** [comment]
I would recommend testing on a brand new repo rather than a fork so any test commits you make don't end up in the commit history here. Any repo with a master and develop branch should work.

**Comment by Vikrant-Khedkar** [comment]
okay

**Comment by Vikrant-Khedkar** [comment]
![image](https://user-images.githubusercontent.com/64966091/224410789-57814e22-fa01-41d7-99c7-24695f1bdb3c.png)
Iam getting this error

**Comment by kgodey** [comment]
@Vikrant-Khedkar Please link to whatever code is generating the error.

**Comment by HimanshuxD79** [comment]
I am interested to work on this issue

**Comment by Vikrant-Khedkar** [comment]
> @Vikrant-Khedkar Please link to whatever code is generating the error.

Okay

**Comment by Vikrant-Khedkar** [comment]
@kgodey name: Create Pull Request

on:
  push:
    branches:
      - master

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: dev
          commit-message: Automated Pull Request
          title: Automated Pull Request
Footer

**Comment by kgodey** [comment]
@Vikrant-Khedkar It looks like there's a new version of that action out, `v4`. https://github.com/peter-evans/create-pull-request. Please use that instead of `v3`.

**Comment by kgodey** [comment]
@HimanshuxD79 this issue is assigned already.

**Comment by Anish9901** [comment]
Unassigned due to a week of inactivity.

**Comment by rajatvijay** [comment]
@HimanshuxD79 would you like to work on this now?

**Comment by kgodey** [comment]
go ahead and submit a PR @AsyncDeveloper245

**Comment by PawanPatil19** [comment]
Can i get this issue assigned to me? I would like to work on it

**Comment by kgodey** [comment]
Resolved in #2801.
