### ISSUE TITLE
Update icon in exploration editor breadcrumb

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2688]
## Description
* Edit an exploration
* Notice the breadcrumb showing the exploration icon for edit:
   ![Screenshot 2023-03-16 at 12 03 52 AM](https://user-images.githubusercontent.com/11850603/225409174-8a8dff5b-8b90-44e9-8994-16d182c56f3e.png)

## Expected
* The icon shown for Edit should be an edit icon. It can imported as `iconEdit` from '@mathesar/icons'.

**Comment by Ary0405** [comment]
The edit icon saved in which folder?

**Comment by pavish** [comment]
@Ary0405 Please refer the codebase on how icons are imported. Check out `mathesar_ui/src/icons/index.ts` which exports the required icon `iconEdit` here.

**Comment by thesujai** [comment]
Can i work on this?

**Comment by pavish** [comment]
@thesujai Sure, go ahead.

@Ary0405 Since you've not expressed explicit interest in taking this issue up, I'm assigning this to @thesujai. Please feel free to look for other open issues.

**Comment by thesujai** [comment]
@pavish sorry for the last pr

I think in `routes/DataExplorerRoute.svelte` the `AppendBreadcrumb` component with `edit` label is having `icon` component set to `iconExploration`. So when we fetch the icon for the edit component by doing item.icon we are getting the exploration icon.

Setting the icon component in `AppendBreadcrumb` to `iconEdit` is solving the issue. This shows the edit icon for the edit label only.

Is this the solution we are aiming for?

**Comment by pavish** [comment]
@thesujai Yes, that's the expected solution

**Comment by thesujai** [comment]
Ok, I am creating a pr with these changes
