### ISSUE TITLE
Protect tables more

### ISSUE THREAD

**Issue by perguth** [centerofci/mathesar#2697]
## Problem

More than once I deleted a table by accident instead of deleting the record as intended.

## Proposed solution

Tables should have a higher protection level. Eg. by "copy and paste the name into this input field" like Github does it when deleting repositories.

## Additional context

The two delete buttons look quite similar and are in about the same spot in the page (different tabs of course). So it's easy to be a bit too fast. And the consequences are much bigger.

## UI Changes

- [x] Prompt users to name-verify the table to be deleted
- [x] Update Inspector Actions
  - [x] Use red warning button style for actions that are high-risk such as deleting tables or columns
  - [x] Use gray default button for actions that are lower risk such as deleting a record

### Design Reference
https://www.figma.com/file/xHb5oIqye3fnXtb2heRH34/Styling?type=design&node-id=5591-31519

**Comment by pavish** [comment]
@perguth Thanks for reporting this.

**Comment by pavish** [comment]
I'm placing this issue to fixed as part of our `0.1.2` release.

**Comment by MayaSatishRao** [comment]
@pavish can I work on this issue? Could you assign this issue to me?

**Comment by pavish** [comment]
@MayaSatishRao This issue requires some understanding of the codebase and the modal systems, and is not suitable as a good first issue for new contributors.

This issue is also a high priority and is scheduled to be part of an upcoming release. I'm restricting this to `maintainers`.

Please feel free to look for other open issues.

**Comment by kgodey** [comment]
This should be assigned to @ghislaineguerin to come up with a solution before we implement.

**Comment by ghislaineguerin** [comment]
I have updated the issue description with the needed UI changes and design reference file.

**Comment by rajatvijay** [comment]
@pavish I'll have a PR for this by tomorrow's EOD.
