### ISSUE TITLE
Set up GitHub Action to triage issues automatically when an issue has a status

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#270]
## Problem

Currently, we need to triage our issues [in the backlog](https://github.com/centerofci/mathesar/projects/2) manually.

## Proposed solution

We should set up [this action](https://github.com/marketplace/actions/move-labeled-or-milestoned-issue-to-a-specific-project-column) (or something similar) with the following rules:
- `type: meta` issues should be in the `Meta Issues` column of the Backlog project, regardless of status label.
- `status: ready` issues should be in the `Ready` column of the Backlog project
- `status: detail needed` issues should be in the `Detail Needed` column of the Backlog project
- `status: blocked` issues should be in the `Blocked` column of the Backlog project
- `status: future` issues should be removed from the Backlog project and put in the Future project (no specific column is necessary)

## Additional context
This wiki page might be helpful: [Issue Triage](https://wiki.mathesar.org/en/engineering/issue-triage)

**Comment by linzhou-zhong** [comment]
@kgodey Can I try this one ?

**Comment by kgodey** [comment]
@linzhou-zhong Sure! Assigned to you. I also updated the issue description with more details.

**Comment by linzhou-zhong** [comment]
![截屏2021-09-01 下午11 37 26](https://user-images.githubusercontent.com/15726680/131748658-2c7270f2-c6e2-4284-aeac-97a1d7d56006.png)

@kgodey If one ticket is labeled as `status: ready` and `type: meta`, it should be kept in `Ready` column or `Meta issues` column ?
