### ISSUE TITLE
Blank Error while creating new schema in live demo

### ISSUE THREAD

**Issue by Muhammad-Ahsan-Rasheed** [centerofci/mathesar#2700]
## Description
I created a new schema without following the guideline. It throw the error but with blank message.

## Expected behavior
It should throw the error like "Name is not according to format."

## To Reproduce
Error can be reproduced if anyone creates a schema with names like Test etc. 

## Environment
 - OS: (Windows)
 - Browser: (Chrome)
 - Browser Version: (111.0.5563.65)
 - Other info:

## Additional context
![image](https://user-images.githubusercontent.com/69692532/225882617-50636845-bec0-4046-9959-fe021a3cb401.png)

**Comment by pavish** [comment]
@Muhammad-Ahsan-Rasheed Could you please check your network tab in the browser's development console and provide the error thrown when the request is made?

**Comment by Muhammad-Ahsan-Rasheed** [comment]
@pavish Hi, nothing came up.

**Comment by kgodey** [comment]
@Muhammad-Ahsan-Rasheed what schema name did you use?

**Comment by rajatvijay** [comment]
Marking this as `draft` since we do not have enough info to reproduce this and work on it.

**Comment by Muhammad-Ahsan-Rasheed** [comment]
> @Muhammad-Ahsan-Rasheed what schema name did you use?

I named it as Test. I mentioned in **to Reproduce**, sorry for the late response.

**Comment by kgodey** [comment]
I cannot reproduce this issue. I created a schema called "Test" in the demo server and it worked fine. @Muhammad-Ahsan-Rasheed would you be able to try again?

**Comment by dmos62** [comment]
Cannot reproduce either. Closing. @Muhammad-Ahsan-Rasheed reopen if you're still able to reproduce.
