### ISSUE TITLE
Show both row level and column level context menu options in the cell level context menu

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2702]
## Description
* The right click context menu on a column header has the following options:
  - ![Screenshot 2023-03-17 at 5 11 03 PM](https://user-images.githubusercontent.com/11850603/225894857-e3429b75-9178-43ce-97aa-12a217b7472d.png)
* The right click context menu on a row header has the following options:
  - ![Screenshot 2023-03-17 at 5 11 43 PM](https://user-images.githubusercontent.com/11850603/225894973-f30d3f29-2070-4c4a-88aa-8f525d2632e9.png)
* The right click context menu on a cell, only shows an option to set the cell to Null.
  - ![Screenshot 2023-03-17 at 5 12 31 PM](https://user-images.githubusercontent.com/11850603/225895177-0c823d4f-2e82-4a66-9fde-07235c1132e5.png)

## Expected
* **The right click context menu on a cell should show the cell level options along with both the column level and row level options.**
* Each section should be separated by a horizontal line in the context menu, and should include headers.

Anyone working on this issue should propose a rudimentary UX design and get it approved before implementation.

----
cc: @ghislaineguerin @seancolsen @rajatvijay Do you think this makes sense?
Update: Resolved, as we are all in agreement.

**Comment by seancolsen** [comment]
This would also help un-draft #1771 because all cells would have entries in the context menu

**Comment by ghislaineguerin** [comment]
@pavish the design you described makes sense.

**Comment by seancolsen** [comment]
@pavish I marked this as ready now because I think we have enough clarity and support to implement it.

**Comment by TafreedAhmad** [comment]
What type of headers do you have in mind for a cell? Same as of row and column headers combined in a presentable manner?

**Comment by TafreedAhmad** [comment]
@seancolsen @pavish Can i work on this?

**Comment by TafreedAhmad** [comment]
![image](https://user-images.githubusercontent.com/107949435/226200130-9148318f-bf98-4383-93ee-baf9c2be44d3.png)

Something like this?

**Comment by TafreedAhmad** [comment]
> @seancolsen @pavish Can i work on this? 

@ghislaineguerin @kgodey ?

**Comment by TafreedAhmad** [comment]
> @TafreedAhmad you're on the right track. We also want dividers and headers using `MenuDivider.svelte` and `MenuHeading.svelte`. I've assigned this issue to you. Please open a PR with your changes and we can continue to discuss the implementation within the PR.

Yeah sure, I've opened the PR.
