### ISSUE TITLE
Scroll sheet all the way down when clicking the New Record button

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2704]
## Steps to reproduce

1. Identify a table with lots of records, and load its Table Page from scratch.

1. Press "New Record" button.

1. Expect to see the empty record row

1. Instead, observe that the sheet has been scrolled down, but not all the way.

    ![image](https://user-images.githubusercontent.com/42411/214366757-87f2dd28-d70d-400c-9079-b94f70152ce0.png)

    This is likely to confuse new users

**Comment by yash7raut** [comment]
I would like to work on this issue, please assign it to me.

**Comment by seancolsen** [comment]
Sure @yash7raut, go ahead.

**Comment by Ayush-Kori** [comment]
Is this open still now I would like to contribute to this.

**Comment by seancolsen** [comment]
No @Ayush-Kori, this ticket is assigned to someone else. Please see our [Contributor Guide](https://wiki.mathesar.org/en/community/contributing).

**Comment by yash7raut** [comment]
I am unassigning myself from this issue. Assign it to some other contributor.

**Comment by monstajoe2002** [comment]
Can someone assign me?

**Comment by rajatvijay** [comment]
@monstajoe2002 in light of the recent influx due to GSoC we have decided not to explicitly assign issues to the new contributors but you can start working on the issue and create a PR. Once you open a PR we will assign the issue to you.

**Comment by Sachin0277** [comment]
I wanted to work on this issue please assign me this issue

**Comment by rajatvijay** [comment]
@Sachin0277, @monstajoe2002 is already working on this. Please feel free to choose any other issue.

**Comment by monstajoe2002** [comment]
No it's okay I closed it off for someone else

**Comment by seancolsen** [comment]
@Sachin0277 I assigned this to you since it seems like @monstajoe2002 is no longer working on it.

**Comment by Sachin0277** [comment]
Thank You.
I will start working on it.

**Comment by varshadr** [comment]
Can I work on this issue?

**Comment by seancolsen** [comment]
Sure, @varshadr go ahead.

@Sachin0277 I'm unassigning you since it's been over 1 week without progress.

**Comment by PawanPatil19** [comment]
Can I have this issue assigned to me?? I want to work on it.

**Comment by Sachin0277** [comment]
Sure, You can start working.

**Comment by varshadr** [comment]
> Sure, @varshadr go ahead.
> 
> @Sachin0277 I'm unassigning you since it's been over 1 week without progress.



> Sure, @varshadr go ahead.
> 
> @Sachin0277 I'm unassigning you since it's been over 1 week without progress.

we already have a scrollBasedOnActiveCell service which scrolls to the active cell. I see, after a new record is created it becomes active, hence calling scrollBasedOnActiveCell after that should scroll the sheet to the last cell right? I'm trying to check this.

Other option we have is to play with dom, but as its a virtual list finding the active element is difficult anyone has more insights?

**Comment by Pulkit0729** [comment]
Hi @seancolsen , I will like to give it a try.

**Comment by Pulkit0729** [comment]
Added a PR #3045, it was a very simple change needed. Please review it @seancolsen .
