### ISSUE TITLE
Multiple Databases on one Server

### ISSUE THREAD

**Issue by MarkCupitt** [centerofci/mathesar#2706]
## Problem
We operate Postgres instances on Kubernetes and are looking at porting this to a K8's environment. Its not immediately obvious to us if the service supports multiple databases on one server or not, can not see any obvious way to choose between databases. Given we have 10 to 15 dbs on one server, its not practical to deploy this for each database

## Proposed solution
If that's not possible, would this be able to be implemented?

**Comment by MarkCupitt** [comment]
We figured it out .. not a relevant question .. Thanks

**Comment by kgodey** [comment]
Thanks @MarkCupitt! I see you also opened #2716, I've responded there.
