### ISSUE TITLE
No tables visible when viewing an existing schema

### ISSUE THREAD

**Issue by hydrandt** [centerofci/mathesar#2709]
## Description
When I connect to an existing schema, which was built on the [Graphile Starter project](https://github.com/graphile/starter), there are no tables.

## Expected behavior
Tables should be visible:) They are correctly counted in the list of schemas, but as soon as I enter the schema, I just get "You've created a new schema, now add tables to it."

## To Reproduce
1. install using official install script; connect to existing database of the Graphile Starter project
2. open the app_public schema
3. no tables are visible

## Environment
 - OS: Debian Sid
 - Browser: Firefox
 - Browser Version: 110.0.1

## Additional context

There are following warnings about unrecognized column types:

```
mathesar_service                | /code/db/tables/operations/select.py:20: SAWarning: Did not recognize type 'citext' of column 'email'                                                                                                
mathesar_service                |   return Table(                                                                                                                                                                                      
mathesar_service                | /code/db/tables/operations/select.py:20: SAWarning: Did not recognize type 'point' of column 'coordinates'                                                                                           
mathesar_service                |   return Table(                                                                                                                                                                                      
mathesar_service                | /code/db/tables/operations/select.py:20: SAWarning: Did not recognize type 'citext' of column 'username'                                                                                             
mathesar_service                |   return Table(                                                                                                                                                                                      
mathesar_service                | /code/db/tables/operations/select.py:20: SAWarning: Did not recognize type 'point' of column 'location_coordinates'                                                                                  
mathesar_service                |   return Table(                                                                                                                                                                                      
mathesar_service                | /code/db/tables/operations/select.py:20: SAWarning: Did not recognize type 'citext' of column 'email'                                                                                                
mathesar_service                |   return Table(                                                                                                                                                                                      
mathesar_service                | /code/db/tables/operations/select.py:20: SAWarning: Did not recognize type 'point' of column 'coordinates'                                                                                           
mathesar_service                |   return Table(  
```

**Comment by pavish** [comment]
This is a user reported issue, we need someone from the backend team to prioritize this and pick it up.
cc: @dmos62, @silentninja, @mathemancer, @Anish9901 

 I'm moving this out of 0.1.2 since there are several unknowns with the issue.

**Comment by notramo** [comment]
`citext` is an often used type, mostly used for e-mail addresses, as they are case-insensitive. It can be found in nearly every webapp which uses e-mail addresses. Could you prioritise this issue?

**Comment by notramo** [comment]
@pavish,  @dmos62, @silentninja, @mathemancer, @Anish9901
This issue makes it impossible to use Mathesar to manage the database of a [Lucky](https://luckyframework.org/) project, as the default migration creates a `citext` column for the e-mail address. Probably several other back-end frameworks are also affected by this.

I took a look at SQLAlchemy versions, and it seems that [v2.0.7](https://github.com/sqlalchemy/sqlalchemy/releases/tag/rel_2_0_7) added support for `citext` type. Mathesar uses the 1.x.x version of SQLAlchemy currently.

**Comment by silentninja** [comment]
@notramo Thanks for reporting! We are in the process of migrating away from SQLAlchemy so it won't make sense to upgrade to SQLAlchemy 2.0 but we should be able to fix this issue by having a custom type for `citext` type. 

I am moving this issue to the upcoming milestone 0.1.3, so you can expect this issue to be fixed when we release Mathesar version 0.1.3.

**Comment by dmos62** [comment]
I presume that this issue is purely about adding support for these types. Does this indeed require work from the frontend?

**Comment by dmos62** [comment]
#3040 added rudimentary support for "unknown types" (types that we've not hardcoded). See this comment for an [in-depth explanation of what rudimentary means exactly](https://github.com/centerofci/mathesar/pull/3040#issuecomment-1641819243). Basically, tables with "unknown types" shouldn't crash the backend anymore.

**Comment by notramo** [comment]
When can I expect a new release? That would make it possible to use this project.

**Comment by kgodey** [comment]
@notramo We'll be doing a new release in ~3 weeks.

**Comment by notramo** [comment]
Can I find nightly or CI build Docker containers somewhere?

**Comment by kgodey** [comment]
@notramo We pushed one for you and updated the install script in [this branch](https://github.com/centerofci/mathesar/tree/2023-06-27), which you can install with:

```
bash <(curl -sfSL https://raw.githubusercontent.com/centerofci/mathesar/2023-06-27/install.sh)
```

Please test and let us know if you find any issues.

We'll also eventually be pushing `develop` Docker images to our Docker Hub, that work is tracked in #3076.
