### ISSUE TITLE
Critical regression: Record page widgets break entirely

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2717]
## Description
* https://github.com/centerofci/mathesar/pull/2213 introduces a bug which **sets the widget table as the same as the current open table**. This commit: https://github.com/centerofci/mathesar/commit/cf62dbfcc2d915f6b3909c5dc84c97a85f9bf323
* This introduces a regression that breaks record page widgets.
* To reproduce the bug: Open record page for a record of a table which has links from other tables.

**Comment by seancolsen** [comment]
> To reproduce the bug: Open record page for a record of a table which has links from other tables.

@pavish can you elaborate? I want to make sure I understand. After you open the record page, what is your expected behavior, and what is your observed behavior?

**Comment by pavish** [comment]
@seancolsen 

Open a record from a table which is linked from other tables.

![Screenshot 2023-03-20 at 4 45 02 PM](https://user-images.githubusercontent.com/11850603/226323967-f516cef7-2e2a-4f95-9bb9-52e7ef4494a7.png)

In the above screenshot you can see that the widgets fail to load because instead of the linked tables it's trying to open the parent table, and adds a filter to itself.

This change from the PR is the cause:
```
          <TableWidget {table} {fkColumn} {recordId} />
          <TableWidget {recordId} table={currTable} {fkColumn}  />
```

Instead of passing the linked table, the parent table is passed here.

**Comment by seancolsen** [comment]
I see. Thanks @pavish

**Comment by pavish** [comment]
Fixed by https://github.com/centerofci/mathesar/pull/2731
