### ISSUE TITLE
Dragging column for reordering interferes with multi-column selection

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2720]
## Description
* In `0.1.0`, click on a column to select it. Then click on it again and move the cursor to other columns to select multiple columns.
* After the column reorder feature was introduced, clicking on a selected column makes the entire column draggable which prevents us entirely from being able to select multiple columns in that state.
* Note: We can still select multiple columns if we click and move from an unselected column.

## Expected behavior
* We need to define the UX for both these behaviours, and have a clear boundary for them.
* A possible solution is to have a dedicated drag handle for each column.

**Comment by kgodey** [comment]
@pavish if we're disabling reordering for now, is this still valid?

**Comment by pavish** [comment]
@kgodey No, this is no longer relevant. I was going through the build for 0.1.1 and testing it and raised it as part of the testing. I'll close this issue.

I do think when we pick the feature up again, this needs to be part of the consideration.
