### ISSUE TITLE
API for connecting a new Database to Mathesar

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar#2732]
## Problem
The credentials for the user Database used by Mathesar are stored as an environment variable. This environment variable is cryptic, moreover, we also need to remember to install Mathesar types and casting functions which might be repetitive across various installation processes.

## Proposed solution
- Add an API to accept the database credentials. 
- Store the credentials in the `Database` model
- Install Mathesar on the Database.

**Comment by rajatvijay** [comment]
@Wali-Muhammad123 This is still in the `status:draft`. This will need more details from core team before someone can start working on it.

**Comment by dmos62** [comment]
Related: https://github.com/centerofci/mathesar/issues/2816

**Comment by seancolsen** [comment]
Closing as this should be covered by #3291.
