### ISSUE TITLE
Database Page not reflecting updated Table Count unless reloaded

### ISSUE THREAD

**Issue by Aritra8438** [centerofci/mathesar#2736]
## Description
The Database page shows the table count of all the schemas from the last time the page is reloaded. Creating a table or deleting one doesn't change the table count of the schema. The Table count updates to the current value once it is reloaded and gets fixed to that until the next reload.

## Expected behavior
The table count should change once the tables are created or deleted.

## To Reproduce
- Go to the database page (login redirects you to this page).
- Select a schema and create a table.
- Now go back to the database page by clicking on the Mathesar icon on the left top corner.
- The table count hasn't changed.

## Environment
 - OS: Ubuntu 22.10 (Kinetic Kudu)
 - Browser: Google Chrome
 - Browser Version: 112.0.5615.29

**Comment by rajatvijay** [comment]
Thanks, @Aritra8438 that's a legit bug. I can reproduce this using the steps mentioned above. 

PS: @pavish I am this is important but not urgent hance putting this in v0.1.3 release milestone.

**Comment by pavish** [comment]
The DB page uses the `num_tables` and `num_queries` schema properties, which I don't think are updated when a table/exploration is created or deleted.

I agree this bug needs to be prioritized.

> this is important but not urgent hance putting this in v0.1.3 release milestone.

Thanks.

**Comment by Aritra8438** [comment]
Also, I want to work on this issue. Considering the added labels, can I work on fixing this issue? @rajatvijay @pavish .

**Comment by rajatvijay** [comment]
@Aritra8438 sure please go ahead. 

About assigning this to you: We generally assign issue to a new contrinutor once they have created a PR as per our contibuting guide here: https://wiki.mathesar.org/en/community/contributing#contributing-code

**Comment by thesujai** [comment]
How can this be a bug when there is a `Sync External Changes` button in db page which is for synchronizing any changes made in dbs?

**Comment by Aritra8438** [comment]
> How can this be a bug when there is a `Sync External Changes` button in db page which is for synchronizing any changes made in dbs?

Well, the help button says **If you make structural changes to the database outside Mathesar (e.g. using another tool to add a schema, table, or column), those changes will not be reflected in Mathesar until you manually sync them with this button.**
So, if we add tables to a schema inside mathesar, that should reflect.

**Comment by LuvvAggarwal** [comment]
@rajatvijay  can I work on this issue?
