### ISSUE TITLE
New issue-openers given inaccurate instructions

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#2740]
`Aritra Majumder` [writes in Matrix](https://matrix.to/#/!vXLxAqmrJWsDMWPSpo:matrix.mathesar.org/$Xw1FnYoPULMKp46XxzowP2Svo--y3WkBb7ib0wJSEAA?via=matrix.mathesar.org&via=matrix.org&via=t2bot.io):

> while opening an issue, page says `If you have a bug or an idea, read the contributing guidelines before opening an issue.`. But there isn't any specific guideline available at the corresponding wiki page for opening an issue.

The rest of the bug report (screenshoting is easier than copying and formatting):

![Capture](https://user-images.githubusercontent.com/2715476/227221195-7e8f1bd3-3a5c-4a0e-9136-c387d9cdddce.PNG)

`this page` link in the DM links to our [`CONTRIBUTING.md`](https://github.com/centerofci/mathesar/blob/3b7e7b8de3176236c51fa8b3de907c6a5d196124/CONTRIBUTING.md).

**Comment by dmos62** [comment]
Not sure where this could be defined. This is not an issue template as far as I can tell. @kgodey ideas?

**Comment by kgodey** [comment]
We need a screenshot of the text being quoted. I can't find it anywhere.

**Comment by Aritra8438** [comment]
Hi, @kgodey, this might be helpful.

![WhatsApp Image 2023-03-27 at 10 54 10 PM](https://user-images.githubusercontent.com/64671908/228020488-928353b8-4211-4554-b99b-4d8dd771fa0f.jpeg)

**Comment by kgodey** [comment]
<img width="1256" alt="Screen Shot 2023-03-27 at 1 37 56 PM" src="https://user-images.githubusercontent.com/287034/228022014-413c1805-3bd9-4a5f-9659-0a5ecd14698b.png">

@Aritra8438 is it something like this? If so, this is a default GitHub feature and there's not much we can do about it. GitHub will link to [`CONTRIBUTING.md`](https://github.com/centerofci/mathesar/blob/3b7e7b8de3176236c51fa8b3de907c6a5d196124/CONTRIBUTING.md) if it exists.

**Comment by kgodey** [comment]
> by wiki issue, do you mean opening an issue on the wiki repo?

Yes. I think we should make the change on the wiki page and leave CONTRIBUTING.md as-is, since CONTRIBUTING.md links to the wiki page and we don't want two sources of truth for contributing guidelines.
