### ISSUE TITLE
Support xlsx

### ISSUE THREAD

**Issue by smruthi49** [centerofci/mathesar#2742]
## Problem

While importing data from our system or through link, the supported type is **tabular format**. It is given as csv,tsv etc. 
It does not support **xlsx**. It supports **xls , csv, tsv**

But, while uploading **xlsx** , this happens:

![image](https://user-images.githubusercontent.com/94833021/227329745-91d5c123-8f75-4c4a-9848-6764e6aa2eaa.png)

## Proposed solution

1. Specific formats must be listed and provided. The formats which Mathesar supports must be given.
2. We can make it support **xlsx** 

## Extras

Please Let me know if it already exists and I am unable to use it.
So let me know I can work on it to support xlsx files.

**Comment by kgodey** [comment]
Supporting Excel files is a [GSoC project](https://wiki.mathesar.org/en/community/mentoring/project-ideas/import-excel-json-files). It's not as simple as accepting `.xlsx` files.

**Comment by pavish** [comment]
Removed `user reported` tag since this was reported by a GSoC applicant.
