### ISSUE TITLE
Support Importing Semicolon Separated Values file 

### ISSUE THREAD

**Issue by Aritra8438** [centerofci/mathesar#2753]
## Problem
Currently Mathesar allows importing [DSV](https://en.wikipedia.org/wiki/Delimiter-separated_values) files with following delimiters:
`,`
 `\t`
 `:`
`|`
Apart from them, semicolons`;` are popular delimiters used in industries (as address and integer generally contain commas).
## Proposed solution
It might be helpful if mathesar allows the user to import data from **semicolon-separated values** files as well.

**Comment by Aritra8438** [comment]
Hi, @dmos62, here is the **feature request** as discussed in the Mathesar Matrix channel. 
Can I work on this issue (if the labels assigned are appropriate)?

**Comment by dmos62** [comment]
Sure. In your PR, and/or here, I'd advise you to link to the underlying library's docs so that a reviewer can make sure that there aren't disadvantanges to expanding the allowed delimiter set.

**Comment by Aritra8438** [comment]
Hi @dmos62, from the docs, I have noted the following definitions that might be relevant.

- **block_char (iterable)** – Characters that are in the Punctuation Other category but that
should not be considered as **escape character**. If None, the default set is used, equal to:
`"!", "?", '"', "'", ".", ",", ";", ":", "%", "*"`

- **quote_chars (iterable)** – Characters that should be considered **quote characters**. If it is
None, the following default set is used:
`"'", '"', "~", "`"`

- **delimiters (iterable)** – List of delimiters to consider. If None, the `get_delimiters()` function is used to automatically detect the delimiter

Also, there is no evidence that semicolon can't be used as a delimiter. Rather semicolon is included in the set of **block_chars**, that means it's a potential candidate of being a delimiter.

Also, 
- **clevercsv.escape.is_potential_escapechar(char, encoding, block_char=None)**
It's a function that check if a character is a potential escape character. **A character is considered a potential escape character if it is in the **“Punctuation, Other”** Unicode category and in the list of blocked characters.**

There is a possible typo in the definition, I have reported the issue [here](https://github.com/alan-turing-institute/CleverCSV/issues/91).

Also 
>I'd read the relevant clevercsv docs, because that's where ```ALLOWED_DELIMITERS``` is used.

Can you provide me the link for this doc also?

**Comment by TafreedAhmad** [comment]
@pavish @rajatvijay is this issue still open?

**Comment by Wali-Muhammad123** [comment]
Hi, if the issue is still open... Can I have a chance to work on it?

**Comment by dmos62** [comment]
@TafreedAhmad @Wali-Muhammad123 this issue is very simple and there's already a PR for it. I don't advise opening another PR for it.

**Comment by pavish** [comment]
@ghislaineguerin This is not user reported. This was reported by a GSoC candidate.
