### ISSUE TITLE
JSON list and Map data types are unavailable as possible data types when creating columns

### ISSUE THREAD

**Issue by IamEzio** [centerofci/mathesar#2755]
## Description

When we create a table from scratch, JSON list and map data type are unavailable while creating columns. However, the column data type can be updated later on.

https://user-images.githubusercontent.com/89375125/227976163-e722e4e6-27ab-433f-a095-4c6938456e60.mp4

## Expected behavior

JSON list and map should be available as data types while creating columns.

## To Reproduce

1. Log into Mathesar.
2. Select a schema / create a schema.
3. Click on `New table` option and select `From Scratch` option.
4. Create a new column and see the available data types.

## Environment
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Browser Version: Version 104.0.5112.79 

## Additional context

None

**Comment by IamEzio** [comment]
If its fine with the maintainers, I'd like to work on this issue.

**Comment by pavish** [comment]
@IamEzio This was disabled on purpose because we the UI does not support both JSON map and list yet. This will be reenabled when the UI supports them.

**Comment by pavish** [comment]
We could maybe keep this issue open to track this. I'll leave it to @rajatvijay.

**Comment by rajatvijay** [comment]
I am closing this. 

This requires two follow-up tasks: 

1. [Do not allow the user to change column types to JSON list and Map](https://github.com/centerofci/mathesar/issues/2764)
2. Enabling these types once the UI for them is ready. This will be covered under their respective enhancement issues. .
