### ISSUE TITLE
Do not allow user to change column types to JSON list and Map

### ISSUE THREAD

**Issue by rajatvijay** [centerofci/mathesar#2764]
## Description
Creating JSON list and Map type columns were disabled from the FE since there is no proper UI for them. But the user is able to change the data type of an existing column to these types from the table inspector. 

https://user-images.githubusercontent.com/11032856/228530785-53e1d1db-c247-472e-8d44-a869f1c3e7e0.mp4

## Expected behavior
The user should not be able to change the data type of existing columns to either a JSON list or a JSON map.

**Comment by thesujai** [comment]
@rajatvijay may I work on this?

**Comment by rajatvijay** [comment]
@thesujai sure, please raise a PR.

**Comment by siddhart1o1** [comment]
@rajatvijay I want to work on this, I will make a PR.
