### ISSUE TITLE
Add Documentation for setting up Mathesar with the Mathesar Service Docker Image

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar#2783]
## Problem
Users want to use Mathesar with Kubernetes, Nomad, etc. Our docker-compose script isn't helpful in such cases. We need to provide the users an option to run a barebone version of Mathesar 

## Proposed solution
Add Documentation for setting up Mathesar with the Mathesar Service Docker Image.

**Comment by JatinKumar001** [comment]
Hey, Can I work on this issue.

And can you tell me where to add this documentation.

Thank you

**Comment by JatinKumar001** [comment]
Hey I have the solution for the same can you please let me know where I have to make these changes?

**Comment by silentninja** [comment]
Sorry @JatinKumar001 I have already started working on this issue. Please feel to pick up another issue to work on
