### ISSUE TITLE
Document our config files

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar#2784]
## Problem
  - Configuration files don't have enough comments, [preventing users from tinkering](https://github.com/centerofci/mathesar/issues/2655#issuecomment-1465731661) and adapting based on their needs

## Proposed solution
Document the config fields.

**Comment by pavish** [comment]
This documentation should also contain a dedicated section on how to configure multiple databases. 

Related: https://github.com/centerofci/mathesar/issues/2006

**Comment by silentninja** [comment]
Sorry @SafeEHA the issue is already assigned to me and I have started working on it. Please feel to pick up another issue to work with
