### ISSUE TITLE
Document upgrade instructions for non-docker-compose environments

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar#2785]
## Problem
We are planning to add additional Installation options. One-click upgrade won't be possible in these installation types.

## Proposed solution
Document upgrades to add instructions for non-docker-compose environments

**Comment by silentninja** [comment]
Blocked by #2809

**Comment by pavish** [comment]
This is fixed in https://github.com/centerofci/mathesar/pull/2809
