### ISSUE TITLE
Text wrapping in column header

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2807]
This is a regression introduced by #2699

## Good

Column names are truncated before wrapping.

(On commit 3be97bef13cedcaafe285ad0a2956e176f89e9f0 before merging #2699)

https://user-images.githubusercontent.com/42411/231209987-28ffef90-78e0-4622-ad0d-d7efb7610460.mp4

## Bad

Column names are wrapped before being truncated.

(On commit 5f44787ae21eaf09b704fd63791263ae8d50f800 after merging #2699)

https://user-images.githubusercontent.com/42411/231210908-c78072bf-92b0-49a0-bf4c-332907c6721e.mp4

**Comment by JatinKumar001** [comment]
Hey @seancolsen, Can I work on this problem?

**Comment by rajatvijay** [comment]
@JatinKumar001 sure. Assigning this to you.

**Comment by rajatvijay** [comment]
@JatinKumar001 Sorry but there is already a PR for this. 


@thesujai comment on the issue so that I can assign it to you.

**Comment by thesujai** [comment]
Let me work on this
