### ISSUE TITLE
Redo how we define user databases

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#2816]
See conversations in https://github.com/centerofci/mathesar/pull/2813 for some context.

Related to #2007.

Basically, we're currently using Django settings to define user databases, which is awkward for a number of reasons. E.g. mutating the settings dict in runtime (like in testing) can cause breakage due to thread-unsafety (or that's a dominant interpretation of some breakages we've seen).

**Comment by dmos62** [comment]
@kgodey [continuing the discussion started in another thread](https://github.com/centerofci/mathesar/pull/2813#issuecomment-1520310573).

I'll try and overview. Me and @mathemancer find the current way to define user dbs bug-prone and difficult to build upon. What we're discussing in this thread, is that when running pytest in parallel mode @mathemancer experienced false test failures caused by how we currently define user dbs. The goal of this issue then is a more robust user db definition mechanic.

Not sure which part gives you pause, so please ask about some aspect of this and I'll try and expand on it.

**Comment by dmos62** [comment]
@kgodey I went over your comment and my response and I'll add that we really don't have that much information about the false test failures we're trying to avoid. I don't really have more information than @mathemancer [submitted here](https://github.com/centerofci/mathesar/pull/2813#pullrequestreview-1384661653). That is to say, I don't understand the immediate problem.

My first instinct was to wait till we experience those false test failures and deal with it then, but @mathemancer is not comfortable with that and I trust his judgment in this case.

There's also the long-term problems of 1) Django being an implementation detail, but we're using its configuration for configuring user dbs (which are unrelated to Django), and 2) not supporting dynamic changes to user db definitions (what if we want to build a UI for it?).

**Comment by kgodey** [comment]
@dmos62 Thanks for the clarifications. I'll respond when I have more time.

**Comment by seancolsen** [comment]
Closing as this should be covered by #3294.
