### ISSUE TITLE
Text Wrapping In table name

### ISSUE THREAD

**Issue by Aritra8438** [centerofci/mathesar#2823]
## Description
Currently, table name is **getting wrapped before being truncated**. So, for the tables with long names, **we can't see the full name of the table.** 

## Expected behavior
- Table name should be truncated before getting wrapped.
- The full name should be visible on **```mouseOver```**.

## To Reproduce
- Name a table long enough.
- The bug will be visible on the schema page. 

## Environment
- OS: Ubuntu 22.04.1 LTS
 - Browser: Google Chrome
 - Browser Version: 111.0.5563.111 (Official Build) (64-bit)

## Additional context
- current behaviour:
![image](https://user-images.githubusercontent.com/64671908/232875858-f684c572-57c7-474f-9090-4c2beada76cd.png)
- expected behaviour:
![image](https://user-images.githubusercontent.com/64671908/232879660-5fe3457c-660f-4818-9313-fa50d9be7378.jpg)

This PR is related to (or very similar to) #2807 where the same bug has been reported but for column headers.

**Comment by Aritra8438** [comment]
**PR #2810 aims to fix the latter issue.**
 
As @seancolsen mentioned, the assignee might want to **submit a PR that fixes these issues at a lower level** (i.e. Both bugs should be addressed by that PR).

Also, @rajatvijay, you might want to add the ```regression``` label here as discussed in the matrix channel.

**Comment by TafreedAhmad** [comment]
@rajatvijay @seancolsen  Can I work on this?

**Comment by seancolsen** [comment]
Sorry @TafreedAhmad, I'm taking this one because we've had some mess around this problem that I want to ensure we sort out correctly without creating more mess. I want to take a very careful look at this since it's a regression and may require undoing some previous work and doing it again in a better way.
