### ISSUE TITLE
Default value of a column can't be unset

### ISSUE THREAD

**Issue by Aritra8438** [centerofci/mathesar#2835]
## Description
Currently, **it is not possible to remove default value of a column.**

## Expected behavior
Mathesar UI should support removing default value of a column.

## To Reproduce
- Set default value of a column.
- Now, there is no way to unset the default value.

## Environment
 - OS: Ubuntu 22.10 (Kinetic Kudu)
 - Browser: Google Chrome
 - Browser Version: 112.0.5615.29

## Additional context
<img width="960" alt="image" src="https://user-images.githubusercontent.com/64671908/234026864-8a228b5b-5ac4-4d94-8323-a746d216f521.png">

Clearing the input of the text fields **sets empty string as default**, instead of ```null```.
There is no ```unset/remove default``` button either.

## Reference Design
https://www.figma.com/file/xHb5oIqye3fnXtb2heRH34/Styling?node-id=5641-31738

**Comment by Aritra8438** [comment]
@ghislaineguerin, **we might need a**  ```remove default``` **button to improve user experience** and so, the design of the same.

Also, I want to work on this issue.

**Comment by ghislaineguerin** [comment]
@Aritra8438 I will assign this to myself and add a design to this issue. You can take it after and work on it.

**Comment by ghislaineguerin** [comment]
@Aritra8438 I have assigned this to you. The design has been added to the issue description.

**Comment by Aritra8438** [comment]
@rajatvijay, @ghislaineguerin Due to my ongoing college semester examination, I couldn't submit a PR. 

I will request you to keep this issue assigned to me. I will submit the PR by the 14th (My college sem ends on the 12th).
