### ISSUE TITLE
Redundant methods for creating constraints

### ISSUE THREAD

**Issue by Anish9901** [centerofci/mathesar#2850]
## Problem

Notice the `db.constraints.operations.create` and `db.constraints.base`, looks like we have 2 ways to achieve creating the same constraint. 

## Expected behavior

We should be having all the constraints creation logic in the `db.constraints.operations.create` and there should be only one method that actually creates different constraints in the db.

## Additional context

Related to RSQLA #2737

**Comment by Anish9901** [comment]
cc @mathemancer

**Comment by ayesha-firdaus** [comment]
can you assign me

**Comment by Anish9901** [comment]
Sorry @ayesha-firdaus, I am currently working on this and the details regarding solving this issue are still being figured out. Please feel free to look through other issues to solve.
