### ISSUE TITLE
Default value input steals focus when using keyboard to move active cell

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2857]
## Steps to reproduce

1. Go to to a table page with a Text column adjacent to a Number column.
1. In the table inspector, select the "Table" tab.
1. Select one cell within the Text column.
1. Use the `Right` and `Left` arrow keys to move the active cell between the Text and Number columns. Observe that the active cell moves along with your key presses. Good!
1. In the table inspector, select the "Column" tab.
1. Using the mouse, select a cell in the Text column.
1. Use the keyboard to move the active cell into the Number column. Observe that it moves. Good!
1. Also observe that **the Number input within the "Default Value" setting is focused**. Not good!

    ![image](https://user-images.githubusercontent.com/42411/235693336-716e50f2-f9a0-4141-8440-aa39d3637916.png)

1. Press the keyboard arrow keys, expecting the active cell to move with your key presses. Observe that the active cell does not move because it is no longer focused.

## Fix

- We should figure out what logic is causing that input to auto-focus and remove it.

**Comment by dauinh** [comment]
Hi! Can I work on this issue?

**Comment by seancolsen** [comment]
@dauinh I've unassigned you from this issue due to inactivity. You're still welcome to submit a PR for it, but we'll leave it unassigned so that others may choose to work on it as well.

**Comment by nikhil-babar** [comment]
@seancolsen Can I work on this issue?

**Comment by seancolsen** [comment]
Sure @nikhil-babar, go ahead

**Comment by seancolsen** [comment]
Unassigned due to inactivity

**Comment by savita-kumari13** [comment]
Hey @seancolsen created a PR for this issue - https://github.com/centerofci/mathesar/pull/2951.
Let me know of any issues
