### ISSUE TITLE
Document recommended OS user to own the /etc/mathesar directory

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2865]
We have [documentation](https://github.com/centerofci/mathesar/blob/5117e494017baba8b09419f96df4ca666f900a31/docs/docs/install/docker-compose/index.md#L63) (published to `/install/docker-compose/#manual`) which recommends that people create an `/etc/mathesar` directory when installing Mathesar, but we don't tell readers which OS use should own that directory. If readers follow our steps as-is, they will choke on step 2 due to OS permissions.

Our docs should be more explicit about the OS user/group/permissions for the `/etc/mathesar`, ideally displaying the exact `chown`/`chmod` commands that the user should run for this directory during installation.

I originally raised this point in a [Matrix discussion](https://matrix.to/#/!UZILDSNKobkelUYwBp:matrix.mathesar.org/$0UCBIcMdyWCWa6zB_t7OnUyR5oJUok4Pm2aqCf2Kem0?via=matrix.mathesar.org&via=matrix.org) and as part of a [PR review](https://github.com/centerofci/mathesar/pull/2826#pullrequestreview-1400216524).

**Comment by seancolsen** [comment]
@silentninja, I assigned this ticket to you because I think you know the most about it. But if you want to explain it to me (even in this ticket), I'd be willing to make the docs updates.

**Comment by silentninja** [comment]
@seancolsen We agreed upon not pointing to any specific directory in the installation documentation, which makes this issue invalid. Can we close it?

**Comment by seancolsen** [comment]
I see that pavish changed `wget` to `sudo wget` in f774f7bf2f9b7f4b4b8ca0077bf11f5084ffbf78 (in #2868). That change is sufficient to address my concern here, so I'll close this ticket now.
