### ISSUE TITLE
Set default value of DOMAIN_NAME to `http://localhost` in docker-compose.yml

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#2869]
## Description
* The user should be able to start Mathesar without errors by the content in our .env.example file while using our docker-compose.yml file.
* We do not have a default value for DOMAIN_NAME specified. This is mandatory for Caddy and by default it assumes it to be `https://localhost`.
* This leads to browser warnings when visiting the site after installation if the user does not configure the variable, since we wouldn't have a valid certificate.

## Expected
* Provide a default value for DOMAIN_NAME in docker-compose.yml file pointing to `http://localhost`.

**Comment by pavish** [comment]
@mathemancer or @silentninja Could one of you take a look at this and let me know if it sounds good, so that I can mark the issue as `status:ready` and make the changes?

**Comment by silentninja** [comment]
@pavish The suggested solution sounds good to me. 
By default Caddy should treat, a blank string value set to the `DOMAIN_NAME` as equivalent to `http://localhost` but instead it treats it as `https://localhost`. So it would be better to explicitly set the default value as `http://localhost`
