### ISSUE TITLE
Retrieve data with psycopg2 - Order not kept

### ISSUE THREAD

**Issue by ricnov** [centerofci/mathesar#2884]
Hello,

I noticed a strange behavior retrieving data from mathesar table with Python library psycopg2: the data are not in order according to the id in the table, but appeared randomly shuffled. Is that the standard behavior? Only with the condition ORDER BY id the order is the same as the one visible to the user

Regards

**Comment by dmos62** [comment]
@ricnov could you clarify how you're retrieving data from a Mathesar table? Are you doing that from another Python program? Your comment about using psycopg2 makes me think that.

We do take care to always order records when returning them within our codebase. We can't impose an ordering if you're not using our library.

**Comment by ricnov** [comment]
@dmos62 Hello, yes I was using another Python program to retrieve the data

**Comment by dmos62** [comment]
@ricnov cool. That means that you have to take care of all processing, including sorting yourself (unless you use our libraries to do the retrieval). I'll close this since this isn't a bug. Unless I misunderstood something, feel free to try and reexplain if that's the case.
