### ISSUE TITLE
Frontend utils: CancellablePromise, FilterUtils

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#290]
These utils are currently present at `/mathesar_ui/src/component-library/common/utils`.

We still need to handle:
* Unit tests
  - Unit tests need to be placed within `/mathesar_ui/src/component-library/common/utils/__tests__`.
  - Naming convention: `{moduleFilename}.test.ts`
* Documentation
  - The files/methods in them need to be commented with their purpose, and any additional information which would make it more accessible for new contributors.

**Comment by patelaryan7751** [comment]
@kgodey @pavish  may I work on this issue ?

**Comment by pavish** [comment]
@patelaryan7751 Sure. Thank you!

**Comment by patelaryan7751** [comment]
Can you give some more information on this ?

**Comment by pavish** [comment]
@patelaryan7751 I've updated the description of this ticket with more information. If you have further questions, or need help setting up Mathesar locally, we could discuss on the Mathesar Matrix channel.

**Comment by patelaryan7751** [comment]
> @patelaryan7751 I've updated the description of this ticket with more information. If you have further questions, or need help setting up Mathesar locally, we could discuss on the Mathesar Matrix channel.

yeah sure!!

**Comment by kgodey** [comment]
@patelaryan7751 Just checking in on this issue. How is it going, and do you need any help?

**Comment by patelaryan7751** [comment]
Actually my health is not good so i am not able to focus on it.

**Comment by kgodey** [comment]
@patelaryan7751 sorry to hear that. I'll un-assign this issue for now. Please let me know when you have more time and we'll find you a new one. I hope you feel better soon.

**Comment by ishqelliot** [comment]
@pavish @kgodey is this still unassigned? can I pick it up?

also was checking utils path mentioned in the description though couldn't find `common` folder under `mathesar/mathesar_ui/src/components/` (under master branch)

**Comment by silentninja** [comment]
@ishqelliot  Sure, thanks! The components folder has been renamed to [component-library](https://github.com/centerofci/mathesar/tree/master/mathesar_ui/src/component-library/common/utils)

**Comment by pavish** [comment]
@ishqelliot I've updated the description of this issue with the correct file path. Let us know if you have any questions. Please feel free to join our [Matrix channels](https://wiki.mathesar.org/en/community#matrix) for more impromptu discussions.

**Comment by ishqelliot** [comment]
cool thanks, got the utils now, will start, have joined the matrix.

**Comment by pavish** [comment]
Hey @ishqelliot, checking in on this issue to see how it's going. Is it going well? Do you require any help?

Please let us know if you need any additional support from us.

**Comment by ishqelliot** [comment]
Hey @pavish sorry for responding this late, was caught up in something. have already covered tests for filterUtils, have started on CancellablePromise, will wrap it up in couple of days.
