### ISSUE TITLE
`AbstractType: Money, URI, Email` columns throw error when summarization is applied

### ISSUE THREAD

**Issue by Aritra8438** [centerofci/mathesar#2908]
## Description
`Money` columns can not be aggregated based on some other grouping column. 
(There won't be any problem, if `Money` column is the grouping column)

## Expected behavior
Users should be able to aggregate `Money` column based on another grouping column. 

## To Reproduce
- Create a table, add two columns, one of them should be `Money` column.
- Go to **Data Explorer**, Select the other column first, then add `Money` column.
- Then go to `Transformation Step` and `Summarize`.

Not every table will produce this error. (refer to **Additional Context**)

Screencast:

https://github.com/centerofci/mathesar/assets/64671908/518006d9-2c5c-4a19-b935-54e0714c4ccf

## Environment
 - OS: Ubuntu 22.10 (Kinetic Kudu)
 - Browser: Google Chrome
 - Browser Version: 112.0.5615.29
 
## Additional context
**The folowing table will not produce the error.**

<img width="395" alt="image" src="https://github.com/centerofci/mathesar/assets/64671908/9b14743a-dc46-487e-bce7-15f98875acdd">

**While this modification will produce the error**.

<img width="396" alt="image" src="https://github.com/centerofci/mathesar/assets/64671908/e35fcb30-e9cd-4f8a-9aaf-3b4dbdb23cd7">

**Comment by seancolsen** [comment]
ping @mathemancer in case you have any ideas what might be causing this bug

**Comment by Aritra8438** [comment]
@mathemancer, While we were discussing things earlier, you pointed out that, `DISTINCT` can not be applied on `DB type(s)` which don't have an equality operator. The error might be due to that?

**Here is the error:**

![image](https://github.com/centerofci/mathesar/assets/64671908/a2052631-b8d4-4d56-b888-ff758960298d)

**Here is the error text:**

- (psycopg2.errors.SyntaxError) syntax error at or near "DISTINCT" LINE 5: ...aults" AS "Test_defaults_grouped", array_agg(CAST(DISTINCT a... ^ [SQL: WITH anon_3 AS (SELECT "Testing"."Test".defaults AS "Test_defaults", "Testing"."Test"."Money" AS "Test_Money" FROM "Testing"."Test"), anon_2 AS (SELECT anon_3."Test_defaults" AS "Test_defaults_grouped", array_agg(CAST(DISTINCT anon_3."Test_Money" AS NUMERIC)) AS "Test_Money_agged" FROM anon_3 GROUP BY anon_3."Test_defaults"), anon_1 AS (SELECT count(%(count_1)s) AS _count FROM anon_2) SELECT anon_1._count FROM anon_1] [parameters: {'count_1': 1}] (Background on this error at: https://sqlalche.me/e/14/f405)
