### ISSUE TITLE
Frontend components: Select

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#291]
These components are currently present. However, we still need to handle:
* [x] #374
* [x] #376
* [x] #375 
* [x] #483
* [x] #608

**Comment by pavish** [comment]
Split out ARIA accessibility for Select: https://github.com/centerofci/mathesar/issues/374

**Comment by pavish** [comment]
Split out documenation to https://github.com/centerofci/mathesar/issues/375

**Comment by kgodey** [comment]
@pavish I updated the main description to use the new GitHub task lists feature.
