### ISSUE TITLE
Styling changes for documentation website

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#2919]
We need to make some style updates to the documentation website to make it more readable.

### Tasks
(1) "Mathesar Documentation" & "On This Page" headers need to be styled differently (text color, size, etc.) to make it clear that they are headers and not part of the nav. Currently, the styling is too similar to nav items. Maybe add a bottom border?
![Screen Shot 2023-06-05 at 4 57 29 PM](https://github.com/centerofci/mathesar/assets/287034/efe98081-9e8e-4531-b3a1-217025c03b85) ![Screen Shot 2023-06-05 at 4 57 33 PM](https://github.com/centerofci/mathesar/assets/287034/e8d99a81-12e0-48e1-9a4d-6458dac2adaa) ![Screen Shot 2023-06-05 at 4 57 46 PM](https://github.com/centerofci/mathesar/assets/287034/c2c0a0cb-f3f0-4820-8160-30612d4d11ff) ![Screen Shot 2023-06-05 at 4 57 42 PM](https://github.com/centerofci/mathesar/assets/287034/f5aa77d6-dfe3-4ed2-bb20-a73577733173)

(2) Links need to be more prominent - they should be different color from main text. This appears to be a regression – links at docs.mathesar.org are blue, but links in the 0.1.2 branch are the same color as the text.

(3) The section headers should be more visually distinct from the actual links you can click on. e.g. in the below screenshot "Installation" is a section header but it's only a slightly bolder version of the actual links.

![Screen Shot 2023-06-05 at 5 00 24 PM](https://github.com/centerofci/mathesar/assets/287034/45065dd9-3a43-4453-aa31-e8c91dc0774d)

The NocoDB docs do this well see "Welcome", "Getting Started" etc. in the sidebar at https://docs.nocodb.com/

(4) Make "current page" styling more distinct from "nav section header" styling

In this screenshot, the current page is "Welcome" and the section header is "Introduction". The styling looks identical.

![Screen Shot 2023-06-05 at 5 02 46 PM](https://github.com/centerofci/mathesar/assets/287034/b2794ed7-a799-4724-bea5-96d3824b95f4)

(5) "On this page" section should be more visually distinct or prominent so that it stands out as the table of contents. Currently it looks identical to the left nav even though the purpose of the two is different.

### Additional context
- Please work off of my branch https://github.com/centerofci/mathesar/pull/2907 since I made some MkDocs configuration changes there that change the look of the site.
- Please note that all style changes should be tested in both dark mode and light mode.

**Comment by silentninja** [comment]
can we also add the feedback from the tester to make the sidebar fonts more visible([Relevant Matrix discussion](https://matrix.to/#/!dwNKVEeYPiAqvkytob:matrix.mathesar.org/$Jpf6-I1uC60ShgpX49ofSRZwysMkBwFZE4sQY1iMXLU?via=matrix.mathesar.org&via=matrix.org)) on this list?

**Comment by kgodey** [comment]
@silentninja Isn't that feedback covered by (1) and (5)?

**Comment by silentninja** [comment]
> @silentninja Isn't that feedback covered by (1) and (5)?

You are correct. (1) and (5) should cover that feedback.

**Comment by kgodey** [comment]
@ghislaineguerin Thanks for the style changes in #2907. This is an improvement, but I still have some feedback:

Feedback:
(1) I don't like underline for "Mathesar Documentation" and "On This Page", it competes too much with the main page header which also has an underline
<img width="1331" alt="Screen Shot 2023-06-06 at 2 21 00 PM" src="https://github.com/centerofci/mathesar/assets/287034/a6f66916-499e-43ee-b3cb-0420c0736e56">

(2) My feedback (5) from the original list seems unaddressed. Both navs are very similar looking.

(3) The link color is not very readable on dark mode
<img width="406" alt="Screen Shot 2023-06-06 at 2 23 04 PM" src="https://github.com/centerofci/mathesar/assets/287034/2efdb2bc-9fc4-4123-ae28-2863ba033234">

(4) Can we try to make the nav headers ("Installation", "Configuration", etc.) more like the ones in NocoDB's docs? https://docs.nocodb.com/ – the typography makes it very clear that those are not click targets. In our docs, they seem like they would be click targets.

**Comment by ghislaineguerin** [comment]
@kgodey I've pushed changes to address your feedback. Please let me know what you think.

**Comment by kgodey** [comment]
@ghislaineguerin it's looking better, here's a little more feedback:

(1) Sub-list items are looking weird. See the spacing of the items under "Appendix to guided script".

![Screen Shot 2023-06-07 at 4 08 11 PM](https://github.com/centerofci/mathesar/assets/287034/f65ff6b7-fe26-4fc6-8acc-c66f29809b70)

(2) There's something weird going on with the header in dark mode

![Screen Shot 2023-06-05 at 5 02 46 PM](https://github.com/centerofci/mathesar/assets/287034/4a8d2549-51a1-4cb9-a7b9-3de40862f9ab)

(3) The link color is now a bit hard to read in light mode. Can we have different link colors for dark and light mode, rather than trying to find a shade that works with both?
![Screenshot 2023-06-07 at 16-09-32 Welcome - Mathesar Documentation](https://github.com/centerofci/mathesar/assets/287034/986903e1-4efe-4101-9425-62c05cc383bf)

(4) Can we try to make the "On this page" section more prominent? Maybe the background color of that menu could be different?

**Comment by ghislaineguerin** [comment]
@kgodey I've pushed additional changes. please review.

**Comment by kgodey** [comment]
@ghislaineguerin Looks good, nice work! No further feedback.

**Comment by kgodey** [comment]
Moving this back to 0.1.2 since all the feedback in this ticket was addressed in the release. #2937 addresses additional feedback that was not tracked in this ticket.
