### ISSUE TITLE
File import preview page

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#295]
Implementation of the file import preview page based on design spec.

  - Show preview of a small set of rows
  - Allow users to change type of column
  - Allow users to change name of columns
  - Use/Not-use first row as headers
  - Tests

**Comment by pavish** [comment]
Blocked by #294

**Comment by kgodey** [comment]
This is still blocked until #506 is merged.

**Comment by kgodey** [comment]
This is now unblocked. Please refer to https://wiki.mathesar.org/engineering/architecture/import-preview-api for the various APIs that will back this page.
