### ISSUE TITLE
Fix incorrect API schema generated by drf-spectacular 

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar#2954]
## Problem

The API spec generated by the `drf-spectacular` library is incorrect for some of the API paths.

## Proposed solution

The generated spec for these APIs can be fixed by manually overriding the inferred APIs spec using custom decorators.
```[tasklist]
### Tasks
```

**Comment by varshadr** [comment]
This issue will be resolved under #2958 .
Hence, closing this issue here.
