### ISSUE TITLE
Column info in `data-explorer` not shown for columns with `hyphenated` name

### ISSUE THREAD

**Issue by Aritra8438** [centerofci/mathesar#2955]
## Description
If column name contains hyphen (e.g. `a-b`), then 
- The column information won't be available under column tab in the inspector in data-explorer.
## Expected behavior
Hyphenated column name is widely used and therefore should work propoerly.
## To Reproduce
- Create a column and give it a name `a-b` (or any hyphenated name)
- Open data explorer and add this column to transformation step.
- Select the column, there won't be any properties available under the column tab in the inspector.

Here is a screenshot of the same:

![image](https://github.com/centerofci/mathesar/assets/64671908/00eeaf32-099f-451c-ad87-9aea3ab686cc)

## Environment
- OS: Ubuntu 22.04.1 LTS
 - Browser: Google Chrome
 - Browser Version: 111.0.5563.111 (Official Build) (64-bit)

**Comment by seancolsen** [comment]
Sure @Aritra8438, go ahead.
