### ISSUE TITLE
Import status indicators

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#296]
We need clear indication of current uploads, in a prominent manner (Similar to how google drive upload works?). Design spec needs to be revised to handle this.

  - Show current uploads prominently
  - Indicate loading on sidebar
  - Indicate users to not close the browser tab/window
  - Tests

**Comment by pavish** [comment]
Blocked by #149, #293 and design spec.

@kgodey and @ghislaineguerin Please let me know if we can update the design spec to add a prototype for this, or if you have any other solution in mind. I've created this ticket, to keep track of the above mentioned requirements.

**Comment by ghislaineguerin** [comment]
Finalized spec can be found here: https://wiki.mathesar.org/en/design/specs/import-status

**Comment by kgodey** [comment]
Reopening because this issue is for the frontend work related to implementing the spec.
