### ISSUE TITLE
Remove the lazydict dependency

### ISSUE THREAD

**Issue by spapas** [centerofci/mathesar#2960]
## Problem
This project has a depencdency on lazydict (https://github.com/janrain/lazydict) which is no longer supported (latest version is 7 years ago)  and does not work with Python 3.10.

## Proposed solution
The lazydict is used only on one place in the code  https://github.com/centerofci/mathesar/blob/76f9d8517dd28d5255852b49f9ab864b5721fd8e/mathesar/api/display_options.py#L4
to avoid re-evaluating the `_money_display_options_schema`... There are a lot of ways that this can be resolved, for example instead of the lazydict we could use a normal dict and wrap `_money_display_options_schema` with `functools.cache` (https://docs.python.org/3/library/functools.html#functools.cache) to evaluate it only once.

## Additional context
I'd be happy to provide a PR for resolving this.

**Comment by silentninja** [comment]
@spapas Please feel free to send a pull request for this issue.
