### ISSUE TITLE
Add margin between the breadcrumb selector and the bottom of the viewport

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2982]
## Current behavior

- The top navigation header has a "breadcrumb selector" which allows the user to pick a database, schema, or table.

- When the list of items within the selector is quite long, the selector extends to fit almost the full height of the viewport. A small gap is left on top. But the bottom of the selector is flush with the bottom of the viewport.

    ![image](https://github.com/centerofci/mathesar/assets/42411/8c3ac7ad-2a7e-4f84-b44f-ab4198d5eb70)

## Desired behavior

- We should increase the margin at the bottom of the selector so that it matches the gap at the top.

## Additional context

- This changes was originally suggest by @ghislaineguerin in a Matrix [conversation](https://matrix.to/#/!vAyoAQoixqNrvBuIcH:matrix.mathesar.org/$HuBS0qw2pW3s5YdB6bNil4rUdFa9UYhpH6QLtC4A_EM?via=matrix.mathesar.org&via=matrix.org).

**Comment by racky7** [comment]
Can I work on this issue?

**Comment by seancolsen** [comment]
Sure, go ahead @racky7

**Comment by racky7** [comment]
![Screenshot from 2023-07-02 00-41-06](https://github.com/centerofci/mathesar/assets/74532684/a0341e1f-63a2-4a6d-be8e-8bc8ac356b19)

Hey @seancolsen, I have tried to install mathesar locally using docker but failed. It stucks to "Attaching ..." something, also I tried installing from scratch using https://docs.mathesar.org/installation/build-from-source/ but getting stuck at "Set up gunicorn". 

Can you please help me?

**Comment by seancolsen** [comment]
@racky7 Come chat with us on [Matrix](https://wiki.mathesar.org/en/community/matrix) to troubleshoot problems like this. It'll be easier there.

**Comment by racky7** [comment]
Sure, Thanks!

**Comment by thesujai** [comment]
@racky7 are you working on this?

**Comment by racky7** [comment]
No, sorry! I have unassigned myself.

**Comment by thesujai** [comment]
@seancolsen  Assign this to me

**Comment by rajatvijay** [comment]
@tush-rastogi can you comment on this so that I can assign this to you
