### ISSUE TITLE
URL cell loses focus when clicking on its contained hyperlink

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#2988]
## Steps to reproduce

1. Prerequisites:
    1. On the table page click on a cell to focus it.
    1. When the cell is focused, you can use the <kbd>Up</kbd> and <kbd>Down</kbd> arrow keys to move the active cell. This is good.
    1. Click on the "Filter" button above the table to open the filtering dropdown. Click it again to close it. Now that button is focused instead of a cell, and you won't be able to use the arrow keys to move the active cell. This is okay, but important to understand.

1. Set up a column with a URL type.
1. Into a cell in that column, enter a relatively short URL like `http://a.b`
1. Click on different cell to make your URL cell inactive.
1. On your inactive URL cell, click _the link text_.
1. Observe that the cell is selected and active (has a thick border). Good!
1. Expect the cell to also be focused, but instead observe that it is not focused (because the link inside the cell is focused instead). Bad.
1. Click on some empty space in the cell but outside the link. Now observe the cell to be focused. Good.

**Comment by manthan-jsharma** [comment]
this looks like a valid issue to me

@pavish , @rajatvijay , can i pick this up ?
