### ISSUE TITLE
The requirement of superuser postgresql access is problematic

### ISSUE THREAD

**Issue by spapas** [centerofci/mathesar#2990]
## Problem
Mathesar needs a Postgres superuser to function correctly, from the docs at https://docs.mathesar.org/installation/build-from-source/ 

## Proposed solution
The mathesar user should not require superuser access. 

## Additional context
The superuser is a global permission meaning that a user that has superuser permission will be able to access (and do stuff) not on the mathesar but *all* the databases of the RDBMS. Considering that many production systems have a single RDBMS hosting many application this is a major problem since the mathsar user won't have any access boundaries on the same RDBMS. The mathesar user access can be unlimited but *must* be bounded without the mathesar database.

**Comment by kgodey** [comment]
Thanks for reporting this, @spapas. This is already a high-priority issue for us to resolve, requiring a superuser is one of the compromises we made to get our alpha version out of the door.

**Comment by spapas** [comment]
Hello friends, any news on this issue? This is very important for us and we can't actually use mathesar in procution until the supertuser requirement is dropped. 

Would it be possible to clarify a bit why the mathesar usr needs global superuser access ? What would happen if we removed the RDBMS superuser access on the mathesar user and made him an owner of the corresponding databases (i.e mathesar_data and mathesar_django) ? 

Thank you

**Comment by rajatvijay** [comment]
Hi @spapas 

We are working on this issue under the [Installations Improvement Project](https://wiki.mathesar.org/en/projects/installation-improvements-0_1_3). This will be part of Release v0.1.3(coming next month)

**Comment by spapas** [comment]
Thank you @rajatvijay for answering me a giving a delivery estimate!

Kind regards,
Serafeim
