### ISSUE TITLE
Support xls and xlsx

### ISSUE THREAD

**Issue by spapas** [centerofci/mathesar#2994]
## Problem
Mathesar does not support excel files (xls or xlsx). Please see this file: 

https://github.com/centerofci/mathesar/blob/0d99ee984206a99c6743a319504a1d86621d71d5/mathesar/imports/base.py#L13

## Proposed solution
Mathesar should support both xls and xlsx files. This should be simple to do with the xlrd (for xls) and openpyxl (for xlsx) libraries and the implementation would be similar to csv.

## Additional context
It is important to keep in mind that non-technical users can't really use csv but are comfortable with xls and xlsx. Implementing this feature would make mathesar much more friendly for these users.

I see that there's an issue about xlsx files: #2742 however it seems to be closed ? If you want and nobody else is working on that I can try providing a PR implementing the xls and xlsx features.

**Comment by rajatvijay** [comment]
@spapas there is already a GSoC project for this & its currently being worked upon. https://wiki.mathesar.org/en/community/mentoring/project-ideas/import-excel-json-files

**Comment by kgodey** [comment]
Reopening, since we definitely are planning to do this. 

I'm checking with @IamEzio about how the work is going and will update this issue afterwards with next steps.

**Comment by kgodey** [comment]
Assigning to @IamEzio since he's starting work on this this week, and putting this in the GSoC milestone.

**Comment by axellpadilla** [comment]
Hi, just checking into, cant see this feature?
