### ISSUE TITLE
Repetition of word "ensure" in point one of "Local Development Setup" - DEVELOPER_GUIDE.md

### ISSUE THREAD

**Issue by tush-rastogi** [centerofci/mathesar#2998]
## Description

I noticed a repetition of the word "ensure" in point one of the "Local Development Setup" section of the DEVELOPER_GUIDE.md .The repetition is causing confusion and affects the readability of the instructions. I would like to report this issue and suggest a correction.

## Details

**File**:DEVELOPER_GUIDE.md
**Section**:Local Development Setup
**Point**:1
**Current text** : Ensure ensure that you have [Docker](https://docs.docker.com/get-docker/) installed.
**Suggested Correction** : Ensure that you have [Docker](https://docs.docker.com/get-docker/) installed.

**Comment by seancolsen** [comment]
@tush-rastogi Thanks for your work on this! For future reference, small PRs like yours in this case don't warrant a dedicated ticket. You're free to open a PR without an associated ticket if that is easier for you.
