### ISSUE TITLE
Error while update & import 

### ISSUE THREAD

**Issue by quangbahoa** [centerofci/mathesar#3002]
## Description
- Cannot upload import files.

## Expected behavior
- Upload & Import

## To Reproduce
- Install Mathesar from source on Ubuntu.
- Create table from import data
- Upload `.tsv` or `.csv` files.
- Error show:

> Failed to import data
> An error has occurred while uploading file

- Browse console error show:
```
Failed to load resource: the server responded with a status of 500 ().      /api/db/v0/data_files/:1
POST https://***.com/api/db/v0/data_files/ 500.    main.dcd458ab.490de31694b8.js:16
```
- I still can access `https://***.com/api/db/v0/data_files/`. It's show [Django REST framework](https://www.django-rest-framework.org/)

## Environment
 - OS: Ubuntu 22.04 
 - Browser: Chrome
 - Browser Version: 114.0.5735.133
 - Other info: Node v18.16.1

**Comment by Aritra8438** [comment]
Hi, @quangbahoa, what delimiter was used in the `.tsv` file?

**Comment by quangbahoa** [comment]
> Hi, @quangbahoa, what delimiter was used in the `.tsv` file?

I use `,` . I've test same file on your demo working fine.

**Comment by kgodey** [comment]
@quangbahoa 
(a) Could you link to the installation instructions that you followed? Did you make any modifications to the installation process?
(b) Could you paste the error response from the API here? Your browser's developer tools should give you the full response from the server.

**Comment by quangbahoa** [comment]
> @quangbahoa 
> 
> (a) Could you link to the installation instructions that you followed? Did you make any modifications to the installation process?
> 
> (b) Could you paste the error response from the API here? Your browser's developer tools should give you the full response from the server.

Please check here: https://cdb.vietlac.com
User: `mathesar`
Pass`12191219`

Im follow install wiki and not modify anything.

**Comment by mathemancer** [comment]
@quangbahoa I've confirmed that it's not possible to load a csv (or TSV) file to your installation. Also, to get logged in I had to change the password to `a12191219`, so be aware of that.

I was able to create a table manually (i.e., from scratch without uploading something

Questions that might help us understand what's happening:
- What are the resources available to Mathesar? (I.e., memory, cpu, disk space)
- Where on your disk did you install Mathesar? I.e., was it `/etc/mathesar`, `home/<username>/mathesar`, or somewhere else?
- In the git repo for mathesar, do you have a directory `.media`? If so, can you view it? Can the user mathesar is running as create a file there?

My gut instinct says that mathesar is having problems writing to the area on your disk where it keeps media files after upload, and before importing them to the database. However, that's only a guess because there isn't much info for me to go on. If you answer the questions above, we might get a solution.

**Comment by quangbahoa** [comment]
@mathemancer 
- I'm install on Azure Standard_D4as_v5: https://learn.microsoft.com/en-us/azure/virtual-machines/dasv5-dadsv5-series
- Locate `/home/cdb` - `/home/cdb/mathesar-venv`
- Inside venv
```
(mathesar-venv) root@mathesar:/home/cdb# ls -a
.                       LICENSE                 install.sh
..                      LICENSES                lint.sh
.dockerignore           README.md               manage.py
.env                    THIRDPARTY              mathesar
.env.example            config                  mathesar-venv
.flake8                 conftest.py             mathesar_ui
.git                    currency_info.json      pyproject.toml
.github                 db                      requirements-demo.txt
.gitignore              demo                    requirements-dev.txt
.media                  dev-run.sh              requirements-prod.txt
CONTRIBUTING.md         docker-compose.dev.yml  requirements.txt
Caddyfile               docker-compose.yml      run.sh
DEVELOPER_GUIDE.md      docs                    setup
Dockerfile              fixtures                setup.cfg
Dockerfile.caddy        get-pip.py              static
Dockerfile.integ-tests  install.py
```
- Outsite venv
```
root@mathesar:/home/cdb# ls -a
.                       LICENSE                 install.sh
..                      LICENSES                lint.sh
.dockerignore           README.md               manage.py
.env                    THIRDPARTY              mathesar
.env.example            config                  mathesar-venv
.flake8                 conftest.py             mathesar_ui
.git                    currency_info.json      pyproject.toml
.github                 db                      requirements-demo.txt
.gitignore              demo                    requirements-dev.txt
.media                  dev-run.sh              requirements-prod.txt
CONTRIBUTING.md         docker-compose.dev.yml  requirements.txt
Caddyfile               docker-compose.yml      run.sh
DEVELOPER_GUIDE.md      docs                    setup
Dockerfile              fixtures                setup.cfg
Dockerfile.caddy        get-pip.py              static
Dockerfile.integ-tests  install.py
```
- I'm install with `root` user.

**Comment by quangbahoa** [comment]
I'ts working! Thanks
