### ISSUE TITLE
Unique columns

### ISSUE THREAD

**Issue by mathemancer** [centerofci/mathesar#302]
**Problem**

Mathesar can currently only handle uniqueness constraints on a primary key column.  We should be able to create non-primary-key columns that also have a uniqueness constraint at the DB level.

**Proposed solution**

Add a uniqueness constraint argument to the `MathesarColumn` class.

**Additional context**

Related to #199 :  The spec requests being able to modify the uniqueness condition on a column, but that's currently not supported by our column object.

**Comment by kgodey** [comment]
@mathemancer I'm assigning this to myself because it's related to my work in
- #326
- #488

**Comment by kgodey** [comment]
I talked to @mathemancer about this issue on a call and we decided against implementing it #326 supersedes this. We don't need a column level unique constraint, we can make all constraints at the table level.
