### ISSUE TITLE
Design spec for Mathesar superuser creation page

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar#3054]
## Problem
A Mathesar superuser is required before a user can start using Mather. The process to create a Mathesar superuser is done using the command line which is slightly complicated and varies based on the installation types. So we will help the user create a Mathesar superuser when Mathesar is launched for the first time(or until a superuser is created) using the Mathesar UI. 

## Proposed solution
A superuser creation page which the user will see when they visit Mathesar for the first time after installing it. It should have a form for accepting the following information.
- username
- password
- confirm password

We also need to inform the user to remember the password they used.

#### Possible states
- Loading states
   - A loading indicator should be shown when submitting the form
- Error states
  - Password mismatch error
  - Invalid characters or short password
- Success state
  - The user is logged in and then redirected to the home page gracefully.

The screen is quite similar to the login page with extra fields for `confirm_password`. So maybe it can be used as a reference.

**Comment by ghislaineguerin** [comment]
@silentninja Please see the design for this feature here:
https://www.figma.com/file/xHb5oIqye3fnXtb2heRH34/Styling?type=design&node-id=5915-32031&mode=design

![image](https://github.com/centerofci/mathesar/assets/845767/5cf5b109-e589-4e46-a597-622a58ed2b2b)
![image](https://github.com/centerofci/mathesar/assets/845767/e81c5158-19b7-4e41-ac97-01d3bb27798c)
![image](https://github.com/centerofci/mathesar/assets/845767/63646904-28b0-42dd-b16e-9d1b379d97dc)
![image](https://github.com/centerofci/mathesar/assets/845767/62083bd1-af56-4f1e-a954-8bcb5815ea39)

**Comment by kgodey** [comment]
@ghislaineguerin Can we add some help text or explanation about why they need to create a user at this stage and what the impact of the action is? 

Also, I don't think we should call this "Create superuser", that is a backend term. I think we are calling the user an "Admin" user elsewhere. Please make sure all terminology used is consistent with the rest of the product.

**Comment by silentninja** [comment]
> We need to inform the user when the superuser is created successfully and redirect him to the login page gracefully.

While I intended it to be a step to make sure the user actually knows the password he used while registering and verify he set things up correctly but after looking at the design, this step looks redundant as we can "log in" the user automatically after the registration is successful. I am not sure what is the best UX any ideas @kgodey @ghislaineguerin

**Comment by ghislaineguerin** [comment]
If we can log them in directly then I'd say we can just add a warning so that they know to "store or remember" the password.

**Comment by kgodey** [comment]
I think it's better to have fewer steps for the user, so I think we should log the user in automatically with a warning to store the password like @ghislaineguerin said.

**Comment by silentninja** [comment]
@kgodey @ghislaineguerin Thanks! I updated the description based on the feedback

**Comment by silentninja** [comment]
@ghislaineguerin The design spec still shows a login screen. I thought we planned to log in the user automatically. So they should be redirected to the home page correct?

**Comment by rajatvijay** [comment]
@ghislaineguerin & I talked. We updated the designs to remove the header and make it look more like the current login page(white card with sand background) to reduce the unnecessary scope. We can circle back to this if and when we do the step-by-step installation. 
Updated designs: [Figma](https://www.figma.com/file/xHb5oIqye3fnXtb2heRH34/Styling?type=design&node-id=5915-32031&mode=design)

**Comment by kgodey** [comment]
I have some feedback on the copy in the updated style, please tag me in the PR that implements the design and I'll make the changes there.
