### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by spapas** [centerofci/mathesar#3065]
## Problem
I can't really understand what features are added or bugs are fixed in mathesar unless I take a look at all the commit messages. 

## Proposed solution
Add a changelog that would list all important changes. 

## Additional context
This would be more useful with some kind of versioning but I'm not really sure that mathesar has a version.

**Comment by rajatvijay** [comment]
Hi @spapas 

Whenever we make a release we post a changelog here: https://github.com/centerofci/mathesar/releases. An email is also sent to the "mathesar-developers" mailing list. See the announcement for v0.1.2 here: https://groups.google.com/a/mathesar.org/g/mathesar-developers/c/EHa3tl06kxw/m/dSUx10cnAwAJ

**Comment by spapas** [comment]
Thank you @rajatvijay yes it is good enough for me !
