### ISSUE TITLE
Support for column descriptions/comments

### ISSUE THREAD

**Issue by domdomegg** [centerofci/mathesar#3069]
## Problem

Managing large Postgres instances can become difficult if they're not well documented. As such, it's often desirable to have a way to add explanatory comments on tables or columns. This can be helpful for keeping things organised and understandable.

This also would align with features from other accessible data management platforms, like Airtable: https://support.airtable.com/docs/adding-descriptions-in-airtable

## Proposed solution

Postgres allows storing comments alongside tables and columns. They can be read back with the comment retrieval functions: https://www.postgresql.org/docs/current/functions-info.html#FUNCTIONS-INFO-COMMENT-TABLE

It would be neat if Mathesar could store and retrieve database comments using these functions.

## Additional context

I think we could do comment retrieval without being able to write them, at least as an initial version.

**Comment by kgodey** [comment]
We already support reading and writing schema and table comments (they're surfaced as "description" in the UI to make it more user-friendly for non-technical users). We don't support column comments yet, but it should be quick to add.

We may also want to consider some sort of popover or help text that explains that descriptions are actual database comments.

**Comment by seancolsen** [comment]
I updated the title to reflect that the remaining work relates only to _columns_.

@domdomegg if you're experiencing any difficulty using comments on tables or schemas, please let us know. It should already be working bidirectionally. That said, if you update a table or schema comment outside Mathesar, you'll need to [manually sync those changes](https://docs.mathesar.org/user-guide/syncing-db/) into Mathesar before you can see the comments in Mathesar.

**Comment by kgodey** [comment]
@seancolsen I'd consider also making a separate issue for this potential action item:

> We may also want to consider some sort of popover or help text that explains that descriptions are actual database comments.

**Comment by seancolsen** [comment]
Good idea, @kgodey. I've splintered the design work off into #3071. As such, I've un-tagged this issue as "design" so that we can keep it focused on implementing comments for columns (which I think is rather straightforward and should not require any design work). I've also un-tagged this as draft because I think we have enough info to get started on this.

**Comment by domdomegg** [comment]
Thanks both! I think the main thing I guess I wanted to raise was the column descriptions, which I think this issue tracks accurately (I didn't see the table descriptions, and while I care about it being stored in the Postgres database for interoperability with other tools, I don't think it's critical that this is made clear).

**Comment by kgodey** [comment]
Thanks for clarifying @domdomegg!

**Comment by seancolsen** [comment]
@domdomegg We've added support for column descriptions now. This feature will be in Mathesar 0.1.4 which should be released in the next few weeks. Descriptions are synchronized with the Postgres COMMENT value within Postgres, just like you wanted.

Here is where it shows up in the UI:

![image](https://github.com/centerofci/mathesar/assets/42411/6ea0b26e-acdb-45c4-b572-c93329d6e4b2)

As such, I'm closing this issue.

If you have any further ideas or feedback about this new feature, we'd love to hear it! Feel free to comment here or open a new ticket. Thanks again for suggesting this feature!

**Comment by domdomegg** [comment]
Looks awesome, thanks!
