### ISSUE TITLE
Create a outline for the simplified Installation documentation

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar#3075]
## Problem
Our current installation documentation is a crude representation of our installation process. But we haven't really considered the documentation from an end-user standpoint. Moreover, we are working on simplifying our installation process which can greatly benefit from having a clear vision of how the installation documentation will be seen and consumed by the end user.

## Proposed solution

Create an outline of the installation documentation which is easier to consume from an end-user perspective.

**Comment by kgodey** [comment]
Can we call this an outline instead of a wireframe since it's (presumably) going to be text?

**Comment by silentninja** [comment]
[Outline of the simplified Installation Documentation](https://wiki.mathesar.org/en/meeting-notes/2023-07/2023-07-28-installation-meeting.md#table-of-contents)
