### ISSUE TITLE
Discussion about active cell height design and regression

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#3091]
_(description pending, based on discussion)_

**Comment by seancolsen** [comment]
I'm starting this ticket as a discussion with the potential to morph into an action-oriented task.

My current task-at-hand is reviewing #3077. In doing so, I noticed what appears to be a regression.

The behavior in the current develop branch is demonstrated in the following video:

https://github.com/centerofci/mathesar/assets/42411/b215c0da-6459-4181-9694-8f87e3d2e767

Currently the active cell has the same height as non-active cells.

Previously, the active cell would grow slightly taller as needed to show more text.

I [asked](https://matrix.to/#/!UnujZDUxGuMrYdvgTU:matrix.mathesar.org/$YzRy952jga-sXyNzJ3e_zgPbv4apGGPEKg5mILQN3hI?via=matrix.mathesar.org&via=matrix.org) on Matrix and @pavish agrees that this seems to be a regression.

I did a small amount of research into what may have caused it, and I identified #2216 as a possible culprit. I was hoping to try reproducing the issue on the commit immediately prior to merging that PR, but alas there have be a number of other docker-related changes which made that troubleshooting process non-trivial; so I gave up for the sake of time.

@pavish since that was your PR, perhaps you would be able to more quickly determine whether it was the cause of this regression.

---

@ghislaineguerin and @pavish, I do want to mention that I've actually never liked our design wherein the cell grows taller when becoming active. Now that we seem to have broken that design, perhaps it's an opportune time to reconsider it. I would guess that the intent of our "taller active cell" design is to let the user see more of the cell text. But I don't think that showing _one more line_ of text adds enough value to justify it. The downside is that it obscures other text. Pluse, while it may be consistent with Airtable, it's inconsistent with every other product as far as I've seen. That inconsistency makes the behavior feel a bit awkward to me. I recall thinking the behavior was a bug when I first started using Mathesar. The goal of "seeing additional text within the cell" seems like it would be much better served by [showing cell content in a Table Inspector "Cell" tab](https://github.com/centerofci/mathesar/issues/2342). That would be more powerful because we could show the _full_ cell content (inside a scroll region). It would be pretty straightforward to implement too. How would you feel about abandoning the "taller active cell" design?

**Comment by seancolsen** [comment]
One more point to clarify: there's a slightly related issue with the current behavior: the active cell doesn't get any ellipses. You can see that demonstrated in my video above. Regardless of the outcome of our design discussion, I think we _do_ need to fix that ellipses problem. I'm not sure if it's a regression or just a bug that's always been present, but I have a hunch that it's related to the issue we're discussion here, and as such I have a hunch that the steps to address it cleanly will depend on the outcome of our design discussion. That's why I've not created a separate ticket for it.

**Comment by ghislaineguerin** [comment]
@seancolsen 
How will the quick edit feature function if we don't expand the cell? I'm currently working on a set of tables where I'm adding lengthy descriptions. I can see this feature being useful if it would allow me to navigate down with the keyboard and read all of my descriptions. Also, if we were to place the cell content in a side panel, would the text area in the panel automatically receive focus, enabling me to edit?

**Comment by seancolsen** [comment]
@ghislaineguerin and @pavish I'd still like to get answers from you in order to resolve this discussion.

**How tall should the active cell be when _viewing_ (not editing) data?**

- (A) **One line**

    This would mean we'd keep the code as-is, essentially codifying to (what appears to be) a regression and abandoning our previous "taller active cell" design.

- (B) **Two lines**

    This would mean making some code changes to fix the regression and restore our previous "taller active cell" design.

Regardless of our choice, we need to fix the problem of missing ellipses on the active cell. But exactly _how_ we fix it will depend on our choice. That's why I'm seeking some clarity here.

In my comment above, I'm making a case for (A). With this ticket, I'm seeking agreement from both of you. I've assigned it to you because I'd like you to comment with your opinion.

**Comment by pavish** [comment]
@seancolsen @ghislaineguerin 

> How tall should the active cell be when viewing (not editing) data?

I don't have any concern with it being (A) One line.

However, we need to take into account readonly views of tables, where the user needs to be able to see the entire value of the cell, and that would be hard if it's only one line. For the record, it would also be hard even if its two lines. 

Though it's not specifically related to this issue, we need account for this case as well and come up with some UX for it, before making a call.

**Comment by seancolsen** [comment]
Cool, because both of you are fine with option A, I'm closing this ticket.

> we need to take into account readonly views of tables, where the user needs to be able to see the entire value of the cell, and that would be hard if it's only one line. For the record, it would also be hard even if its two lines.

I think we can open a separate ticket to address that need when/if it becomes a priority.
