### ISSUE TITLE
Links do not work after adding check constraint to a table

### ISSUE THREAD

**Issue by domdomegg** [centerofci/mathesar#3109]
## Description

It appears that tables with any check constraint (e.g. on an unrelated column) breaks the display of all links on that table.

The foreign key constraint is held by the underlying database, and the links are shown in the link panel on the sidebar. However, in the grid the cells just show the raw value rather than a dropdown.

Another clue: clicking table > advanced > constraints results shows the error 'Unable to fetch table constraints When making an XHR request, the server responded with an error, but the response body was not valid JSON.' Under the hood this corresponds with a 500 request to `/api/db/v0/tables/22/constraints/?limit=500`

<details>
<summary>
500 response body
</summary>

```

<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
</body>
</html>
```

</details>

## To Reproduce

Steps:
1. Add a link column to a table in Mathesar OR in another tool, add a foreign key constraint and refresh the schema in Mathesar
2. [at this point, if you view the table you should see the link as a dropdown]
3. In another tool, add a constraint to any column in the table
4. View the table in Mathesar: The links continue to display fine
5. Refresh the schema in Mathesar
6. View the table in Mathesar

Expected: The links display as before
Actual: The raw value of the links (e.g. the number for an integer id column) are shown

7. In another tool, remove the constraint
8. View the table in Mathesar: all the data will disappear. Adding a record also seems broken from this point, but under the hood the record is actually added.
9. Refresh the schema in Mathesar
10. View the table in Mathesar: all the data is present and link works correctly again

Video:

This is all mock data. Ignore bit where I try to add person_id manually at the beginning, this is force of habit 😅. Also, I add a record in the external tool but this is not necessary for reproduction (this is just meant to show the check constraint appears to work fine in other tools, and doesn't stop manipulating data there, so I don't think this is a problem with the other tool).

https://github.com/centerofci/mathesar/assets/4953590/044e5e4f-ddbc-4d77-8032-c08375ff9055

## Environment

 - OS: Host: macOS, but mathesar 0.1.2 is running inside a [podman](https://podman.io/) container. I don't think this is relevant though.
 - Browser: Google Chrome
 - Browser Version: 115.0.5790.114 (Official Build) (arm64)
 - Other info: Using postgres:14 container.

**Comment by kgodey** [comment]
@mathemancer tagging you here since you're going to be working on better compatibility with existing DBs.

**Comment by mathemancer** [comment]
This appears to be because we're throwing an error when any constraint exists on the table that Mathesar doesn't understand, breaking the constraints endpoint. Thans for reporting this @domdomegg !

**Comment by MrChadMWood** [comment]
Are there any workarounds? Besides implementing a trigger (costly on performance), `CHECK` constraint is the only way to implement mutually exclusive columns (e.g, foreign keys) in a table. Basically either/or relationships at the record level.

**Comment by Anish9901** [comment]
@domdomegg & @MrChadMWood since the merging of #3243 you should be able to add `CHECK` & `EXCLUSION` constraints to a table, without breaking the core functionalities of Mathesar, this change will get rolled out with our next release 0.1.4 which would be within the next few weeks. You could try it out now if you decide to run the latest `develop` though.

However it is worth noting that, we are yet to figure out a way to effectively display these constraints within our app and therefore these constraints won't be visible in the constraints section even if they exist for a given table.
