### ISSUE TITLE
Create new `/v0/databases/` API

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#311]
**Problem**

We need a database API that has more information than just the database key. For example, we want to show the types installed in the database.

**Proposed solution**

We should create a new `/v0/databases/` API that includes the database key and types installed/supported by the database. We should also create a `Database` model, which should track whether a database is deleted or not.

**Additional context**

Ideally, we'd just rename and extend the `database_keys` API, but the frontend is using it and we don't want to break that. So we'll do this in a two step process where we create a new API first, wait for the frontend to switch, and delete the old API.

**Comment by eito-fis** [comment]
In this case, would it make sense to treat each database as an object? Something like:
```python
{
  'counts': 2,
  'results': [
    'db_1_name': {
      'key': 'db_1_key',
      'types': ['type_1', 'type_2'],
    },
    'db_2_name': {
      'key': 'db_2_key',
      'types': ['type_2', 'type_3', 'type_4'],
    },
  ]
} 
```
for the response?

**Comment by kgodey** [comment]
Yes, it would.

**Comment by kgodey** [comment]
`types` should be something like `supported_types`, to be clearer.

**Comment by kgodey** [comment]
@eito-fis Please update the issue description to include expanded scope from https://github.com/centerofci/mathesar/pull/320. Thanks!

**Comment by eito-fis** [comment]
I've started working on this, but I have a couple questions, in particular about how much we want to use the new Database model:
* How do we want to specify the database for schemas on the API side of things? I've been trying to preserve the current style where we just pass the name of a database, but we have a lot of options here. In particular, we could make the database endpoint the top level endpoint and nest schemas and tables inside them (although this would be a pretty huge change).
* With the addition of the Database model, we have two sources of truth with regards to what dbs we're handling: the Database objects and the django.settings.DATABASES dictionary. It feels like using the Database objects for everything would be nicest (and would reduce our `create_mathesar_engine()` usage quite a bit), but would also require fairly substantial changes. Alternatively, we can leave most functions as is and just use the Database objects when reflecting from the dbs.

**Comment by kgodey** [comment]
1. We should not change the structure of the schema and table APIs. I think it's best to leave the schema API structure as-is to keep the scope of this issue small. We can make further changes in the schema API (like returning a database ID) in future issues if we think it will be an improvement.

2. Let's keep the scope small on this too. We should just reflect the databases configured in settings in the Database models. At this point, the only reason we are even creating a Database model is to show users information about DBs that are no longer connected (which we need to fully implement the Multiple Databases design spec). 

If you'd like to propose additional changes that would simplify engine creation, I suggest opening a separate issue for it that outlines the problem you're solving.
