### ISSUE TITLE
Remove database keys API

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#313]
**Problem**

The database keys API is deprecated, we don't need it around.

**Proposed solution**

Delete code associated with it once the frontend switches away from using it.

**Additional context**

- Blocked by #312

**Comment by arvind-1** [comment]
@kgodey Thanks. I will start work on this one then. I will start setting up my code.

**Comment by kgodey** [comment]
Thanks @arvind-1! Please feel free to [join us on Matrix](https://wiki.mathesar.org/en/community) and ask questions either there or on the issue.

**Comment by arvind-1** [comment]
@kgodey i am facing following error while trying run app. Could you help me on this?
```
db_1   | 2021-08-18 10:10:37.073 UTC [86] STATEMENT:  SELECT "mathesar_database"."id", "mathesar_database"."created_at", "mathesar_database"."updated_at", "mathesar_database"."name", "mathesar_database"."deleted" FROM "mathesar_database" WHERE "mathesar_database"."name" = 'favicon.ico' LIMIT 21
web_1  | Internal Server Error: /favicon.ico/
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
web_1  |     return self.cursor.execute(sql, params)
web_1  | psycopg2.errors.UndefinedTable: relation "mathesar_database" does not exist
web_1  | LINE 1: ...abase"."name", "mathesar_database"."deleted" FROM "mathesar_... 
```

**Comment by kgodey** [comment]
@arvind-1 Did you run all the local development steps in the README: https://github.com/centerofci/mathesar#local-development? It looks like you may not have run the `migrate` step.

**Comment by arvind-1** [comment]
@kgodey I haven't run that. I tried right after  docker-compose up. Now that i followed other two steps it works alright now. Thanks.

**Comment by arvind-1** [comment]
@kgodey I went through all the change that have made for this. To be clear here i have to delete file `mathesar/database/utils.py`
is that correct or am i doing wrong ?

**Comment by kgodey** [comment]
@arvind-1 That is not correct. You have to delete all the code related to serving the `/api/v0/database_keys/` API, which includes the URL, viewset, serializer, and tests. You should also ensure that any functions called in any of those are used in other places in the code, otherwise you should delete those. You can see the API locally at `http://localhost:8000/api/v0/database_keys/`.
