### ISSUE TITLE
[bug]: Drop down menu doesn't close on double click

### ISSUE THREAD

**Issue by Harsh-kumar-jha** [centerofci/mathesar#3147]
## Description
On the Navbar menu section, there are two drop-down items and when I tried to click it showed all the drop-down items but when I double click on them, it doesn't close.

## Expected behavior
When anyone double-taps on the drop-down menu, it should close automatically

## To Reproduce
1. Go to the website of mathesar.org
2. look for the nav menu 
3. Now look for drop-down items.
4. Try to double-click on it 

## Additional context
https://github.com/centerofci/mathesar/assets/87357941/93cab1b1-196e-4654-b7ca-ac32f7d6fbc9

**Comment by rajatvijay** [comment]
@Harsh-kumar-jha thanks for reporting this. 

Unfortunately this bug belongs to the [website repo](https://github.com/centerofci/mathesar-website) hence will be closing this. Can you please re-open this there? 

Thanks!

**Comment by Harsh-kumar-jha** [comment]
Yeah, sure will do that
Thanks
