### ISSUE TITLE
Update the database objects created using the env to be consistent with the database objects created using the API

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar#3158]
Follow-up of #3157  Database objects added using the environment variable `MATHESAR_DATABASES` should also include `username`, `password`, `hostname` and `port` to be consistent with the database objects created using the database API. These databases objects added using the environment variable should also be read-only and should not be editable using the API.

## Additional context

- [This is the line](https://github.com/centerofci/mathesar/blob/8018a4404301e896b95ffe857acb55669456a434/mathesar/apps.py#L13) which adds the environment variables

**Comment by silentninja** [comment]
Blocked by #3157

**Comment by seancolsen** [comment]
I've un-tagged this as "Blocked" because #3157 is now essentially complete.

@Anish9901 are you able to begin work on this now?

**Comment by Anish9901** [comment]
@seancolsen this issue will be fixed by #3170
