### ISSUE TITLE
Design spec for adding user database credentials using the UI

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar#3159]
## Problem
The current method is to add user database credentials to Mathesar using environment variables. Using env variables as the only option for configuring Mathesar is not user friendly due to 
- Lack of feedback - The user gets feedback about the problems in the environment variables only when they start using Mathesar or when they run a specific script.
- Need for service restart - Mathesar needs to be restarted for the environment variable changes to take place. This is okay for one-time configurations but not ideal for adding user database credentials which the user can do more than once
- Unfriendly format - Environment variables can only be a key, value pair which is not ideal for complicated values involving nested objects

## Proposed solution

Users should be able to add database credentials using the Mathesar UI, this lets us give immediate feedback as well preventing the need to restart Mathesar

### Product requirements

 - The user will be taken to the page to add database credentials after installing Mathesar and after creating a superuser if there are no databases added during installation through environment variables.
 - The user should be able to add additional user database credentials later even after adding a database credential on his first visit. So there should be a link to take the user to this page. Maybe we can add an "Add database credential" button to the database list sidebar
- Only the superuser will be able to add database credentials
- The user can edit and remove a database credential added using the UI
- **Special case**: Database added using environment variables cannot be edited or removed. They can just be viewed.

- The user needs to provide the following details to add a database credential
    - Unique name for the database
    - Database name
    - Database Username
    - Database password
    - Database host URL
    - Database port

- The user can edit an existing database credential. The following fields can be edited
    - Database name
    - Database Username
    - Database password
    - Database host URL
    - Database port

#### UI for adding a database credential

- Help Text
    - Inform the user to provide a DB user with correct privilege(`SUPERUSER` or DB `OWNER`)
    - Inform the user that we will be installing Mathesar schema on the given database
    - When there are no databases available, they will be redirected to this page. We should inform the user that it is necessary to connect to a database to start using Mathesar
  
Possible States:

- Success state: 
   - We were able to connect to the database and install Mathesar schema using the provided credentials
 - Failure state:
      - We were unable to connect to the database
         - Along with the Error log 
      - The provided DB user does not have the privilege to install Mathesar schema in the database
  
#### UI for removing the user database credentials from the user

- The following information is needed
    - Checkbox asking if the user wishes to remove the Mathesar schema additionally.
- Limitations
   -  Database credentials added using environment variables should not be editable nor be deleted and should not have the option deletion option
  
- Help Text: Warn the user of potential data loss if the Mathesar custom types are used and the user wants to remove the Mathesar schema
      - "Deleting this schema will also delete any database objects that depend on it. This should not be an issue if you don’t have any data using Mathesar’s custom data types."
     
- Success state: 
   - The database credentials are removed from the Mathesar
    - Mathesar schema is removed if the checkbox was ticked
- Failure state:
    - We were unable to remove the Mathesar schema
       - Along with the error log

#### UI for listing the user database credentials from the user
  - List of all the user databases added to Mathesar
  - We can use our existing side panel. There won't be any change needed in this case
  
#### UI for editing the user database credentials from the user
  - Similar to "UI for adding a database credential"
  - Refer to product requirment section above for the editable fields

#### UI to link the pages
The database list section should have the links to the following pages
 - Page to add database credential
 - Page to edit database credential
 - Page to remove database credential

**Comment by ghislaineguerin** [comment]
@silentninja The design for Database Credentials is ready for review: https://www.figma.com/file/xHb5oIqye3fnXtb2heRH34/Styling?type=design&node-id=6055-60&mode=design

**Comment by pavish** [comment]
@ghislaineguerin @silentninja I added some comments in the design. 

@seancolsen I'd like you to additionally review the UX and ensure that the copy is good.

**Comment by seancolsen** [comment]
I've reviewed and commented. Unassigning myself.

**Comment by silentninja** [comment]
@ghislaineguerin The design looks good from the requirement perspective. However, there are a few minor issues which I have added as comments to the design

**Comment by ghislaineguerin** [comment]
@pavish @silentninja I've updated the design to include options for "Test Connection". No other changes pending, please review.

**Comment by pavish** [comment]
Ghislaine, Mukesh, and I had a quick review call and finalized on the design.

@rajatvijay Please make sure to take a look and have all UX related questions answered, if you have any, before starting frontend work on this.

**Comment by rajatvijay** [comment]
@ghislaineguerin @silentninja it looks good overall. I have added a few questions in the comments on the [Figma](https://www.figma.com/file/xHb5oIqye3fnXtb2heRH34/Styling?node-id=6075%253A5700)

**Comment by seancolsen** [comment]
Because the front end implementation is now well underway, I'm assuming that the design is now complete. As such, I'm closing this ticket because I'm working to move things out of the v0.1.4 milestone. Feel free to re-open if more design work is needed.
