### ISSUE TITLE
Decommission Wiki.js server

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#3173]
Today I [migrated](https://github.com/centerofci/mathesar-wiki/pull/102) the wiki from wiki.js to MkDocs. The new site is now hosted with GitHub pages and built with GitHub actions. As part of the deployment, I removed an `A` record from our DNS which was pointing `wiki.mathesar.org` to `34.69.72.202`. @kgodey Tells me that we have been maintaining a GCP server at that address, and she says that server can now be decommissioned.

@mathemancer, at Kriti's request, I'm assigning you to decommission this server.

**Comment by mathemancer** [comment]
Okay, done.
