### ISSUE TITLE
Critical regression: User profile store not present in App context, breaks Record selector 

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#3174]
## Description
The User profile store context was moved from App to `AnonymousAccessRoutes` and `AuthenticatedRoutes`. This breaks Record Selector functionality since it's placed within App.

## Expected behavior
UserProfileStore context should be present in Record selector model 

## To Reproduce
* Follow steps of Library demo video, until the scenario where you create records from search terms in Record Selector. Notice that the 'Create Record From Search Criteria' button is not present.

**Comment by mathemancer** [comment]
For some reason, this didn't close automatically, but it was solved by #3175 .
