### ISSUE TITLE
Visual regression: Custom input elements appear disabled

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#3192]
## Description
* Open a table and attempt to add a new column.
* Notice that the 'Select Type' input box appears disabled.
* <img width="238" alt="Screenshot 2023-08-31 at 4 57 17 PM" src="https://github.com/centerofci/mathesar/assets/11850603/fa85a389-5bde-4173-b371-f34ad63c29b1">
* It functions normally, this is a visual regression.
* The cause behind this is the common global css style:
  ```
  .input-element:read-only {
        background: var(--slate-50);
  }
  ```
  within `component-library/common/styles/components/input.scss`.
* Since the input here in a custom input element wrapped in a `ul`, the element is considered readonly.
* There may be other places where custom inputs appear disabled, I haven't checked everywhere.

## Expected behavior
* This readonly style should only apply for inputs that have an explicit `readonly` html attribute.
   * eg., TextInput within `src/systemt/shares/ShareEntity` component:
     ```
     <TextInput bind:element={linkInput} readonly value={shareLink} />
     ```
* The 'Select Type' input box and other custom inputs should not be affected by this style.

**Comment by manthan-jsharma** [comment]
Hello @pavish , I'm eager to help address this bug. Would it be possible for me to take this on?

**Comment by Anish9901** [comment]
This regression seems to have occurred again(here is a screenshot for reference):
<img src="https://github.com/centerofci/mathesar/assets/52523023/8da470bf-da92-48d3-a6b3-d7b9871963fc" width=238px height=403px>
while trying to add a new column the selected type(Money in this case) isn't highlighted.
