### ISSUE TITLE
Support importing Excel and JSON files project (GSoC 2023)

### ISSUE THREAD

**Issue by IamEzio** [centerofci/mathesar#3216]
**Primary Mentor**: Dominykas @dmos62 
**Secondary Mentor**: Anish @Anish9901 
**Contributor**: Anshuman @IamEzio 
## Objective

Mathesar UI allows users to import data from CSV and TSV files. We aim to expand this functionality into importing JSON and Excel files too. The project will allow users to import JSON and Excel files and create a table from the imported data. The user can preview the table, remove/rename columns, change data types, and more. If the imported file is not in a suitable format for creating a table, we will develop algorithms to convert the file into a suitable format. If the algorithm doesn’t work, the system will refuse to import the file and give the user a readable error.
[See detailed description](https://wiki.mathesar.org/community/gsoc/project-ideas/import-excel-json-files/)

### Importing JSON
The functionality for importing JSON is completed.
- Users can upload JSON files in the current import UI seamlessly.
- Invalid JSON formats are handled and appropriate errors are returned to the frontend.
- Column data type guessing functionality works on JSON files too.
- Tests have been added for all the new code.

[See Documentation](https://github.com/centerofci/mathesar/blob/develop/docs/docs/user-guide/importing-data.md#importing-json-data-json)
Related Meta ticket: #2895 

### Importing Excel
The functionality for importing Excel is completed.
- Users can upload Excel files in the current import UI seamlessly.
- Invalid Excel formats are handled and appropriate errors are returned to the frontend.
- Column data type guessing functionality works on Excel files too.
- Tests have been added for all the new code.

Related Meta ticket: #3027 

### Additional Tasks
- #3009 

## Pending Tasks
- #3030 
- #3031
  - Related PR: #3211

**Comment by seancolsen** [comment]
Closing since the GSoC project is over
