### ISSUE TITLE
Selecting a different column when the editing the column name, results in an inconsistent state.

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#3218]
## Description
* Select a column
* Click on 'Name' under 'Column Properties' in the inspector
* Notice that the 'Cancel' and 'Save' buttons appear.
* Select a different column.
* Notice that the name remains the same as that of the previously selected column, and an error is shown saying 'A column with that name already exists.'

## Screenshots
* First column selected, Name textbox is focused.
  * ![Screenshot 2023-09-20 at 7 03 54 PM](https://github.com/centerofci/mathesar/assets/11850603/e98fb06c-b447-4104-b3b1-b04c17e34e81)

* Selection changed to another column.
  * ![Screenshot 2023-09-20 at 7 04 10 PM](https://github.com/centerofci/mathesar/assets/11850603/57bbe2a8-aec0-4b2e-bb76-adf6c3a64b76)

## Expected behavior
* Changing selected column should display the name of the newly selected column.

**Comment by seancolsen** [comment]
Nice catch. 

> Changing selected column should display the name of the newly selected column.

Can we also cancel the edit state of the column name, thus re-hiding the "Cancel" and "Save" buttons?
