### ISSUE TITLE
Create button component in the component library.

### ISSUE THREAD

**Issue by Dhruvi16** [centerofci/mathesar#322]
### Context
We need to build a design system that includes both design and front-end guidelines. Initially, a component library will allow us to create prototypes in Figma. This library will become the foundation for Mathesar's UI, as engineers will reference it to implement product requirements.

### What needs to be done
- Set up a component library project in Figma
- Create button component based on buttons in [current specification documents](https://wiki.mathesar.org/en/design/specs)
- Update existing prototypes to use the updated button component

**Comment by kgodey** [comment]
@Dhruvi16 I updated the task description based on #161.

**Comment by kgodey** [comment]
@Dhruvi16 Thanks for your work on this! I'm going to close this issue for now because as we discussed, we realized that Mathesar's design is not mature enough that we can document the full component, including intent and variations. at this time. I'll create separate issues for new tasks.
