### ISSUE TITLE
install.py is not working after upgrading to latest version

### ISSUE THREAD

**Issue by spapas** [centerofci/mathesar#3224]
## Description
I upgraded to latest version (from master) and when I try to run 
python db/install.py I get the following error:

```
(venv) [serafeim@imp-uat mathesar]$ python db/install.py
Traceback (most recent call last):
  File "/home/serafeim/mathesar/mathesar/db/install.py", line 1, in <module>
    from psycopg.errors import InsufficientPrivilege
  File "/home/serafeim/mathesar/venv/lib/python3.9/site-packages/psycopg/__init__.py", line 7, in <module>
    import logging
  File "/usr/local/lib/python3.9/logging/__init__.py", line 26, in <module>
    import sys, os, time, io, re, traceback, warnings, weakref, collections.abc
  File "/usr/local/lib/python3.9/re.py", line 124, in <module>
    import enum
  File "/usr/local/lib/python3.9/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
ImportError: cannot import name 'MappingProxyType' from 'types' (/home/serafeim/mathesar/mathesar/db/types/__init__.py)
```

## Expected behavior
install.py should work fine

## To Reproduce
Fetch latest version and try running `python db/install.py`

## Environment
 - Centos 7
 - Python 3.9

## Additional context
Please notice that the instructions here are also wrong: https://docs.mathesar.org/installation/build-from-source/ 

They mention running python install.py but there's no install.py file.

**Comment by spapas** [comment]
My understanding for the cause of this problem is the fact that there's a `types` package inside db (db/types) in mathesar. When you run `python db/install.py` python will confuse the db/types package with the types module and won't find the stuff it expects to find there so it breaks (i.e `MappingProxyType` is from *python* types but it tries to get it from mathesar db/types).

**Comment by spapas** [comment]
Things seem to work after I move the file mathesar/install.py (this one https://github.com/centerofci/mathesar/blob/develop/mathesar/install.py) to install.py (i.e move the file to root folder)

**Comment by silentninja** [comment]
@spapas Thanks for reporting this issue! As you mentioned the problem is occurring due to a file name conflict with the system package. To fix it you should be running it as a module `python -m db.install`

Also, why are you using `db/install.py`? It is not a standalone module and does nothing when called directly. Instead, you should be using the `mathesar/install.py` by calling it using `python -m mathesar.install`

**Comment by spapas** [comment]
Hello @silentninja thank you fort clarifying! Please notice that the instructions here mention: 

> Install Mathesar functions on the database:


```
python install.py --skip-confirm | tee /tmp/install.py.log
```

**Comment by silentninja** [comment]
@spapas Ah! Thanks for the catch! I will create a PR to fix it ASAP.
