### ISSUE TITLE
I cannot see schemas after upgrading

### ISSUE THREAD

**Issue by spapas** [centerofci/mathesar#3238]
## Description
After upgrading to latest version I can't see any of the schemas of the mathesar data database.

## Expected behavior
To see the schemas. Do I need to do something more after upgrading ? 

## To Reproduce
I'm not really sure. I updated from the  version I had to the latest version from the develop branch

## Environment
 - OS: Centos 7
 - Browser: Chrome 
 - Browser Version: Latest
 - Other info:

## Additional context
This is what I see after login with the administrator:

![image](https://github.com/centerofci/mathesar/assets/3911074/9066f112-f425-41ce-9d49-5553620d5449)

Please notice that with the previous version I was seeing the schemas I had (and of course the schemas are there).

No errors on the backend console or js.

**Comment by spapas** [comment]
It seems that the issue was related to https://github.com/centerofci/mathesar/issues/3158 , the `mathesar_database` table contained garbage for the username and an empty db_name, It was fixed after I run

`update mathesar_database set username='mathsar' db_name='mathesar_data'`

**Comment by pavish** [comment]
@spapas Thanks for letting us know! Do you need any further help with this issue?

Regarding upgrades:

The `develop` branch contains unstable development code. It isn't fully tested and certainly not meant for installation and regular usage.

When upgrading, we recommend you to make use of [our releases](https://github.com/centerofci/mathesar/releases), which are more stable and tested. Keep in mind that we're still in alpha, so there may be some breaking changes between releases.

**Comment by spapas** [comment]
No let's close it since it's working
