### ISSUE TITLE
Design for editing column properties and table constraints

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#324]
## Problem

Users may want to edit column properties and table constraints.

Column properties are properties of an individual column. they are:
- column name
- column type
- nullable (whether column can contain null values)
- default value (default value for newly added rows)

Table constraints are properties of the table and can involve multiple columns. For now, let's just handle the `UNIQUE` constraint. `UNIQUE` can involve only one column or a group of columns, and it means that the values in that column or group of columns have to be unique together.

e.g. Imagine this table

| Name | Position | Rank | 
|-|-|-|
| Peter Quincy Taggart | Commander | Commander |
| Tawny Madison | Computer Specialist | Lieutenant |
| Chen | Chief Engineer | Tech Sergeant |

If you had a `UNIQUE` constraint on `Name`, then you could not add any new row that repeats any of the names already in the table. However, if you had a `UNIQUE` constraint on `Name, Position`, then you could add a row with values `Peter Quincy Taggart, Leader, Commander`, but not `Peter Quincy Taggart, Commander, Leader`, because there's already a row with that same name and position in the DB.

## Proposed solution

We should have a design to edit column properties and table constraints.

## Additional context

[Postgres documentation on constraints](https://www.postgresql.org/docs/current/ddl-constraints.html), we might support other constraints in the future.

**Comment by ghislaineguerin** [comment]
Prototype and notes posted at : https://wiki.mathesar.org/en/design/specs/working-with-columns
