### ISSUE TITLE
Inaccurate info for a foreign key column referencing a non-pk column

### ISSUE THREAD

**Issue by Anish9901** [centerofci/mathesar#3247]
## Description

We've been assuming a foreign key column to be referencing only a primary key column(which is not always true, as a foreign key can also reference a non-pk column), there is an info alert in the data type section of a foreign key column that reflects the same. 

![Screenshot from 2023-10-17 15-40-56](https://github.com/centerofci/mathesar/assets/52523023/cd816f76-ab70-47c2-9056-ddd0d4ef8439)

context: tab2_refferer column refers a unique text column but the info in the data type section is inaccurately assumes it to be referring to a pk column.
## Expected behavior

Show accurate info.

## To Reproduce

Setup a column with a fk referencing a column which is not a pk, similar to #3232

**Comment by FidalMathew** [comment]
@Anish9901 @kgodey Can I work on this issue?

**Comment by Anish9901** [comment]
Go ahead @FidalMathew

**Comment by seancolsen** [comment]
I'd like to propose a path towards resolving this issue.

The help text is currently:

> The data type of the foreign key column is restricted to the data type of the primary key column and cannot be changed.

I suggest changing that text to the following:

> The data type of this column cannot be changed because it has a foreign key constraint requiring that its type matches that of its referenced column.

@Anish9901 does that sound okay to you?

I'm making this suggestion here because I was reviewing #3257 but I don't like the approach in that PR. I don't think we need any changes in _functionality_ to resolve the underlying problem described in this issue. I think we only need a minor adjustment to the language used in the UI.

If we can reach an agreement on my proposal, then I will close #3257.

**Comment by Anish9901** [comment]
I agree @seancolsen, I don't think we need a functionality change either.

I've come up with a couple more suggestions for the help text that you might like:
> 1. The data type of this foreign key column cannot be changed as it must match the data type of the column it references.
> 2. The data type of the foreign key column is restricted to data type of the underlying referenced column, and hence cannot be changed.

**Comment by kgodey** [comment]
I'll throw in a suggestion:

"The data type of this column must match the referenced column and cannot be changed."

**Comment by seancolsen** [comment]
I don't feel strongly about this. Happy to go with Kriti's suggestion because it's succinct.

**Comment by seancolsen** [comment]
Ok we have an agreement. The UI text should be changed to:

> The data type of this column must match the referenced column and cannot be changed.

@FidalMathew @ejenk0 if either of you would like to submit a PR for that change, go ahead.
