### ISSUE TITLE
Add tests for DB creation/editing/deletion via API

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#3259]
Test coverage for adding/removing/editing DBs via the API is insufficient. I didn't search our test suite for relevant tests (there might be some), but I was able to break basic database creation (via the API) without having any test fail.

**Comment by FidalMathew** [comment]
Hi @dmos62. I want to work on it, could you guide me on how to proceed with this issue?

**Comment by Shraeyas** [comment]
@dmos62 Can you please give some details on how to reproduce this?

**Comment by dmos62** [comment]
@Shraeyas you'd have to figure out which endpoints do these things and what tests are missing for them.

**Comment by seancolsen** [comment]
I'm closing this ticket because this API is be ripped out and completely replaced, as specified in #3291
