### ISSUE TITLE
Frontend work for viewing and deleting table constraints

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#328]
## Problem

Users may want to view or delete table constraints.

## Proposed solution

We should provide a way to do these actions from the UI following [the "Working with Columns" design spec](https://wiki.mathesar.org/en/design/specs/working-with-columns).

This covers:
- Displaying table constraints of all types
- Deleting table constraints of all types

## Additional context

- Design issue: #324 
- Design discussion: #436
- Backend issue: #326 
- Backend PR: #488 
- This issue blocks: #531

**Comment by raduab** [comment]
I'm ready to work on this issue. Haven't been able to spin up mathesar on my Linux box though. I get an error of file not found when running `docker-compose up`:

`File "/usr/lib/python3.9/site-packages/docker/transport/unixconn.py", line 43, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory`

**Comment by kgodey** [comment]
@raduab I've assigned this to you.

That seems like an error with Docker. This issue might help: https://github.com/docker/compose/issues/7896

**Comment by raduab** [comment]
Thanks, it runs now. I am ready to start working on this issue, please assign it to me.

**Comment by kgodey** [comment]
@raduab already done :)

**Comment by raduab** [comment]
@kgodey Were exactly should I add the "Table Actions" button?

The design prototype differs from the current implementation:

![design_proposal](https://user-images.githubusercontent.com/64026120/130238700-ad80a2fe-bd15-465b-8913-e108ed94e314.png)

versus:

![current_implementation](https://user-images.githubusercontent.com/64026120/130238714-cc482015-cc53-47b4-8949-e21a50aea7ef.png)

**Comment by kgodey** [comment]
@raduab You can add it either before or after the Filters, Sort, Group fields, thanks for checking. 

The design prototype and frontend are somewhat out of sync for a couple of reasons:
- the designs are ahead of the frontend by a few features so they include things the frontend doesn't have yet (like adding records)
- we also had to make some improvised decisions while implementing the frontend because the designs don't cover all states.

**Comment by raduab** [comment]
@kgodey Thanks for clarifying this for me!
