### ISSUE TITLE
Record page widget causing overflow

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#3289]
## Reproduce

1. Go to a record page that contains a table widget.
1. Resize columns within the widget in order to make the total width of all columns wider than the viewport.
1. Expect to see a horizontal scroll bar which allows the _sheet_ to be scrolled.
1. Expect the content of the record fields at the top of the page to be unaffected by the width of the widget columns.
1. Instead, observe that wide columns in the widget push the content of the _whole page_ out, causing horizontal scrolling for the records fields at the top of the page, too.

https://github.com/centerofci/mathesar/assets/42411/c145adc7-d527-4f69-9ae4-295198fb9d80

I'm fairly certain that this is a regression, because I vaguely recall ensuring that this bug did _not_ exist when I implemented that table widget within the record page. However I could be mistaken.

**Comment by Mayank77maruti** [comment]
Hey @seancolsen , please do assign this task to me .

**Comment by seancolsen** [comment]
@Mayank77maruti you're welcome to work on this and submit a PR, but in general we don't assign tickets to new contributors, as noted in our [Contributor Guide](https://github.com/centerofci/mathesar/blob/develop/CONTRIBUTING.md). Once we've already merged a PR of yours, then we'll be happy to assign tickets to you after that. The reason for this policy is that in the past it has been a maintenance burden for us to manage ticket assignments while having an overwhelming volume of people fail to submit their first PR when initially expressing intent to contribute.

**Comment by rajesh604** [comment]
I'd like to work on this issue.

**Comment by rajesh604** [comment]
is the issue the below one. Do you want me to remove the scrollbar. can you please write a reply so that I can work on it


https://github.com/centerofci/mathesar/assets/77529419/d665d6e3-4c14-45a6-9589-949b1503f306

**Comment by seancolsen** [comment]
@rajesh604 your video above is irrelevant to this ticket. Your video depects the _Import_ page. This ticket pertains to the _Record_ page.

You'll need to view a record page that has related records. You can [load](https://github.com/centerofci/mathesar/blob/develop/DEVELOPER_GUIDE.md#opening-a-shell-in-the-container) the [all_types](https://github.com/centerofci/mathesar-data-playground/blob/master/all_data_types/all_data_types.sql) table and navigate to the first record in the table, titled "Lorem". Then you should see this:

![image](https://github.com/centerofci/mathesar/assets/42411/f3c47d7c-92c6-4e7d-806e-de2002bd5148)

See how that white section at the top of the page is off-center? It should be centered. That misalignment is indicative of the problem that this ticket describes.

Separately, I noticed you made a [comment](https://github.com/centerofci/mathesar/issues/3297#issuecomment-1797185502) in another ticket, calling my attention to this ticket. Please do not do that. It creates unnecessary notifications for me. Mentioning a GitHub user in _one_ ticket is sufficient to get their attention.
