### ISSUE TITLE
Create sidebar component for the component library.

### ISSUE THREAD

**Issue by Dhruvi16** [centerofci/mathesar#332]
### Context
We need to build a design system that includes both design and front-end guidelines. Initially, a component library will allow us to create prototypes in Figma. This library will become the foundation for Mathesar's UI, as engineers will reference it to implement product requirements.

### What needs to be done
- Create sidebar component based on sidebar in [current specification documents](https://wiki.mathesar.org/en/design/specs)
- Update existing prototypes to use the updated sidebar component

**Comment by kgodey** [comment]
I'm going to close this issue for now because we realized that Mathesar's design is not mature enough that we can document the full component, including intent and variations. at this time.
