### ISSUE TITLE
DB syncing is not triggered when objects are fetched without involving the API

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#365]
## Description

DB syncing currently is triggered by accessing the `SchemaViewSet`. However, schemas can be fetched without the API being involved. Our initial load of the frontend uses Django templates (and querysets) to fetch schemas and pre-render them without needing a network call. This should trigger DB syncing.

## Expected behavior

The DB should be synced when the Schema queryset is fetched, not when the API is called. This also applies to tables and databases.

## To Reproduce

Wipe your database and load the Mathesar UI. It won't load any schemas.

**Comment by pavish** [comment]
@kgodey We need to prioritize this issue. All new contributors would face this issue, and until they reach out to us, they won't be able to import any files.

**Comment by kgodey** [comment]
@pavish it's assigned to @eito-fis for this week.
