### ISSUE TITLE
Store friendly to DB type mapping in the backend

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#367]
Please see https://github.com/centerofci/mathesar/issues/269 for the mapping of types and context.

The plan with this issue is to store the mapping of friendly to DB types so that it can be served as part of the API.

**Comment by mathemancer** [comment]
I don't think we need a model if we're just keeping a map from friendly to DB types.  Couldn't it just be a dict?  Especially if the only way we intend for the map to be modified is when we update Mathesar, it seems like loading the updated file into a model is just extra steps.  For context, we're looking at something less than 1 kilobyte of text.  Keeping it in a dict would free up DB connections, and generally be quicker (though I admit that the DB call isn't really expected to be much of a bottleneck)

**Comment by kgodey** [comment]
@mathemancer I specced it out as a Django model for a couple of reasons:
- Default querysets, serializers, APIs, etc. will just work.
- Eventually it would be nice for users to be able to modify this to work with their own types. e.g. they might want to add their own custom types to the list. I think having it in the DB will be better for that than having it in the code.

**Comment by mathemancer** [comment]
Good point about the adding types; that makes sense to me.

**Comment by kgodey** [comment]
@mathemancer I thought about this more while implementing and I think your initial instinct was right, having a model seems like over-optimizing at this point. We can easily refactor to create a model if it becomes expedient to do so.
