### ISSUE TITLE
Unit tests for Select component

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#376]
## Problem
We have a custom Select menu (`/mathesar_ui/src/components/select`), which does not any tests yet.

## Proposed solution
We need to add unit tests to the Select menu.
Unit tests need to be placed within `/mathesar_ui/src/components/select/__meta__`. Refer button component.
Naming convention: `Select.test.ts`

## Update
* @HenryRocha did great work writing a number of tests in https://github.com/centerofci/mathesar/pull/812.
* We still require one more test as mentioned in https://github.com/centerofci/mathesar/issues/376#issuecomment-971468648.
* Anyone working on this issue would be writing that particular test, and can suggest and write additional tests that may not have been covered.

**Comment by HenryRocha** [comment]
Just to give an update, almost done writing the tests. Should be finished either tomorrow or the day after.

**Comment by pavish** [comment]
PR #812 handles majority of test cases. Tests yet to be handled:
* The list scrolls automatically to display the currently selected option
   - Comment with additional information on how to write this test: https://github.com/centerofci/mathesar/pull/812#issuecomment-967194874

**Comment by kgodey** [comment]
@HenryRocha are you working on the remaining tests as well?

**Comment by HenryRocha** [comment]
@kgodey If no else wants to take them up, yes, I plan on working on the remaining ones.

**Comment by kgodey** [comment]
@HenryRocha great thanks! I'll leave the issue assigned to you.

**Comment by pavish** [comment]
Hey @HenryRocha, just checking in to see the status of this issue. Are you working on it? Do you need any help from the team?

**Comment by kgodey** [comment]
@HenryRocha I've unassigned you from this issue since we haven't heard from you in a couple of months. Please let us know if you're still interested in contributing to it.

**Comment by nimishbongale** [comment]
Hello @kgodey @pavish, can I take this up?

**Comment by kgodey** [comment]
Sure, go ahead @nimishbongale.

**Comment by nimishbongale** [comment]
@pavish Just a doubt, when a certain option in the dropdown list gets selected, the dropdown container becomes null–I assume that's because the dropdown list isn't visible anymore (collapsed in). As a result, we won't be able to read the scrollTop or the clientHeight value of a null object. Is the dropdownContainer initialization correct here?

```ts
const selectUl = getByRole('listbox');
const dropdownContainer = selectUl.parentElement;
```

**Comment by pavish** [comment]
@nimishbongale 

> I assume that's because the dropdown list isn't visible anymore (collapsed in)

Yes, it's because the dropdown is removed from the DOM.

> As a result, we won't be able to read the scrollTop or the clientHeight value of a null object

We don't have to read it during selection. The test case required is for the dropdown to scroll automatically to the selected element when opened. Here's the scenario:
* Have a select menu with several options so that a scrollbar is visible, and some options are hidden (they will be visible only when we scroll down).
* Scroll down the scrollbar and select an option which was not initially visible. The option will be selected and the dropdown will get closed. 
* Open the dropdown. Assert that the selected option comes into view. Here the dropdown will not be null and you'll be able to access the required attributes.

**Comment by nimishbongale** [comment]
That's very helpful, thanks for clarifying @pavish! Will raise a PR for the same.
