### ISSUE TITLE
Handle `DECIMAL` data type in the backend.

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#381]
This issue is to ensure that Mathesar can handle the Postgres `DECIMAL` data type.

As part of this issue, we need to ensure that:
- Users can use the API to change a column to `DECIMAL` if it's possible to do so.
- Users can set and change the `precision` and `scale` of a given `DECIMAL` column via a `type_options` field in the API.
- There's nothing to do here on automatic type inference. It should never suggest `DECIMAL` since it's equivalent to `NUMERIC`, which is handled in #377.

**Additional Context** 
- See PR #368 for code that calculates which types are allowed for a column.

**Comment by mathemancer** [comment]
@kgodey Please note that PostgreSQL treats `DECIMAL` as `NUMERIC`.  That is, when you create a column of type `DECIMAL` (even in SQL), a column of type `NUMERIC` is actually created (and reflected).  (This is similar to the behavior for `FLOAT`, which creates a column of type `DOUBLE PRECISION`).
