### ISSUE TITLE
Implement range based grouping for numeric types.

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#384]
## Problem
Users may want to group their records by ranges such as 0-1, 1-2, 2-3, or 0-10, 10-20, 20-30, or 0-100, 100-200, 200-300, etc. The range that they will want to group on will depend on the kind of data they have. For example, if the values in a column range from 0.3 to 5.2, then grouping by 0-10, 10-20 etc. is not very useful.

We need to provide both useful ranges for a given column and the ability to group by them.

## Solution
- Columns of Number types should provide useful grouping ranges for that column in the Column API based on either:
  - the number of groups desired
  - the group size desired
- We should extend our record grouping mechanism to accept ranges for columns of Number types. We should be able to accept arbitrary ranges, not just the ranges suggested in the Column API.
  - Users should be able to set a min and max value for a range and the increment size 

This involves:
- Implementing the grouping in the backend
- ~Updating the `/api/v0/databases/<id>/types/` endpoint to store available grouping on this type~ This will be done in #1310 

## Additional context
- Please review these design specs carefully before implementing this issue:
  - The [Global Data Types](https://wiki.mathesar.org/design/specs/global-data-type-components) spec has the latest version of the UX.
  - The [Number Data Type](https://wiki.mathesar.org/design/specs/number-data-type) spec has an older version of the UX but more information on user scenarios.
- Design issue: #238 
- Please see these PRs for code related to grouping:
  - #315
  - #353
- Complete implementation of this issue is blocked by implementation of Number types, but we can start work with the `NUMERIC` type which is already implemented.
  - #377
  - #378 
  - #379 
  - #380 
  - #381 
  - #382 
  - #383 
  - #434
- #557 provides some context on storing groups.

**Comment by mathemancer** [comment]
@kgodey @ghislaineguerin Should the ranges have the same size on the number line, or the same number of entries?  For example, if a column has entries
```
mycol
-----
   1
   2
   3
   4
   5
   6
   7
  20
```

Should splitting into two groups result in

```
 1-10
-----
   1
   2
   3
   4
   5
   6
   7
-----
11-20
-----
  20
```
or
```
 1-4
-----
   1
   2
   3
   4
-----
 5-20
-----
   5
   6
   7
  20
```

**Comment by kgodey** [comment]
@mathemancer Good question. From the backend perspective, I think it makes sense to provide both options. The frontend (or other Mathesar clients) can use whichever would be best in the use case.

**Comment by kgodey** [comment]
@powellc FYI I updated the issue description with more details.

**Comment by kgodey** [comment]
@mathemancer That sounds fine to me. I think we'll want different frontend experiences for grouping by distinct tuples vs. range-based grouping, but there's no reason why the API can't be the same for both.
