### ISSUE TITLE
Implement display options for Number types.

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#386]
## Problem
The Number Mathesar type supports the following display options:
- Whether to show the data as a percentage.
- The locale to format the number in.

## Solution
(1) We should store these display options in the following format in the `display_options` field of the corresponding column.
```
{
  "show_as_percentage": true,
  "locale": "en_US"
}
```

(2) We should also validate these so that:
- Only columns of this type can have these display options. They should not be able to be set if the column is of a different type.
- `show_as_percentage` should be a boolean
- `locale` should be a valid locale

(3) If the column type is changed, the display options should be deleted.

(4) We should add supported display options to the `types` endpoint.

## Additional Context
- [Design of Number type options on Figma](https://www.figma.com/proto/Uaf1ntcldzK2U41Jhw6vS2/Mathesar-MVP?page-id=4260%3A37440&node-id=4270%3A39634&viewport=324%2C48%2C0.29&scaling=contain&starting-point-node-id=4270%3A39634&show-proto-sidebar=1)
- Blocked by #658
- #392

**Comment by kgodey** [comment]
@mathemancer I'm considering making percentage a service-layer display option on a correctly configured `NUMERIC` or `DECIMAL` type. What do you think?

**Comment by mathemancer** [comment]
I think we should do it at the data layer so we can properly detect it when reflecting a table.  We can create a percentage type in the DB that's nothing more than a name for a  numeric type in the DB using domains.

**Comment by kgodey** [comment]
Issue for percentage type: https://github.com/centerofci/mathesar/issues/434
