### ISSUE TITLE
Implement display options for Boolean types

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#390]
## Problem
The boolean data type supports the following display options:
- Whether to show the field as a checkbox or a dropdown.
- Whether to show custom labels for `TRUE` and `FALSE`
- Custom label names for `TRUE` and `FALSE`

## Solution
(1) We should store these display options in the following format in the `display_options` field of the corresponding column.
```
{
  "input": "dropdown",
  "use_custom_labels": true,
  "custom_labels": {
    "TRUE": "yes",
    "FALSE": "no"
  }
}
```

(2) We should also validate these so that:
- Only columns of this type can have these display options. They should not be able to be set if the column is of a different type.
- `input` should be set to either `checkbox` or `dropdown`
- `use_custom_labels` should be a boolean
- `custom_labels` can only have the keys `TRUE` and `FALSE`

(3) If the column type is changed, the display options should be deleted.

(4) We should add supported display options to the `types` endpoint.

## Additional Context
- [Design for Boolean type options on Figma](https://www.figma.com/proto/Uaf1ntcldzK2U41Jhw6vS2/Mathesar-MVP?page-id=4260%3A37440&node-id=4308%3A43205&viewport=324%2C48%2C0.29&scaling=contain&starting-point-node-id=4270%3A40031&show-proto-sidebar=1)
- Blocked by #658
- #392

**Comment by silentninja** [comment]
@kgodey @pavish @seancolsen Do we actually need to `use_custom_columns` field, shouldn't `custom_labels` be enough, you either set it or you don't

**Comment by pavish** [comment]
I don't think we require the `use_custom_labels` field.

**Comment by kgodey** [comment]
According to our [API standards](https://wiki.mathesar.org/en/engineering/architecture/api-standards), we need to always include all keys in responses:

> The portion of the API response describing to a given resource should always contain the same set of keys.

So as long as we don't ever skip the `custom_labels` key in the response, I'm good.

**Comment by silentninja** [comment]
Got into a [nasty bug](https://github.com/encode/django-rest-framework/issues/3847) with nested serializer partial update. JsonField default update method makes it even worse as partial update ends up replacing the whole object on the database but acts as a partial object on the serializer.

 Do we need partial update for display_options , I am thinking of disabling partial update for the custom columns as it makes sense to treat the JSON field as immutable, but this could be supported if needed.

**Comment by kgodey** [comment]
@silentninja I'm not sure what you mean by partial update for `display_options`, could you elaborate?

**Comment by silentninja** [comment]
Should we support updating certain fields of display_options instead of specifying the complete options during a patch request to columns API

For example:
Should this API request be allowed:
PATCH - table/id/columns/id - {'display_options': {'"custom_labels": {
    "TRUE": "yes",
    "FALSE": "no"
  }}
or should the display options be specified only as a whole object(acts like a put request for the display_options field):
PATCH - table/id/columns/id - {'display_options': {'"custom_labels": {
    "TRUE": "yes",
    "FALSE": "no"
  }, 'input': 'dropdown'}

**Comment by kgodey** [comment]
We should not allow nested partial serialization. `display_options` should only be specified as a full object. We're following this pattern elsewhere as well.

**Comment by silentninja** [comment]
> (4) We should add supported display options to the types endpoint.

Should the endpoint return just the keys of the supported display_options or the complete list with the values/choices allowed(something like Entity value attribute)? 

Entity value attribute would mean something like

```
{'BOOLEAN': 
{"options":  [{"name": "input",
                       "values": ['dropdown'. 'checkbox']
}]}}
```

Not sure if this would work for options that need nested data.

**Comment by kgodey** [comment]
I like the entity value attribute option. Our eventual goal is for the frontend to be completely unaware of types (see #661) so I think we'll need that.
