### ISSUE TITLE
Backend support for tables without single-column primary keys

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#395]
## Problem

Currently, our Record API only works with tables with single-column primary keys. We need to explicitly handle tables without primary keys or with multi-column primary keys to prevent unexpected behavior or errors.

## Proposed solution

We need to:
- disable the record detail views (read, edit, delete) for records without primary keys.
- disable the record detail views (read, edit, delete) for records with multi-column primary keys.
- add a field to the `TableSerializer` (and therefore the table API) that indicates the type of primary key that a table has, so that the frontend can handle displaying it properly.

## Additional context
- There's a partial PR with some work on this: #522. Please use this PR as a starting point when working on this.

**Comment by aaditkamat** [comment]
Hi @kgodey, can I take up this issue?

**Comment by kgodey** [comment]
@aaditkamat Yes, go ahead!

**Comment by kgodey** [comment]
I'll close this issue, we can figure out more detailed tickets once design work is done.
