### ISSUE TITLE
Create canonical ordering for tables and return it by default

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#397]
## Problem

We should have a canonical ordering for each table whenever possible. This will make infinite scroll easier to deal with.

## Proposed solution

We should order by primary key by default if the table has one. Otherwise, we should use the entire row as a sorting key (it won't be possible to tell the difference if two identical rows "switch order"). We should always return rows in these orders when they are accessed unless the user specifies a different `ORDER BY`.

## Additional context

- Please see #361

**Comment by mathemancer** [comment]
Be aware, using the entire row as a sorting key will be performance-degrading at scale, so we'll eventually need to revisit.
