### ISSUE TITLE
Implement filtering options for Text types.

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#406]
## Problem
We need to ensure that records that include columns of all Text types support the following filters via API: 
- contains {x}
- is {x}
- is not {x}
- starts with {x}
- ends with {x}
- does not contain {x}
- does not start with {x}
- does not end with {x}
- is empty
- is not empty

This involves:
- Implementing the filters in the backend
- Updating the `/api/v0/databases/<id>/types/` endpoint to store available filters on this type
  - Filter information should include the number of parameters needing to be passed in (e.g. `contains` needs 1 parameter, `is empty` needs 0)

## Additional context
- We're using our fork of `sqlalchemy-filters` to provide filtering. See: https://github.com/centerofci/sqlalchemy-filters.
- This issue is blocked by implementation of Text types: 
  - #404 
  - #405 
  - #407
- #557 provides some context on storing filters.

**Comment by dmos62** [comment]
Should we have a way to filter in a case-insensitive manner?

**Comment by kgodey** [comment]
@dmos62 Yes, we should.
