### ISSUE TITLE
Implement filtering options for the money type

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#418]
## Problem
We need to ensure that records that include columns of all Money types support the same filters as Number types via the API. Please see #385 for the full list. 

We should be able to reuse the implementation for Number types here.

This involves:
- Implementing the filters in the backend
- Updating the `/api/v0/databases/<id>/types/` endpoint to store available filters on `Number` types.
  - Filter information should include the number of parameters needing to be passed in (e.g. `between` needs 2 parameters, `is empty` needs 0)

## Additional context
- We're using our fork of `sqlalchemy-filters` to provide filtering. See: https://github.com/centerofci/sqlalchemy-filters.
- This issue is blocked by #385 
- This issue is also blocked by: 
  - #417
  - #420
- #557 provides some context on storing filters.

**Comment by dmos62** [comment]
Closing, since [it was decided not to use a custom money type](https://github.com/centerofci/mathesar/issues/417#issuecomment-1038962542).

**Comment by kgodey** [comment]
> We still need filters for [Postgres Money Type](https://github.com/centerofci/mathesar/issues/420) I think

Yes, we do.
