### ISSUE TITLE
Handle `MONEY` data type in the backend.

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#420]
This issue is to ensure that Mathesar can handle the Postgres `MONEY` data type.

As part of this issue, we need to ensure that:
- Users can use the API to change a column to `MONEY` if it's possible to do so.
- Automatic type inference during file import suggests `MONEY` when the `MATHESAR_MONEY` type is not installed and the currency detected matches the Postgres `lc_monetary` setting.

**Additional Context** 
- Blocked by #417
- See PR #368 for code that calculates which types are allowed for a column.
- #269

**Comment by mathemancer** [comment]
To double-check my understanding, we should expect a currency symbol to infer a column should be a `MONEY` type, correct?

**Comment by kgodey** [comment]
@mathemancer Yes.
