### ISSUE TITLE
Handle `TIMESTAMP` data type in the backend

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#424]
This issue is to ensure that Mathesar can handle the Postgres `TIMESTAMP` data type.

As part of this issue, we need to ensure that:
- Users can use the API to change a column to `TIMESTAMP`(with time zone) if it's possible to do so.
- Users can use the API to change a column to `TIMESTAMP`(without time zone) if it's possible to do so.
- Users can set and change the `precision` of a given `TIMESTAMP` column via a `type_options` field in the API.
- Automatic type inference during file import suggests `TIMESTAMP` when it makes sense to do so. 
  - We could use something like https://dateparser.readthedocs.io/

**Additional Context** 
- #250 (parent issue)
- See PR #368 for code that calculates which types are allowed for a column.
- This issue was previously specced out in #128

**Comment by silentninja** [comment]
Timestamps data type cause a conflict with date type  when inferring a `date without time` value as it allows a lossy coercion, same with timestamp being able to accept a date without time. We can solve this problem by restricting only if the data contains exact details(date and time mandatory for timestamp). 

There are two ways I can think of:

1.Restrict inference to timestamps - When inferring, we don't consider date type, instead we always infer any date(with or without time) as a timestamp.
2. Throw up an error when casting with inappropriate data - If a data is does not confer exactly to the data type(missing date or time for timestamp or contains time for date type) we throw an error. We end up opinated with this approach and restrict the user who would intentionally want to cast a date to a timestamp.
3. Add strict parameter to casting function - This extend upon the previous suggestion(Option 2) by adding a strict parameter. We enable strict casting only when infering, but allow lossy cast when done manually.

@mathemancer @kgodey @dmos62 Would like your opinion with this issuel.

**Comment by dmos62** [comment]
For context (probably just for me), Postgres `date` contains date (no time of day) information; `Postgres `time` contains time of day (no date) information; Postgres `timestamp` contains date and time information. If we have date+time information, treating it as `timestamp` should be first priority. If we have only time or date information treating it as `time` and `date` respectively should be the priority. We can do inaccurate casting as well (`date` to `timestamp`), but not by default.

**Comment by silentninja** [comment]
> casting a `timestamp` from a `date` is not lossy,

By lossy I mean there is no way to get back the data once it has been coerced. For example

```
SELECT '1997-12-17 07:37:16-08'::DATE::TIMESTAMP;
1997-12-17 00:00:00.000000
```
The time data is lost upon downcasting to date and upcasting to a timestamp.

**Comment by mathemancer** [comment]
I've already been thinking along the lines of option (3) above.  I think we're going to need to have different casting functions based on whether we're trying to infer a type or not.  For now, I suggest using a custom function for casting that disallows lossy conversion (see the one for casting to integer, for example).  We already have an issue #402 involving setting up default casting behavior when appropriate.  Perhaps that could be the first step to an "advanced mode" that would allow lossy casting.

**Comment by kgodey** [comment]
Option 3 sounds fine to me. To confirm, this means that if we see both date and time information, we would infer it to be `TIMESTAMP` and only date information would be a `DATE`, correct?

**Comment by silentninja** [comment]
@kgodey Yes, that's right.
