### ISSUE TITLE
Implement filtering options for date & time types

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#427]
## Problem
- We need to ensure that records that include columns of all Date & Time types support the following filters via API: 
  - between {x} and {y}
  - is {x}
  - is not {x}
  - before {x}
  - after {x}
  - on or before {x}
  - or or after {x}
  - is empty
  - is not empty
- We need to also ensure that values of the filters don't have to be an exact date. We should accept natural language like "next month", or "tomorrow".
  - We could use https://dateparser.readthedocs.io/

This involves:
- Implementing the filters in the backend
- Updating the `/api/v0/databases/<id>/types/` endpoint to store available filters on this type
  - Filter information should include the number of parameters needing to be passed in (e.g. `between` needs 2 parameters, `is empty` needs 0)

## Additional context
- We're using our fork of `sqlalchemy-filters` to provide filtering. See: https://github.com/centerofci/sqlalchemy-filters.
- This issue is blocked by implementation of Date & Time types: 
  - #424 
  - #425 
  - #426
- #557 provides some context on storing filters.

**Comment by dmos62** [comment]
A brief survey on Matrix suggests that we don't need `time x is before time y` phrasing and can do with `time x is lesser than time y`. This simplifies implementation, since under-the-hood we're using a simple `x < y` comparison. An alternative would have been to make up a mechanism for providing filter name aliases for when parameters match some pattern (like them being time-like).

**Comment by kgodey** [comment]
Since the conversation in that Matrix channel has moved on, I'll comment here. 

@dmos62 I think "21 January is less than 4 February" is not as intuitive for non-technical users, people don't regularly say that in English. I'd like to stick to the original phrasing.

**Comment by dmos62** [comment]
Ok, I'll set up filter name aliases in a dedicated PR.
