### ISSUE TITLE
Implement filtering options for duration type

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#431]
## Problem
- We need to ensure that records that include columns of duration types support the following filters via API: 
  - between {x} and {y}
  - equals {x}
  - does not equal {x}
  - greater than {x}
  - less than {x}
  - greater than or equals {x}
  - less than or equals  {x}
  - is empty
  - is not empty
- We need to also ensure that values of the filters don't have to be a number. We should accept natural language like "an hour", or "2 days".
  - We could use something like https://github.com/oleiade/durations or https://github.com/wroberts/pytimeparse

This involves:
- Implementing the filters in the backend
- Updating the `/api/v0/databases/<id>/types/` endpoint to store available filters on this type
  - Filter information should include the number of parameters needing to be passed in (e.g. `between` needs 2 parameters, `is empty` needs 0)

## Additional context
- These filters are the same as those for Number types. We should just reuse those.
  - The only additional thing we need to implement is converting natural language to numbers.
  - Relevant issue: #385 
- We're using our fork of `sqlalchemy-filters` to provide filtering. See: https://github.com/centerofci/sqlalchemy-filters.
- This issue is blocked by implementation of #430  
- #557 provides some context on storing filters.

Marking as blocked until #385 and #430 are complete.

**Comment by mathemancer** [comment]
As with #426, I think there are advantages to using the native PostgreSQL parsing for the human-friendly duration strings, and it's already quite sophisticated and complete.

**Comment by kgodey** [comment]
Reopening this since it was on @dmos62's standup today.

**Comment by dmos62** [comment]
Closing. I double checked and the linked PR indeed makes sure that the `interval` DB type is supported, also the `duration` UI type is properly declared where appropriate in the `filters` endpoint.
