### ISSUE TITLE
Backend work for custom `MATHESAR_TYPES.PERCENTAGE` type.

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#434]
This issue is to create a custom `MATHESAR_TYPES.PERCENTAGE` data type to handle monetary data.

As part of this issue, we need to:
- Create a custom `MATHESAR_TYPES.PERCENTAGE` type in the database.
  - We should probably create a Postgres domain type that uses the `NUMERIC` type under the hood.
  - The type should be case-insensitive at the DB layer and uppercase in the API
- Users should be able to use the API to change a column to `MATHESAR_TYPES.PERCENTAGE` if it's possible to do so.
- Users should be able to change the precision and scale of a column of type `MATHESAR_TYPES.PERCENTAGE` via the API.
- Automatic type inference during file import suggests `MATHESAR_TYPES.PERCENTAGE` when it makes sense to do so.

**Additional Context** 
- Blocked until #409 is complete, to serve as a model for DB case insensitivity
- #269 
- See PR #368 for code that calculates which types are allowed for a column.
- [Postgres documentation on Domain types](https://www.postgresql.org/docs/current/domains.html)
- Inspired by discussion on #386

**Comment by kgodey** [comment]
Per discussion with @mathemancer, we're not going to do a custom type for percentages. It will be a display option for other number types. Closing this issue.

**Comment by silentninja** [comment]
@kgodey Any link to that discussion?

**Comment by kgodey** [comment]
@silentninja It was on a call, sorry. Do you have any specific questions about it?
