### ISSUE TITLE
Improve type inference so that it looks at patterns in the entire dataset

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#438]
## Problem

Currently, our type inference is not "global-property-aware". It does not look for patterns in the entire dataset to infer types. For instance, if we're inferring whether a column is boolean, it would be helpful to be aware of whether there are more than two values in that column in the entire dataset, but our current architecture does not support this. 

## Proposed solution

We should figure out an architecture for more advanced type inference that allows us to look at the entire data before making recommendations. This requires a technical spec.

## Additional context

- See discussion on https://github.com/centerofci/mathesar/issues/387

**Comment by bohemia420** [comment]
Someday, file uploads can be a few GBs, and it anyways can be a p >> n problem (e.g files with 10k columns), and inferring schema globally may begin taking ages (bereft of threading/routines and distributed data processing libs e.g spark).

Will not a "best effort" mining the closest data type besides a datatype hierarchy/ontology be the best strategy (by 10% randomly sampled indices/top N)? i.e inferring numeric but suggesting bool/int or better, inferring 'varchar' but users can click and choose "ip" or "email" or float as they please.

**Comment by kgodey** [comment]
@bohemia420 The implementation details for this issue are not yet defined. It's a placeholder issue to make sure that we improve our inference algorithm beyond the naive "one row at a time" approach that we're currently taking.

**Comment by Anish9901** [comment]
@kgodey Maybe we can use [pandas](https://pandas.pydata.org/) for our type inference and we can map the types used in pandas with the types we are using in Mathesar, I ran a few example files for type inference using pandas please take a look.
```
>>> import pandas as pd
>>> df = pd.read_csv('test_data/type_inference.csv')
>>> df.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   col_1   4 non-null      int64 
 1   col_2   4 non-null      int64 
 2   col_3   4 non-null      object
 3   col_4   4 non-null      object
 4   col_5   4 non-null      object
 5   col_6   4 non-null      int64 
dtypes: int64(3), object(3)
memory usage: 320.0+ bytes

>>> df = pd.read_csv('test_data/data_types.csv')
>>> df.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Integer  3 non-null      int64  
 1   Boolean  3 non-null      bool   
 2   Text     3 non-null      object 
 3   Decimal  3 non-null      float64
dtypes: bool(1), float64(1), int64(1), object(1)
memory usage: 203.0+ bytes
```

**Comment by kgodey** [comment]
@Anish9901 We're not yet ready to work on this issue. We first need to identify what the current problems with inference are, including coming up with concrete examples of current inference algorithm failures. We then need to come up with a new algorithm that fixes these issues. 

The technology used to implement the new algorithm is a very small part of the problem we need to solve. We can't evaluate specific technologies until we have a technical spec for the above. We might consider `pandas` at that stage. Although I'm not sure it will be useful because it does not support all the data types that Mathesar does, so it seems like any inference would be incomplete.

**Comment by dmos62** [comment]
I think it's not obvious that we need a new algorithm for type inference in the foreseeable future. In the interest of keeping our backlog more focused, can we close this issue, @kgodey?

**Comment by kgodey** [comment]
Yes, I'm fine with closing this, we can open a new issue if/when we prioritize this.
