### ISSUE TITLE
Query Builder and Views design

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#442]
Mathesar should support Postgres views. This is a meta-issue to structure all of the work needed to support that functionality. We will complete this work in milestone [Working with Views](https://github.com/centerofci/mathesar/milestone/13).

Please see the following more information about views and queries:
- [Queries and Views Product Spec](https://wiki.mathesar.org/en/product/specs/2022-01-views)
- [Views "Concepts" wiki page](https://wiki.mathesar.org/en/product/concepts/views)

## Issues

Issues directly related to queries and views:
- [ ] #1065
- [x] #455
- [ ] #466 
- [x] #456
- [ ] #781
- [ ] #783
- [ ] #782
- [ ] #834
- [ ] #1252

Issues supporting or depending on queries and views:
- [ ] #723 
- [ ] #978 
- [ ] #1274
- [ ] #1028 

Previously created issues that were folded into other issues above:
- #454
- #805

**Comment by mathemancer** [comment]
@kgodey
Continuing the conversation from #471 :

One problem is going to be that if the purpose for having views is to be able to put a table back together that's been normalized into its constituent atoms, this will fall outside of what PostgreSQL will be able to deal with automatically.  Note from the [docs](https://www.postgresql.org/docs/13/sql-createview.html):

> * The view must have exactly one entry in its FROM list, which must be a table or another updatable view.

This means we won't be able to compose an automatically-updatable view from multiple tables.  We _would_ be able to compose one from a select on a single table under some circumstances.  Off the top of my head, some uses for which this makes sense are:
- hiding columns,
- reordering columns (i.e., changing the column order, not the record order), 
- renaming columns without renaming the underlying data columns,
- changing the type of the columns without changing the underlying type
  - suppose you want to see a given `REAL` column without the digits after the decimal point, but don't want to actually remove those digits in the underlying data.  You could create a view where that column is an `INTEGER`.

**Comment by kgodey** [comment]
@mathemancer That makes sense. I'd like us to build out the product a little more before we decide whether we need to provide functionality to update views that don't meet the PostgreSQL definition of updatable. I'll create an issue for it but put it in "future" for now. We can reevaluate when to schedule it in a few weeks.

**Comment by mathemancer** [comment]
Another quick note about views:  When implementing, note that they _do_ have OIDs (and are available the same way as tables in the `pg_catalog.pg_class` system catalog table).  So, the implementer setting up the views could probably create a model similar to the `Table` model, using the same `id` -- `oid` mapping.

**Comment by kgodey** [comment]
Although we are doing this feature in Cycle 3, this ticket no longer covers accurate design requirements, so I'm going to close it.
