### ISSUE TITLE
Implement adding a table from copy/pasted data

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#445]
## Problem

Users may want to create a table from copy/pasted data.

## Proposed solution

The ["Basic Table Operations" design spec](https://wiki.mathesar.org/design/specs/table-operations) has a solution for this, which we need to implement on the frontend. This issue involves the following portions of the spec:
- _User Experience_: 
  - User adds a new table
  - User adds a table from imported data via clipboard content
 
## Additional context

- Backend work: #190 
- Design issue: #185

**Comment by kgodey** [comment]
Currently blocked by backend work.

**Comment by pavish** [comment]
@kgodey Do we need to support this for alpha or can we de-prioritize this issue?

**Comment by pavish** [comment]
@kgodey Sounds good. Thanks.
