### ISSUE TITLE
Implement editing a table's name

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#447]
## Problem

Users may want to rename tables.

## Proposed solution

The ["Basic Table Operations" design spec](https://wiki.mathesar.org/design/specs/table-operations) has a solution for this, which we need to implement on the frontend. This issue involves the following portions of the spec:
- _User Experience_: 
  - User edits an existing table name
 
## Additional context

- Backend work: #184
- Design issue: #185

**Comment by seancolsen** [comment]
This [comment thread in our weekly discussion](https://github.com/centerofci/mathesar/discussions/840#discussioncomment-1691057) had me thinking more about this ticket.

This ticket seems like it should be quick, but it unfortunately requires some refactoring which has been a bit tricky for me so far. Pavish and I have already discussed it a couple times. I originally opened #764 with the aim of doing a _small_ amount of refactoring, but we decided that direction was not in the best interest of our component library project.

Given our timeline, I wonder if it's worth taking a step back and considering sacrificing some of our UX design for the sake of an easier implementation.

Here's an alternate UX design that would make this ticket much easier to implement:

1. User wants to rename a table.
2. User opens table actions menu.
3. User selects "Rename" option.
4. A modal dialog appears allowing the user to enter a new name and press a "Save" button.

Putting the table name input in the tab would certainly offer a more slick UX. But our tabs system is not set up to accommodate that use case. If we did the modal rename approach now, we could defer the "rename within tab" approach until later.

@kgodey @ghislaineguerin @pavish what do you think?

**Comment by kgodey** [comment]
That sounds good to me. I'll defer to @ghislaineguerin in case she has any UX concerns.

**Comment by pavish** [comment]
I am okay with this. Editing the tab directly for rename involves considerable work which I don't think is essential right away for this particular usecase.

@ghislaineguerin I like the UX where we can edit the tab directly. Is it okay if we went with @seancolsen's suggestion for now and put down the original UX as low priority and come back to later at a later stage in time?

**Comment by ghislaineguerin** [comment]
@seancolsen I think the plan works. It is not worth implementing something if we can't ensure a good user experience. What you describe will work consistently and make it easier to display any error information if needed.
