### ISSUE TITLE
Support for deleting a database view

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#454]
The Mathesar UI should allow users to delete existing views.

## Scenarios
1. The user wants to delete a view with no dependencies. We ask them to confirm the action and go ahead and delete it once they do.
2. The user wants to delete a view with some dependencies. We show them all the existing dependencies that will be deleted if they delete the view and ask them to confirm the action. We go ahead and delete it and all its dependencies once they confirm.
3. The user wants to delete a view (with or without dependencies). We ask them to confirm the action and they change their mind. We don't delete anything.
4. The user wants to delete a view (with or without dependencies). We ask them to confirm the action, they agree. The backend call to delete fails and we don't delete anything.

## Additional Context
- Blocked by design work on #466

**Comment by kgodey** [comment]
@ghislaineguerin @pavish @mathemancer @seancolsen This issue has been updated and is ready for review. Please look through it and unassign yourself after you've added any feedback that you might have.

**Comment by mathemancer** [comment]
There's a subtle detail we'll need to handle on the back end w.r.t. scenarios 2 and 4.  For 4, we'll want to be using `CASCADE` for safety, i.e., so we can roll back if the deletion of the object _or its dependencies_ fails.  However, 2 would be safest if we deleted every dependency ourselves (without `CASCADE`) in a recursive fashion.  That way, we guarantee we don't ever delete an object that we haven't first shown the user we'll delete.  (I.e., it may be there are some edge cases where we don't manage to detect a dependency that would be deleted if we use `CASCADE`).

I suggest we still go with `CASCADE`, but we'll need to be very clear with the user that such a deletion (i.e., deleting an object with dependencies using `CASCADE`) can have unintended consequences, and if they want to be super safe, they should themselves go through and delete the dependencies before deleting the view in question.

**Comment by kgodey** [comment]
I'm marking this as ready and moving to the backlog for @ghislaineguerin to take up when she has the time.

**Comment by kgodey** [comment]
Closing this issue in favor of #466
