### ISSUE TITLE
Support for opening and interacting with a View

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#466]
Once the user has opened a view (see #455), they should be able to view it in a tab in the Mathesar UI.

## View Components
The user should be able to see the following components of Views. Please see [View Structure](https://wiki.mathesar.org/en/product/specs/2022-01-views/05-view-structure) and [View Columns](https://wiki.mathesar.org/en/product/specs/2022-01-views/06-view-columns) for more details.

All users should easily be able to see:
1. **Columns**, including [Column attributes](https://wiki.mathesar.org/en/product/specs/2022-01-views/05-view-structure):
    1. Data Type
    2. Sources
    3. Formula
    4. Link?
2. **Rows**: Similar to table rows (at least as far as viewing goes, editing will be different and is out of scope for this issue)
3 **Filters**: Similar to tables.
4. **Sorts**: Similar to tables.
5. **Groups**: Similar to tables.
6. **Structure Editable?**: The user should be able to see whether the View structure is editable (i.e. whether it can be modified using the Data Explorer)

Advanced users should be able to see:
1. **Query**. This is the underlying SQL query that defines the view, It should support syntax highlighting and be able to be copied easily. Please note that this only 

## View Actions
The user should be able to:
- Open the view in the data explorer if the structure supports it
- Delete the view
    - The user wants to delete a view with no dependencies. We ask them to confirm the action and go ahead and delete it once they do.
    - The user wants to delete a view with some dependencies. We show them all the existing dependencies that will be deleted if they delete the view and ask them to confirm the action. We go ahead and delete it and all its dependencies once they confirm. 
    - The user wants to delete a view (with or without dependencies). We ask them to confirm the action and they change their mind. We don't delete anything.
- Rename the view

## Scenarios
1. The user should be able to see all view components listed above.

### Error scenarios
1. There should be error scenarios for failure to load for each individual component. Examples:
    1. View data fails to load from the backend for some reason.
    2. Backend call to get the view query fails for some reason. 
    3. User has permissions to view the view, but not the query.
2. There should also be error scenarios for failure of all actions - buttons, links, auto-save actions, etc. Examples:
    1. Backend call for filter, sort, or group fails for some reason.
    2. No results for a given filter.
3. Renaming a view fails because the new name entered is an invalid name for the view. Cases for invalid name include:
    1. View name is too long
    2. View name is already taken by another object 
4. View rename fails in the backend for some other reason.
5. The backend call to delete a view fails.

## Design problems to solve
This design presents a few new design problems:

### Differentiating Views from Tables
Views are a new type of database object, so we should consider how to present them to the user. Views are contained within a schema just like tables, but they are used for different purposes. Likely, non-technical users will not easily understand the difference between tables and views, so we need to emphasize this in the design.

There are a few potential confusion points with this difference:
#### Loss of  information about relations (primary keys, foreign keys)
At the table level, users were defining relationships between tables and linking to records. There's no concept for constraints at a view level, and there's also no concept of a related record. The user needs to understand that the foreign key columns they have set (if that was the case) are being used to define the joins.

#### Views that are built on top of other views (no clear table references)
Views can also be built from other views, as described in the scenarios above. However, It's not clear if users should see the table references from the referenced view. The design assumes that table references can help users understand the view definition and locate the tables if they wish to edit a referenced record. They should be able to do the same with referenced views.

### Representing Column Attributes
View columns are quite different from table columns and have different attributes. The same type of column menus may not work for the type of data we need to show about view columns (for example, formulas might be long and not fit in a menu).

[Here is a rough wireframe representing the type of data that needs to be shown about columns](https://wiki.mathesar.org/en/product/specs/2022-01-views/05-ui-requirements-for-views#columns).

### Representing the View Query
We need to allow users to see the raw SQL Query defining the View.  A common use cases for the View Query might be to paste into a database client, we should make this easy by offering syntax highlighting and easy copying.

If the query is editable, we should also show the breakdown of the query into filters, sorts, and aggregations. Actually editing the query will be addressed in #783, the scope of this issue is limited to showing the breakdown.

Another problem to solve here is how accessible the query should be. We don't want to overwhelm non-technical users, but we want to keep the query accessible to technical users. We may not need to show the breakdown of the query at all unless the user wants to edit the structure of a view.

### Introduce concept of joins
Unless a view is referencing a single table, joins will be involved in most views, and users need to see these joins and their properties. The "Link" field of a column denotes whether it is being used as a join column.

## Additional Context
- Previous design and discussion: #624 
- [Views Product Spec](https://wiki.mathesar.org/en/product/specs/2022-01-views) 
- More about [Views Concept](https://wiki.mathesar.org/en/product/concepts/views)
- Closely related to design work in #455
- See discussion on the following issues about deleting and renaming views:
    - #454 
    - #805

**Comment by kgodey** [comment]
@ghislaineguerin @pavish @mathemancer @seancolsen This issue has been updated and is ready for review. Please look through it and unassign yourself after you've added any feedback that you might have.

**Comment by mathemancer** [comment]
> Advanced users should be able to view the query that the entire view is derived from. The query should be syntax highlighted and should be able to be copy/pasted easily.

One use for a view is to provide an interface for less-privileged users to be able to query a subset of the data (for example, you could create a view that excludes student grades, but leaves their ID numbers and emails).  Access to view the underlying query, while it wouldn't create access to the underlying tables, is an information leak.  On a user experience front, we'd need to check what privileges are needed to view the query that created a view, and make sure those are appropriate for less-privileged users (or turn off this feature for such users as appropriate).

**Comment by kgodey** [comment]
I added an error scenario for the case where a user has permissions to view the view itself but not the query underlying it.

**Comment by ghislaineguerin** [comment]
@ppii775 
Figma Walkthrough part 1: https://www.loom.com/share/cd11d43509ad4c2fae997e1b6e6193d2
Figma Walkthrough part 2: https://www.loom.com/share/9d58a5c5c16f45f0bfec85d2ab50b5f2

**Comment by kgodey** [comment]
Assigning this to myself to add details about the new data source attribute for View columns. @ppii775 I'll be rewriting this section of the issue but everything else should stay the same.

> 3. The user should be able to see which column and/or table are referenced in each column, if that data is available. Please note that the column name in the view could be different from the column name of the table, even if the data is the same. There are many possible states for column information:
>    - [...sub-items...]

**Comment by kgodey** [comment]
@ghislaineguerin Assigned you to this since you'll be collaborating with @ppii775.

**Comment by kgodey** [comment]
Although we are doing work related to this in Cycle 3, this ticket no longer covers accurate design requirements, so I'm going to close it.
