### ISSUE TITLE
Changes to sorting order behavior

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#474]
## Problem

Currently, if there are multiple sorts applied, and I add a new sort to a column, I would expect that it would be the first sort applied, not the last.

## Proposed solution

Update the frontend so that applying a sort from a column header makes it the primary sort applied.

## Additional context

- ~@pavish suggested that the grouping and sorting behavior should be different, and grouping should retain default behavior but sorting should be updated. We'll resolve this in the comments of the issue and I'll update the description above once resolved.~
  - This was resolved and the issue description has been updated 
- See conversation on #450

**Comment by kgodey** [comment]
@pavish Could you explain your reasoning for what you're proposing for the ordering of sorting and grouping?

**Comment by pavish** [comment]
My reasoning:

1. For grouping: (I think we should keep current behaviour)

    When we group by Column A, and then Column B, the behaviour is:
    - We create several groups of rows based on Column A.
    - Then we further sub-group the rows within each group, based on Column B.

    If we change this behaviour to latest first, it changes to:
    - We create several groups of rows based on Column A.
    - We create a new set of groups by Column B, and we take chunks of rows from Column A, and arrange them there.

    The earlier would be my assumption when I perform grouping. The second seems to be confusing for me.


2. For sorting: (I agree with changing behaviour to latest first)

    When users sort, however, they would expect to see immediate changes in rows.
    If we sort by Column A, and then Column B, the behaviour is:
    - Column A is sorted.
    - Column B is sorted within entries of same Column A value.

    This may/may not cause major changes on the rows order. Users are generally prone to assume that sorting is done on only one column, hence they would expect immediate changes.

    Changing the order to latest first, will produce immediate changes in order, as a user would expect.

**Comment by kgodey** [comment]
@pavish I played around with the UI a bit and I think you're correct. I'll update the issue to apply to sorting.

**Comment by mr-gabe49** [comment]
@kgodey could you assign me this issue, please?

**Comment by kgodey** [comment]
@mr-gabe49 Done! Thanks :)
