### ISSUE TITLE
Fix GH actions for PRs from forks

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#485]
## Description
As specified in comment https://github.com/centerofci/mathesar/pull/484#issuecomment-886474147, GH actions from forks seem to be running on the current master, instead of the branch from the fork for which the PR was raised.

## Expected behavior
GH actions that are related to state of the code should run on the branch for which the PR is raised. GitHub actions that are related to workflow (e.g. putting PRs into the Active project) should continue to run on `master`.

**Comment by kgodey** [comment]
@pavish I updated the Expected Behavior portion to cover different types of GitHub actions.
