### ISSUE TITLE
Implement adding a new column, resizing columns

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#495]
## Problem

Users might want to add a new column to their table. Users would also want to resize the column widths.

### Adding a column
The ["Working with Columns" design spec](https://wiki.mathesar.org/en/design/specs/working-with-columns) has a solution for adding a new column, which we need to implement on the frontend.

### Resizing columns
The frontend has a set of display stores. The `columnPosition` store contains the position and width of each column, which is currently defaulted to 160px. For each column, we would need to provide a drag indicator which resizes the column and updates this store.

The `columnPosition` information is currently not persisted anywhere. It will be stored in the local storage in a future PR along with a set of table configurations. For the purpose of this issue, we do not have to handle persisting the state when the table is closed.

## Additional context

- Backend work: #199 
- Design issue: #324 
- Design discussion: #436

**Comment by pegnott** [comment]
Hello! I can help with this.

**Comment by kgodey** [comment]
Thanks @pegnott! Assigned to you.

**Comment by pegnott** [comment]
I will be getting started on this tonight or tomorrow and will comment with status updates as they are pertinent. Thanks!

**Comment by kgodey** [comment]
Sounds good, @pegnott! Please let us know if you have questions along the way.

**Comment by pegnott** [comment]
Here's what's done so far and where you can check it out:

- **ui/src/stores/TableData.ts:** added addColumn function
- **ui/src/sections/table-view/TableView.svelte:** added columnAdd func
- **ui/src/sections/table-view/Header.svelte:** add UI for basic column creation

**My forked branch:**
https://github.com/pegnott/mathesar/tree/add_column

**Still to do:**
- open/close state on add_column dropdown
- add UI for other column values (currently hardcoding type to varchar)
- style tweaks as needed once all functionality / ui elements are all in place

**Comment by kgodey** [comment]
Thanks @pegnott! Feel free to open a draft pull request whenever you'd like feedback.

**Comment by pegnott** [comment]
Am in the final stretch, switching the initial resize implementation to an action. Will have that ready for review later today.

**Comment by pegnott** [comment]
I have moved the resizable functionality (and because it can do all sorts of moveable things, renamed it to moveable) into common/actions following the popper example. 

The pull request asks also for a tableColumn component, and that is the next step. Today (through 08/22) I am interrupted by travel, and today I'll be mostly driving. I will be able to work, but be a little slower in response times. I anticipate that I can have a tablecolumn component done by Monday evening. If it's preferred before then, let me know and we can discuss the options.

**Comment by kgodey** [comment]
@pegnott Thanks for the update! Monday evening is fine.
