### ISSUE TITLE
Implement deleting a column

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#496]
## Problem

Users might want to delete a new column from their table.

## Proposed solution

The ["Working with Columns" design spec](https://wiki.mathesar.org/en/design/specs/working-with-columns) has a solution for this, which we need to implement on the frontend.

## Additional context

- Backend work: #199 
- Design issue: #324 
- Design discussion: #436

**Comment by mr-gabe49** [comment]
Hey @kgodey, I have two questions regarding this issue: 
1. What type of warning should a user receive when deleting a column? I didn't see one in the Figma prototype.  A modal similar to the one a user gets when deleting a table? 
2. Will users be able to delete the mathesar id column?

**Comment by kgodey** [comment]
@mr-gabe49 

1. Yes, similar to the one gets for deleting a table. We don't have a way of figuring out column dependencies yet, but a column can have dependencies (e.g. it may be used in a view, or linked via foreign key).
2. Yes, see #439 for more information. We don't have a design for this yet, though, I'll defer to @pavish on the best thing to do as a stop-gap.

Should I assign this issue to you?

**Comment by mr-gabe49** [comment]
Thanks! Yes please, I'll take it.
