### ISSUE TITLE
Implement setting a default value for a column

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#500]
## Problem

Users might want to set a default value for a column.

## Proposed solution

The ["Working with Columns" design spec](https://wiki.mathesar.org/en/design/specs/working-with-columns) has a solution for this, which we need to implement on the frontend.

We should make sure to handle:
- Adding, updating, and deleting a default value.
- Validation errors for default values.

## Additional context

- Backend work: #494 
- Design issue: #324 
- Design discussion: #436

**Comment by Lucasmiguelmac** [comment]
Hello there! Please assign me this issue.

**Comment by pavish** [comment]
Blocked until all data type implementations are complete on the frontend.

**Comment by pavish** [comment]
I'm marking this as ready. The groundwork for all types are done, so we should be able to implement this.

However, the input shown for types will only reflect upon completion of each type implementation. At the time of this comment, only Text and Boolean are ready.
