### ISSUE TITLE
Split up API and serializer code by object

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#510]
## Problem

Currently, our API code and serializer code are in one file each (`views/api.py` and `serializers.py`). These files are getting long.

## Proposed solution

We should split this up per-object (e.g. `views/api/tables.py` and `serializers/tables.py`). It'll be easier to find code and it will be consistent with how we organize our code in other places.

**Comment by arvind-1** [comment]
@kgodey Can i work on this or any other issue you would think priority

**Comment by kgodey** [comment]
@arvind-1 You're welcome to work on this. Please be aware that you might end up having to resolve a few merge conflicts along the way, since this refactor touches a lot of the codebase. If you're not comfortable with that, I suggest one of these instead:
- https://github.com/centerofci/mathesar/issues/313
- https://github.com/centerofci/mathesar/issues/559
