### ISSUE TITLE
Uncaught 404s in record viewsets and pagination classes

### ISSUE THREAD

**Issue by eito-fis** [centerofci/mathesar#517]
## Description
The record viewset, column viewset and paignation classes regularly call `Table.objects.get(id=table_pk)`, which throws a `mathesar.models.Table.DoesNotExist: Table matching query does not exist.` when an invalid table id is passed.

To recreate, run `client.get(f'/api/v0/tables/3000/records/')`.

## Expected behavior
We should ensure that the table exists before querying, or catch the `DoesNotExist` error after querying. We should also include tests for table 404s. 

This is probably best done after  #488 is merged, as it includes a function to do exactly this.

**Comment by kgodey** [comment]
@linzhou-zhong Let us know if you need any help with this issue or if you have questions.

**Comment by linzhou-zhong** [comment]
@kgodey Yes, sorry for the late reply. I'm working on it and I'll let you know if I need some help. Appreciate !
