### ISSUE TITLE
Switch open tables when schema is changed

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#524]
As part of #362 and #525, a navigation menu and layout changes are to be implemented to facilitate switching between schemas.

As per our design specs, when schemas are switched, the open tables should change based on the selected schema. This issue is created inorder to track that behaviour.
* Should retain open table information and load based on selected schema
* tabs store needs to be refactored to depend on selectedSchema store

## Additional context
The [schemas design spec](https://wiki.mathesar.org/en/design/specs/schemas).

**Comment by kgodey** [comment]
@pavish Please note what this is blocked by so I know when to update the status to ready.

**Comment by pavish** [comment]
@kgodey This is blocked by the open PR for schema selector, https://github.com/centerofci/mathesar/pull/525. It should be ready to pick up, when the PR is merged.
