### ISSUE TITLE
Frontend work for adding multi-column unique constraints

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#531]
## Problem

Users may want to create unique constraints on tables.

## Proposed solution

We should provide a way to create unique constraints from the UI following [the "Working with Columns" design spec](https://wiki.mathesar.org/en/design/specs/working-with-columns).

This covers allowing the addition of a new unique constraint, including auto-complete for column names.

Adding other types of constraints will not yet be supported.

## Additional context

- Design issue: #324 
- Design discussion: #436
- Backend issue: #326 
- Backend PR: #488 
- Blocking frontend issue: #328

**Comment by kgodey** [comment]
This is ready for work now that #328 is done.

**Comment by seancolsen** [comment]
@ghislaineguerin and I chatted about the design for this and agreed on the following:

- Build on the current Table Constraints modal.
- Insert an "Add" button above the list of constraints.
- When you click "Add", the whole contents of the modal slide to the left and are replaced by a form to add a new table constraint.
    - The form has "Cancel" and "Save" buttons at the bottom.
    - If you click "Cancel", the modal slides back to view the list of constraints.
    - If you fill out the form and click "Add", the modal slides back to view the list of constraints and the newly-added constraint is briefly highlighted.
