### ISSUE TITLE
 Column API should support creating columns without names 

### ISSUE THREAD

**Issue by eito-fis** [centerofci/mathesar#555]
## Problem
The `name` parameter for the column API shouldn't be required.

## Proposed solution
We should auto-generate a name if it was not specified.

## Additional context
Similar to #449. Please follow a similar naming scheme of `Column n`.

**Comment by kgodey** [comment]
@arvind-1 How's this issue going? Do you need any help?

**Comment by arvind-1** [comment]
@kgodey working on it following the other PR which was similar to this. I will let you know if needed any help. Thank you.

**Comment by kgodey** [comment]
@arvind-1 Checking in on this since it's been a couple of months.

**Comment by kgodey** [comment]
@arvind-1 I've unassigned you since we haven't heard from you in a few months.

**Comment by Anish9901** [comment]
Hey @kgodey, I would like to take up this issue, can you please point me to some docs related to the project that would help me solve this issue. I have already taken a look at #449.

**Comment by pavish** [comment]
@Anish9901 I've assigned this issue to you. We do not have enough docs documenting code level architecture at the moment. Please feel free to ask your questions on our [matrix channels](https://wiki.mathesar.org/en/community/matrix).

It's night at @kgodey's part of the world, she might have additional pointers for you when she's back online.

**Comment by Anish9901** [comment]
ok, @pavish

**Comment by mathemancer** [comment]
@Anish9901 Please see `db/columns/operations/create.py` for the db-layer part of the code. You'll need to add a bit of logic there. Please let us know here or on Matrix if you have some specific questions. The developer docs are a bit light as we're moving quickly to get this released.

**Comment by kgodey** [comment]
@Anish9901 There's no frontend changes necessary for this issue, it's purely a backend issue to enhance the capabilities of our API.

**Comment by Anish9901** [comment]
@kgodey Ok. Also ,How should I change the incoming request.data when an empty string is added in the column name field?

**Comment by kgodey** [comment]
> @kgodey Ok. Also ,How should I change the incoming request.data when an empty string is added in the column name field?

@Anish9901 I'm not sure what you mean, could you elaborate?

**Comment by Anish9901** [comment]
Currently I am removing the disabled tag inside the html and adding the column without any name, after that I am changing the `request.data['name']` to `Column n`.

**Comment by kgodey** [comment]
@Anish9901 I'm still not sure what you're referring to. You shouldn't need to make any changes in the HTML.

Could you open a draft pull request with what you have so far? I think it will be easier to discuss if we can see your code.

**Comment by Anish9901** [comment]
@kgodey I have opened a draft PR #1194 please take a look.
