### ISSUE TITLE
Set up user defined types for Postgres types that aren't reflected in SQL Alchemy

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#558]
## Problem

SQLAlchemy doesn't reflect all Postgres data types (e.g. `XML`, `POLYGON`, `POINT`, etc.), so columns of these types are not handled currently in Mathesar despite being Postgres native types.

## Proposed solution

We should write basic user defined types for these so that they're known to Mathesar. 

## Additional context

This is a placeholder. More details will be added to the issue before it's marked ready.

**Comment by dmos62** [comment]
Superseded by https://github.com/centerofci/mathesar/issues/3095
