### ISSUE TITLE
Tables PATCH endpoint does not update column properties

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#562]
## Description
As per the [import preview api documentation](https://wiki.mathesar.org/engineering/architecture/import-preview-api), a patch request to Tables endpoint, with different values for column properties (name, type) should update specified properties.

This is not working at the moment. The request results in a 200, but the column properties are not updated.

## Expected behavior
The specified column properties should be updated.

## To Reproduce
Send a patch requests to any table.

**Comment by kgodey** [comment]
@pavish Can you post the `PATCH` request body you're sending and the response body you're receiving?

**Comment by pavish** [comment]
@kgodey 

`http://localhost:8000/api/v0/tables/79/`

Sample PATCH request:

```
{
    "columns": [
        {},
        {
            "name": "New Center"
        },
        {
            "name": "New Status"
        },
        {
            "name": "New Case Number"
        },
        {
            "name": "New Patent Number"
        },
        {
            "name": "New Application SN"
        },
        {
            "name": "New Title"
       },
        {
            "name": "New Patent Expiration Date"
        }
    ]
}
```

Response: 

```
{
    "id": 79,
    "name": "patents 17",
    "schema": 1,
    "created_at": "2021-08-15T22:39:09.453340Z",
    "updated_at": "2021-08-15T22:39:09.453353Z",
    "import_verified": false,
    "columns": [
        {
            "name": "mathesar_id",
            "type": "INTEGER",
            "type_options": null
        },
        {
            "name": "Center123",
            "type": "VARCHAR",
            "type_options": null
        },
        {
            "name": "Status",
            "type": "VARCHAR",
            "type_options": null
        },
        {
            "name": "Case Number",
            "type": "VARCHAR",
            "type_options": null
        },
        {
            "name": "Patent Number",
            "type": "VARCHAR",
            "type_options": null
        },
        {
            "name": "Application SN",
            "type": "VARCHAR",
            "type_options": null
        },
        {
            "name": "Title",
            "type": "VARCHAR",
            "type_options": null
        },
        {
            "name": "Patent Expiration Date",
            "type": "VARCHAR",
            "type_options": null
        }
    ],
    "records_url": "http://localhost:8000/api/v0/tables/79/records/",
    "constraints_url": "http://localhost:8000/api/v0/tables/79/constraints/",
    "columns_url": "http://localhost:8000/api/v0/tables/79/columns/",
    "data_files": [
        31
    ],
    "has_dependencies": true
}
```

Note: Combinations of sending both name and type, and empty objects for certain columns, have no effect. The column properties returned are original values of the columns.

**Comment by kgodey** [comment]
We somehow missed implementing this while implementing the preview APIs, so this functionality will have to be implemented from scratch. The current DB` update_table` function only handles renaming the table.

**Comment by mathemancer** [comment]
To be specific, we need to be able to:
- rename table
- rename columns
- change column types
- drop columns
in the same request.

@pavish @kgodey please confirm.

**Comment by kgodey** [comment]
@mathemancer Yes, confirmed.

**Comment by kgodey** [comment]
We can't rename the table in the same `PATCH` request, but we'll be able to:

- rename columns
- change column types
- drop columns

**Comment by pavish** [comment]
@kgodey In that case, I'm not sure using the table PATCH for this is a good idea. Maybe we can create a new endpoint for these column operations?

Separately, it might be better to have a specific endpoint that updates everything (columns, table name, import_verified) in one transaction. As of now, on saving we might have to send two requests (which is fine).
1. Request to update the columns.
2. Request to update import_verified and table name.

But these can only be done synchronously since import_verified should only be updated after everything is ready. Generally, it is better to avoid synchronous requests in the UI. This isn't a priority, but something to consider later on.

**Comment by kgodey** [comment]
@pavish The table `PATCH` will work fine since you'll only need to `PATCH` the `columns` key for all the operations to work.

Renaming the table and updating columns in the same transaction will be a hard problem to solve. The alter table statements in SQL for updating columns use the table name to identify the table, so we can't change the table name during that process.

I'll create a new issue to investigate this after the MVP, Postgres does support DDL rollbacks (unlike some other DBMSes), so it might be possible but I don't think it's worth prioritizing for the MVP.

**Comment by kgodey** [comment]
@pavish Also, I'd do the requests like so:

1. Request to update the table name
2. Request to update columns and import_verified together

**Comment by pavish** [comment]
@kgodey Is there a reason for placing import_verified with the columns?
I thought it was a propery of the table, and makes more sense to send with the table name update.

**Comment by kgodey** [comment]
@pavish it is a property of the table but so are the columns, they're both top level properties of the table. 

I think UX-wise it would make more sense to synchronously verify the import in the same transaction as the column updates, that way if there's an error with the column updates and they don't actually save, import verified doesn't get set to True.

**Comment by pavish** [comment]
@kgodey I agree. What I meant by saying that the requests will be synchronous was:

The approach I had in my mind was,
* First the columns will be updated, if it fails, the error is shown immediately.
* Only if it succeeds, we'll send a request to update the table name and import_verified.

import_verified will not be set to True if either of these requests fail.

I thought it might be better to have a separate PATCH endpoint for this columns update, rather than the tables PATCH endpoint. Having a single endpoint behave differently based on different request body is not rest compliant, atleast it would confuse me if I am using those APIS.

**Comment by kgodey** [comment]
@pavish That makes sense, thanks. I thought you meant simultaneous requests when you said "synchronous".

I think `PATCH` to a list view wouldn't be RESTful either. Django REST Framework only supports `GET` and `POST` requests to list views out of the box.

We're returning an error that says two specific keys in a resource cannot be updated simultaneously. Not every key in a resource can be updated, I see this as pretty similar ("you can't update name and columns at the same time"), especially since it represents an actual limitation with the underlying resource (a database table).
