### ISSUE TITLE
Error importing CSV file through the frontend

### ISSUE THREAD

**Issue by aaditkamat** [centerofci/mathesar#577]
## Description

There is an error sending the XHR request when I try to import the `patents.csv` file from the `test/data` folder through the frontend.

## Expected behavior

I expected to see the contents of the CSV file rendered as a table.

## To Reproduce

1. Click on the New table button that appears in the header of the Mathesar frontend interface
2. Click to browse file from computer
3. Import CSV file from the project folder
4. Click on the Next Button

## Environment
 - OS: macOS Big Sur 11.4
 - Browser: Mozilla Firefox
 - Browser Version: 91.0.1 (64-bit)

## Additional context

<img width="1310" alt="Screenshot 2021-08-18 at 9 45 32 PM" src="https://user-images.githubusercontent.com/30969577/129909287-3522ccbf-7634-442e-86b2-d64ab431f594.png">

**Comment by pavish** [comment]
@aaditkamat Could you please open developer tools -> network tab, choose the request that is fired when Next button is clicked, and show what is displayed in the response?

**Comment by aaditkamat** [comment]
Never mind, I'll close this. I think that I had run this from my branch 🤦🏾‍♂️
