### ISSUE TITLE
`PATCH` requests to the Table API should support changing the table's name and columns at the same time

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#593]
## Problem

The current implementation of the table API does not allow you to update both the `name` and `columns` at the same time. This is counterintuitive and it would be ideal if you could update both at once.

## Proposed solution

We need to figure out how to update the name first, use the updated table name in the column-related changes and roll the whole thing back if any of the operations fail (including the name change).

## Additional context

- See conversation on #562 
- We should do #592 first since this involves more single-transaction operations. Marking this issue as blocked by it.
- [Postgres wiki page on transactional DDL](https://wiki.postgresql.org/wiki/Transactional_DDL_in_PostgreSQL:_A_Competitive_Analysis)

**Comment by dmos62** [comment]
Since the operations of changing a table's name and changing its columns are somewhat distinct (order-sensitive, one depends on the other), maybe let's not try to create a transaction out of it and just expose an API for doing these things separately. Something like `PUT tables/1/name` and something similar for the columns sub-resource.

**Comment by kgodey** [comment]
@dmos62 We already have an API for doing those things separately, this issue was created to help us follow the REST paradigm for the Table resource better. Please see the linked discussion under "additional context" for how this issue came about.

**Comment by Aditramesh** [comment]
@kgodey can i work on this issue?

**Comment by dmos62** [comment]
Either this was implemented without referencing this issue or there's a lack of interest. Close this issue?

**Comment by kgodey** [comment]
Closed, thanks for flagging @dmos62.
