### ISSUE TITLE
Set up automatic code-coverage reporting for the backend

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#603]
## Problem

We should ensure that our backend code is tested thoroughly.

## Proposed solution

It seems like it would be useful to set up automatic code coverage reports.

## Additional context

We could use:
- `coverage`
- `figleaf`
- A service like Codecov

**Comment by VFermat** [comment]
@kgodey I would love to tackle this issue!

**Comment by mathemancer** [comment]
I also like [`pytest-cov`](https://pypi.org/project/pytest-cov/).

**Comment by seancolsen** [comment]
Thanks for helping out, @VFermat! I've assigned this ticket to you. Let us know if you have any questions. Feel free to reach out within this ticket or in the `Code` channel on [Matrix](https://wiki.mathesar.org/community)

**Comment by VFermat** [comment]
@seancolsen Awesome!
Do you prefer if we go with `coverage`/`pytest-cov` (`pytest-cov` is just a plugin for `coverage`), or with Codecov?

From what I know and researched, Codecove is more complete and it's easier to integrate with the repository. If we end up choosing to go with it, I will need one of you guys to give Codecov the necessary permission!

**Comment by seancolsen** [comment]
@kgodey can you help @VFermat answer the above questions?

**Comment by silentninja** [comment]
@VFermat I think you need both. Coverage tools help in generating the test coverage report, [which would be used by CodeCov](https://about.codecov.io/language/python/), correct me if I'm wrong.

**Comment by kgodey** [comment]
@silentninja is correct, we should start with `pytest-cov` and then evaluate CodeCov once we have that running.

**Comment by VFermat** [comment]
Awesome! Already installed `pytest-cov` and got it running!

I have two questions:

- Do you think it should be a workflow that is run for every merged pull request?
- Should we generate an extra report aside from the .coverage file?

**Comment by silentninja** [comment]
> * Do you think it should be a workflow that is run for every merged pull request?

It should run along with the test workflow, so each time a pull request is created and merged.

**Comment by silentninja** [comment]
> * Should we generate an extra report aside from the .coverage file?
Codecov does not support .coverage so you will need to generate report in the [format supported by codecov](https://docs.codecov.com/docs/supported-report-formats). You can refer to the [example](https://github.com/codecov/example-python)

**Comment by VFermat** [comment]
@silentninja @kgodey 
Started working on this (draft pull request is [here](https://github.com/centerofci/mathesar/pull/817))

I think it would be great if we already integrated with Codecov!
For that I will need a maintainer of the repository to register the project on Codecov website.

**Comment by silentninja** [comment]
@VFermat Awesome! @kgodey should help you out with CodeCov part. Btw I think you would need to include db directory too as part of coverage directories.

**Comment by kgodey** [comment]
I've registered the repository with CodeCov and set up the token as a secret called `CODECOV_TOKEN`. It should be available for GitHub Actions.

Let me know if there's any other action needed.
