### ISSUE TITLE
Select component: When scrollbar is present within the dropdown, active option should always be visible

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#608]
## Description
This issue occurs when there are several options for Select menu, which leads to a scrollbar within the dropdown.
When the user presses arrow keys up or down, the active option changes accordingly, as handled in PR #541. If the active option is later in the list, and hidden by the scroll, it is not visible to the user.

**Here the option 'Patent Expiration Date' is active**

<img width="169" alt="Screenshot 2021-08-27 at 4 03 05 PM" src="https://user-images.githubusercontent.com/11850603/131115044-47fa7117-6bd3-4abd-b989-801492431d44.png">

**Here the option 'newcolumn' is active, it's after the 'Patent Expiration Date' option, and it becomes active when arrow key down is pressed. It is not visible to the user.**

<img width="169" alt="Screenshot 2021-08-27 at 4 04 15 PM" src="https://user-images.githubusercontent.com/11850603/131115053-00db2953-fd13-4123-89fb-72cbb956e7f3.png">

## Expected behavior
In the above example, 'newcolumn' should come into view when it becomes active.

## Additional context
1. When the new element is after the current element, height of a single element should be added to the scrollTop value of the container.
2. Similarly, when the element is before the current element, the height of a single element should be subtracted from the scrollTop value of the container.

Examples of components for reference, which implement this well: https://select2.org/i18n

**Comment by mr-gabe49** [comment]
I would like to take this issue :)

**Comment by kgodey** [comment]
Thanks @mr-gabe49! Assigned.

**Comment by pavish** [comment]
As mentioned in the comment: https://github.com/centerofci/mathesar/pull/621#issuecomment-914168654, we need to define the proper UX for scroll behaviour.

> Quoting the review comment from PR #621 
> 
> In this PR:
> * When down arrow is pressed, the active option is shifted from top to bottom. When the active option is out of the viewable region, then scrollTop is modified.
> * When up arrow is pressed, scrollTop is first modified until 0, and then the active option shifts from bottom to top.
> 
> Desired:
> The more desirable behaviour would be to shift the option from bottom to up, and only modify scrollTop when the option is out of the viewable region.
> 
> Here's a video to demonstrate it better: (Keep audio on while viewing)
> <a href="https://www.loom.com/share/6ee216fa550b4f58bc04c56e67d74688">
>     <p>Scroll behaviour within Select dropdown - Watch Video</p>
>     <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/6ee216fa550b4f58bc04c56e67d74688-with-play.gif">
>   </a>
> 
> I'm going to merge this PR, but not close the associated issue.
> I'd let @ghislaineguerin  and @kgodey  take a look, before we finalize on the UX behaviour.

**Comment by kgodey** [comment]
@pavish I watched the video, I agree with you that the behavior in the Ant Design dropdown is more intuitive.
