### ISSUE TITLE
Preserve table scroll across live table updates

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#632]
## Problem
At the moment, while browsing a table in the UI, when a table update is performed (for example a column type is changed or a sort is added) the scroll state of the table view is reset to top left. In terms of UX that might not be desirable or expected.

After some table updates the vertical scroll might lose meaning (for example after changing row sort) and therefore it could be argued that resetting vertical scroll automatically might be desirable at least in some cases. However, I think that resetting of horizontal sort is always undesirable.

## Proposed solution
Persist scroll state across table updates; don't perform automatic scroll resets. I've not looked into what this amounts to technically.

**Comment by pavish** [comment]
@dmos62 Thanks for reporting the issue!
1. I do not think persisting vertical scroll makes sense for table updates. We can persist it while moving to a different tab and getting back. For filters/sort etc., the whole table data changes, so it is essential to reset vertical scroll.
2. I agree that we can persist horizontal scroll. Resetting it does not make sense.

**Comment by dmos62** [comment]
@pavish might make sense to persist vertical scroll selectively. For example when changing the type of a column, but not when chaning sorts, filters or groups.

**Comment by pavish** [comment]
@dmos62 That's a good point. We can preserve vertical scroll if table/column definitions change, but not when only the records change.

**Comment by Jyuart** [comment]
Hey 👋
I'd like to work on this one
May I?

**Comment by Jyuart** [comment]
Key points:
1. When switching between tabs scroll should be persisted (currently it's not)
2. When updating table or column properties scroll should be persisted (currently it is)
3. When adding filtering, sorting, or grouping it should **not** be persisted (currently it is)

Is everything correct?

https://user-images.githubusercontent.com/20342130/162470743-b5ceb751-6fb9-4ac8-af5c-ffe001c62563.mp4

**Comment by Jyuart** [comment]
@pavish, hello!
So, these points (https://github.com/centerofci/mathesar/issues/632#issuecomment-1092975173) are done. Currently working on integration tests to validate the new behavior.

In the meantime, I noticed a few places, that were not in the ticket but I could work on additionally: changing pages and page size. What is the expected behavior if you think it's appropriate to work on them in this task?
I'd say reset scroll position in both cases. What do you think?

**Comment by pavish** [comment]
@Jyuart Yes, when changing pages or pageSize, the scroll positions have to be reset.
