### ISSUE TITLE
Table, Database, & Schema APIs should support sorting by ID & name

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#635]
## Problem

The table, database, and schema APIs don't currently support sorting results.

## Proposed solution

All three APIs should support sorting by ID and name.

## Additional context

We can use `django-filter` / `django-property-filter` for this.

**Comment by bohemia420** [comment]
can it be a simple KW supplied i.e
`/api/v0/tables/2/columns?sort=-name` for descending order w.r.t names?

Can I work on this?

**Comment by kgodey** [comment]
@bohemia420 Sure, I'll assign it to you. Thanks!

The easiest thing would be to use `django-filter`'s `OrderingFilter`: https://django-filter.readthedocs.io/en/stable/ref/filters.html?highlight=sort#orderingfilter

This should apply to:
- `/api/v0/tables/`
- `/api/v0/schemas/`
- `/api/v0/databases/`

This issue doesn't cover adding filters to the columns API (e.g. `/api/v0/tables/2/columns/`)

**Comment by bohemia420** [comment]
Hi @kgodey 
This looks done - I have tested it for all the specified api endpoints:
```
- /api/v0/tables/
- /api/v0/schemas/
- /api/v0/databases/
```

and it seems to sort the entries by either the field i.e "id" or the property i.e "name" (for `schemas` and `tables`). As of now, the capability is basis the assumptions:
- In the Django API, the Label is set to a standard **"Sort By"** followed by drop-down options (`id`, `id(desc)`, `name`, `name(desc)`)
- The `ordering_param` name is being inferred implicitly from the **OrderingFilter variable name**, set to `sort_by`. 
- As of now, ordering has been only accomplished for fields / properties **"id" and "name"**. 

For example,
`http://0.0.0.0:8000/api/v0/schemas/?sort_by=-name`
`http://0.0.0.0:8000/api/v0/tables/?sort_by=name`
`http://0.0.0.0:8000/api/v0/databases/?sort_by=-id`

Which can easily be reached from the "Filters" Modal inside django API `http://0.0.0.0:8000/api/v0/`. 

Have raised a PR #691 for the same. 
> (note: Albeit have simply tested capabilities via Django API, than pytests giving coverage).

**Comment by kgodey** [comment]
Thanks @bohemia420. I'll review the PR.

**Comment by silentninja** [comment]
Created a new bug fix issue for the failing test cases that got merged along with PR related to this issue
