### ISSUE TITLE
Translate `server_default` values

### ISSUE THREAD

**Issue by mathemancer** [centerofci/mathesar#648]
## Problem

For SQLAlchemy columns, `server_default` can only be a string (or a default clause).  This implies needing to know the actual DB representation of values for columns where we want to set a `server_default` value.  In particular, this is a problem for custom (or any) types where the python representation of values for that type is different from the DB representation.  

## Proposed solution

We should be able to use the same python types that we'd use for inserting into a column of a table for setting the `server_default`.  That is, in the case of composite types, we should be able to set the `server_default` with an appropriate dictionary (or JSON) rather than a string.

Implementation suggestion:

We can get the string from the python type by creating a temp table with a column of the desired type, inserting the desired default value as normal, and catching the generated SQL.

## Additional context

This is still only dealing with static default values (not dynamic such as `NOW()`).

**Comment by dmos62** [comment]
Unplanned, because we're removing SQLAlchemy from the codebase. The wider issue of defaults has been addressed in the case of static ones, and we have some open issues for implementing dynamic defaults.
