### ISSUE TITLE
Refactor frontend stores for table-data

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#651]
## Purpose of this refactor:
1. Our tableData store handles colums, records and meta information needed for parameters and display purposes. It also includes the type definitions for all of them. This makes it cluttered, and there is an overlap of different concerns.
A better approach would be to split it into separate stores, and have a parent store which maintains the rest.
2. Currently, logic of certain requirements such passing parameters to table record request, refetching table data when params change etc., are done on the component. This can be side stepped and done entirely by observing store values. This gives a cleaner view/data model.
3. We need to simplify certain display specific stores such as column position map, to improve readability.
4. General improvements, separate out cells from header and row as different components.
5. Update svelte, vite and related packages.

**Comment by pavish** [comment]
@dmos62 Thanks. Your comments make a lot of sense.

> That would imply one or more other parallel namespaces that would sit between the stores and the HTTP client. This would give a central place for holding state and declaring its flow graph, without the mixing of logic.

This is a cleaner structure, and I did consider it while starting on the stores. But that would have been premature optimization. These were my reasons:

The major issue with making modules thin on the frontend is that it eventually leads to a larger build size. The approach module bundlers use to bundle frontend code results in a set of boilerplate code for each file when it's built. The more the number of files, the higher the bundle size.

The tradeoff here is between good user experience (with lower load time) and good developer experience(with thinner modules). As a team, we prioritize the user.

It was a calculated decision to keep the stores and api calls in one place. We only refactor when it becomes essential, as in this case, where the stores are better managed separately. However, separating the api layer would still be premature at this juncture. When we get to it when we reach the point where it becomes essential.

**Comment by mr-gabe49** [comment]
I'm so sorry, I don't know what I did. I was playing around.

**Comment by kgodey** [comment]
@mr-gabe49 No worries.

**Comment by pavish** [comment]
This issue has the following tasks:
- [x] Update svelte and vite to latest versions
- [x] Handle segregation needed for views
- [x] Create dedicated stores for columns, records, meta, display
- [x] Handle records re-request directly in store bypassing component layer
- [x] Handle column position recalc directly in store bypassing component layer
- [x] Handle record deletion directly from store
- [x] Use pagination instead of infinite scroll
- [ ] Handle URL sync from store instead of component layer
- [x] Handle grouping on store response instead of component
- [x] Fix errors reported by svelte-typecheck
- [x] Separate cells from header and row

PRs that handle these:
* #654 

Yet to handle:
* Handle URL sync from store instead of component layer

**Comment by kgodey** [comment]
@pavish It seems like there's one item left to do on your list, so I'm reopening this. Feel free to close if the URL sync is already done.

**Comment by pavish** [comment]
@kgodey Thanks. I missed the fact that the issue got closed. It's not yet been handled, I will handle it in future PRs.

**Comment by pavish** [comment]
@kgodey We have a dedicated milestone for [Sharing](https://github.com/centerofci/mathesar/milestone/39).

I think URL sync belongs in that milestone. Let me know your thoughts.

**Comment by kgodey** [comment]
@pavish What is the current state of URL sync? If there's broken functionality, I think it would be better to fix it sooner.

**Comment by pavish** [comment]
@kgodey URL sync currently does not retain pagination, filters, groups and sort. These parts need to be re-implemented based on the new stores. I was thinking it belongs more in the Sharing milestone, but now I agree that it's better to fix it sooner.

**Comment by kgodey** [comment]
@pavish I'll leave it in here then.
