### ISSUE TITLE
Update design for money data type options

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#655]
## Problem

During implementation of the money type, we realized that decimal precision should be a display option for money, not a database option.

## Proposed solution

The data type options for money should be updated to have decimal precision as a display setting, not a database setting.

## Additional context

- #417

**Comment by ghislaineguerin** [comment]
@kgodey I have updated the prototype and added a note to the global data types document https://wiki.mathesar.org/en/design/specs/eding-view-records

**Comment by kgodey** [comment]
@ghislaineguerin I don't see a display tab here: https://www.figma.com/proto/Uaf1ntcldzK2U41Jhw6vS2/Mathesar-MVP?page-id=4260%3A37440&node-id=4270%3A40881&viewport=324%2C48%2C0.29&scaling=contain&starting-point-node-id=4270%3A40881&show-proto-sidebar=1, only a database tab.

**Comment by ghislaineguerin** [comment]
The prototype is fixed now.
