### ISSUE TITLE
Frontend implementation for non-Mathesar data types

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar#659]
## Requirements

Users should be able to:
- view data in columns that have data types that aren't mapped to Mathesar types
- be blocked from changing data type to and from non-Mathesar types
- ~~view, set, and change data type options related to non-Mathesar data types~~ (Removed after [clarification](https://github.com/centerofci/mathesar/issues/659#issuecomment-1111383608))
- edit data in columns with non-Mathesar types similarly to text types

### Design
- The [Global Data Types](https://wiki.mathesar.org/design/specs/global-data-type-components) spec has the latest version of the UX.
- The [Non-Mathesar Data Types](https://wiki.mathesar.org/design/specs/non-mathesar-data-types) spec has an older version of the UX but more information on user scenarios.
    - **Please note that we no longer have a distinction between "Custom" and "Other" types, any types not on the available types list should be treated as "Other".**

### Backend
- `/api/v0/tables/` lists the name and DB type of each columns 
- `/api/v0/tables/<id/columns/` lists column information in more detail
- `/api/v0/databases/<id>/types/` maps Mathesar types to DB types and provides a list of filtering and grouping options per-type. 

## Additional Context
- #537 (design)
- #269 (concept of Mathesar types)
- #627 (conversation about data types)

## Status

- Blocked by #1316 because I need to be able to test Mathesar with non-Mathesar data types

**Comment by seancolsen** [comment]
@kgodey Can you clarify this text within the "Requirements" section of the ticket description:

> view, set, and change data type options related to non-Mathesar data types

Can you provide a specific example?

**Comment by kgodey** [comment]
@seancolsen It's been too long since I wrote the ticket, I don't know. I _think_ I may have meant that if a data type had options you could set in the database (like scale and precision for `NUMERIC`) and if it was possible to expose them through the API somehow, you should be able to set them through the UI. If that is what I meant, it's technically infeasible anyway. 

I think ignoring or removing that requirement makes sense.

**Comment by seancolsen** [comment]
I'm closing this because:

- I have chatted privately with @kgodey and reached an agreement that testing the following non-Mathesar types is sufficient to determine acceptance of the requirements in this ticket:

    - `jsonb`
    - `integer[]`
    - `circle`

- I've tested Mathesar with those three types, evaluating our current behavior against the requirements:

    - View data as text
    - Edit data as text
    - Be blocked from changing types _to_ the type
    - Be blocked from changing types _away from_ the type

- I've opened the following more-specific tickets to track the remaining work to be done.

    - #1324
    - #1321
    - #1316
