### ISSUE TITLE
Extract columns from table, creating new table

### ISSUE THREAD

**Issue by mathemancer** [centerofci/mathesar#67]
## Problem

Database schema normalization is difficult, and not something many are used to.  However, a properly normalized set of database tables enables reduction of repetition, helps enforce consistency, and more.  So, we should try to help users normalize the set of tables they're working with (I'm avoiding saying schema since it's a reserved word in this project).

## Proposed Solution

The `db.tables` module should be able to extract a set of columns from a table, and connect the resulting tables with a foreign key relationship.  This would be part of a flow to help a user get their tables into [2NF](https://en.wikipedia.org/wiki/Second_normal_form).  Note that we're being a bit sloppy here, since the entries in cells may yet be non-atomic.

Something like:

```
            TABLE 1                                TABLE 1'                 TABLE 2
|=============================|           |=======================|   |=================|
| ID  |  A  |  B  |  C  |  D  |  EXTRACT  | ID  |  A  |  B  |T2ID |   | ID  |  C  |  D  |
|=====|=====|=====|=====|=====|    C,D    |=====|=====|=====|=====|   |=====|=====|=====|
|  1  | ... | ... | ... | ... |  ------>  |  1  | ... | ... | ... |   |  1  | ... | ... |
|  2  | ... | ... | ... | ... |           |  2  | ... | ... | ... |   |  2  | ... | ... |
|  3  | ... | ... | ... | ... |           |  3  | ... | ... | ... |   |  3  | ... | ... |
|  4  | ... | ... | ... | ... |           |  4  | ... | ... | ... |   |  4  | ... | ... |
```
Where `T2ID` is the `ID` key of the new `TABLE 2` as a foreign key.

### Assumptions

- In the extraction process, each table should be reduced to the unique set of tuples from the columns in the table.
- Any columns which are themselves foreign key columns before the extraction should remain so.

**Comment by pavish** [comment]
For the UX to work as expected, we will need a value for the relationship column. We can do one of these:
1. We can retain one of the columns as a foreign key column which we can ask the user to specify during extraction.
2. Join the two tables every time we fetch data, we will still need the user to decide on a column to show on the parent.

We would need a discussion to confirm upon the behaviour for this.

**Comment by kgodey** [comment]
There's also a third option, which is to automatically create a view that retains all the columns but pulls data from the different tables. e.g. if I extract columns A and B from table T to table S, we show a view that includes all the columns in table T plus A and B pulled from table S. The user doesn't have to make any decisions when extracting the column.

**Comment by kgodey** [comment]
I don't think we need to resolve the behavior to move over the code from the prototype though, we can extend/modify later.

**Comment by mathemancer** [comment]
I was kind of imagining that the UX would eventually be something where the user could click/hover/whatever on the FKEY column and see the relevant row from the new table.  However, I think we'll need to ask users.  The good thing about the intended underlying DB structure is that it makes it possible to recover any desirable views.  

I'd definitely want to avoid the user being forced to choose an appropriate FKEY column if possible, since one of the goals here is that they shouldn't really need the expertise to make that choice.

**Comment by pavish** [comment]
The third option mentioned by @kgodey seems like the most intuitive one for the end user. A user is extracting columns into a separate table, but they aren't necessarily removing them. If they wanted to, they can remove by deleting that column from the view.

@mathemancer Upon click, we can show the row from the referenced table. That is an enhancement which we can add, and does not relate to the default view itself. We cannot show just an id in the table, and expect the user to click/hover that particular column to view the name or email.

**Comment by mathemancer** [comment]
I think a number of views may have utility for the split case.  For instance, if they have a `roster` table, and they split it into `teachers`, `students`, and `classes`, they may want to view each table individually, or any joining of the three tables (including all three).  This is the functionality that the underlying data structure will enable (along with the consistency and lack of redundancy advantages).

**Comment by mathemancer** [comment]
This was completed by #85
