### ISSUE TITLE
mathesar stuck in an infinite reload on deleting postgres tables

### ISSUE THREAD

**Issue by bohemia420** [centerofci/mathesar#679]
Owing to issue https://github.com/centerofci/mathesar/issues/398, I had he "NoSuchTableError at /mathesar_tables/1/
" after deleting all its columns via API. 

while restarting docker containers was bringing me to the same issue above on firing `localhost:8000` in the browser, 

I decided to connect to postgres, and clear/truncate the tables, and now while I have truncated the tables:
`mathesar_datafile` and `mathesar_table`, 

<img width="1435" alt="Screenshot 2021-09-23 at 5 03 47 PM" src="https://user-images.githubusercontent.com/3143799/134499941-1f16b04c-c106-4a62-a3da-0f1835478473.png">

it is stuck at a reload for last 20mins - it should have ideally complained of some violation/null records exception IMO.

**Comment by kgodey** [comment]
@bohemia420 Could you please post the traceback in this issue? There's a "Switch to copy and paste view" next to the "Traceback" header that should give you easily pasteable text.
