### ISSUE TITLE
Tests that depend on schema fixture in import/test_csv throws up integrity error when run individually

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar#689]
## Description

Test cases that use schema fixture in mathesar/tests/imports/test_csv fail when run individually or the first test fails when run as a group.

## Expected behavior
Test cases should be pass irrelevant of the order.

## To Reproduce
`docker exec mathesar_service_1 pytest mathesar/tests/imports/test_csv.py::test_csv_upload` - Run individual test 
`docker exec mathesar_service_1 pytest mathesar/tests/imports/test_csv.py` - Run all tests in test_csv

## Additional context

- Related issues:
  - #876

**Comment by silentninja** [comment]
The reason it happens is due to database reflection creating a missing schema, which is followed by the Schema object being created again by the create function causing integrity error. The solution would be to use get_or_create function for objects which could be created by the reflection.

The issue does not occur when running as a whole set due to the reflection cache key being set by others and creating a new schema object won't trigger reflection

**Comment by silentninja** [comment]
The problem seems to be that `schema` fixture using a reflection manager(`objects`) to create a `Schema` object rather than using the default manager(`current_objects`)

**Comment by Anish9901** [comment]
@silentninja I tried fixing this issue by changing the `objects` to `yield Schema.current_objects.create(oid=schema_oid, database=test_db_model)` is this the correct approach to solve this?

**Comment by Anish9901** [comment]
The tests are passing individually as well.

**Comment by silentninja** [comment]
> I tried fixing this issue by changing the objects to yield Schema.current_objects.create(oid=schema_oid, database=test_db_model) is this the correct approach to solve this?

Yes, that is the correct way to do it.


> The tests are passing individually as well.

Make sure to run the test without the fix to confirm if the problem still exists.

Since you have started working on the fix I will assign this to you, for further issues please make sure to have a maintainer assign the issue to you before starting to work on it, to prevent conflicts.

**Comment by Anish9901** [comment]
> Make sure to run the test without the fix to confirm if the problem still exists.

The problem did exist before the fix.

> Since you have commented out the fix, I hope you would be submitting a PR for it, so I will assign this to you, for further issues please make sure to have a maintainer assign the issue to you before starting to work on it, to prevent conflicts.

Sure, I'll take care from next time.

**Comment by Anish9901** [comment]
@silentninja I have made the PR #1217 resolving the issue please take a look.
