### ISSUE TITLE
Left pane UX improvements

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#723]
## Requirements
1. All tables and views from the db are listed on the left pane. This would become impractical to use if the number of tables/views is large (>50). We require an improved UX where we do not show all the tables/views.
2. We need to allow closing and opening of the left pane.
3. We need to consider how graphs, apps etc., would fit into the left pane.

@ghislaineguerin please feel free to add more details

## Additional context
- See discussion on #455

**Comment by ghislaineguerin** [comment]
Long list handling will be addressed in #981

**Comment by kgodey** [comment]
Assigning to myself to make implementation issues

**Comment by kgodey** [comment]
I'm tracking creating implementation issues in #1027 so I'm closing this issue.
