### ISSUE TITLE
Improvements for table deletion flow

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#755]
## Description
From the PR https://github.com/centerofci/mathesar/pull/650, we identified certain improvements we could do for the UX for deleting table.

Quoting points from this comment: https://github.com/centerofci/mathesar/pull/650#pullrequestreview-787938023
* Show loading inside the modal when deletion is in progress
* Close the modal only after deletion completes
* Keep modal open, if the delete request fails. Show error inside the modal.
* Always ask for confirmation (by opening the modal), when user clicks delete. Right now, it is only shown when the table has dependencies (which is usually always the case).

Our existing UX does not cover loading and failure states. These are minor changes that keep the same flow and handle the missing states.

@ghislaineguerin Please take a look and update if this looks good or if we need a fundamental change in the UX.

**Comment by kgodey** [comment]
@seancolsen Assigned you to this per discussion in #836
