### ISSUE TITLE
Allow resizing of columns

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#765]
## Problem
We need columns to be resizable inorder to make it easier for the user to view and work with their data.

## Proposed solution
For each column, we would need to provide a drag indicator which the user could use to resize the column. The frontend has a set of display stores. The `columnPosition` store contains the position and width of each column, which is currently defaulted to 160px. 

The `columnPosition` information is currently not persisted anywhere. It will be stored in the local storage in a future PR along with a set of table configurations. For the purpose of this issue, we do not have to handle persisting the state when the table is closed.

**Comment by sahilsaini110** [comment]
Hey, @pavish I would like to work on this issue. I don't have have exact idea on how to do it so i am exploring it and will solve it in few days.

**Comment by pavish** [comment]
@sahilsaini110 Sure! I've assigned this issue to you. There's a closed PR which might give you a better idea of previous approaches: https://github.com/centerofci/mathesar/pull/649

Feel free to ask us anything to help you with this issue.

**Comment by kgodey** [comment]
@sahilsaini110 I wanted to follow up on this issue since it's been a few days and I don't see a PR yet. Please let us know if you need any help or if you are no longer working on the issue.

**Comment by sahilsaini110** [comment]
I would like to try it for some more time maybe 3-4 days. After that may someone else can work on this. Also, it will be very helpful if you provide me with some guidance regarding the issue.

**Comment by kgodey** [comment]
@sahilsaini110 There's information about the issue in the issue description and in the related PR, that is the guidance. If you have a specific question, please ask.

**Comment by sahilsaini110** [comment]
@pavish @kgodey I attempted to resolve this problem but was unable. I've tried the earlier approach as well, but I'm still unable to complete it. You can assign this issue to someone else.
