### ISSUE TITLE
Add UI to filter on the presence of duplicate values in one column

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#770]
## Problem

User wants to add a filter condition that shows duplicate values for one column.

## Proposed solution

![image](https://user-images.githubusercontent.com/42411/139340390-088c655e-2769-4c10-b957-78e30fc6be17.png)

## Additional context

- Backend issue: #501 

## Out of scope

- filtering on duplicates across multiple columns

**Comment by yankevn** [comment]
Hi, I'd like to work on this issue!

**Comment by mathemancer** [comment]
Go for it, @yankevn .  Please ask if you have any questions!

**Comment by yankevn** [comment]
Just to clarify, is this issue purely frontend work, so all I do is add an additional filter to the dropdown menu? How much is expected from this issue in terms of integration with the rest of the backend and db?

**Comment by seancolsen** [comment]
@yankevn Thanks for clarifying. Yes, this issue is purely front-end. The back-end work to filter by duplicate values should already be complete. See the [this Python test](https://github.com/centerofci/mathesar/blob/e4c0fbf63d4249d3fcca7ad9c724bc3ebd63bbf7/mathesar/tests/api/test_record_api.py#L88-L88) for an example of the API filtering by the presence of duplicates.

> all I do is add an additional filter to the dropdown menu

Yes.

It's also worth noting that @pavish is currently working on some changes to the way we handle column types in the front end. When completed, those changes will allow us to improve the filtering UI, making it dynamic based on the column type information. For example, some columns don't allow duplicates. In those cases, we probably won't want to give the user the option to filter by duplicates. But for now, I recommend you take the simplest path towards completing this feature, which will mean giving _every_ column the ability to filter on the presence of duplicate values.

**Comment by yankevn** [comment]
I see. After some investigation, it looks like the current API expects a url of the format "/tables/2/records/..." while the url to invoke the duplicate filter requires an additional prefix: "/api/v0/tables/2/records/...". Is this intentional, and is this within the scope of this issue?

**Comment by kgodey** [comment]
@yankevn All API calls require the `/api/v0/` prefix. I'm not sure where you're seeing the API calls without the prefix.

**Comment by yankevn** [comment]
Sorry about that, looks like it was a false alarm, you can ignore my last message!

**Comment by yankevn** [comment]
I do notice that I can filter by duplicates when I pass in a hardcoded API call uri, but the API returns error 400 if there's an "and".

In other words, 
`'/tables/2/records/?limit=500&offset=0&filters=[{"field": "", "op": "get_duplicates", "value": ["Patent Expiration Date"]}]'`

will work, but

`'/tables/2/records/?limit=500&offset=0&filters={"and": [{"field": "", "op": "get_duplicates", "value": ["Patent Expiration Date"]}]}'`

will not work. Is this a known issue?

**Comment by kgodey** [comment]
@yankevn Yes, it's a known issue, see https://github.com/centerofci/mathesar/issues/501#issuecomment-899795976

**Comment by yankevn** [comment]
Was there a reason for requiring that the "value" field needs to be an array instead of just a string? It seems to be causing problems with regards to casting as well as the db commands.

![image](https://user-images.githubusercontent.com/43934572/143373388-3ec5a43c-0167-4c3d-b4ae-2964b407094f.png)

**Comment by yankevn** [comment]
Also, sorry, if this is a silly question, I think I've got code that I'd like someone to take a look at, but I can't find my branch anywhere when trying to create a pull request. Am I missing something when creating my branch, or do I have to fork the repo to create a pull request?

**Comment by pavish** [comment]
> @yankevn Yes, it's a known issue, see [#501 (comment)](https://github.com/centerofci/mathesar/issues/501#issuecomment-899795976)

@kgodey This filter seems to function very differently compared to the rest.

1. The UI has a column selector which is used to identify the field to filter, however in 'get_duplicates' case, it is empty and the columns are mentioned on the value param. This will require special handling.
2. This filter cannot work with the other filters together at the moment making the entire filter pane UI non-functional if this filter is used. How would we send the request when the user adds this as a second condition?
3. If we plan to use a separate param for get_duplicates later, instead of the filter param, the entire UX has to change to adapt to this.

I think we should handle this as soon as possible.

**Comment by pavish** [comment]
> Also, sorry, if this is a silly question, I think I've got code that I'd like someone to take a look at, but I can't find my branch anywhere when trying to create a pull request. Am I missing something when creating my branch, or do I have to fork the repo to create a pull request?

@yankevn Yes, you will have to fork the repo to create a PR.

**Comment by pavish** [comment]
@yankevn 

> Was there a reason for requiring that the "value" field needs to be an array instead of just a string?

This particular filter requires special handling for now, which includes `value` having to be an array, and `field` having to be empty string. This is not the same as other filters (the other filters work on the WHERE clause while this doesn't), but we have it as part of the `filter` param in the api request for now. @kgodey might offer better insight into why and how to structure this later.

> EDIT: to clarify, I am hardcoding these URLs in the "sendXHRRequest" method in mathesar_ui/src/utils/api.ts

The api.ts file is supposed to be common throughout the application and it should not be modified for this usecase.

Please refer the method `setRecordRequestParamsStore` in `/stores/table-data/meta.ts`. The special handling should be done in the part where the filter param is set in the request.

**Comment by yankevn** [comment]
Hi pavish,

I actually have an initial implementation that seeks to solve the issues you're bringing up. Currently, I have it implemented so only the first filter in the list has the option of filtering by duplicates. DisplayFilter.svelte and the setRecordRequestParamsStore methods have been updated to accommodate for this special case. I don't expect my implementation to be perfect, but I will be creating the PR after I send this message, and hopefully you can take a look and see what thoughts you may have.

**Comment by yankevn** [comment]
> field needs to be empty.

From my testing, it seems that the API still works if field is populated. Does field *for sure* need to be empty?

**Comment by kgodey** [comment]
> @kgodey This filter seems to function very differently compared to the rest.
> [...]
> I think we should handle this as soon as possible.

@pavish I created a draft issue #846 so we don't forget about it. Once you've reviewed this PR, we can flesh it out further.

**Comment by pavish** [comment]
> > field needs to be empty.
> 
> From my testing, it seems that the API still works if field is populated. Does field _for sure_ need to be empty?

@yankevn Turns out the api just ignores this param for get_duplicates so it doesn't matter what we provide at the moment. 

Eventually, we'll expect this to work like the other filters as tracked by the issue #846

**Comment by yankevn** [comment]
@pavish I've just pushed a new commit that hopefully addresses your comments, I'm not sure if I'm supposed to create a new PR or not. Let me know if I need to do anything special!

**Comment by pavish** [comment]
@yankevn Thank you! I'll take a look.

The usual process is to re-request review or comment on the PR once changes are done.  You can find the option to re-request review on the right bar of the PR under 'Reviewers' section, next to the reviewer name.

It's not required at the moment, just mentioning it for future PRs. Here's the guidelines mentioned on our wiki: https://wiki.mathesar.org/en/engineering/code-review#authors
