### ISSUE TITLE
Improve UX when adding new records to a table with a NOT NULL column

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#775]
## Reproduce

1. Set up a table with a NOT NULL column that doesn't have a default value.
2. Click "New Record".
3. Observe new row with yellow background, spinner that spins several seconds, finally a "Couldn't save changes" error.

![image](https://user-images.githubusercontent.com/42411/139354253-40fc87e5-9a4b-4c58-9154-ca01824a9f43.png)

I'm not sure what the expected behavior would be here. I think we need some more clarity around that from a UX perspective. @ghislaineguerin @pavish would you like to weight in?

**Comment by seancolsen** [comment]
I'm marking this as blocked by #859 because we'll need more granular error info from the API before we're able to display a warning inside the cell

**Comment by seancolsen** [comment]
This should be ready to implement now that #859 is closed

**Comment by seancolsen** [comment]
In a separate [discussion](https://github.com/centerofci/mathesar/pull/1053#issuecomment-1032841315), we came to the conclusion that we should shift the "NOT NULL" validation responsibility to the front end. This means that before sending the API request to create an new empty record, we'll check the columns store to see which columns have a NOT NULL constraint. Then we'll provide some UX for the user to fill in the values. We'll need to think this through a bit more to hammer out the details.

**Comment by kgodey** [comment]
@seancolsen Is this unblocked since we decided on client side validation (#1057)?

**Comment by seancolsen** [comment]
@kgodey Indeed! Thanks for the follow-up. I've marked this ticket as unblocked now. Although I'll also mention that before resuming work on this ticket, I'd like to complete our (hopefully quick) planned synchronous discussion on "UX for failure to save a cell" at this Wednesday's [meeting](https://hackmd.io/OEXWY519TceOUi53q0Ay1A).
