### ISSUE TITLE
Pytest does not respect environment variables

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar#800]
## Description
Pytest is using hardcoded configuration variables like database host etc and environment variables don't seem to override the configuration variables.
## Expected behavior
Since we use environment variables for specifying database configuration when running a django server, environment variables should also be used for pytest when available and the test configuration defaults should be used only when their respective environment variables are missing.
## To Reproduce
1. Add `DJANGO_DATABASE_URL=postgres://mathesar:mathesar@**custom_mathesar_db**:5433/mathesar_django` to environment variable list
2. Run pytest
3. Test cases would still be using `postgres://mathesar:mathesar@db:5432/mathesar_django` as `DJANGO_DATABASE_URL` variable.

## Environment
 - OS: macOS
 - pytest: 6.2.3

**Comment by kgodey** [comment]
@silentninja The environment variables used in `pytest` are specified in the `setup.cfg` file. We're using this package: https://github.com/MobileDynasty/pytest-env
