### ISSUE TITLE
Facing issues in setting up repo on Windows

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar#830]
I am trying to setup this repository in my local. I am using Windows OS. I have installed docker. I am facing difficulty in the following step.
Clone the repository and then copy the .env.example file to .env like so:
cp .env.example .env
Please help me.

_Originally posted by @agrawalanshul053 in https://github.com/centerofci/mathesar/issues/292#issuecomment-972744504_

**Comment by pavish** [comment]
@silentninja Linking to: https://github.com/centerofci/mathesar/issues/570 to keep track of it there as well.

**Comment by silentninja** [comment]
> @agrawalanshul053 These commands are to copy files in a posix-like environment.

> In windows, you can copy the `.env.example` to a new file and name it `.env`.

> Alternatively, you can use your WSL (Windows subsystem for Linux) shell, and use posix-like commands. 

@agrawalanshul053  Please use the above solution suggested by @pavish and see if it works for you

**Comment by pavish** [comment]
I'm going to close this issue since there's no update here and most of our issues with Windows is users not cloning the repo in the linux subsystem.
