### ISSUE TITLE
Consider updating to Python 3.10

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#831]
## Problem
Our currently used Python version is 3.9, released 2020-10. In 2021-10 Python 3.10 was released. It offers some interesting improvements.

## Proposed solution

Here's a 3.10 [what's new document](https://docs.python.org/3/whatsnew/3.10.html). Among other things, it adds structural pattern matching, and more importantly it iterates over the [`dataclasses` module](https://docs.python.org/3/library/dataclasses.html), adding some significant improvements (especially concerning default field values; search for `3.10` in the `dataclasses` docs for more information). The `dataclasses` improvements make Python 3.10 the desirable runtime for [our recently discussed data structures](https://github.com/centerofci/mathesar/issues/823).

## Additional context
Relevant to implementing https://github.com/centerofci/mathesar/issues/823.

**Comment by kgodey** [comment]
I don't think we should have Mathesar depend on Python 3.10. We're trying to make it easy for users to install on their systems and some users have older servers that don't come with 3.10.  e.g. Debian stable currently uses 3.9.

I'm already iffy about depending on 3.9, I think we should support a larger range of Python versions.

**Comment by kgodey** [comment]
Marking this as a draft because it's not actionable yet cc @mathemancer since he's on comms this week.

**Comment by silentninja** [comment]
I agree with @kgodey on supporting older versions that are being [supported by python](https://endoflife.date/python). A refactor proposal that describes how an upgrade might help the codebase could help us in weighing the advantage of an early upgrade before the python version gets deprecated(or a few months before it).

**Comment by mathemancer** [comment]
We've also had discussion around which Postgres versions to support.  See  #505 and #708 .  

I think it's _much_ more reasonable to require fairly new versions of Python than PostgreSQL.  If needed, an administrator of a server could:
- Use downloadable Python binaries + virtualenv to install any version of Python we desire, and use that for Mathesar, or
- Use docker for the service.

To contrast, requiring a new (or any particular) version of PostgreSQL might well involve upgrading a DB version, which is a major endeavor (especially if the DB is in use).  Thus, I think that it's more reasonable to be restrictive for Python versions than PostgreSQL versions.  So, I suggest we defer supporting multiple Python versions until after we have multiple PostgreSQL versions sorted.  I expect supporting multiple versions of PostgreSQL to be quite difficult, by the way.

As for 3.9 vs. 3.10, I don't care too much.

**Comment by dmos62** [comment]
If running in Docker, using 3.10 is painless. Do we expect early adopters to use Docker? For local development you probably will have to fiddle with your Python install to get 3.10, but that's pretty standard.

The thing about 3.10 is that it brings important improvements over 3.9 in an area we care about: `dataclasses`. It has improvements relating to context managers too (not sure if significant), which were recently discussed for error handling and such in #623.

**Comment by mathemancer** [comment]
> Do we expect early adopters to use Docker?

Not sure.  My point with that is that there are a number of options for managing python versions that make it easier than managing PostgreSQL versions.

I _do_ think it's reasonable to expect someone to be able to set up a non-system installation of python for Mathesar if needed.

**Comment by kgodey** [comment]
> The thing about 3.10 is that it brings important improvements over 3.9 in an area we care about: dataclasses. I think when we start working on #823 this will become apparent. It has improvements relating to context managers too (not sure if significant), which were recently discussed for error handling and such in #623.

I'm not disputing that using 3.10 might make things easier for us, but I don't want to make Mathesar harder for people to deploy. I don't think we should be opinionated about how Mathesar is deployed and I also think that we should make it as easy as possible to deploy it across a variety of scenarios.

>  Do we expect early adopters to use Docker? 

We do not expect _all_ early adopters to use Docker.

> I suggest we defer supporting multiple Python versions until after we have multiple PostgreSQL versions sorted.

I don't think we should prioritize supporting pre-3.9 versions at the moment but I am reluctant to upgrade to a version that's not supported by default in e.g. the latest Debian stable. I'm most familiar with Debian so I'm going to continue using that as an example – sysadmins I've known like Debian stable because it's dependable, and will sometimes not use software if it requires non-standard packages.

---

I suggest closing this issue as `wontfix` for now. We can always upgrade at a later date, but it's going to be more difficult to support lower versions in the future.

**Comment by silentninja** [comment]
For someone not that technical, it is easier to run `pip install` if they are using a unix system compared to creating a new virtualenv. Moreover not every managed server out there would be having support for the latest python. For example [Elastic beanstalk supports only python 3.8 and 3.7](https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.python)
