### ISSUE TITLE
`undefined` shown as `id` column type during import

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#867]
## Reproduce

1. Within the UI, click on "New table" at the top right. 
1. Choose "Import data".
1. Upload [birds.csv](https://github.com/centerofci/mathesar/files/7662974/birds.csv).
1. During the preview step, observe `undefined` displayed as the column type for the `id` column.

    ![image](https://user-images.githubusercontent.com/42411/144892161-cd131122-35da-400c-899d-3d4c33c2fe5a.png)
    
## Expected behavior

- An empty cell would be fine. That's probably the easiest fix.
- Alternatively we could show the type as `INTEGER` and disable the select element.

**Comment by Carlosbogo** [comment]
Hi, I would like to work on this issue, but I haven't worked on this repository before. Where should I search to find the code for the GUI shown in your picture?

**Comment by seancolsen** [comment]
Hi @Carlosbogo Thanks for helping out! I've assigned this ticket to you and added some clarification in the origin ticket description that I hope will make it easier for you to reproduce. If you have any trouble, you can also find me on [Matrix](https://wiki.mathesar.org/en/community#matrix) with this same user name or in the "Code" channel.

**Comment by silentninja** [comment]
Hello @Carlosbogo, Welcome to Mathesar!. You can set up the project using these [instructions](https://github.com/centerofci/mathesar/blob/7a5a8da293eed084ffd4bb1bc563a6a6aeb159a0/db/tests/types/operations/test_cast.py#L31). Once the project is set up you can reproduce the bug using the steps listed in the issue description.

**Comment by seancolsen** [comment]
Also, to point you in the direction of the code you'll need to modify, see `Preview.svelte` which contains `PreviewColumn.svelte`. I think the changes will most likely end up being in `PreviewColumn.svelte`.

**Comment by Carlosbogo** [comment]
Thank you very much, but I have some doubts as I haven't used TypeScript before: 

Would the issue be solved with an `if` statement that checks whether or not the column type is undefined in the following code to change the label acordingly?
https://github.com/centerofci/mathesar/blob/96856d92bd61b66d0c712e74f9fb332ec5c77394/mathesar_ui/src/sections/import-data/preview/PreviewColumn.svelte#L13-L16

**Comment by silentninja** [comment]
A null coalescing operator should be used if you want to check for undefined during object initialisation, but from what I can see the problem is not with the `Column.type` being undefined, the selected option for `id` seems to be having `{'id': 'INTEGER', 'label': 'INTEGER'} when I tried printing the object to console.

**Comment by pavish** [comment]
Hey @Carlosbogo, just checking in to see the status of this issue. How's it coming along? Do you need any help from our team?

Please feel free to reach out to us if you do.

**Comment by kgodey** [comment]
@Carlosbogo I've unassigned you from this issue since we haven't heard from you in a couple of months. Please let us know if you're still interested in contributing to the project.

**Comment by A1O** [comment]
I would like to work on this issue.

**Comment by seancolsen** [comment]
Thanks @A1O I've assigned you
