### ISSUE TITLE
Fix github-actions bot applying incorrect labels to new tickets that it opens

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#873]
The github-actions bot is opening tickets like #864 and creating labels like `type:bug` in doing so. Unlike the labels we commonly use, the labels that the bot applies don't have spaces after the colon. I deleted the label `type:bug` a few weeks ago. Now it's back because of the bot and our labels are more cluttered. Can we make the bot use the labels with spaces? Or can we remove the spaces from the labels that we're applying manually?

@kgodey

**Comment by kgodey** [comment]
This is a bug with the upstream GitHub action, updating the version of the action should fix it. See https://github.com/centerofci/mathesar/pull/721#discussion_r724564546
