### ISSUE TITLE
Makefile tasks for doing common tasks like first-time setup

### ISSUE THREAD

**Issue by dmos62** [centerofci/mathesar#874]
## Problem
We have some sequences of commands that every developer has to run at one point or another. For example, for first time setup you run:

```
> cp .env.example .env
> docker-compose up -d
> docker exec mathesar_service python manage.py migrate
> docker exec -it mathesar_service python install.py
```

Last two might depend on docker-compose having finished setting up.

## Proposed solution
Would be nice to have a way to perform such tasks by running a single command, or just having a way not to have to remember the specific python commands or the container name, or that the `.env` file has to be instantiated.

## Additional context
Another task to automate would be reseting/purging development environment's state in case it got corrupted.

**Comment by abhishak3** [comment]
I would like to work on this issue.

**Comment by kgodey** [comment]
Go ahead @abhishak3. Thanks for your interest!
