### ISSUE TITLE
Add CI pipeline workflow to check for TypeScript errors

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#877]
From what I can tell, we don't have any continuous integration checks in place to verify the absence of TypeScript errors.

I think we need to add:

- `svelte-check` to check `*.svelte` files
- `tsc --noEmit` to check `*.ts` files

Does that sound good, @pavish?

**Comment by pavish** [comment]
@seancolsen We could configure `svelte-check` to also check ts files by passing the tsConfig file to it. Refer `--tsconfig` option in [docs](https://github.com/sveltejs/language-tools/tree/master/packages/svelte-check).

I'm not sure if this might introduce other issues, in which case we can go with `tsc --noEmit`.
