### ISSUE TITLE
Get TypeScript working within Storybook stories components

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#878]
Currently we can't use TypeScript within a Storybook components.

This is a pain for the following reasons:

- I always seem to forget, and I begin writing my story with TypeScript only to get strange errors from Storybook.
- We miss out on catching bugs early during component development, only to find the bug later on once we're able to use the component in a TypeScirpt component.
- It's harder to copy code snippets between stories and our app.

Storybook [claims](https://storybook.js.org/blog/storybook-for-svelte/) "Zero-config setup w/ built-in TypeScript support" (for Svelte)

**Comment by seancolsen** [comment]
I spent about 2 hours in a rabbit hole this morning trying to get TypeScript to work. I eventually gave up and moved on.

My approach was a bit of splatter paint, but I'll try to do a brain dump of the things I tried to the best of my recollection.

- Modify our `main.js` file to look more like [this one](https://github.com/storybookjs/storybook/issues/12754#issuecomment-708884287). (I tried _lots_ of different ways of melding that config with our config).
- Remove our custom alias logic.
- Remove all the MDX stuff.
- Upgrade to the most recent pre-release version of Storybook.
- Uninstall storybook. Remove `.storybook`. Remove all stories (by adding a `.old` suffix to the file name). Begin from scratch with `npx sb init`.
    - I thought for sure this would get me somewhere, but no. I was just working with the default stories that came with Storybook. When I would enable TypeScript in one of them, that story would disappear from Storybook.
    - I tried switching to `builder: 'webpack4'` to `builder: 'webpack5'` (and installing `@storybook/manager-webpack5 @storybook/builder-webpack5`) I couldn't figure out how to get Storybook to start.

**Comment by pavish** [comment]
@seancolsen Writing TS within Storybook stories does not work well i.e whenever we try to specify or define types/interfaces on the story, it breaks storybook. I've previously tried fixing this but gave up, it was pain just to get the rest working without TS.

I should have made a note somewhere, I'm glad we have this open issue now. We can come back to this after Storybook's next major release.

**Comment by pavish** [comment]
Closing this issue, since Storybook is removed as of [this PR](https://github.com/centerofci/mathesar/pull/3214).
