### ISSUE TITLE
Make TS TableRecord interface contain the record response instead of extending it

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#906]
## Problem

[Here](https://github.com/centerofci/mathesar/blob/ad2f6b1d38157476f6656c43e68d626d5a9b3d3c/mathesar_ui/src/stores/table-data/records.ts#L23-L23) we have the following code:

```ts
interface TableRecordInResponse {
  [key: string]: unknown,
}

export interface TableRecord extends TableRecordInResponse {
  __identifier: string,
  __isAddPlaceholder?: boolean,
  __isNew?: boolean,
  __isGroupHeader?: boolean,
  __rowIndex?: number,
  __state?: string,
  __groupValues?: Record<string, unknown>,
}
```

That means that for one table cell, I might have an object like this:

```ts
{
  id: 1,
  Common Name: "Coast redwood",
  latin_name: "Sequoia sempervirens",
  height_in_meters: 115.92,
  name: "Hyperion",
  class: "Conifer",
  country: "United States",
  __identifier: "__0_normal_0",
  __rowIndex: 0,
  __state: "done",
}
```

This design leaves our internal front-end state data intermingled with the user data from postgres. What if I have a column named `__state`?

## Example bug

1. Go to "New Table" > "Import Data".
1. Set "Import From" to "Clipboard".
1. Paste the following:

    ```txt
    task,__state
    Foo,done
    Bar,error
    Baz,loading
    Bat,idle
    ```
1. Click "Continue".
1. Click "Finish Import".
1. When the table loads, observe "done" printed for every row in the table.
1. Expect to see "done", "error", "loading", and "idle" values in the rows respectively.

There's all sorts of other strange behavior when a column shares a name with one of our internal fields.

## Solution

Instead of `TableRecord` _extending_ `TableRecordInResponse`, I think `TableRecord` should _contain_ `TableRecordInResponse` as follows:

```ts
interface TableRecordInResponse {
  [key: string]: unknown,
}

export interface TableRecord {
  record: TableRecordInResponse, // <-- new property
  identifier: string,
  isAddPlaceholder?: boolean,
  isNew?: boolean,
  isGroupHeader?: boolean,
  rowIndex?: number,
  state?: string,
  groupValues?: Record<string, unknown>,
}
```

This design also eliminates the need for the double underscores.

## Notes

I'm marking this "draft" until we get an okay from @pavish

**Comment by pavish** [comment]
@seancolsen The solution mentioned sounds good to me. We may also want to restructure the TableRecord interface to better suit our new grouping model.

**Comment by seancolsen** [comment]
Thanks @pavish I'll try to work on this as part of the front end changes for #862

**Comment by seancolsen** [comment]
@pavish I decided not to get into this today because I didn't want to add more complexity than necessary to the range grouping PR. We can take up this refactoring later.

**Comment by pavish** [comment]
@seancolsen That's fine. I was specifying the structure changes based on the new grouping model as a potential refactor we can do when this issue is picked up, we don't have to prioritize this right away.
