### ISSUE TITLE
Create components for building in-app documentation and help content

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#914]
We need a Tooltip or Help component, akin to [Carbon's Tooltip component](https://carbon-components-svelte.onrender.com/components/Tooltip) that will allow us to add documentation and help messages within the UI.

**Comment by pavish** [comment]
I think it would be better to implement `Tooltip` as an action, so that we can attach one to any element.

We could have a help component that uses Icon and Tooltip to provide similar functionality as Carbon's tooltip component.

**Comment by seancolsen** [comment]
Using actions under the hood seems great. We'll need to be mindful about supporting rich text within tooltip content, which might be a little trickier with actions, but still worth going that direction I think.

**Comment by pavish** [comment]
I don't think tooltips should support rich text. If we need support for rich text or custom components, it should rather be a popover component.

We already have the `popper` action which can convert any element as a dropdown or a popover, which can be used for such scenarios. We'd also probably be implementing `tooltip` on top of this.
