### ISSUE TITLE
Provide a clearer visual distinction between edit mode and select mode

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#927]
## Current behavior

1. Find a cell with a value set to an empty string.
1. Toggle between edit mode and select mode by alternately double clicking and pressing `Esc`.
1. Observe the presence of a cursor to change -- good.
1. Observe the border thickness to change -- good.
1. Observe no other changes.

## Goal

- I'd like it to be a bit clearer which mode I'm in.

## Desired behavior

- Add a drop shadow behind the cell. Google sheets does this and I think it looks pretty good.
- Change the border color too. I propose blue during select and black during edit. I don't feel too strongly about the specifics here -- just looking for some extra cue.

## Other thoughts

- Spreadsheet software places a square in the bottom right hand corner of the selection region. This square disappears when entering edit mode, providing an additional cue to the mode change. I predict we likely will not want to add the square because we won't want to implement the "fill" functionality for which spreadsheets use the square. As such I think it would be useful to provide an extra visual cue to our users indicating the current mode, which is why I'm suggesting the additional switch to a black border.

**Comment by pavish** [comment]
I'll defer to @ghislaineguerin to comment on this before we pick up the frontend changes for it.

**Comment by ghislaineguerin** [comment]
@pavish @seancolsen 
I think this looks good. I particularly like the idea of having the drop-shadow. Additionally, we should also consider how we represent a cell that might not be editable. Border color makes sense to me and I agree with not having the square.

**Comment by seancolsen** [comment]
Thanks @ghislaineguerin I'm making this as ready now

**Comment by pavish** [comment]
We use a gray border when the cell is non-editable. So, I'm concerned about using a black border while editing the cell. Anyone who works on this issue should feel free to experiment.

**Comment by nk183** [comment]
hi @seancolsen @kgodey can I work on this

**Comment by silentninja** [comment]
Thanks! @nk183 I have assigned the issue to you.

**Comment by nk183** [comment]
Hi @silentninja  @pavish @seancolsen 
i was thinking if in edit mode color may be light red  i guess ( as of color of Mathesar icon but may be more light )

https://user-images.githubusercontent.com/58779460/160114958-fe793536-41c5-4cdb-9e87-b3d1628ccddb.mp4
or should I stick with black

**Comment by seancolsen** [comment]
Red looks a little bit too much like an error I think.

**Comment by pavish** [comment]
@nk183 The red border seems to me like the cell has an error. I personally think retaining the blue border is better since the width changes, and we could probably only have a drop shadow additionally.

This issue involves experimenting with different styles (border colors, dropshadows etc.,) and referring similar products. Please post a list of suggestions that you feel are good so that the team can take a look before deciding on the final look.

**Comment by nk183** [comment]
hi @seancolsen  @pavish  I am suggesting some designs :
a)
select mode - same
edit mode - border change 
![image](https://user-images.githubusercontent.com/58779460/160268570-ce56db3e-ab8a-4a96-81f3-8c2eff702b50.png)
b)
select mode - same
edit mode - border change   &&  background-color : blue
               
![image](https://user-images.githubusercontent.com/58779460/160269012-1cc3d537-bf3e-4d2d-b33f-0235db3c147e.png)

c)
select mode - background-color : blue
edit mode - border change 

https://user-images.githubusercontent.com/58779460/160269081-1c7a3ef0-0893-4565-81b3-9c146354c86d.mp4

**Comment by pavish** [comment]
@ghislaineguerin You may want to take a look at this as well.

**Comment by seancolsen** [comment]
@nk183 For reference, here is how Google Sheets behaves:

![Peek 2022-03-29 07-37](https://user-images.githubusercontent.com/42411/160602965-52c8fca2-760e-42d0-beb3-3a503874a603.gif)

Your screenshots above appear to be using a blue drop shadow, which looks more like a glowing effect. I'd like for the drop shadow to behave similarly to Google Sheets. It's subtle, but present. And it has no saturation. It's translucent black, nearly transparent. 

Adding the drop shadow as I've described might actually be sufficient. Can we begin with a PR that just does that?

**Comment by seancolsen** [comment]
Ahh I meant to close this when I merged the PR. Thanks for the ping @kgodey
