### ISSUE TITLE
Wait until user is done editing a cell before saving

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#928]
## Current behavior

1. Double click a cell to enter edit mode.
1. Modify the value by typing something new.
1. Wait 1 second.
1. Expect nothing.
1. Observe the value of the cell is saved.
1. Press `Esc`.
1. Mode changes from edit to select.
1. Expect the cell value to be its original value before edits began, because I pressed `Esc`.
1. Observe the cell value to be changed.

## Proposed behavior

- Follow the same UX that spreadsheets use. LibreOffice Calc and Google Sheets both behave as follows... The cell value does not get saved until you leave edit mode with one of the following options:

    - `Enter`
    - `Shift+Enter`
    - `Tab`
    - `Shift+Tab`
    - a click outside the cell

## Notes

- I think this is relevant to our recent [discussion](https://github.com/centerofci/mathesar-wiki/pull/13#discussion_r770537811) about data integrity during editing. If our users expect the same behavior that I expect, then they might be annoyed that pressing `Esc` did not "undo" (so-to-speak) the edits they made to a cell.

**Comment by kgodey** [comment]
This sounds good to me.

**Comment by seancolsen** [comment]
Thanks @kgodey. I'm marking this as ready now that we have support from one other person.

@ghislaineguerin @pavish you two might still like to weigh in if you have any concerns here.

**Comment by seancolsen** [comment]
#1080 seems to have fixed this, so I'm closing it.

@pavish I noticed you marked that PR as "related to" this issue instead of "fixes" this issue. Is that just because of the difference in behavior with regard to the Esc key? (If so, I'm planning to open a separate issue for that where we can discuss it.)
