### ISSUE TITLE
Add context menu to set cell value to NULL

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#930]
## Current behavior

The user has no way to set a cell value to NULL.

## Desired behavior

1. Right click within a cell (or click-hold on a touch device).
1. The browser's native context menu is suppressed.
1. The cell is selected.
1. A Mathesar-specific context menu appears.
1. An item exists within the context menu labeled "Set to NULL".
1. The menu entry is disabled if any of the following conditions are met:
    - The value is already NULL.
    - The column does not allow NULL.
1. After the user clicks on the menu entry, the context menu disappears and Mathesar exhibits the same loading, success, and error behavior as when updating a value within a cell via typing new text and pressing Enter.

## Notes

- `faBackspace`, or `faTimes` would probably be acceptable icons to use in the menu.

## Additional context

- See [NULL Value Specs, scenario 3a](https://wiki.mathesar.org/design/specs/specs-null-values#steps-for-3a)

## See also

- #936

## Status

- Blocked by #742, especially because we should rely on `DropdownMenu` functionality to implement the disabled feature.

**Comment by seancolsen** [comment]
@ghislaineguerin the specs require the context menu entry to be "Set as NULL". That wording seems a bit awkward. Can we use "Set to NULL" instead?

**Comment by kgodey** [comment]
@seancolsen I think it's fine to use "Set to `NULL`".

**Comment by seancolsen** [comment]
Thanks @kgodey I've updated the issue description to reflect that adjustment.
