### ISSUE TITLE
Default value of column should have additional information to identify if default value is auto-generated

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#933]
## Description
When the default value is auto-generated, the returned value is a string representing the procedure call.

Eg., for all PKs for the default id column, the value for `default` is `"nextval('\"public\".data_types_id_seq'::regclass)"`.

We need additional information to help the client differentiate this from a normal string value.

## Expected behavior

It would be better if default returned an object, something similar to:
```
default: {
   type: 'constant' // auto-generated or constant
   value: 'some default value'
}
```

For auto-generated values, we could send additional information based on how we intend to support formulas, procedures and functions in the future. For now, we can just send the same value and on the frontend the input can be disabled.

**Comment by pavish** [comment]
@kgodey Marking this issue as draft inorder to decide on the format for the default value returned in the columns endpoint.

**Comment by mathemancer** [comment]
@pavish I have a quick implementation that uses:

```
...
"default": {
    "default_value": <some_val>
    "is_dynamic": <true|false>
}
...
```

Does that work?

**Comment by pavish** [comment]
@mathemancer I think this format works. We could always extend this object when we need to provide additional information.
