### ISSUE TITLE
Redesign import preview UX

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#934]
Our import preview UX doesn't match the rest of the application, since it was one of the first pages designed. We should update it. Some specific problems and related issues/discussions are listed below.

### Description
Upon file upload, the preview page displays a list of database types.

![Screenshot 2022-01-03 at 11 49 12 AM](https://user-images.githubusercontent.com/11850603/147904486-fed45142-f96b-480d-9bac-8cd720fa752d.png)

In our table, we display the mathesar types and we do not allow directly setting the database type

![Screenshot 2022-01-03 at 12 00 41 PM](https://user-images.githubusercontent.com/11850603/147904517-5d59d04a-cf1f-477d-a67e-3a2912d0479c.png)

### Expected behavior

We should have similar UX in both these places since it may confuse users otherwise. However, we might want to only show few configuration options in the preview page.

## Related discussions
- #1242
- #1227

**Comment by pavish** [comment]
@kgodey @ghislaineguerin Marking this issue as draft until both of you to take a look and add any additional detail if required.

**Comment by kgodey** [comment]
This is because we designed the import preview page way before we figured out data types. I think we should address this in the [UI Styling](https://github.com/centerofci/mathesar/milestone/42) milestone since that's where we'll be making sure what we've built is consistently styled (I've moved it there).

**Comment by kgodey** [comment]
We need an updated design for this, so marking as draft.

**Comment by vrutik2809** [comment]
While importing the data, one file named `<file_name>_<id>.csv` is created in `.media` directory.
So, when the user cancels the import then it would be better to delete that file from the directory to utilize the space efficiently.

**Comment by kgodey** [comment]
Assigning this to @pavish to close since he's implementing this.
