### ISSUE TITLE
Display NULL while editing a NULL cell

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#939]
## Current behavior

1. Find a NULL cell.
1. Double click to enter edit mode.
1. Observe that `NULL` no longer displays when in edit mode, leaving the user with no way to distinguish NULL from empty string while editing.

## Desired behavior

1. Double click to enter edit mode on a NULL cell.
1. `NULL` appears after the cursor, styled the same as when viewing the cell in select mode.
1. Begin entering text.
1. Observe that `NULL` disappears, being replaced by the text entered.
1. Delete all text entered.
1. Observe the cell to be blank (no `NULL` displayed) indicating the value is an empty string.

## Notes

- In edit mode, the user won't have a way to set the cell to NULL. That's okay for now. #930 and #936 will give users the capability to set a cell to NULL (but only from select mode).
- We should also style the NULL value the same in edit mode as it is styled in select mode. See discussion within #778 to learn more about our thinking on style.

## See also

- See #929 for a bug that you may hit while working on this ticket. (Note that you can still preserve your NULL value by clicking outside the cell instead of pressing Esc.)

## Additional context

See [NULL Value Specs, scenario 2b](https://wiki.mathesar.org/design/specs/specs-null-values#steps-for-2b)

**Comment by gagan2005** [comment]
I would like to work on this

**Comment by seancolsen** [comment]
Thanks @gagan2005! I've assigned this ticket to you. Let us know if you need any help. Feel free to ask questions here or in [Matrix](https://wiki.mathesar.org/en/community#matrix) (our chat system).

**Comment by gagan2005** [comment]
#961
