### ISSUE TITLE
Type Inference 4:  Set best types for columns of table

### ISSUE THREAD

**Issue by mathemancer** [centerofci/mathesar#94]
**Problem**

Different types in Mathesar will enable different operations; for example, strings could be aggregated by concatenating, but numeric types could be aggregated by summing or multiplying. So far, while we can reflect different types, we have no way to determine the type most appropriate for a table.

**Proposed solution**

Using the functions from #91 , #92 , and #93 , we should make a function that takes a `schema`, `original_table_name`, and `new_table_name`, creates a new table with typed columns of the same names as the old table, and inserts all data there.  The old table can be optionally dropped.

**Comment by kgodey** [comment]
This should not directly take the output of #93, since types need to be verified manually by the user.
