### ISSUE TITLE
Modify records API to return preview data for foreign key columns

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#946]
## Problem

- For cells in columns with foreign keys, the front end will sometimes need to display a preview of the referenced record instead of the value stored in the column.
- Separate API calls to retrieve that record preview data would result in poor performance because we'd need to issue one call per row. Ideally the records API would return that data within the same response as the table data.

## Solution
- The records API should accept a query parameter (perhaps something like `fk_previews`) to allow clients to toggle whether to return the preview data for foreign keys, (along with the underlying column value too). 
    - `fk_previews` should support three values:
        - `auto`: This will return previews if the display options for that column is set to show the preview (see #944)
        - `all`: This will return previews for all columns
        - `none` (this is the default value): This will not return any previews
    - This would allow the front end to _always_ request the preview and toggle visibility of the preview without any additional requests. It also allows clients not to request the preview if it is not needed.
    - This would also open the door to other subtle UX enhancements such as displaying a record preview within a popover when the preview is disabled.
- The implementer should spec out the API response schema changes for this issue and get feedback from others on the team before implementing this issue.

## Additional context
- In #944 we are deciding how the record preview settings will be stored.
- [Foreign Key Constraints Spec](https://wiki.mathesar.org/en/design/specs/foreign-key-constraints) discusses the record preview in Scenario 4.

## Status
- Blocked by #944 because the back end will need to know which columns to return and whether to return them.

**Comment by seancolsen** [comment]
@kgodey I'm assigning this to you to help answer the above questions and loop others in as needed.

**Comment by kgodey** [comment]
Updated issue description to resolve questions.

**Comment by pavish** [comment]
@kgodey Since we will have to store `show_link_preview` as mentioned in https://github.com/centerofci/mathesar/issues/944#issuecomment-1011338408, would it make sense to use that in the records endpoint to determine if or not to send the preview data additionally?

We could let the client control it via a query param as mentioned but that would mean the client would first have to fetch columns and then request for records, one after the other. Currently both these requests happen in parallel saving some ms.

I would suggest the query param `fk_previews` to support `auto`,`show`,`hide` (or any equivalent naming). On `auto` mode, it will refer the `show_link_preview` configuration to determine whether or not to send the preview. The default could be `hide` because this is a feature mostly specific to frontend client and not all clients.

**Comment by kgodey** [comment]
@pavish I like that idea, I've updated the ticket description to specify those details.

**Comment by silentninja** [comment]
@seancolsen I am planning to use the following schema

```json5
{
  "count": 1393,
  "grouping": {
  },
  "preview_data": {
    "1": {
      "data": [
        {
          "0": 1,
          "1": "NASA Goddard Space Flight Center"
        },
        {
          "0": 2,
          "1": "NASA Ames Space Flight Center"
        },
        {
          "0": 3,
          "1": "NASA Kennedy Space Flight Center"
        }
      ],
      "metadata": {
        "identifier_column": "0"
      }
    },
    "2": {
      "data": [
        {
          "0": 1,
          "1": "Application"
        },
        {
          "0": 2,
          "1": "Issued"
        }
      ],
      "metadata": {
        "identifier_column": "0"
      }
    },
    "3": {
      "data": [
        {
          "0": 1,
          "1": "LA"
        },
        {
          "0": 2,
          "1": "Boston"
        }
      ],
      "metadata": {
        "identifier_column": "0"
      }
    }
  },
  "results": [
    {
      "0": 1,
      "1": 1, // NASA Goddard Space Flight Center
      "2": null,
      "3": 2, // Boston
      "4": "KSC-12871"
    },
    {
      "0": 2,
      "1": 2,
      "2": 2,
      "3": 1,
      "4": "KSC-12872"
    },
    {
      "0": 3,
      "1": 3,
      "2": 2,
      "3": 2,
      "4": "KSC-12873"
    }
  ]
}
```
`preview_data` property is a dictionary with the 
- key denoting the `id` of the referrer foreign key column. 
- value contains two properties `data` and `metadata`
  - `data` contains a list of the preview data for that column
  - `metadata` contains information about the column(pk column for now) which was used to match the foreign key record, The value of that column should be used by the frontend to match that value of the foreign key column in the results.



I am looking for an opinion on converting the `preview_data data` array into a dictionary with the value of the identifier column as the key.

```
{
  "preview_data": {
    "1": {
      "1": {
        "1": "NASA Goddard Space Flight Center"
      },
      "2": {
        "1": "NASA Ames Space Flight Center"
      },
      "3": {
        "1": "NASA Kennedy Space Flight Center"
      }
    }
  }
}
```

 This would convert the `integer` value of that column into a `string`. What do you think about that change?

**Comment by seancolsen** [comment]
@silentninja this is looking good. Both option are workable, but I like the second option a bit better.
