### ISSUE TITLE
Allow user to remove a foreign key constraint from the column header menu

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#951]
## Current behavior

- To remove a FK constraint, the user must open the Table Constraints dialog.

## Desired behavior

- Find a column associated with a single-column foreign key constraint.
- Click on the column header to open the column header menu.
- Choose "Remove Table Link".
- Observe the same loading/success/error behavior as when clicking on the "Allow NULL" option in the column header menu.

## Limitations

- To delete a multi-column foreign key, you'll still need to do it from the Table Constraints dialog.

## Additional context

- [Foreign Key Constraints Spec](https://wiki.mathesar.org/en/design/specs/foreign-key-constraints) -- see Scenario 2.

**Comment by seancolsen** [comment]
@kgodey I put this in the same milestone as all the other FK tickets, but I think we could safely defer it until later. I'll leave it to you to re-prioritize if you so choose.

**Comment by kgodey** [comment]
> @kgodey I put this in the same milestone as all the other FK tickets, but I think we could safely defer it until later. I'll leave it to you to re-prioritize if you so choose.

I think it's important to do this with the rest of the feature to make it friendlier for non-technical users. It seems like it would be pretty quick to implement.
