### ISSUE TITLE
Display record previews for foreign key cells

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#953]
## Current behavior

- A cell within a column having an FK constraint only displays the value of the target column.
- Because the target column is usually a primary key, users cannot easily identify linked records while viewing a table.

## Desired behavior

- A "Record Preview" setting can be enabled.
- When Record Preview is enabled, the cell will show additional fields from the record, with special styling.

## Specs

- [Foreign Key Constraints Spec](https://wiki.mathesar.org/en/design/specs/foreign-key-constraints) -- see Scenario 4a and Scenario 4b.

## Status

- Blocked by #946

**Comment by seancolsen** [comment]
@ghislaineguerin @kgodey Should we support record previews for multi-column FKs? This seems like a pretty clear "no" to me, but just thought I'd check.

**Comment by kgodey** [comment]
> @ghislaineguerin @kgodey Should we support record previews for multi-column FKs? This seems like a pretty clear "no" to me, but just thought I'd check.

You are correct, not right now.

**Comment by seancolsen** [comment]
I'm closing this ticket because, as spec'ed, it is now so out-of-date with our current design that it no longer seems useful. The product goal that this ticket intended to address will now be addressed by the [Record Summary feature](https://wiki.mathesar.org/en/design/specs/record-summary) and work work on the feature is being tracked more loosely in the [features spreadsheet](https://docs.google.com/spreadsheets/d/1IqW3GiwYibvS3gleIKHhTa51WF_coOg2BqJA5ffPtVI/edit#gid=0).
