### ISSUE TITLE
Use record selector when editing cells in FK columns

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#954]
## Current behavior

- Editing a cell within a FK column requires the user to know the value of the target column which is usually a meaningless id number. This makes it tedious for users to link records.

## Desired behavior

- Editing a cell within a FK column will open a record selector, allowing the user to search and select a record from the target table.

## Specs

- [Foreign Key Constraints Spec](https://wiki.mathesar.org/en/design/specs/foreign-key-constraints) -- see Scenario 5a and Scenario 5b.

## Status

- Blocked by #945

**Comment by seancolsen** [comment]
@ghislaineguerin @kgodey The specs read:

> in the case of multi-column foreign key constraints, the system could modify additional fields.

I don't think we should enable the record selector for multi-column FKs. Is that okay? If it becomes a problem we could address it as-needed.

**Comment by kgodey** [comment]
> I don't think we should enable the record selector for multi-column FKs. Is that okay? If it becomes a problem we could address it as-needed.

Agreed, I don't think there should be any special behavior for multi-column FKs, it should be treated as a text field. @ghislaineguerin Can you remove the part that Sean quoted in the spec to avoid confusion?

**Comment by ghislaineguerin** [comment]
@kgodey I agree, we should just treat it as text input. I'll update the spec.

**Comment by seancolsen** [comment]
This work was started in #1445. Subsequent polish work will be tracked in more detailed tickets as-needed.
