### ISSUE TITLE
Front end support for configuring table settings

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#955]
## Current behavior

- User has no way to configure the behavior of the record previews (within foreign key columns) and record selector (while editing data in foreign key columns).

## Desired behavior

- The [Foreign Key Constraints Spec](https://wiki.mathesar.org/en/design/specs/foreign-key-constraints) briefly talks about "Table Link Preferences" in the video for Scenario 5.
- Some details of the data storage are still TBD in #944. When that ticket is done, we should add the UI to view and update those settings.
- We'll most likely want a modal dialog to configure the settings.
- Entry points to open the modal, as shown in the specs and prototype:
    - Within the record selector for a cell in a FK column
    - Within the column header menu of a FK column
- There's some nuance to how we set up this dialog though. If table X is referencing table Y, then we need to open the Y settings when viewing X. If we add other table-level settings later on then we might not want those table-level settings for table Y to display from an entry point in table X. I think it might be best to have a component that displays the "table link" settings. From table X we open a modal that displays only the "table link" settings from table Y. From table Y, we can also open a "Table Settings" modal which displays all table settings for table Y and includes the component which displays the "table link" settings.

## Questions to answer

- If, in #944, we decide to store the record preview toggle state at the table level, then do we still want to allow the user to toggle the record preview from column header menu, even though it would affect other columns too? I think we probably do.
- Do we want to provide an additional entry point to open the settings modal from the _target_ table? If so, I think we'd add a "Settings" menu item.

## Status

- Blocked by back-end work in #944 which still has a number of open questions.

**Comment by kgodey** [comment]
> If, in API support for storing table-level settings #944, we decide to store the record preview toggle state at the table level, then do we still want to allow the user to toggle the record preview from column header menu, even though it would affect other columns too? I think we probably do.

Yes, we're assuming the user will be likely to want to change them at the column level while searching.

**Comment by seancolsen** [comment]
I'm closing this ticket because, as spec'ed, it is now so out-of-date with our current design that it no longer seems useful. "Record Summary" and "Record Selector" actually mean different things now! The product goal that this ticket intended to address will now be addressed by the "Summary Expression Builder" within [Record Summary feature](https://wiki.mathesar.org/en/design/specs/record-summary).
