### ISSUE TITLE
Secure Mathesar against SQL injection

### ISSUE THREAD

**Issue by mathemancer** [centerofci/mathesar#958]
## Problem

We have not audited the codebase for potential security problems, e.g., from SQL injection attacks.

## Proposed solution

We should do an initial round of research and auditing for any such problems.  If possible, we should add some automated testing for SQL injection problems into our pipeline to make sure no vulnerabilities are added in the future.

## Additional context

This isn't an immediate problem, since our initial users are assumed to own their databases, so there isn't too much concern about vulnerabilities of this sort.  I'm calling this a meta issue for now until we figure out how to attack this problem.

**Comment by kgodey** [comment]
Closing this since we're relying on default framework methods and tooling for the APIs and we're not accepting unsanitized data. We'll probably need outside help to do a full security audit at some point.
