### ISSUE TITLE
Improve focus indicator of `InputGroup` component

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#971]
The [form-builder PR](https://github.com/centerofci/mathesar/pull/915) introduced the `InputGroup` component, which helped make the input components more cleaner but lead to a stylistic regression.

Comments from @seancolsen on the PR:

> I really like the changes that simplify `TextInput` to a single DOM element, and I want to make sure to keep those changes. There's also clearly value in keeping the "grouped input" functionality. But the changes in this PR lead to a minor stylistic regressions in my opinion.
> 
> Examples:
> 
> - Filter tables
> 
>     | Before | After |
>     | -- | -- |
>     ![image](https://user-images.githubusercontent.com/42411/148478215-7999cfa4-f5ae-444b-8135-9af315affa5a.png) | ![image](https://user-images.githubusercontent.com/42411/148478304-b98116a8-9b5e-4b8c-9b97-21283fa1da89.png) |
> 
> - Add column
> 
>     | Before | After |
>     | -- | -- |
>     | ![image](https://user-images.githubusercontent.com/42411/148479870-a1ee2b9c-9aa9-478f-b350-9c6d1e4d045e.png) | ![image](https://user-images.githubusercontent.com/42411/148479532-95a1eedd-b15c-45ab-af43-40c7e0cf4cc3.png) |
> 
> I'd prefer that the focus indicator encompass the entire group, like it did before.
> 
> I'd like to keep the changes that add a grey background to the group items as it helps to distinguish the label from the input.
> 
> In Storybook, I see that `InputGroup` is also intended to handle the use case of multiple inputs grouped together, in which case the focus indicators would _need_ to be separate. But this use-case seems quite esoteric to me. I can't recall ever having seen a UI like that. I'd suggest we abandon any attempts to support it.

## Proposed solution

1. We need to analyze if it's worth it to bind focus indicator between the InputGroup component and the slotted input components.
2. [Bootstrap's InputGroup](https://getbootstrap.com/docs/5.0/forms/input-group/#multiple-inputs) was the main inspiration for this component. We can further analyze the need to group multiple inputs together instead of just text with input.

Based on the analysis, we'd like to perform necessary improvements on the component.

**Comment by pavish** [comment]
Blocked by https://github.com/centerofci/mathesar/pull/915

**Comment by seancolsen** [comment]
I splintered off some of the content that was originally in the body of this ticket and put it into #1042

**Comment by pavish** [comment]
This ticket is no longer required since our UX no longer contains such scenarios where `InputGroup` is used for the label and the component.

`InputGroup` now only groups inputs together, so focus is retained for each of the inputs independently.
