### ISSUE TITLE
Text overflow should be represented by ellipsis in schema selector

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#984]
## Description
In the schema selector, if the name of the schema is large, text overflows and visually breaks abruptly.

<img width="476" alt="Screenshot 2022-01-19 at 10 11 08 PM" src="https://user-images.githubusercontent.com/11850603/150175641-31e48206-afb8-408c-a971-ba50941c4765.png">

## Expected behavior
Overflown text should be truncated and ellipsis should be displayed, as represented in the following image:

<img width="476" alt="Screenshot 2022-01-19 at 10 16 15 PM" src="https://user-images.githubusercontent.com/11850603/150176111-a9ae20d9-87f8-4a33-a387-c67fbeb0481a.png">

## To Reproduce
1. Create a schema with a large name
2. Open schema selector in the navigation menu

**Comment by seancolsen** [comment]
Suggestion to implementer: do this in CSS via `text-overflow: ellipsis;`

**Comment by sahilsaini110** [comment]
@seancolsen please assign this to me.

**Comment by silentninja** [comment]
Thanks, @sahilsaini110 I have assigned the issue to you.
