### ISSUE TITLE
Clicking on the name in 'Manage Schemas' page should set is as the current schema and redirect to base page

### ISSUE THREAD

**Issue by pavish** [centerofci/mathesar#985]
In the 'Manage Schemas' page, upon clicking on the schema name, we should make it the active schema and redirect to the main page.

<img width="528" alt="Screenshot 2022-01-19 at 10 38 04 PM" src="https://user-images.githubusercontent.com/11850603/150180008-8098932a-73f7-41c7-91e0-117d1d517731.png">

### Expected behaviour
* Click schema selector -> Manage schemas
* The list of schemas in the database will be displayed. eg., In the above image, it's public, mathesar_inference_schemas, test.
* The names of the schemas currently have no actions associated with them.
* The names should be hyperlinks, and upon clicking them, the following should happen:
   * The clicked schema should become the `currentShema`
       * Refer store `currentSchemaId` within /mathesar_ui/src/stores/schemas.ts
       * Update `currentSchemaId` which would inturn update the `currentSchema`
   * Redirect to the main page once the currentSchema is updated

**Comment by A1O** [comment]
I'm working on this.
