### ISSUE TITLE
Filter/Sort/Group are broken when referencing a deleted column

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar#987]
## Reproduce

1. Sort a table by one column.
1. Delete that column.
1. Expect the column to be removed from the sort criteria.
1. Observe the sort criteria to still contain the column.
1. Refresh the table.
1. Expect the records to load.
1. Observe an error 400 from the records API when attempting to fetch the records because the sort criteria is now invalid.

## Implementation

- The `Columns` store should dispatch an `EventListener` event whenever a column is deleted. `TabularData` should listen to that event and react by altering `Meta` to remove all references to the deleted column from within the `filtering`, `sorting`, and `grouping` properties on the `Meta` class.
- We should provide some E2E test coverage along with this fix for this bug.

**Comment by Jinxiao0302** [comment]
I may try to help with this bug

**Comment by kgodey** [comment]
Go ahead @Jinxiao0302!
