### ISSUE TITLE
Remove `column_index` from MathesarColumn class

### ISSUE THREAD

**Issue by mathemancer** [centerofci/mathesar#996]
## Problem

Currently, column operations use `column_index` to identify columns.  This is brittle, and leads to bugs.  We've decided to change to `attnum`.  Once this is done, the `column_index` attribute will be extraneous.

## Proposed solution

We should remove the `column_index` attribute of the `MathesarColumn` class in `db/columns/base.py` and make sure nothing breaks.

## Additional context

Blocked by:
- #992 
- #993 
- #994 
- #995

**Comment by kgodey** [comment]
I realized that column index is not extraneous, it should still be used by the frontend to order columns for display. See: https://github.com/centerofci/mathesar/issues/1185.

I do think we need to make sure nothing in the `db` module depends on the `column_index` attribute of the `MathesarColumn` class, but I don't think we should remove it, we need to be able to send it to the frontend easily.

**Comment by mathemancer** [comment]
The `attnum` of a column is _always_ in the same order as the index. I.e., if you order by `attnum`, it will always be the same as if you order by column index. If the API needs to return an index instead of `attnum`, I think we should do that as close to the actual API as possible.

**Comment by kgodey** [comment]
Okay, makes sense. Based on conversations in #1185 and #1186, I don't think the API needs to return an index, just order by `attnum`, so we can go ahead and remove the `index`.
